#!/usr/bin/env python3
"""Populate theorem.tex files for GTM099 concepts with actual LaTeX from the book."""
import os, re

STAGING = "/home/a123/文档/mathpkg/pipeline_output/v7_test/staging/_GTM099_Finite_Reflection_Groups"

# Map slug -> LaTeX statement
# The statements are extracted from the book text
statements = {
    "proposition-1.2.1-stabilizer-orbit-cardinality": r"""\textbf{Proposition 1.2.1}
If $G$ is a permutation group on a set $S$ and $x \in S$, then $[G : \operatorname{Stab}(x)] = |\operatorname{Orb}(x)|$.""" ,

    "theorem-2.3.1-euler-rotation": r"""\textbf{Theorem 2.3.1 (Euler)}
Suppose that $T$ is a rotation in $\mathcal{O}(V)$. Then $T$ is a rotation about a fixed axis, in the sense that $T$ has an eigenvector $x$ having eigenvalue $1$ such that the restriction of $T$ to the plane $\mathcal{P} = x^\perp$ is a two-dimensional rotation of $\mathcal{P}$.""" ,

    "theorem-2.3.2-orthogonal-determinant-minus-one": r"""\textbf{Theorem 2.3.2}
Suppose that $T \in \mathcal{O}(V)$ with $\det T = -1$. Then geometrically the effect of $T$ is that of a reflection through a plane $\mathcal{P}$, followed by a rotation about the line through the origin orthogonal to $\mathcal{P}$.""" ,

    "proposition-2.4.1-poles-permutation": r"""\textbf{Proposition 2.4.1}
If $\dim V = 3$ and $\mathcal{G} \leq \mathcal{O}(V)$, then $\mathcal{G}$ is a permutation group on its set $\mathcal{S}$ of poles.""" ,

    "proposition-2.5.1-rotation-subgroup-index-2": r"""\textbf{Proposition 2.5.1}
If $\mathcal{G} \leq \mathcal{O}(V)$ and $\mathcal{H}$ is the rotation subgroup of $\mathcal{G}$, then either $\mathcal{H} = \mathcal{G}$ or else $[\mathcal{G} : \mathcal{H}] = 2$. In particular, $\mathcal{H}$ is a normal subgroup of $\mathcal{G}$.""" ,

    "theorem-2.5.2-classification-3d": r"""\textbf{Theorem 2.5.2}
If $\dim V = 3$ and $\mathcal{G}$ is a finite subgroup of $\mathcal{O}(V)$, then $\mathcal{G}$ is one of the following:
\begin{enumerate}
\item[(a)] $\mathcal{C}_3^n, n \geq 1; \mathcal{H}_3^n, n \geq 2; \mathcal{T}; \mathcal{W}; \mathcal{I}$;
\item[(b)] $(\mathcal{C}_3^n)^*, n \geq 1; (\mathcal{H}_3^n)^*, n \geq 2; \mathcal{T}^*; \mathcal{W}^*; \mathcal{I}^*$;
\item[(c)] $\mathcal{C}_3^{2n}]\mathcal{C}_3^n, n \geq 1; \mathcal{H}_3^n]\mathcal{C}_3^n, n \geq 2; \mathcal{H}_3^{2n}]\mathcal{H}_3^n, n \geq 2; \mathcal{W}]\mathcal{T}$.
\end{enumerate}""" ,

    "proposition-3.1.1-vector-space-not-union-of-subspaces": r"""\textbf{Proposition 3.1.1}
If $\dim V \geq 1$, then $V$ is not the union of a finite number of proper subspaces.""" ,

    "theorem-3.1.2-fundamental-region-fricke-klein": r"""\textbf{Theorem 3.1.2}
The set $F$ constructed by the Fricke--Klein method is a fundamental region for $\mathcal{G}$ in $V$.""" ,

    "proposition-4.1.1-conjugate-root-is-root": r"""\textbf{Proposition 4.1.1}
If $r$ is a root of $\mathcal{G} \leq \mathcal{O}(V)$ and if $T \in \mathcal{G}$, then $Tr$ is also a root of $\mathcal{G}$. In fact, if $Tr = x$, then $S_x = T S_r T^{-1} \in \mathcal{G}$.""" ,

    "proposition-4.1.2-effective-iff-roots-span": r"""\textbf{Proposition 4.1.2}
Suppose that $\mathcal{G} \leq \mathcal{O}(V)$ is generated by reflections along roots $r_1, \ldots, r_k$. Then $\mathcal{G}$ is effective if and only if $\{r_1, \ldots, r_k\}$ spans $V$.""" ,

    "proposition-4.1.3-finite-root-system-implies-finite-group": r"""\textbf{Proposition 4.1.3}
Suppose that $\mathcal{G} \leq \mathcal{O}(V)$ is generated by a finite set of reflections, and that $\mathcal{G}$ is effective. If the root system $\Delta$ is finite, then $\mathcal{G}$ is finite.""" ,

    "proposition-4.1.4-neither-positive-nor-negative": r"""\textbf{Proposition 4.1.4}
If $r_i, r_j \in \Pi$, with $i \neq j$, and $\lambda_i$ and $\lambda_j$ are positive real numbers, then the vector $x = \lambda_i r_i - \lambda_j r_j$ is neither positive nor negative.""" ,

    "proposition-4.1.5-roots-in-base-obtuse": r"""\textbf{Proposition 4.1.5}
If $r_i, r_j \in \Pi$ and $i \neq j$, then $(r_i, r_j) \leq 0$ and $S_i r_j$ is positive.""" ,

    "proposition-4.1.6-obtuse-set-linearly-independent": r"""\textbf{Proposition 4.1.6}
Suppose that $x_1, x_2, \ldots, x_m \in V$ are all on the same side of a hyperplane; i.e., $(x_i, x) > 0$, $1 \leq i \leq m$, for some $x \in V$. If $(x_i, x_j) \leq 0$ whenever $i \neq j$, then $\{x_1, \ldots, x_m\}$ is a linearly independent set.""" ,

    "proposition-4.1.8-uniqueness-of-t-base": r"""\textbf{Proposition 4.1.8}
The $t$-base $\Pi$ for the root system $\Delta$ is unique; consequently, the notion of positivity depends only on $t$ and not on the choice of $\Pi$.""" ,

    "proposition-4.1.9-reflection-preserves-positive-roots": r"""\textbf{Proposition 4.1.9}
Suppose that $S_i$ is the reflection along $r_i \in \Pi = \{r_1, \ldots, r_n\}$. If $r \in \Delta^+$ but $r \neq r_i$, then $S_i r \in \Delta^+$.""" ,

    "proposition-4.1.10-maximal-inner-product": r"""\textbf{Proposition 4.1.10}
If $x \in V$, there is a transformation $T \in \mathcal{G}_t$ such that $(Tx, r_i) \geq 0$ for all $r_i \in \Pi$.""" ,

    "proposition-4.1.11-positive-root-hits-base": r"""\textbf{Proposition 4.1.11}
If $r \in \Delta^+$, then $T r \in \Pi$ for some $T \in \mathcal{G}_t$.""" ,

    "theorem-4.1.12-fundamental-reflections-generate": r"""\textbf{Theorem 4.1.12}
The fundamental reflections generate $\mathcal{G}$; i.e., $\mathcal{G}_t = \mathcal{G}$.""" ,

    "theorem-4.2.1-only-identity-fixes-t-base": r"""\textbf{Theorem 4.2.1}
If $T \in \mathcal{G}$ and $T \Pi = \Pi$, then $T = 1$.""" ,

    "proposition-4.2.2-image-of-positive-roots": r"""\textbf{Proposition 4.2.2}
If $T \in \mathcal{G}$, then $T(\Delta_t^+) = \Delta_{T(t)}^+$; consequently, $T(\Pi_t) = \Pi_{T(t)}$.""" ,

    "proposition-4.2.3-region-F-is-fundamental-region-halfspaces": r"""\textbf{Proposition 4.2.3}
The fundamental region $F_t$ can be expressed as
\[
F_t = \{x \in V : (x, r_i) > 0, \text{ for all } r_i \in \Pi\}
= \bigcap_{i=1}^{n} \{x \in V : (x, r_i) > 0\}.
\]""" ,

    "theorem-4.2.4-F-is-fundamental-region": r"""\textbf{Theorem 4.2.4}
The set $F = F_t$ is a fundamental region for the Coxeter group $\mathcal{G}$.""" ,

    "theorem-4.2.5-every-reflection-conjugate-to-fundamental": r"""\textbf{Theorem 4.2.5}
Every reflection in $\mathcal{G}$ is conjugate in $\mathcal{G}$ to a fundamental reflection; consequently, every root of $\mathcal{G}$ is in the root system $\Delta$.""" ,

    "theorem-4.2.6-dual-basis-nonnegative": r"""\textbf{Theorem 4.2.6}
Suppose that $\{r_1, \ldots, r_n\}$ is a basis for $V$ with $(r_i, r_j) \leq 0$ if $i \neq j$, and let $\{s_1, \ldots, s_n\}$ be the dual basis. Then $(s_i, s_j) \geq 0$ for all $i, j$.""" ,

    "proposition-5.1.1-root-inner-product-cosine": r"""\textbf{Proposition 5.1.1}
If $r_i, r_j \in \Pi$, then there is an integer $p_{ij} \geq 1$ such that
\[
\frac{(r_i, r_j)}{\|r_i\| \|r_j\|} = -\cos(\pi/p_{ij}).
\]
In fact, $p_{ij}$ is the order of $S_i S_j$ as a group element.""" ,

    "theorem-5.1.2-same-coxeter-graph-implies-isomorphic": r"""\textbf{Theorem 5.1.2}
If $\mathcal{G}_1, \mathcal{G}_2 \leq \mathcal{O}(V)$ are Coxeter groups having the same Coxeter graph, then $\mathcal{G}_1$ and $\mathcal{G}_2$ are conjugate in $\mathcal{O}(V)$, and hence are isomorphic.""" ,

    "theorem-5.1.3-coxeter-graph-positive-definite": r"""\textbf{Theorem 5.1.3}
The Coxeter graph of a Coxeter group is positive definite.""" ,

    "proposition-5.1.4-coxeter-graph-connected-iff-irreducible": r"""\textbf{Proposition 5.1.4}
The Coxeter graph of a Coxeter group $\mathcal{G}$ is connected if and only if $\mathcal{G}$ is irreducible.""" ,

    "proposition-5.1.5-determinant-recursion": r"""\textbf{Proposition 5.1.5}
For a marked graph $G$ with nodes $a_1$ and $a_2$ joined by a single branch marked $p$, let $G_1 = G \setminus \{a_1\}$, $G_2 = G \setminus \{a_1, a_2\}$. Then
\[
\det G = \det G_1 - (\cos^2 \pi/p) \det G_2.
\]""" ,

    "proposition-5.1.6-subgraph-determinant-inequality": r"""\textbf{Proposition 5.1.6}
If $H$ is a proper subgraph of a positive definite Coxeter graph $G$, then $H$ is also positive definite. Consequently, none of the non-positive-definite graphs $P_n, Q_n, S_n, T_n, U_3, Z_4, Y_5, V_5, R_7, R_8, R_9$ can occur as subgraphs of positive definite Coxeter graphs.""" ,

    "theorem-5.1.7-classification-connected-positive-definite-coxeter-graphs": r"""\textbf{Theorem 5.1.7}
If $G$ is a connected positive definite Coxeter graph, then $G$ is one of the graphs $A_n$, $B_n$, $D_n$, $H_2^n$, $G_2$, $I_3$, $I_4$, $F_4$, $E_6$, $E_7$, or $E_8$.""" ,

    "proposition-5.2.1-crystallographic-pij-values": r"""\textbf{Proposition 5.2.1}
If $\mathcal{G}$ is crystallographic, then each $p_{ij}$ is one of the integers $1, 2, 3, 4,$ or $6$.""" ,

    "theorem-5.3.1-classification-finite-reflection-groups": r"""\textbf{Theorem 5.3.1}
If $\mathcal{G}$ is a finite subgroup of $\mathcal{O}(V)$ that is generated by reflections, then $V$ may be written as the orthogonal direct sum of $\mathcal{G}$-invariant subspaces $V_0, V_1, \ldots, V_k$, with the following properties:
\begin{enumerate}
\item[(a)] If $\mathcal{G}_i = \{T | V_i : T \in \mathcal{G}\}$, then $\mathcal{G}_i \leq \mathcal{O}(V_i)$ and $\mathcal{G}$ is isomorphic with $\mathcal{G}_0 \times \mathcal{G}_1 \times \cdots \times \mathcal{G}_k$.
\item[(b)] $\mathcal{G}_0$ consists only of the identity transformation on $V_0$.
\item[(c)] Each $\mathcal{G}_i$, $i \geq 1$, is one of the groups
\[
\mathcal{A}_n, n \geq 1; \mathcal{B}_n, n \geq 2; \mathcal{D}_n, n \geq 4; \mathcal{H}_2^n, n \geq 5, n \neq 6;
\]
\[
\mathcal{G}_2; \mathcal{I}_3; \mathcal{I}_4; \mathcal{F}_4; \mathcal{E}_6; \mathcal{E}_7; \text{or } \mathcal{E}_8.
\]
\end{enumerate}
The group $\mathcal{G}$ is a Coxeter group if and only if $V_0 = 0$, and $\mathcal{G}$ is crystallographic if and only if $\mathcal{H}_2^n$, $\mathcal{I}_3$, and $\mathcal{I}_4$ do not appear among the direct factors $\mathcal{G}_i$.""" ,

    "theorem-5.4.1-witt-stabilizer-theorem": r"""\textbf{Theorem 5.4.1 (Witt)}
If $\mathcal{H}$ is the subgroup of $\mathcal{G}$ leaving $s_i$ fixed, then
\[
\mathcal{H} = \langle S_1, \ldots, S_{i-1}, S_{i+1}, \ldots, S_n \rangle.
\]""" ,

    "proposition-5.4.2-irreducible-unmarked-graph-transitive": r"""\textbf{Proposition 5.4.2}
Suppose that $\mathcal{G}$ is irreducible and that its Coxeter graph $G$ has no marks over its branches. Then $\mathcal{G}$ is transitive as a permutation group on its root system $\Delta$.""" ,

    "proposition-6.1.1-length-as-positive-roots-sent-to-negative": r"""\textbf{Proposition 6.1.1}
For each $T \in \mathcal{G}$, let $n(T) = |T(\Delta^+) \cap \Delta^-|$ be the number of positive roots sent to negative roots by $T$. Then $n(T) = l(T)$, the length of $T$ as a product of fundamental reflections. Moreover,
\[
n(T S_i) = \begin{cases}
n(T) + 1 & \text{if } T r_i \in \Delta^+,\\
n(T) - 1 & \text{if } T r_i \in \Delta^-.
\end{cases}
\]""" ,

    "proposition-6.1.2-root-positivity-under-alternating-product": r"""\textbf{Proposition 6.1.2}
If $S_i$ and $S_j$ are fundamental reflections in $\mathcal{G}$ and $1 \leq m \leq p_{ij}$, then
\[
(\cdots S_i S_j)_{m-1} r_i \in \Delta^+.
\]""" ,

    "proposition-6.1.3-unique-maximal-region-sharing-edge": r"""\textbf{Proposition 6.1.3}
Of all the fundamental regions sharing a common edge (wall), there is a unique one whose corresponding word has maximal length; equivalently, it has the highest Roman numeral in the path representation.""" ,

    "theorem-6.1.4-coxeter-presentation": r"""\textbf{Theorem 6.1.4 (Coxeter)}
Every relation $W = S_{i_1} \cdots S_{i_k} = 1$ in a Coxeter group $\mathcal{G}$ is a consequence of the relations $(S_i S_j)^{p_{ij}} = 1$, so $\mathcal{G}$ has the presentation
\[
\langle S_1, \ldots, S_n \mid (S_i S_j)^{p_{ij}} = 1,\; 1 \leq i \leq j \leq n \rangle.
\]""" ,

    "proposition-6.1.5-homomorphism-onto-H": r"""\textbf{Proposition 6.1.5}
There is a homomorphism $\psi$ from $\mathcal{G}$ onto $\mathcal{H}$ with $\psi(T_i) = S_i$, $1 \leq i \leq n$. In particular, $\mathcal{H}$ is a finite group.""" ,

    "proposition-6.1.6-invariant-inner-product": r"""\textbf{Proposition 6.1.6}
If $\mathcal{H}$ is any finite group of invertible transformations of $V$ then there is an inner product $C$ on $V$ so that $\mathcal{H}$ is contained in the orthogonal group relative to $V$.""" ,

    "proposition-6.1.7-schur-lemma": r"""\textbf{Proposition 6.1.7 (Schur's Lemma)}
If $\mathcal{H}$ is an irreducible group of transformations on $V$ and $S \neq 0$ is a linear transformation on $V$ such that $ST = TS$ for all $T \in \mathcal{H}$, then $S$ is non-singular.""" ,

    "corollary-schur-lemma-eigenvalue": r"""\textbf{Corollary (to Schur's Lemma)}
If $S$ has an eigenvalue $\lambda$ in $\mathcal{F}$, then $S = \lambda \cdot 1$.""" ,

    "proposition-6.1.9-commutation-matrix-identity": r"""\textbf{Proposition 6.1.9}
If $T \in \mathcal{H}$ is represented by the matrix $M$ with respect to the basis $\{e_1, \ldots, e_n\}$, then
\[
M(P^{-1}A) = (P^{-1}A)M.
\]""" ,

    "theorem-6.1.11-H-is-coxeter-group": r"""\textbf{Theorem 6.1.11 (Coxeter)}
The group $\mathcal{H}$ is a Coxeter subgroup of $\mathcal{O}(V)$, and $\mathcal{G}$ is isomorphic with $\mathcal{H}$.""" ,

    "proposition-7.2.2-Lr-divides-difference": r"""\textbf{Proposition 7.2.2}
If $0 \neq r \in V$ then the linear polynomial $L_r$ is a divisor of $S_r f - f$ for all $f \in \mathfrak{P}$.""" ,

    "proposition-7.3.1-averaging-operator-projection": r"""\textbf{Proposition 7.3.1}
Suppose $\mathcal{G} \leq \mathcal{GL}(V)$ is finite. Then
\begin{enumerate}
\item[(i)] if $f \in \mathfrak{P}$ then $M f \in \mathfrak{J}$, and
\item[(ii)] $M^2 = M$, and $M$ restricts to the identity map on $\mathfrak{J}$.
\end{enumerate}
Thus $M$ is a projection from $\mathfrak{P}$ onto $\mathfrak{J}$.""" ,

    "proposition-7.3.3-relations-among-invariants": r"""\textbf{Proposition 7.3.3}
Suppose $g_1, g_2, \ldots, g_k \in \mathfrak{J}$; $h_1, h_2, \ldots, h_k$ are homogeneous in $\mathfrak{P}$; and $g_1 h_1 + \cdots + g_k h_k = 0$. Then either $h_1 \in \mathfrak{a}$ or else $g_1$ is in the ideal $\mathfrak{b}$ in $\mathfrak{J}$ generated by $g_2, \ldots, g_k$.""" ,

    "theorem-7.3.4-algebraically-independent-basic-invariants": r"""\textbf{Theorem 7.3.4}
There exist homogeneous invariants $f_1, \ldots, f_m \in \mathfrak{J}$ that are algebraically independent over $\mathcal{R}$, such that $\mathfrak{J}$ is finitely generated as an $\mathcal{R}[f_1, \ldots, f_m]$-module.""" ,

    "theorem-7.3.5-shephard-todd-chevalley": r"""\textbf{Theorem 7.3.5 (Shephard and Todd, Chevalley)}
Every invariant of $\mathcal{G}$ is a polynomial over $\mathcal{R}$ in the basic generators $f_1, \ldots, f_m$, and hence $\mathfrak{J} = \mathcal{R}[f_1, \ldots, f_m]$.""" ,

    "proposition-7.4.1-trace-formula-series": r"""\textbf{Proposition 7.4.1}
If $T \in \mathcal{GL}(V)$ then
\[
\sum_{d=0}^{\infty} (\operatorname{tr}_d T) t^d = \det(1 - t T^{-1})^{-1}.
\]""" ,

    "proposition-7.4.2-dimension-of-projection-equals-trace": r"""\textbf{Proposition 7.4.2}
Suppose $W$ is a subspace of $V$ and $P$ is a projection of $V$ onto $W$, i.e., $PV = W$ and $P^2 = P$. Then $\dim W = \operatorname{tr} P$.""" ,

    "proposition-7.4.3-dim-invariant-via-average-trace": r"""\textbf{Proposition 7.4.3}
If $\mathcal{G} \leq \mathcal{GL}(V)$ is finite then
\[
\dim \mathfrak{J}_d = |\mathcal{G}|^{-1} \sum \{ \operatorname{tr}_d T : T \in \mathcal{G} \}.
\]""" ,

    "theorem-7.4.4-molien": r"""\textbf{Theorem 7.4.4 (Molien's Theorem)}
If $\mathcal{G} \leq \mathcal{GL}(V)$ is finite then its Molien series is
\[
\Phi(t) = \sum_{d=0}^{\infty} (\dim \mathfrak{J}_d) t^d = |\mathcal{G}|^{-1} \sum \{ \det(1 - tT)^{-1} : T \in \mathcal{G} \}.
\]""" ,

    "proposition-7.4.5-molien-series-product-form": r"""\textbf{Proposition 7.4.5}
Under the assumptions that $\mathfrak{J} = \mathcal{R}[f_1, \ldots, f_n]$ for algebraically independent homogeneous basic generators $f_i$ of degree $d_i$, the Molien series of $\mathcal{G}$ is
\[
\Phi(t) = \prod_{i=1}^{n} (1 - t^{d_i})^{-1}.
\]""" ,

    "proposition-7.4.6-uniqueness-of-basic-degrees": r"""\textbf{Proposition 7.4.6}
The degrees $d_1, d_2, \ldots, d_n$ of the basic generators are uniquely determined by $\mathcal{G}$.""" ,

    "proposition-7.4.7-order-equals-product-of-degrees": r"""\textbf{Proposition 7.4.7}
$|\mathcal{G}| = \prod_{i=1}^{n} d_i$.""" ,

    "proposition-7.4.8-number-of-reflections-formula": r"""\textbf{Proposition 7.4.8}
The number $N$ of reflections in $\mathcal{G}$ is $\sum_{i=1}^{n} (d_i - 1)$.""" ,

    "corollary-group-contains-reflection": r"""\textbf{Corollary}
If $\mathcal{G} \neq 1$ then $\mathcal{G}$ contains at least one reflection.""" ,

    "theorem-7.4.9-shephard-todd-converse": r"""\textbf{Theorem 7.4.9 (Shephard and Todd)}
Suppose $\mathcal{G} \leq \mathcal{GL}(V)$ is finite and that $\mathcal{G}$ has algebraically independent homogeneous invariants $f_1, \ldots, f_n$, $n = \dim V$, such that $\mathfrak{J} = \mathcal{R}[f_1, \ldots, f_n]$. Then $\mathcal{G}$ is generated by reflections.""" ,

    "proposition-7.4.10-no-invariant-linear-polynomials": r"""\textbf{Proposition 7.4.10}
An effective Coxeter group has no nonzero linear invariants.""" ,

    "proposition-7.4.11-coxeter-group-has-degree-2-invariant": r"""\textbf{Proposition 7.4.11}
A Coxeter group $\mathcal{G}$ has a homogeneous invariant of degree $2$, so it must have a basic generator of degree $2$.""",
}

count = 0
for slug, tex in statements.items():
    folder = os.path.join(STAGING, slug)
    tex_file = os.path.join(folder, "theorem.tex")
    if os.path.exists(folder):
        with open(tex_file, 'w') as f:
            f.write(tex + "\n")
        count += 1

print(f"Updated {count} theorem.tex files")

# Also update the .done marker
done_file = os.path.join(STAGING, ".done")
with open(done_file, 'w') as f:
    f.write("DONE\n")
print("Done.")
