import Mathlib

open scoped Classical
open Ideal
open MvPolynomial

/-!
# Algebraic Variety

An **algebraic set** `V` defined by polynomials `f₁, …, fₘ` in `F[x₁, …, xₙ]` is called
an **algebraic variety** if the ideal `⟨f₁, …, fₘ⟩` generated by those polynomials is
a prime ideal of `F[x₁, …, xₙ]`.

Equivalently, an algebraic set `V = zeroLocus(I)` is a variety iff `vanishingIdeal(V)`
is prime (by the Nullstellensatz, over an algebraically closed field).

This file formalizes the classical definition using Mathlib4's existing
`MvPolynomial.zeroLocus` and `Ideal.IsPrime`.

## Main Definitions
* `MvPolynomial.zeroLocus K I` -- the zero set of an ideal `I` of multivariate polynomials
  (defined in `Mathlib/RingTheory/Nullstellensatz.lean`)
* `IsAlgebraicVariety V` -- the predicate that a subset `V ⊆ Fⁿ` is a nonempty algebraic set
  arising from a **prime ideal** of polynomials.

## Mathlib4 Cross-References
* `MvPolynomial.zeroLocus` -- defines algebraic sets in `RingTheory/Nullstellensatz.lean`
* `MvPolynomial.vanishingIdeal` -- the ideal of polynomials vanishing on a set
* `Ideal.IsPrime` -- prime ideal typeclass in `RingTheory/Ideal/Prime.lean`
* `MvPolynomial.IsPrime.vanishingIdeal_zeroLocus` -- for a prime ideal `P`,
  `vanishingIdeal(zeroLocus(P)) = P`
-/

variable {F : Type*} [Field F] {n : ℕ}

/-- An **algebraic variety** is a nonempty subset of `Fⁿ` that can be expressed
as the zero locus of a **prime ideal** of multivariate polynomials.

Formally, `V ⊆ Fⁿ` is an algebraic variety if `V ≠ ∅` and there exists a prime
ideal `P ⊲ F[x₁, …, xₙ]` such that `V = zeroLocus F P`.

This captures the classical definition: an algebraic set defined by polynomials
`f₁, …, fₘ` is a variety exactly when the ideal `⟨f₁, …, fₘ⟩` is prime. -/
def IsAlgebraicVariety (V : Set (Fin n → F)) : Prop := by
  sorry
