import Mathlib

open MvPolynomial

/-!
# Definition of Coordinate Ring of an Algebraic Set

The coordinate ring C(A) of an algebraic set A ⊆ K^σ (where K is a field and σ is an
index type for the variables) is the ring of all polynomial functions on A, with
pointwise addition and multiplication.

Formally, C(A) = K[X_σ] / I(A), where I(A) = `vanishingIdeal K A` is the ideal of
polynomials that vanish at every point of A. The field K is identified with the constant
polynomials (via the map `k ↦ [k]`), making C(A) a ring extension of K generated by the
images of the coordinate functions `X_i`.

## Main definitions

* `coordinateRing K A` : The coordinate ring of a subset A ⊆ (σ → K), defined as the
  quotient `MvPolynomial σ K ⧸ MvPolynomial.vanishingIdeal K A`.
* `coordinateRing.mk` : The quotient map from the polynomial ring onto the coordinate ring.
* `coordinateRing.coordinate i` : The image of the variable `X_i` in the coordinate ring.

## References

* `Mathlib/RingTheory/Nullstellensatz.lean` for `vanishingIdeal` and `zeroLocus`.
-/

noncomputable section

variable (K : Type*) [Field K] {σ : Type*}

/-- The coordinate ring of a subset `A` of K^σ. This is the ring of polynomial functions
on A, obtained by quotienting the polynomial ring K[X_σ] by the ideal `I(A)` of polynomials
that vanish on A.

If A = V(J) is an algebraic set (the zero locus of an ideal J), then by the Nullstellensatz
(for algebraically closed K) the coordinate ring is K[X_σ] / √J, i.e., the reduced ring
of polynomial functions on A. For an arbitrary subset A, we take the ideal
`MvPolynomial.vanishingIdeal K A` of all polynomials that vanish everywhere on A. -/
def definition_of_coordinate_ring_of_an_algebraic_set_coordinateRing (A : Set (σ → K)) : Type _ := by
  sorry
