import Mathlib

open scoped Classical

/-!
# Description of Principal Ideal

Let `R` be a ring and `a ∈ R`. The principal two-sided ideal `(a)` consists of
all finite sums of elements of the following forms:
- `n • a` where `n : ℤ` (integer multiples)
- `r * a` where `r : R` (left multiples)
- `a * s` where `s : R` (right multiples)
- `r * a * s` where `r, s : R` (two-sided multiples)

## Relation to Mathlib4

Mathlib4's `Ideal.span {a}` is defined as a *left* ideal (via `Submodule.span R {a}`).
For commutative rings, left ideals and two-sided ideals coincide, and `Ideal.mem_span_singleton`
already gives `x ∈ span({a}) ↔ a ∣ x`. This file provides the explicit construction
of the two-sided principal ideal as an additive subgroup generated by the four basic forms.
In a `CommRing`, we prove equality with `Ideal.span {a}`.
-/

namespace description_of_principal_ideal

variable {R : Type*} [Ring R]

/-- The four types of basic generators for the principal two-sided ideal (a).
This inductive predicate captures exactly the four forms appearing in the concept. -/
inductive PrincipalIdealGen (a : R) : R → Prop
  | int_mul (n : ℤ) : PrincipalIdealGen a (n • a)
  | left_mul (r : R) : PrincipalIdealGen a (r * a)
  | right_mul (s : R) : PrincipalIdealGen a (a * s)
  | two_sided_mul (r s : R) : PrincipalIdealGen a (r * a * s)

/-- The principal two-sided ideal of `a` in `R`. It is defined as the additive subgroup
generated by the four basic forms: `n • a`, `r * a`, `a * s`, `r * a * s`.

This is the explicit construction of the (two-sided) principal ideal `(a)`. -/
def principalIdeal (a : R) : AddSubgroup R := by
  sorry
