import Mathlib

open Set
open Subgroup

set_option maxHeartbeats 800000

/-
Description of the subgroup generated by a set.

If `G` is a group and `X` is a nonempty subset of `G`, then the subgroup `⟨X⟩` generated by `X`
equals the join (in the subgroup lattice) of all cyclic subgroups `⟨a⟩` for `a ∈ X`.
In other words, every element of `⟨X⟩` is a finite product of integer powers of elements of `X`.

In particular, for a single element `a ∈ G`, `⟨a⟩ = {aⁿ | n ∈ ℤ}` (the `zpowers` of `a`).
-/

/-- The subgroup generated by a nonempty set `X` equals the supremum (join) of the cyclic
subgroups `zpowers a` for `a ∈ X`. This is the fundamental characterization theorem:
`⟨X⟩` consists of all finite products `a₁ⁿ¹ a₂ⁿ² ⋯ aₜⁿᵗ` where `aᵢ ∈ X` and `nᵢ ∈ ℤ`. -/
theorem closure_eq_iSup_zpowers_of_nonempty {G : Type*} [Group G] {X : Set G} (hX : X.Nonempty) :
    closure X = ⨆ a ∈ X, zpowers a := by
  sorry
