import Mathlib

/-!
# Existence and Uniqueness of Maximal Normal Centerless CR-subgroup

In any group `G`, there exists a unique maximal normal centerless CR-subgroup.
Moreover, this subgroup is characteristic in `G`.

## Background

A **CR-group** (completely reducible group) is a group generated by its normal nonabelian
simple subgroups. A group is **centerless** if its center is trivial.

## Mathlib4 API used

- `Subgroup.Characteristic` and `characteristic_iff_map_eq`
- `Subgroup.Normal`
- `IsSimpleGroup` (from `GroupTheory/Subgroup/Simple.lean`)
- `zorn_subset` (from `Mathlib/Order/Zorn.lean`)
- `IsChain` (from `Mathlib/Order/Preorder/Chain.lean`)
-/

open Subgroup
open Set

set_option maxHeartbeats 800000

universe u

variable {G : Type u} [Group G]

/-!
## Definitions
-/

/-- A subgroup `H` of `G` is **centerless** if the only element of `H` that commutes
with all elements of `H` is the identity. -/
def IsCenterless (H : Subgroup G) : Prop := by
  sorry
