import Mathlib

/-!
# Initial Form and Initial Form Ideal

Let `K` be a commutative ring and `σ` an index type for variables. For a nonzero polynomial
`f ∈ K[X_σ]`, write `f = Σ_{d ≥ 0} f_d` where `f_d` is the homogeneous component
of degree `d`. The **initial form** `f_in` of `f` is the lowest-degree nonzero
homogeneous component:
  `f_in := f_m` where `m = min { d | f_d ≠ 0 }`.

For an ideal `I ⊆ K[X_σ]`, the **initial form ideal** is the ideal generated by
the initial forms of all nonzero elements of `I`:
  `I_in := (f_in | f ∈ I \ {0})`.

This definition is the basis for the theory of tangent cones and the study of
singularities via associated graded rings. The initial form ideal describes the
"lowest-order" behaviour of the ideal `I` at the origin.

## Main definitions

* `MvPolynomial.initialForm f` : the homogeneous component of `f` of lowest
  total degree (returns 0 if `f = 0`).
* `initialFormIdeal I` : the ideal generated by the initial forms of all nonzero
  elements of `I`.

## References

* `Mathlib/RingTheory/MvPolynomial/Homogeneous.lean` for `homogeneousComponent` and
  `totalDegree`.
-/

open scoped BigOperators

variable {σ : Type*} {K : Type*} [CommRing K]

namespace MvPolynomial

/--
The **initial form** of a multivariate polynomial `f` over a commutative ring `K`:
the homogeneous component of lowest total degree. When `f = 0`, returns `0`.

Formally, `initialForm f` is `homogeneousComponent m f` where `m` is the minimal
natural number such that `homogeneousComponent m f ≠ 0`. This is well-defined
because `sum_homogeneousComponent` says `f = Σ_{i ≤ totalDegree f} homogeneousComponent i f`,
so for `f ≠ 0` there exists at least one `n` with a nonzero homogeneous component.
-/
noncomputable def initialForm (f : MvPolynomial σ K) : MvPolynomial σ K := by
  sorry
