import Mathlib

open scoped Classical nonZeroDivisors

/-!
# Locally Principal Ideal

A fractional ideal `I` of an integral domain `R` is called **locally principal** if for every
prime ideal `P ∈ Spec(R)`, the localization `I_P` is a principal ideal of the local ring `R_P`,
i.e., `I_P = (a)R_P` for some `a ∈ I`.

Equivalently, for each prime ideal `P`, the `R_P`-submodule of the fraction field `K`
generated by `I` is a principal submodule (spanned by a single element).

This property is fundamental in Dedekind domain theory: a Dedekind domain is precisely an
integral domain in which every nonzero fractional ideal is locally principal (and invertible).

## Mathlib4 relation

Mathlib4 provides:
- `FractionalIdeal R⁰ K` for fractional ideals of `R` in its fraction field `K`
- `IsLocalization.AtPrime RP P` for the localization of `R` at the complement of prime ideal `P`
- `Submodule.IsPrincipal` for the property of being generated by a single element
- `IsScalarTower R (Localization.AtPrime P) K` which allows viewing `K` as an `R_P`-module

There is no existing `IsLocallyPrincipal` definition in Mathlib4; this is new.

## Implementation note

Since `IsScalarTower R (Localization.AtPrime P) K` holds (the fraction field is a
localization of `R_P`), we can view the localized ideal `I_P` as the `R_P`-submodule
of `K` spanned by `I`. This avoids needing to construct a map from `K` into a separate
localization type — we work entirely within the fraction field `K`.
-/

section locally_principal_ideal

variable {R : Type*} [CommRing R] [IsDomain R] (K : Type*) [Field K]
  [Algebra R K] [IsFractionRing R K]

/-- A fractional ideal `I` of an integral domain `R` is **locally principal** if for every
prime ideal `P` of `R`, the localization `I_P` is a principal ideal of the local ring `R_P`.

Formally, we require that for each prime ideal `P`, the `R_P`-submodule of `K` spanned by
`I` (where `R_P = Localization.AtPrime P`) is principal, i.e., generated by a single
element of `K`.

Parameters:
- `R` : an integral domain
- `K` : the fraction field of `R`
- `I` : a fractional ideal of `R` in `K`

See also:
- `Mathlib/RingTheory/FractionalIdeal/Basic.lean` for the definition of `FractionalIdeal`
- `Mathlib/RingTheory/DedekindDomain/Basic.lean` for Dedekind domains where all fractional
  ideals are locally principal
- `Mathlib/RingTheory/Localization/AtPrime/Basic.lean` for localization at a prime ideal
-/
def IsLocallyPrincipal (I : FractionalIdeal R⁰ K) : Prop := by
  sorry
