import Mathlib

open scoped Classical

/-!
# Locality and Completion of Cohen–Macaulay Rings

## Statement

1. A ring `R` is Cohen–Macaulay iff `R_P` is Cohen–Macaulay for every maximal ideal `P`.
   In that case, `R_Q` is Cohen–Macaulay for every prime ideal `Q`.
2. A local ring is Cohen–Macaulay iff its completion is Cohen–Macaulay.

## References

* [M. F. Atiyah and I. G. Macdonald, *Introduction to Commutative Algebra*][atiyah1969]
* [H. Matsumura, *Commutative Ring Theory*][matsumura1986]
-/

section

variable (R : Type*) [CommRing R]

/-- A commutative ring `R` is **Cohen–Macaulay** if every ideal generated by a system of
parameters is an unmixed ideal, or equivalently, `depth I R = krullDim I` for every ideal `I`.

This is a placeholder definition — `IsCohenMacaulay` is not yet available in Mathlib4. -/
opaque IsCohenMacaulay (R : Type*) [CommRing R] : Prop

/-- **Locality of Cohen-Macaulayness.** `R` is Cohen–Macaulay iff its localization at every
maximal ideal is Cohen–Macaulay. Moreover, if `R` is Cohen–Macaulay, then its localization
at every prime ideal is Cohen–Macaulay. -/
theorem locality_of_cohen_macaulay (R : Type*) [CommRing R] :
    IsCohenMacaulay R ↔
      (∀ (P : Ideal R) [P.IsMaximal],
        ∀ (S : Type*) [CommRing S] [Algebra R S] [IsLocalization.AtPrime S P],
          IsCohenMacaulay S) := by
  sorry

/-- If `R` is Cohen–Macaulay, then `R_Q` is Cohen–Macaulay for every prime ideal `Q`. -/
theorem localization_at_prime_of_cohen_macaulay (R : Type*) [CommRing R]
    (hR : IsCohenMacaulay R) (Q : Ideal R) [Q.IsPrime]
    (S : Type*) [CommRing S] [Algebra R S] [IsLocalization.AtPrime S Q] :
    IsCohenMacaulay S := by
  sorry

/-- **Completion of Cohen-Macaulay local rings.** A local ring is Cohen–Macaulay iff its
completion (with respect to the maximal ideal) is Cohen–Macaulay. -/
theorem cohen_macaulay_iff_completion_cohen_macaulay (R : Type*) [CommRing R] [IsLocalRing R] :
    IsCohenMacaulay R ↔ IsCohenMacaulay (AdicCompletion (IsLocalRing.maximalIdeal R) R) := by
  sorry

end
