import Mathlib

open scoped Classical

/-!
# Maschke's Theorem

Let `G` be a finite group and `k` a field. The group algebra `k[G]` is semisimple
if and only if the characteristic of `k` does not divide the order of `G`.

The forward direction (`¬ ringChar k ∣ Fintype.card G → IsSemisimpleRing (MonoidAlgebra k G)`)
follows from the existing proof in `Mathlib/RepresentationTheory/Maschke.lean`.

This file provides the complete if-and-only-if statement with the converse:
if `k[G]` is semisimple, then `ringChar k ∤ |G|`.

## Proof of the converse

Assume `ringChar k ∣ |G|`. Define the norm element `z = ∑_{g∈G} e_g`.
Then `z² = |G| · z = 0` (since `|G| = 0` in `k`) and `z ≠ 0`.
The element `z` is central (conjugation by any `g` just permutes the basis),
so the two-sided ideal `I = (z)` satisfies `I² = 0`.
In a semisimple ring, every ideal is generated by an idempotent:
`I = (e)` with `e² = e`. But then `(e) = (e)² = I² = 0`, so `z = 0`, contradiction.
-/

section maschke_theorem

variable (k : Type*) [Field k] (G : Type*) [Group G] [Fintype G]

open MonoidAlgebra

/-- The norm (averaging) element `z = ∑_{g∈G} e_g` in the group algebra.
This is the sum of all standard basis elements. It is central and satisfies `z² = |G|·z`. -/
noncomputable def normElement : MonoidAlgebra k G := by
  sorry
