import Mathlib

open scoped Classical

/-!
# Purely Transcendental Extension

A field `F` is called a **purely transcendental extension** of a field `K` if
`F = K(S)`, where `S ⊆ F` and `S` is algebraically independent over `K`.

This is the typeclass `purely_transcendental_extension_IsPurelyTranscendental K F`, the transcendental dual
to Mathlib's `IsPurelyInseparable`.
-/

/-! ### Typeclass definition -/

section purely_transcendental

variable (K F : Type*) [Field K] [Field F] [Algebra K F]

/-- `purely_transcendental_extension_IsPurelyTranscendental K F` means `F` is a purely transcendental extension of `K`:
there exists a subset `S` of `F` that is algebraically independent over `K`
and generates `F` as a field extension. -/
class purely_transcendental_extension_IsPurelyTranscendental : Prop where
  exists_algebraicIndependent_generating_set : ∃ (S : Set F),
    AlgebraicIndependent K (fun x : S => (x : F)) ∧
    IntermediateField.adjoin K S = ⊤

end purely_transcendental

/-! ### Examples -/

section examples

open IntermediateField

/-- The rational function field `RatFunc K` is a purely transcendental
extension of `K` (generated by `X`). -/
example (K : Type*) [Field K] : purely_transcendental_extension_IsPurelyTranscendental K (RatFunc K) := by
  sorry
