import Mathlib

/-!
# Stable Quotient of an Ideal

Let `R` be a commutative ring, `I` an ideal of `R`, and `f ∈ R`.
The **stable quotient** of `I` with respect to `f`, denoted `I : f^∞`, is the ideal

  `I : f^∞ := { g ∈ R | ∃ n ≥ 1, f^n * g ∈ I }`

In commutative algebra, this is also called the **saturation of `I` with respect to the
multiplicative set `{1, f, f^2, …}`**. The colon ideals `I : (f^n)` form an increasing chain:

  `I ⊆ (I : f) ⊆ (I : f^2) ⊆ … ⊆ (I : f^∞)`

and the stable quotient is the union of this ascending chain.

## Main definition

* `Ideal.stableQuotient I f` : the ideal `I : f^∞`.

## Notation

* `I :ₛ f` : scoped notation for `Ideal.stableQuotient I f`.

## Source

This is definition 67 from the pipeline.

-/

namespace Ideal

/-- The **stable quotient** `I : f^∞` is the ideal consisting of all `g ∈ R` such that
`f^n * g ∈ I` for some `n ≥ 1`.

Formally: `I :ₛ f = { g : R | ∃ n : ℕ, 1 ≤ n ∧ f ^ n * g ∈ I }`.

This is also written `I : ⟨f⟩^∞` or `S_f(I)` (saturation with respect to the
multiplicative set generated by `f`) in the literature. -/
def stableQuotient {R : Type*} [CommRing R] (I : Ideal R) (f : R) : Ideal R := by
  sorry

end Ideal
