import Mathlib

open Set

/-!
# Structure of the Ω-subgroup generated by a set

If G is an Ω-group and X is a nonempty subset, then the Ω-subgroup X^Ω generated
by X consists of all elements of the form

  (x_{i₁}^{ε₁})^{ω₁} · (x_{i₂}^{ε₂})^{ω₂} · ... · (x_{i_r}^{ε_r})^{ω_r}

where x_i ∈ X, ε_i = ±1, r ≥ 0, and each ω_i is a finite sequence of operators
from Ω applied successively.

## Mathlib4 References
- `MulDistribMulAction`: `GroupAction/Defs.lean`
- `Subgroup`: `Algebra/Group/Subgroup/Defs.lean`
- `Subgroup.closure`: `Algebra/Group/Subgroup/Lattice.lean`
-/

universe u v

/-! ### Ω-subgroup definition -/

variable {Ω : Type v} [Monoid Ω] {G : Type u} [Group G] [MulDistribMulAction Ω G]

/-- An Ω-subgroup of an Ω-group G is a subgroup H that is Ω-admissible, i.e.,
for every h ∈ H and ω ∈ Ω, we have ω • h ∈ H. -/
def IsOmegaSubgroup (H : Subgroup G) : Prop := by
  sorry
