import Mathlib

open scoped TensorProduct

/-!
# Tensor Product of Modules (Definition 5.1)

Let `A` be a right module and `B` a left module over a ring `R`. For a commutative `R`
these coincide with ordinary `R`-modules. The **tensor product** `A ⊗_R B` is
constructed as follows:

1. Let `F` be the free abelian group on the set `A × B`.
2. Let `K` be the subgroup of `F` generated by all elements of the forms:
   - `(a₁ + a₂, b) - (a₁, b) - (a₂, b)` (additivity in the first factor)
   - `(a, b₁ + b₂) - (a, b₁) - (a, b₂)` (additivity in the second factor)
   - `(r·a, b) - (a, r·b)` (balanced/associative property)
3. The tensor product is the quotient group `F / K`.

In Mathlib4, `TensorProduct R A B` (notation `A ⊗[R] B`) is constructed
equivalently as the quotient of `FreeAddMonoid (A × B)` by the additive
congruence generated by the bilinearity relations. This file documents
the available API and proves the fundamental properties.

## Main concepts
* `TensorProduct R A B` : the tensor product type, notation `A ⊗[R] B`
* `tmul R a b` : the canonical map `a ⊗ₜ[R] b`, the image of `(a, b)` in the quotient
* `TensorProduct.mk R A B` : the canonical bilinear map `A →ₗ[R] B →ₗ[R] A ⊗[R] B`
* `TensorProduct.lift` : the universal property lift

## References
* Dummit & Foote, Definition 5.1 (Tensor Product)
* Mathlib: `Mathlib/LinearAlgebra/TensorProduct/Defs.lean`
-/

/-! ### Core definition (from Mathlib) -/

section Definition

variable (R : Type*) [CommSemiring R]
variable (A B : Type*) [AddCommMonoid A] [Module R A] [AddCommMonoid B] [Module R B]

/--
The tensor product `A ⊗[R] B` is Mathlib's `TensorProduct`, which follows the
textbook construction of Definition 5.1 as a quotient of `FreeAddMonoid (A × B)`
by the additive congruence of bilinearity relations.
-/
example : Type _ := A ⊗[R] B

/-- The canonical function `A → B → A ⊗[R] B` sending `(a, b)` to the
coset of the generator `(a, b)` in the quotient. -/
example (a : A) (b : B) : A ⊗[R] B := a ⊗ₜ[R] b

/-- The canonical `R`-bilinear map `A →ₗ[R] B →ₗ[R] A ⊗[R] B`. -/
example : A →ₗ[R] B →ₗ[R] A ⊗[R] B := TensorProduct.mk R A B

/-- The `TensorProduct` is an `R`-module. -/
example : Module R (A ⊗[R] B) := by infer_instance

/-- The `TensorProduct` is an additive commutative monoid. -/
example : AddCommMonoid (A ⊗[R] B) := by infer_instance

/-- Addition is commutative in the tensor product. -/
example (x y : A ⊗[R] B) : x + y = y + x := by
  sorry
