#!/bin/bash
# GTM016 Complete Concept Extraction - ALL 33 sections
# Clean slugs, proper statements and proofs
set -e
SRC="/home/a123/文档/mathpkg/pipeline_output/stitched_sections/(GTM016)The.structure.of.fields,.Winter"
DST="/home/a123/文档/mathpkg/pipeline_output/math_pkg_tmp/concepts_batch2/gtm016"
DATE="2026-06-27"
mkdir -p "$DST"

w() {
  local slug="$1" type="$2" ch="$3" sec="$4" title="$5" ch_name="$6" sec_name="$7"
  local dir="$DST/$slug"; mkdir -p "$dir"
  local subdomain="field-theory"
  [[ "$ch_name" == *"algebra"* || "$ch_name" == *"group"* || "$ch_name" == *"ring"* ]] && subdomain="abstract-algebra"
  [[ "$ch_name" == *"function"* ]] && subdomain="algebraic-geometry"
  shift 7
  local stmt="$*"
  # concept.yaml
  cat > "$dir/concept.yaml" << Y
id: $slug
title_en: "$title"
title_zh: ""
type: $type
domain: algebra
subdomain: $subdomain
difficulty: intermediate
tags: []
depends_on: {required:[], recommended:[], suggested:[]}
source_books: [{book_id:"gtm016",author:"David J. Winter",title:"The Structure of Fields",chapter:"$ch_name",section:"$sec_name",pages:"",role_in_book:""}]
content_hash: ""
extraction_date: "$DATE"
extraction_agent: "v8-full-extract"
Y
  # theorem.tex (STATEMENT ONLY)
  echo "$stmt" > "$dir/theorem.tex"
  # introduce.en.md
  cat > "$dir/introduce.en.md" << I
---
role: introduce
locale: en
content_hash: ""
written_against: ""
---

$stmt
I
  echo "OK: $slug ($type)"
}

p() {
  local slug="$1" ch="$2" sec="$3"; shift 3
  local proof="$*"
  local dir="$DST/$slug"
  [ ! -d "$dir" ] && echo "WARN: no dir for $slug" >&2 && return
  cat > "$dir/proof_gtm016_${ch}.${sec}.en.md" << P
---
role: proof
locale: en
of_concept: $slug
source_book: gtm016
source_chapter: "$ch.$sec"
source_section: "$ch.$sec"
---

$proof
P
}

e() {
  local slug="$1" ch="$2" sec="$3" num="$4"; shift 4
  local ex="$*"
  local dir="$DST/$slug"
  [ ! -d "$dir" ] && echo "WARN: no dir for $slug" >&2 && return
  cat > "$dir/exercise_gtm016_${ch}.${sec}.${num}.en.md" << X
---
role: exercise
locale: en
chapter: "$ch"
section: "$sec"
exercise_number: $num
---

$ex
X
}

echo "=== GTM016: The Structure of Fields - David J. Winter ==="
echo ""

# === Ch.0 Introduction ===
echo "--- Ch.0 ---"

# s002: 0.1.2-0.2.1
w kx-is-a-principal-ideal-domain proposition 0 1 "K[X] is a principal ideal domain" "0 Introduction" "0.1 Basic algebra" \
  "Let \$K\$ be a field. Then \$K[X]\$ is a principal ideal domain."

p kx-is-a-principal-ideal-domain 0 1 "Let \$I\$ be a nonzero ideal of \$K[X]\$. Take \$f(X)\$ to be a nonzero element of \$I\$ of least degree. For any \$g(X) \\in I \\setminus \\{0\\}\$, by the Euclidean algorithm we can write \$g(X) = f(X)h(X) + r(X)\$ where \$\\operatorname{Deg} r(X) < \\operatorname{Deg} f(X)\$. Since \$r(X) = g(X) - f(X)h(X) \\in I\$ and \$f(X)\$ has minimal degree in \$I\$, we must have \$r(X) = 0\$. Thus \$g(X) = f(X)h(X)\$ and \$I\$ is generated by \$f(X)\$."

w unique-factorization-in-kx theorem 0 1 "Unique factorization in K[X]" "0 Introduction" "0.1 Basic algebra" \
  "A nonconstant polynomial \$f(X) \\in K[X]\$ can be factored into \$f(X) = \\prod_{i=1}^m g_i(X)\$ where the \$g_i(X)\$ are monic irreducible elements of \$K[X]\$. Moreover, the factorization is unique up to ordering of the factors."

p unique-factorization-in-kx 0 1 "The existence follows by induction on \$\\operatorname{Deg} f(X)\$. The uniqueness follows from 0.1.4 (the prime divisor property for irreducible polynomials in \$K[X]\$)."

w evaluation-homomorphism-universal-property proposition 0 1 "Universal property of evaluation homomorphism" "0 Introduction" "0.1 Basic algebra" \
  "Let \$R\$ be a commutative ring containing \$x\$ and containing the field \$k\$ as subring. Then there is precisely one homomorphism \$e: k[X] \\to R\$ such that \$e(a) = a\$ for \$a \\in k\$ and \$e(X) = x\$."

w gauss-lemma-polynomial proposition 0 1 "Gauss Lemma: Product of primitive polynomials is primitive" "0 Introduction" "0.1 Basic algebra" \
  "Let \$f^*(X)\$ and \$g^*(X)\$ be primitive elements of \$k[x][X]\$. Then \$f^*(X)g^*(X)\$ is a primitive element of \$k[x][X]\$."

p gauss-lemma-polynomial 0 1 "Let \$f^*(X) = \\sum_0^m a_i(x)X^i\$ and \$g^*(X) = \\sum_0^n b_j(x)X^j\$. Let \$c(x)\$ be irreducible in \$k[x]\$. Let \$a_i\$ and \$b_j\$ be the first coefficients not divisible by \$c(x)\$. The \$(i+j)\$th coefficient of \$f^*g^*\$ is \$a_i b_j + \\sum a_{i-r}b_{j+r} + \\sum a_{i+s}b_{j-s}\$ which is not divisible by \$c(x)\$."

w lagrange-theorem-for-groups theorem 0 2 "Lagrange Theorem" "0 Introduction" "0.2 Groups" \
  "Let \$G\$ be a group, \$H\$ a subgroup of \$G\$. Then \$G:1 = (G:H)(H:1)\$. In particular, the order \$H:1\$ of any subgroup \$H\$ divides the order \$G:1\$ of \$G\$."

# s003: 0.2.2, 0.2.4
w decomposition-of-finite-nilpotent-group theorem 0 2 "Decomposition of finite nilpotent group" "0 Introduction" "0.2 Groups" \
  "Let \$G\$ be a finite nilpotent group. Then \$G = \\prod_1^n G_{p_i}\$ (inner direct product) where \$G:1 = \\prod_1^n p_i^{e_i}\$ is the prime decomposition of the order of \$G\$."

p decomposition-of-finite-nilpotent-group 0 2 "For each prime \$p_i\$ dividing \$G:1\$, the subset \$G_{p_i} = \\{g \\in G \\mid g^{p_i^f} = e \\text{ for some } f\\}\$ is a subgroup. For distinct primes \$p, q\$, elements of \$G_p\$ commute with elements of \$G_q\$. Thus the product map is a homomorphism with trivial kernel, giving \$G = \\prod_1^n G_{p_i}\$."

w element-of-exponent-order-in-nilpotent-group theorem 0 2 "Finite nilpotent group has element of exponent order" "0 Introduction" "0.2 Groups" \
  "Let \$G\$ be a finite nilpotent group. Then \$G\$ has an element of order \$\\operatorname{Exp} G\$."

p element-of-exponent-order-in-nilpotent-group 0 2 "Write \$G = \\prod G_{p_i}\$. Each \$G_{p_i}\$ has an element \$g_i\$ whose order is the exponent of \$G_{p_i}\$. Then \$g = \\prod g_i\$ has order \$\\prod p_i^{e_i}\$ which equals \$\\operatorname{Exp} G\$."

# s004: 0.3.1, 0.3.2, 0.3.3, 0.3.5
w cauchy-theorem-for-groups theorem 0 3 "Cauchy Theorem" "0 Introduction" "0.3 Transformation groups" \
  "Let \$G\$ be a finite group and let \$p\$ be a prime number dividing \$G:1\$. Then \$G\$ has an element of order \$p\$."

p cauchy-theorem-for-groups 0 3 "By induction on \$G:1\$. Use the class equation \$G:1 = C(G):1 + \\sum G:G_{x_i}\$. If any proper centralizer \$G_{x_i}\$ has order divisible by \$p\$, induction applies. Otherwise \$p\$ divides each \$G:G_{x_i}\$, so \$p\$ divides \$C(G):1\$. Since \$C(G)\$ is Abelian, it has an element of order \$p\$."

w order-of-finite-p-group-is-power-of-p corollary 0 3 "Order of a finite p-group is a power of p" "0 Introduction" "0.3 Transformation groups" \
  "Let \$p\$ be a prime number and let \$G\$ be a finite \$p\$-group. Then the order \$G:1\$ of \$G\$ is a power of \$p\$."

p order-of-finite-p-group-is-power-of-p 0 3 "If not, there exists a prime \$q \\neq p\$ dividing \$G:1\$. By Cauchy's theorem, \$G\$ has an element of order \$q\$, contradicting that \$G\$ is a \$p\$-group."

w center-of-finite-p-group-is-nontrivial theorem 0 3 "Center of nontrivial finite p-group is nontrivial" "0 Introduction" "0.3 Transformation groups" \
  "The center \$C(G)\$ of a nontrivial finite \$p\$-group \$G\$ is nontrivial."

p center-of-finite-p-group-is-nontrivial 0 3 "Using the class equation and the fact that \$G:1\$ is a power of \$p\$, each \$G:G_{x_i}\$ is divisible by \$p\$, so \$p\$ divides \$C(G):1\$. Hence \$C(G) \\neq 1\$."

w generation-of-sp-by-transposition-and-p-cycle theorem 0 3 "S(p) is generated by a transposition and a p-cycle" "0 Introduction" "0.3 Transformation groups" \
  "Let \$p\$ be a prime number. Then for any transposition \$\\sigma\$ and \$p\$-cycle \$\\tau\$ in \$S(p)\$, \$S(p)\$ is generated by \$\\sigma\$ and \$\\tau\$."

# s005: 0.4.3, 0.4.4, 0.4.5
w krull-topology-homomorphism-continuity corollary 0 4 "Continuity of homomorphism in Krull topology" "0 Introduction" "0.4 Krull topology" \
  "A homomorphism \$f\$ from \$G\$ with the Krull Topology to a group with the discrete topology is continuous if and only if the kernel of \$f\$ is a subgroup of \$G\$ of finite index."

w continuous-action-of-g-on-g-space definition 0 4 "Continuous action of G on a G-space" "0 Introduction" "0.4 Krull topology" \
  "Let \$X\$ be a \$G\$-space and let \$G\$, \$X\$, \$G \\times X\$ have the Krull, discrete, and product topologies respectively. If the product mapping \$G \\times X \\to X\$ is continuous, we say that \$G\$ acts continuously on \$X\$."

w continuous-action-iff-finite-orbits corollary 0 4 "Continuous action iff finite orbits" "0 Introduction" "0.4 Krull topology" \
  "Let \$X\$ be a \$G\$-space. Then \$G\$ acts continuously on \$X\$ if and only if the \$G\$-orbits in \$X\$ are finite."

echo "--- Ch.1: Some elementary field theory ---"

# s006: 1.1.1, 1.1.4, 1.1.5, 1.1.6, 1.1.9, 1.1.10, 1.1.11
w prime-field-of-a-field definition 1 1 "Prime field" "1 Some elementary field theory" "1.1 Preliminaries" \
  "The subfield \$\\pi(K)\$ of \$K\$ is called the prime field of \$K\$. If \$K = \\pi(K)\$, we say that \$K\$ is a prime field."

w exponent-characteristic definition 1 1 "Exponent characteristic" "1 Some elementary field theory" "1.1 Preliminaries" \
  "The exponent characteristic of \$K\$ is \$1\$ if \$\\pi(K)\$ is isomorphic to \$\\mathbb{Z}_0\$ and is \$p\$ if \$\\pi(K)\$ is isomorphic to \$\\mathbb{Z}_p\$, \$p\$ a prime number. The exponent characteristic of \$K\$ is denoted \$\\operatorname{Exp Char} K\$."

w field-extension definition 1 1 "Field extension" "1 Some elementary field theory" "1.1 Preliminaries" \
  "An extension field (or extension) of \$k\$ is a field \$K\$ containing \$k\$ as subfield together with the vector space structure over \$k\$. Such an extension field is denoted \$K/k\$. The degree of an extension \$K/k\$ is the dimension of \$K\$ over \$k\$. A subextension is an extension \$k'\$ of \$k\$ such that \$k'\$ is a subfield of \$K\$."

w k-homomorphism-and-k-isomorphism definition 1 1 "k-homomorphism and k-isomorphism" "1 Some elementary field theory" "1.1 Preliminaries" \
  "If \$K_1\$ and \$K_2\$ are extension fields of \$k\$, a \$k\$-homomorphism (resp. \$k\$-isomorphism) from \$K_1\$ to \$K_2\$ is a homomorphism (resp. isomorphism) from \$K_1\$ to \$K_2\$ which is \$k\$-linear."

w generation-by-finite-subsets proposition 1 1 "Generation of k-span, k-ring, k-field by finite subsets" "1 Some elementary field theory" "1.1 Preliminaries" \
  "\$k\\langle S \\rangle = \\bigcup_{T \\in \\mathbb{S}} k\\langle T \\rangle\$, \$k[S] = \\bigcup_{T \\in \\mathbb{S}} k[T]\$, and \$k(S) = \\bigcup_{T \\in \\mathbb{S}} k(T)\$, where \$\\mathbb{S}\$ is the set of finite subsets of \$S\$."

p generation-by-finite-subsets 1 1 "The containment \$\\supset\$ is clear. Since the right hand side contains \$S\$, it suffices to show the right hand side is a \$k\$-subspace, subring containing \$k\$, or subfield containing \$k\$ respectively. This is obvious, since finitely many elements of \$S\$ form a finite set."

w notation-for-finite-generation definition 1 1 "Notation for finite generation" "1 Some elementary field theory" "1.1 Preliminaries" \
  "Let \$s_1, \\ldots, s_n \\in K\$. Then \$k\\langle s_1, \\ldots, s_n \\rangle = k\\langle S \\rangle\$, \$k[s_1, \\ldots, s_n] = k[S]\$, and \$k(s_1, \\ldots, s_n) = k(S)\$ where \$S = \\{s_1, \\ldots, s_n\\}\$."

w simple-extension-and-primitive-element definition 1 1 "Simple extension and primitive element" "1 Some elementary field theory" "1.1 Preliminaries" \
  "If \$K = k(s)\$, then \$K/k\$ is a simple extension of \$k\$ and \$s\$ is a primitive element of the extension \$K/k\$."

# s007: 1.1.14-1.2.8
w root-field-of-polynomial definition 1 1 "Root field of a polynomial" "1 Some elementary field theory" "1.1 Preliminaries" \
  "Given a field \$k\$ and a polynomial \$f(X)\$ in \$k[X]\$, a root field of \$f(X)\$ over \$k\$ is a field extension \$K\$ of \$k\$ of the form \$K = k(s)\$ where \$f(s) = 0\$."

w existence-of-root-field proposition 1 1 "Existence of a root field" "1 Some elementary field theory" "1.1 Preliminaries" \
  "Let \$k\$ be a field, \$f(X)\$ a nonconstant polynomial in \$k[X]\$. Then \$f(X)\$ has a root field over \$k\$."

p existence-of-root-field 1 1 "Let \$g(X)\$ be an irreducible factor of \$f(X)\$ in \$k[X]\$. Then \$K = k[X]_g\$ is a root field for \$g(X)\$ over \$k\$, hence also a root field for \$f(X)\$."

w induced-homomorphism-on-polynomial-ring definition 1 1 "Induced homomorphism on polynomial ring" "1 Some elementary field theory" "1.1 Preliminaries" \
  "Let \$\\varphi\$ be a homomorphism from a field \$k\$ to a field \$k'\$. Then we let \$\\varphi\$ also denote the extension to the homomorphism \$\\varphi: k[X] \\to k'[X]\$ such that \$\\varphi(\\sum_0^n a_i X^i) = \\sum_0^n \\varphi(a_i) X^i\$."

w finite-dimensional-integral-domain-is-a-field proposition 1 2 "Finite-dimensional integral domain containing k is a field" "1 Some elementary field theory" "1.2 Algebraic extensions" \
  "Let \$A\$ be an integral domain containing \$k\$ as subfield and suppose that \$A:k < \\infty\$. Then \$A\$ is a field."

p finite-dimensional-integral-domain-is-a-field 1 2 "Let \$a \\neq 0\$ in \$A\$. Left translation \$a_L: b \\mapsto ab\$ is \$k\$-linear and injective since \$A\$ is an integral domain. By finite dimensionality it is surjective, so \$a_L(x) = 1\$ has a solution, giving \$ax = 1\$."

w algebraic-element-criterion proposition 1 2 "Characterization of algebraic elements" "1 Some elementary field theory" "1.2 Algebraic extensions" \
  "Let \$s \\in K\$. Then \$s\$ is algebraic over \$k\$ if and only if \$s\$ is contained in some finite dimensional extension \$k'\$ of \$k\$ contained in \$K\$."

p algebraic-element-criterion 1 2 "It suffices to show \$s\$ is algebraic over \$k\$ iff \$k(s):k < \\infty\$. This is true by definition (see 1.1.12)."

w algebraic-finite-subset-proposition proposition 1 2 "Finite set of algebraic elements generates finite extension" "1 Some elementary field theory" "1.2 Algebraic extensions" \
  "Let \$S\$ be a finite subset of \$K\$. Then the elements of \$S\$ are all algebraic over \$k\$ if and only if \$k(S):k < \\infty\$."

p algebraic-finite-subset-proposition 1 2 "If \$n=1\$, this follows from 1.2.2. For \$n>1\$, let \$s \\in S\$. By induction, \$k(s)(S \\setminus \\{s\\}):k(s) < \\infty\$ and \$k(s):k < \\infty\$. By transitivity of dimension, \$k(S):k < \\infty\$."

w algebraic-extension definition 1 2 "Algebraic extension" "1 Some elementary field theory" "1.2 Algebraic extensions" \
  "\$K\$ is algebraic over \$k\$ (or \$K/k\$ is algebraic) if \$s\$ is algebraic over \$k\$ for every \$s \\in K\$."

w algebraic-closure-under-generation proposition 1 2 "Closure under generation by algebraic elements" "1 Some elementary field theory" "1.2 Algebraic extensions" \
  "Let \$S\$ be a set of elements of \$K\$ which are algebraic over \$k\$. Then \$k(S)\$ is algebraic over \$k\$."

w g-stability-of-roots proposition 1 2 "G-stability of roots and finite orbits" "1 Some elementary field theory" "1.2 Algebraic extensions" \
  "For \$f(X) \\in K^G[X]\$, \$\\operatorname{Roots}_K f(X)\$ is \$G\$-stable. An element \$x \\in K\$ is algebraic over \$K^G\$ if and only if the \$G\$-orbit \$Gx\$ of \$x\$ in \$K\$ is finite."

p g-stability-of-roots 1 2 "If \$f \\in K^G[X]\$ and \$x\$ is a root, \$f(\\sigma(x)) = \\sigma(f(x)) = \\sigma(0) = 0\$. Thus roots are \$G\$-stable. If \$x\$ is algebraic over \$K^G\$, its orbit is contained in the finite set of roots of its minimum polynomial. Conversely, if \$Gx = \\{x_1,\\ldots,x_n\\}\$ is finite, let \$f(X) = \\prod(X-x_i)\$. For \$\\sigma \\in G\$, \$\\sigma(f(X)) = f(X)\$, so \$f \\in K^G[X]\$, and \$x\$ is algebraic over \$K^G\$."

echo "--- s008: 1.3-1.5 ---"

# s008: 1.4.3-1.5.3
w characterization-of-algebraically-closed-field corollary 1 4 "Characterization of algebraically closed fields" "1 Some elementary field theory" "1.4 Algebraic closure" \
  "\$k\$ is algebraically closed if and only if each \$f(X) \\in k[X]\$ has the form \$f(X) = c \\prod_i (X - s_i)\$ for suitable \$s_i \\in k\$."

w algebraic-closure-notation definition 1 4 "Algebraic closure notation" "1 Some elementary field theory" "1.4 Algebraic closure" \
  "\$k_{\\text{Alg}}\$ denotes an algebraic closure of \$k\$."

w algebraic-closure-is-algebraically-closed proposition 1 4 "The algebraic closure is algebraically closed" "1 Some elementary field theory" "1.4 Algebraic closure" \
  "\$k_{\\text{Alg}}\$ is algebraically closed."

p algebraic-closure-is-algebraically-closed 1 4 "Let \$K'\$ be an algebraic extension of \$k_{\\text{Alg}}\$. Then \$K'/k\$ is algebraic by transitivity. Thus \$K' = k_{\\text{Alg}}\$, so \$k_{\\text{Alg}}\$ is algebraically closed."

w algebraic-closure-of-algebraic-extension proposition 1 4 "Algebraic closure of an algebraic extension" "1 Some elementary field theory" "1.4 Algebraic closure" \
  "Let \$k'\$ be an algebraic extension of \$k\$. Then \$k'_{\\text{Alg}}\$ is an algebraic closure of \$k\$."

p algebraic-closure-of-algebraic-extension 1 4 "\$k'_{\\text{Alg}}\$ is algebraically closed, and \$k'_{\\text{Alg}}/k\$ is algebraic by transitivity."

w imbedding-algebraic-extension-into-algebraic-closure corollary 1 4 "Imbedding algebraic extension into algebraic closure" "1 Some elementary field theory" "1.4 Algebraic closure" \
  "If \$k'\$ is an algebraic extension of \$k\$, then there exists a \$k\$-isomorphism from \$k'\$ to a subfield of \$k_{\\text{Alg}}\$."

w algebraic-closure-of-subfield proposition 1 4 "Algebraic closure of a subfield of the algebraic closure" "1 Some elementary field theory" "1.4 Algebraic closure" \
  "If \$k'\$ is an extension of \$k\$ contained in \$k_{\\text{Alg}}\$, then \$k_{\\text{Alg}}\$ is an algebraic closure of \$k'\$."

p algebraic-closure-of-subfield 1 4 "\$k_{\\text{Alg}}\$ is algebraically closed and \$k_{\\text{Alg}}/k'\$ is algebraic."

w finiteness-of-k-homomorphisms proposition 1 4 "Finiteness of k-homomorphisms from a finite extension" "1 Some elementary field theory" "1.4 Algebraic closure" \
  "Let \$K\$ be a finite dimensional extension of \$k\$. Then the set \$\\operatorname{Hom}_k(K, k_{\\text{Alg}})\$ of \$k\$-homomorphisms from \$K\$ into \$k_{\\text{Alg}}\$ is finite."

p finiteness-of-k-homomorphisms 1 4 "Let \$s_1,\\ldots,s_n\$ be a basis for \$K/k\$. For \$\\sigma \\in \\operatorname{Hom}_k(K, k_{\\text{Alg}})\$, \$\\sigma(s_i)\$ is a root of the minimum polynomial \$f_{s_i}(X)\$. There are only finitely many choices for each \$\\sigma(s_i)\$, and \$\\sigma\$ is determined by these values."

w fixed-field-of-algebraic-closure-automorphisms proposition 1 4 "Fixed field of algebraic closure automorphisms" "1 Some elementary field theory" "1.4 Algebraic closure" \
  "\$k_{\\text{Alg}}^G = \\{s \\in k_{\\text{Alg}} \\mid f_s(X) \\text{ has only one root in } k_{\\text{Alg}}\\}\$, where \$f_s(X)\$ denotes the minimum polynomial of \$s\$ over \$k\$ for \$s \\in k_{\\text{Alg}}\$ and \$G = \\operatorname{Aut}_k k_{\\text{Alg}}\$."

p fixed-field-of-algebraic-closure-automorphisms 1 4 "If \$s \\in k_{\\text{Alg}}^G\$, then for any root \$s'\$ of \$f_s(X)\$, there is \$\\sigma \\in G\$ with \$\\sigma(s) = s'\$, so \$s = s'\$. Conversely, if \$f_s(X)\$ has only one root, then for any \$\\sigma \\in G\$, \$\\sigma(s)\$ is a root of \$f_s(X)\$, hence \$\\sigma(s) = s\$."

w orbits-under-absolute-galois-group proposition 1 4 "Orbits under absolute Galois group" "1 Some elementary field theory" "1.4 Algebraic closure" \
  "For \$s \\in k_{\\text{Alg}}\$, the minimum polynomial \$f(X)\$ of \$s\$ over \$k_{\\text{Alg}}^G\$ has distinct roots and \$\\operatorname{Roots} f(X)\$ is the orbit of \$s\$ under \$G\$."

w structure-of-finite-fields proposition 1 5 "Structure of finite fields" "1 Some elementary field theory" "1.5 Finite fields" \
  "If \$k\$ is a field extension of dimension \$m\$ of a prime field \$\\pi\$ of \$p\$ elements, then \$k\$ has \$p^m\$ elements, \$k\$ is the splitting field of \$X^{p^m} - X\$ over \$\\pi\$. Conversely, if \$p\$ is prime and \$m\$ a positive integer, the splitting field of \$X^{p^m} - X\$ over \$\\mathbb{Z}_p\$ is a field extension of dimension \$m\$ of \$\\mathbb{Z}_p\$."

w classification-of-finite-fields corollary 1 5 "Classification of finite fields" "1 Some elementary field theory" "1.5 Finite fields" \
  "The number of elements of a finite field of characteristic \$p\$ is \$p^m\$ for some \$m\$. For every \$m\$, there exists a field of characteristic \$p\$ having \$p^m\$ elements, and any two fields of \$p^m\$ elements are isomorphic."

w separability-of-finite-field-extensions corollary 1 5 "Separability of finite field extensions" "1 Some elementary field theory" "1.5 Finite fields" \
  "Let \$k\$ be a finite field and let \$s \\in k_{\\text{Alg}}\$. Then the roots in \$k_{\\text{Alg}}\$ of the minimum polynomial \$f_s(X)\$ of \$s\$ over \$k\$ are distinct."

echo "--- s009: 1.5.5-1.6.5 ---"

# s009: 1.5.5, 1.5.6, 1.5.7, 1.6.3, 1.6.4, 1.6.5
w finite-subgroup-of-units-is-cyclic proposition 1 5 "Finite subgroup of units of a field is cyclic" "1 Some elementary field theory" "1.5 Finite fields" \
  "Let \$A\$ be a finite subgroup of the group \$L^*\$ of units of a field \$L\$. Then \$A\$ is cyclic."

p finite-subgroup-of-units-is-cyclic 1 5 "Let \$m\$ be the exponent of \$A\$. Then \$A \\subset \\operatorname{Roots}_L(X^m - 1)\$, so \$A:1 \\leq m\$. But \$A\$ has a cyclic subgroup of order \$m\$ by 0.2.4. Thus \$A\$ is cyclic of order \$m\$."

w finite-field-multiplicative-group-is-cyclic corollary 1 5 "Multiplicative group of a finite field is cyclic" "1 Some elementary field theory" "1.5 Finite fields" \
  "\$K^*\$ is cyclic and \$K/k\$ is a simple extension."

p finite-field-multiplicative-group-is-cyclic 1 5 "Since \$K^*\$ is finite, it is cyclic by 1.5.5. If \$K^* = \\langle s \\rangle\$, then \$K = k(s)\$."

w galois-group-of-finite-field proposition 1 5 "Galois group of a finite field" "1 Some elementary field theory" "1.5 Finite fields" \
  "\$\\operatorname{Aut}_k K\$ is the cyclic group generated by \$\\tau\$ and \$k = K^{\\operatorname{Aut}_k K}\$."

p galois-group-of-finite-field 1 5 "Let \$K = k(s)\$. The minimum polynomial \$f_s(X)\$ has \$\\operatorname{Aut}_k K\$ acting transitively on its roots, and \$\\tau\$ generates the cyclic group of order equal to the degree."

w algebraic-independence definition 1 6 "Algebraic independence" "1 Some elementary field theory" "1.6 Transcendency basis" \
  "A subset \$S\$ of \$K\$ is algebraically independent over \$k\$ if \$s \\not\\prec S \\setminus \\{s\\}\$ for all \$s \\in S\$."

w purely-transcendental-extension definition 1 6 "Purely transcendental extension" "1 Some elementary field theory" "1.6 Transcendency basis" \
  "\$K/k\$ is purely transcendental if \$K = k(S)\$ for some algebraically independent subset \$S\$ of \$K\$ over \$k\$."

w characterization-of-algebraic-independence theorem 1 6 "Characterization of algebraic independence" "1 Some elementary field theory" "1.6 Transcendency basis" \
  "A subset \$S\$ of \$K\$ is algebraically independent over \$k\$ if and only if for any distinct elements \$s_1, \\ldots, s_n\$ of \$S\$ and any nonzero polynomial \$f(X_1, \\ldots, X_n) \\in k[X_1, \\ldots, X_n]\$, \$f(s_1, \\ldots, s_n) \\neq 0\$."

echo "--- s010: 1.6.12-1.6.13 ---"

# s010: 1.6.12, 1.6.13
w transcendency-basis definition 1 6 "Transcendency basis" "1 Some elementary field theory" "1.6 Transcendency basis" \
  "A transcendency basis for \$K/k\$ is a subset \$S\$ of \$K\$ algebraically independent over \$k\$ such that \$K/k(S)\$ is algebraic."

w existence-and-cardinality-of-transcendency-basis theorem 1 6 "Existence and cardinality of transcendency basis" "1 Some elementary field theory" "1.6 Transcendency basis" \
  "\$K/k\$ has a transcendency basis \$S\$. If \$S\$ and \$T\$ are transcendency bases for \$K/k\$, then \$S\$ and \$T\$ have the same number of elements (cardinality)."

p existence-and-cardinality-of-transcendency-basis 1 6 "By 1.6.11, \$K\$ has a maximal algebraically independent subset \$S\$, so \$K/k(S)\$ is algebraic and \$S\$ is a transcendency basis. The cardinality invariance follows from an exchange argument analogous to the proof of invariance of dimension of a vector space."

echo "--- Ch.2: The Structure of algebraic extensions ---"

# s011: 2.1.1, 2.1.2, 2.1.6, 2.2.1, 2.2.2, 2.2.3, 2.2.6, 2.2.7, 2.2.8, 2.2.9
w separable-and-radical-polynomials definition 2 1 "Separable and radical polynomials" "2 The Structure of algebraic extensions" "2.1 The structure of an irreducible polynomial" \
  "We say that \$f(X)\$ is separable over \$k\$ if the roots \$s_i\$ are pairwise distinct, and radical (or purely inseparable) over \$k\$ if the \$s_i\$ are all equal."

w separability-criterion-via-derivative proposition 2 1 "Separability criterion via derivative" "2 The Structure of algebraic extensions" "2.1 The structure of an irreducible polynomial" \
  "\$f(X)\$ is separable over \$k\$ if and only if \$f'(X) \\neq 0\$."

p separability-criterion-via-derivative 2 1 "\$f(X)\$ has a multiple root iff \$f(X)\$ and \$f'(X)\$ have a common root, i.e., iff they are not relatively prime. Since \$f\$ is irreducible, they have a common factor of positive degree iff \$f'(X) = 0\$."

w radical-exponent-corollary corollary 2 1 "Radical exponent and separability" "2 The Structure of algebraic extensions" "2.1 The structure of an irreducible polynomial" \
  "Let \$e\$ be the radical exponent of \$f(X)\$. Then \$f(X)\$ is separable over \$k\$ if and only if \$e = 0\$, and \$f(X)\$ is radical over \$k\$ if and only if \$f(X) = c(X - s)^{p^e}\$ for some \$s \\in k_{\\text{Alg}}\$."

w separable-element definition 2 2 "Separable and radical elements" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "An element \$s \\in K\$ is separable (resp. radical) over \$k\$ if its minimum polynomial \$f_s(X)\$ over \$k\$ is separable (resp. radical) over \$k\$."

w radical-element-characterization proposition 2 2 "Characterization of radical elements via fixed field" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "An element \$s \\in K\$ is radical over \$k\$ if and only if \$s \\in k_{\\text{Alg}}^G\$, where \$G = \\operatorname{Aut}_k k_{\\text{Alg}}\$."

w structure-of-radical-element proposition 2 2 "Structure of a radical element" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "If an element \$s \\in K\$ is radical over \$k\$, then its minimum polynomial has the form \$f_s(X) = g(X^p)\$ where \$g(Y)\$ is the minimum polynomial of \$s^p\$ over \$k\$. Moreover, \$k(s) \\neq k(s^p)\$ unless \$s \\in k\$."

w separable-and-radical-extensions definition 2 2 "Separable and radical extensions" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "The extension \$K/k\$ is separable (resp. radical) if each \$s \\in K\$ is separable (resp. radical) over \$k\$."

w radical-extension-characterization proposition 2 2 "Radical extension as subfield of fixed field" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "The extension \$K/k\$ is radical if and only if \$K\$ is a subfield of \$k_{\\text{Alg}}^G\$, where \$G = \\operatorname{Aut}_k k_{\\text{Alg}}\$."

w stability-of-separable-radical-under-subextension proposition 2 2 "Stability of separable/radical under subextension" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "If the extension \$K/k\$ is separable (resp. radical), then \$K/k'\$ is separable (resp. radical) for any subfield \$k'\$ of \$K\$ containing \$k\$."

w separable-radical-simple-extension-theorem theorem 2 2 "Separability/radicality via simple extension" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "Let \$s \\in K\$. Then \$s\$ is separable (resp. radical) over \$k\$ if and only if \$k(s)/k\$ is separable (resp. radical)."

p separable-radical-simple-extension-theorem 2 2 "If \$s\$ is radical, then \$s^{p^e} \\in k\$ for some \$e\$. For any \$t = \\sum a_i s^i \\in k(s)\$, we have \$t^{p^e} = \\sum a_i^{p^e} s^{p^e i} \\in k\$, so \$t\$ is radical. The separable case follows similarly."

echo "--- s012: 2.2.11-2.2.22 ---"

# s012: 2.2.11, 2.2.12, 2.2.13, 2.2.16, 2.2.17, 2.2.19, 2.2.22
w separable-and-radical-closures-in-k definition 2 2 "Separable and radical closures in K" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "We let \$k_{\\text{sep}} = \\{s \\in K \\mid s \\text{ is separable over } k\\}\$ and \$k_{\\text{rad}} = \\{s \\in K \\mid s \\text{ is radical over } k\\}\$. These are called the separable and radical closures of \$k\$ in \$K\$ respectively."

w separable-and-radical-closures-in-alg-closure definition 2 2 "Separable and radical closures in algebraic closure" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "We let \$k_{\\text{Sep}} = \\{s \\in k_{\\text{Alg}} \\mid s \\text{ is separable over } k\\}\$ and \$k_{\\text{Rad}} = \\{s \\in k_{\\text{Alg}} \\mid s \\text{ is radical over } k\\}\$. These are called the separable closure and radical closure of \$k\$."

w separable-closure-is-simple-and-radical-extension-theorem theorem 2 2 "The separable closure theorem" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "Let \$K:k < \\infty\$. Then \$k_{\\text{sep}} = k(s)\$ for some \$s \\in K\$, the extension \$K/k_{\\text{sep}}\$ is radical, and the mapping \$\\sigma \\mapsto \\sigma|_{k_{\\text{sep}}}\$ from \$\\operatorname{Hom}_k(K, k_{\\text{Alg}})\$ to \$\\operatorname{Hom}_k(k_{\\text{sep}}, k_{\\text{Alg}})\$ is a bijection."

p separable-closure-is-simple-and-radical-extension-theorem 2 2 "If \$k\$ is finite, \$K = k(s)\$ and \$K/k\$ is separable, so \$k_{\\text{sep}} = K\$. If \$k\$ is infinite, \$\\operatorname{Hom}_k(K, k_{\\text{Alg}})\$ is finite. Choose \$\\sigma_1, \\ldots, \\sigma_n\$ and let \$s\$ be such that the values \$\\sigma_i(s)\$ are all distinct. Then the minimum polynomial of \$s\$ has degree \$n\$, and one shows \$k_{\\text{sep}} = k(s)\$."

w separability-and-radical-degree definition 2 2 "Separability degree and radical degree" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "We let \$(K:k)_{\\text{sep}} = k_{\\text{sep}}:k\$ and \$(K:k)_{\\text{rad}} = K:k_{\\text{sep}}\$. The integer \$(K:k)_{\\text{sep}}\$ (resp. \$(K:k)_{\\text{rad}}\$) is called the separability degree (resp. radical degree) of \$K\$ over \$k\$. Note that \$K:k = (K:k)_{\\text{sep}}(K:k)_{\\text{rad}}\$."

w number-of-k-homomorphisms-equals-separability-degree theorem 2 2 "Number of k-homomorphisms equals separability degree" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "Let \$K:k < \\infty\$. Then the number of elements of \$\\operatorname{Hom}_k(K, k_{\\text{Alg}})\$ is \$(K:k)_{\\text{sep}}\$. If \$G\$ is a subgroup of \$\\operatorname{Aut}_kK\$, then \$G:1 = K:K^G\$. Two subgroups \$G, H\$ of \$\\operatorname{Aut}_kK\$ are equal iff their fixed fields \$K^G, K^H\$ are equal."

w separability-of-composite proposition 2 2 "Separability of composite with radical closure" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "\$K = k_{\\text{sep}}k_{\\text{rad}}\$ if and only if \$K/k_{\\text{rad}}\$ is separable."

w tensor-product-of-separable-and-radical-extensions theorem 2 2 "Tensor product of separable and radical extensions" "2 The Structure of algebraic extensions" "2.2 Separable and radical extensions" \
  "If \$k_s/k\$ and \$k_r/k\$ are finite dimensional separable and radical extensions of \$k\$ respectively, then \$\\bar{K} = k_s \\otimes k_r\$ (tensor product of \$k\$-algebras) is a field extension of \$k = 1 \\otimes k\$."

echo "--- s013: 2.3 Normal and Galois extensions ---"

# s013: 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 2.3.11, 2.3.12, 2.3.14, 2.3.15, 2.3.16
w normal-extension definition 2 3 "Normal extension" "2 The Structure of algebraic extensions" "2.3 Normal and Galois extensions" \
  "\$K/k\$ is normal if \$K\$ is stable under the group \$\\operatorname{Aut}_k k_{\\text{Alg}}\$ of \$k\$-automorphisms of \$k_{\\text{Alg}}\$."

w normality-characterization-via-automorphisms proposition 2 3 "Normality and restriction of automorphisms" "2 The Structure of algebraic extensions" "2.3 Normal and Galois extensions" \
  "\$K/k\$ is normal if and only if \$\\operatorname{Aut}_k K\$ is the set \$\\operatorname{Aut}_k k_{\\text{Alg}}|_K\$ of restrictions of elements of \$\\operatorname{Aut}_k k_{\\text{Alg}}\$ to \$K\$."

w normality-of-subextension proposition 2 3 "Normality of subextensions" "2 The Structure of algebraic extensions" "2.3 Normal and Galois extensions" \
  "Let \$K\$ be a normal algebraic extension of \$k\$ containing \$k'\$. Then the following are equivalent: (1) \$k'/k\$ is normal; (2) \$k'\$ is stable under \$\\operatorname{Aut}_k K\$; (3) \$\\operatorname{Aut}_k k' = \\operatorname{Aut}_k K|_{k'}\$."

w normality-as-splitting-field theorem 2 3 "Normality as splitting field" "2 The Structure of algebraic extensions" "2.3 Normal and Galois extensions" \
  "\$K/k\$ is normal if and only if \$K\$ is the splitting field of some set \$\\mathbf{P}\$ of irreducible polynomials in \$k[X]\$."

p normality-as-splitting-field 2 3 "If \$K\$ is the splitting field of \$\\mathbf{P}\$, then \$K = k(\\operatorname{Roots}_{k_{\\text{Alg}}} \\mathbf{P})\$ which is clearly stable under \$\\operatorname{Aut}_k k_{\\text{Alg}}\$. Conversely, if \$K/k\$ is normal, take \$\\mathbf{P}\$ to be the minimum polynomials of elements of \$K\$."

w normal-closure definition 2 3 "Normal closure" "2 The Structure of algebraic extensions" "2.3 Normal and Galois extensions" \
  "\$K^{\\text{norm}}\$ is the normal closure of \$K\$."

w fixed-field-of-normal-extension proposition 2 3 "Fixed field of a normal extension" "2 The Structure of algebraic extensions" "2.3 Normal and Galois extensions" \
  "Let \$K/k\$ be normal and \$G = \\operatorname{Aut}_k K\$. Then \$K^G = k_{\\text{rad}}\$ and \$K/k_{\\text{rad}}\$ is separable."

w decomposition-of-normal-extension corollary 2 3 "Decomposition of a normal extension" "2 The Structure of algebraic extensions" "2.3 Normal and Galois extensions" \
  "Let \$K/k\$ be normal. Then \$K = k_{\\text{sep}} k_{\\text{rad}}\$."

w galois-extension definition 2 3 "Galois extension" "2 The Structure of algebraic extensions" "2.3 Normal and Galois extensions" \
  "\$K/k\$ is Galois if \$k\$ is the fixed field \$K^G = \\{x \\in K \\mid \\sigma(x) = x \\text{ for } \\sigma \\in G\\}\$ of some subgroup \$G\$ of \$\\operatorname{Aut} K\$."

w finite-extensions-of-finite-fields-are-galois proposition 2 3 "Finite extensions of finite fields are Galois" "2 The Structure of algebraic extensions" "2.3 Normal and Galois extensions" \
  "If \$K\$ is a finite dimensional extension of a finite field \$k\$, then \$K/k\$ is Galois."

w equivalent-conditions-for-galois-extension proposition 2 3 "Equivalent conditions for Galois extension" "2 The Structure of algebraic extensions" "2.3 Normal and Galois extensions" \
  "The following conditions are equivalent: (1) \$K/k\$ is Galois; (2) \$K/k\$ is the splitting field over \$k\$ of a set of separable irreducible polynomials in \$k[X]\$; (3) \$K/k\$ is normal and separable."

w galois-stability-under-subextension corollary 2 3 "Galois stability under subextension" "2 The Structure of algebraic extensions" "2.3 Normal and Galois extensions" \
  "Let \$K/k\$ be Galois. Then \$K/k'\$ is Galois for every subfield \$k'\$ of \$K\$ containing \$k\$."

w normal-closure-is-galois corollary 2 3 "Normal closure of finite separable extension is Galois" "2 The Structure of algebraic extensions" "2.3 Normal and Galois extensions" \
  "Let \$K/k\$ be finite dimensional and separable. Then \$K^{\\text{norm}}\$ is a finite dimensional Galois extension of \$k\$ containing \$K\$ as subfield."

w structure-of-normal-extension-as-galois-times-radical theorem 2 3 "Normal extension = Galois x radical" "2 The Structure of algebraic extensions" "2.3 Normal and Galois extensions" \
  "\$K/k\$ is normal if and only if \$K = k_{\\text{sep}}k_{\\text{rad}}\$ and \$k_{\\text{sep}}/k\$ is Galois."

p structure-of-normal-extension-as-galois-times-radical 2 3 "If \$K/k\$ is normal, then \$K = k_{\\text{sep}}k_{\\text{rad}}\$ by 2.3.9. And \$k_{\\text{sep}}\$ is stable under \$\\operatorname{Aut}_k K\$, so \$k_{\\text{sep}}/k\$ is normal by 2.3.3, hence Galois by 2.3.12. Conversely, if \$K = k_{\\text{sep}}k_{\\text{rad}}\$ and \$k_{\\text{sep}}/k\$ is Galois, then both factors are stable under \$\\operatorname{Aut}_k k_{\\text{Alg}}\$, so \$K/k\$ is normal."

echo "--- s014: 2.4 Composites ---"

# s014: 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9
w normal-galois-lifting-to-composite proposition 2 4 "Lifting normal/Galois to composite" "2 The Structure of algebraic extensions" "2.4 Composites" \
  "Let \$A, B\$ be subfields of \$K\$ containing \$k\$. Suppose that \$A/k\$ is algebraic and normal (resp. Galois). Then \$AB/B\$ is normal (resp. Galois) and \$A\$ is stable under \$\\operatorname{Aut}_B AB\$. Furthermore, the groups \$\\operatorname{Aut}_B AB\$ and \$\\operatorname{Aut}_{A \\cap B} A\$ are isomorphic under restriction."

w normal-composite-proposition proposition 2 4 "Normal composite and product of automorphism groups" "2 The Structure of algebraic extensions" "2.4 Composites" \
  "Let \$A, B\$ be subfields of \$K\$ containing \$k\$ and suppose that \$A/k\$ and \$B/k\$ are algebraic and normal. Then the homomorphism \$f: \\operatorname{Aut}_k AB \\to \\operatorname{Aut}_k A \\times \\operatorname{Aut}_k B\$ defined by \$f(\\sigma) = \\sigma|_A \\times \\sigma|_B\$ is injective."

w injective-group-property definition 2 4 "Injective group property" "2 The Structure of algebraic extensions" "2.4 Composites" \
  "A property \$P\$ of groups is injective if whenever a group has \$P\$, so do all of its subgroups and quotient groups."

w p-extension definition 2 4 "P-extension" "2 The Structure of algebraic extensions" "2.4 Composites" \
  "An extension \$K/k\$ is a \$P\$-extension if \$K/k\$ is separable algebraic and \$\\operatorname{Aut} K^{\\text{norm}}/k\$ has \$P\$."

w cyclic-abelian-solvable-extensions definition 2 4 "Cyclic, Abelian, solvable extensions" "2 The Structure of algebraic extensions" "2.4 Composites" \
  "If \$K/k\$ is a \$P\$-extension where \$P\$ is the property of being cyclic (resp. Abelian, solvable, of exponent dividing \$n\$), then \$K/k\$ is said to be cyclic (resp. Abelian, solvable, of separable exponent dividing \$n\$)."

w p-extension-composite-property proposition 2 4 "Composite of P-extensions" "2 The Structure of algebraic extensions" "2.4 Composites" \
  "Let \$A, B\$ be subfields of \$K\$ containing \$k\$. If \$P\$ is injective and \$A/k, B/k\$ are \$P\$-extensions, then \$AB/k\$ is a \$P\$-extension. In particular, if \$A/k, B/k\$ are Abelian (resp. solvable), then \$AB/k\$ is Abelian (resp. solvable)."

echo "--- s015: Ch.3 Galois theory ---"

# s015: 3.1.1, 3.1.3 (Dedekind), 3.2.1, 3.2.2, 3.2.4, 3.2.5 (Speiser)
w linear-independence-of-endomorphisms theorem 3 1 "Linear independence of endomorphisms" "3 Galois theory" "3.1 Linear independence of homomorphisms" \
  "If \$\\sum_1^n \\sigma_i v_i = 0\$ with distinct endomorphisms \$\\sigma_i\$ and vectors \$v_i\$, then \$v_1 = \\cdots = v_n = 0\$."

w dedekind-independence-theorem corollary 3 1 "Dedekind Independence Theorem" "3 Galois theory" "3.1 Linear independence of homomorphisms" \
  "Let \$\\sigma_1, \\ldots, \\sigma_n\$ be distinct homomorphisms from a field \$K\$ to a field \$L\$. Then \$\\sigma_1, \\ldots, \\sigma_n\$ are linearly independent over \$L\$ in the vector space of functions from \$K\$ to \$L\$."

w algebraic-subgroup definition 3 2 "Algebraic subgroup of Aut K" "3 Galois theory" "3.2 Galois correspondences" \
  "A subgroup \$G\$ of \$\\operatorname{Aut} K\$ is algebraic if the orbits of \$G\$ in \$K\$ are finite."

w g-product-on-vector-space definition 3 2 "G-product on a vector space" "3 Galois theory" "3.2 Galois correspondences" \
  "A \$G\$-product on a vector space \$V\$ over \$K\$ is a mapping from \$G \\times V\$ to \$V\$, denoted \$(\\sigma, v) \\mapsto \\sigma(v)\$, satisfying certain natural axioms."

w averaging-under-finite-group proposition 3 2 "Averaging under finite group action" "3 Galois theory" "3.2 Galois correspondences" \
  "Let \$G\$ be finite, let \$V\$ be a vector space over \$K\$, and let \$\\sigma(v)\$ be a \$G\$-product on \$V\$. For \$v \\in V\$, let \$\\bar{v} = \\sum_{\\sigma \\in G} \\sigma(v)\$. Then \$\\bar{v} \\in V^G\$ and for each nonzero \$v \\in V\$, there exists \$a \\in K\$ such that \$\\overline{av} \\neq 0\$."

w speiser-theorem theorem 3 2 "Speiser's Theorem" "3 Galois theory" "3.2 Galois correspondences" \
  "Let \$V\$ be a vector space over \$K\$ and \$\\sigma(v)\$ a continuous \$G\$-product on \$V\$ with \$G\$ an algebraic subgroup of \$\\operatorname{Aut} K\$. Then \$V^G\$ is a \$K^G\$-form of \$V\$, i.e., \$V = K \\otimes_{K^G} V^G\$."

echo "--- s016: 3.2.6-3.3.6 ---"

# s016: 3.2.6, 3.2.7, 3.3.1, 3.3.2, 3.3.5, 3.3.6
w g-forms-and-g-products-bijection proposition 3 2 "Bijection between G-forms and G-products" "3 Galois theory" "3.2 Galois correspondences" \
  "Let \$G\$ be algebraic and let \$V\$ be a vector space over \$K\$. Then there is a bijection between the set of \$K^G\$-forms of \$V\$ and the set of \$G\$-products on \$V\$ such that the orbits of \$G\$ in \$V\$ are finite."

w galois-action-on-functions definition 3 2 "Galois action on function spaces" "3 Galois theory" "3.2 Galois correspondences" \
  "For \$f \\in \\mathbf{F}(X, K)\$ and \$\\sigma \\in G\$, let \$\\sigma(f)\$ be the element of \$\\mathbf{F}(X, K)\$ defined by \$\\sigma(f)(x) = \\sigma(f(x))\$."

w galois-subgroup definition 3 3 "Galois subgroup of Aut K" "3 Galois theory" "3.3 Galois correspondence" \
  "\$G\$ is Galois if \$G = \\operatorname{Aut}_k K\$ for some subfield \$k\$ of \$K\$."

w galois-correspondence-bijection proposition 3 3 "Galois correspondence is a bijection" "3 Galois theory" "3.3 Galois correspondence" \
  "\$\\Gamma\$ is a bijection from the set \$\\mathbf{F}\$ of subfields of \$K\$ to the set \$\\mathbf{G}\$ of Galois subgroups of \$\\operatorname{Aut} K\$."

w algebraic-closure-of-subgroups proposition 3 3 "Fixed fields and closures of subgroups" "3 Galois theory" "3.3 Galois correspondence" \
  "Suppose that \$G\$ is algebraic and let \$H, H'\$ be subgroups of \$G\$. Then \$K^{\\bar{H}} = K^H\$, and \$K^H = K^{H'}\$ if and only if \$\\bar{H} = \\bar{H}'\$."

w algebraic-automorphism-group-corollary corollary 3 3 "Algebraicity of automorphism group" "3 Galois theory" "3.3 Galois correspondence" \
  "Let \$K/k\$ be algebraic. Then \$\\operatorname{Aut}_k K\$ is algebraic and the Galois subgroups of \$\\operatorname{Aut}_k K\$ are precisely the closed subgroups in the Krull topology."

echo "--- s017-s023: more Ch.3 ---"

# s017: 3.3.8, 3.3.11, 3.3.12
w finite-number-of-subfields proposition 3 3 "Finitely many subfields for finite separable extension" "3 Galois theory" "3.3 Galois correspondence" \
  "Let \$K/k\$ be a finite dimensional separable extension. Then \$K/k\$ has only finitely many subfields."

p finite-number-of-subfields 3 3 "Since \$K^{\\text{norm}}/k\$ is finite dimensional Galois, the Galois group is finite, so it has only finitely many subgroups. By the Galois correspondence, there are only finitely many subfields between \$k\$ and \$K\$."

w galois-correspondence-for-subfields proposition 3 3 "Galois correspondence for subfields and subgroups" "3 Galois theory" "3.3 Galois correspondence" \
  "Let \$K/k\$ be Galois and \$G = \\operatorname{Aut}_k K\$. Then the mappings \$k' \\mapsto \\operatorname{Aut}_{k'} K\$ and \$H \\mapsto K^H\$ are inverse bijections between the set of subfields \$k'\$ of \$K\$ containing \$k\$ and the set of subgroups \$H\$ of \$G\$."

w disjoint-product-and-tensor-product corollary 3 3 "Disjoint product and tensor product of Galois extensions" "3 Galois theory" "3.3 Galois correspondence" \
  "Let \$K/k\$ be an algebraic Galois extension and \$K = k_1 \\cdots k_n\$ (disjoint product over \$k\$). Then \$k_1 \\otimes_k \\cdots \\otimes_k k_n\$ and \$K\$ are \$k\$-isomorphic via the mapping \$x_1 \\otimes \\cdots \\otimes x_n \\mapsto x_1 \\cdots x_n\$."

# s018: 3.4.3, 3.5.3
w normal-basis-theorem theorem 3 4 "Normal Basis Theorem" "3 Galois theory" "3.4 The normal basis theorem" \
  "Let \$K/k\$ be a finite dimensional Galois extension and let \$\\operatorname{Aut}_k K = \\{\\sigma_1, \\ldots, \\sigma_n\\}\$. Then \$\\sigma_1(y), \\ldots, \\sigma_n(y)\$ is a basis for \$K\$ over \$k\$ for some \$y \\in K\$."

w polynomial-identity-criterion theorem 3 5 "Polynomial identity criterion for k-homomorphisms" "3 Galois theory" "3.5 Polynomial identities" \
  "Let \$k\$ be an infinite field, \$K\$ and \$L\$ extension fields of \$k\$, and \$L'\$ an extension of \$L\$. Let \$\\sigma_1, \\ldots, \\sigma_n\$ be distinct \$k\$-homomorphisms from \$K\$ to \$L\$. Then for \$f(X_1, \\ldots, X_n) \\in L'[X_1, \\ldots, X_n]\$, the function \$f(\\sigma_1, \\ldots, \\sigma_n)\$ is \$0\$ if and only if the polynomial \$f\$ is \$0\$."

# s019: 3.7.1, 3.7.4, 3.7.5, 3.7.6, 3.7.11, 3.7.12, 3.7.13
w cyclic-group-cohomology-bijection proposition 3 7 "Bijection for cyclic group cohomology" "3 Galois theory" "3.7 Galois cohomology" \
  "Let \$G\$ be cyclic of order \$n\$ with generator \$\\sigma\$ and let \$N_\\sigma(h) = \\sigma^{n-1}(h) \\cdots \\sigma(h)h\$. Then \$Z^1(G, H)\$ is mapped bijectively to \$\\{h \\in H \\mid N_\\sigma(h) = e_H\\}\$ by \$f \\mapsto f(\\sigma)\$."

w hilbert-theorem-90-multiplicative corollary 3 7 "Hilbert's Theorem 90 (multiplicative form)" "3 Galois theory" "3.7 Galois cohomology" \
  "Let \$\\sigma\$ be an element of \$\\operatorname{Aut} K\$ of finite order and let \$y \\in K\$ such that \$N_\\sigma(y) = 1\$. Then \$y = \\sigma(x^{-1})x\$ for some \$x \\in K\$."

w hilbert-theorem-90-additive corollary 3 7 "Hilbert's Theorem 90 (additive form)" "3 Galois theory" "3.7 Galois cohomology" \
  "Let \$\\sigma\$ be an element of \$\\operatorname{Aut} K\$ of finite order and let \$y \\in K\$ such that \$\\operatorname{Tr}_\\sigma(y) = 0\$. Then \$y = x - \\sigma(x)\$ for some \$x \\in K\$."

w cohomologous-cocycles-finite-images proposition 3 7 "Cohomologous cocycles have finite image" "3 Galois theory" "3.7 Galois cohomology" \
  "Let \$\\sigma \\in \\operatorname{Aut} K\$ and let \$f, g \\in Z^1(G, H)\$ be cohomologous. Then the images of \$f\$ and \$g\$ are finite."

w every-coboundary-is-continuous corollary 3 7 "Every coboundary is continuous" "3 Galois theory" "3.7 Galois cohomology" \
  "Every coboundary \$B^1(G, H)\$ is continuous in the Krull topology."

w continuous-cohomology-group definition 3 7 "Continuous first cohomology group" "3 Galois theory" "3.7 Galois cohomology" \
  "\$H^1(G, H)^{\\text{cont}}\$ is the set of equivalence classes in \$Z^1(G, H)^{\\text{cont}}\$. If \$Z^1(G, H)^{\\text{cont}} = B^1(G, H)\$, we say that \$H^1(G, H)^{\\text{cont}} = 1\$."

w vanishing-of-continuous-h1-of-kstar theorem 3 7 "Vanishing of continuous H^1 of K*" "3 Galois theory" "3.7 Galois cohomology" \
  "Let \$G\$ be an algebraic subgroup of \$\\operatorname{Aut} K\$. Then \$H^1(G, K^*)^{\\text{cont}} = 1\$."

# s020: 3.8.3, 3.9.1, 3.9.2
w cyclotomic-extension-structure proposition 3 8 "Structure of cyclotomic extensions" "3 Galois theory" "3.8 Cyclotomic extensions" \
  "Let \$n\$ and \$p\$ be relatively prime and let \$K\$ be the cyclotomic extension of \$X^n - 1\$ over \$k\$. Then \$K\$ contains \$\\varphi(n)\$ primitive \$n\$th roots of unity, and if \$x\$ is any primitive \$n\$th root of unity in \$K\$, then \$K = k(x)\$. The extension \$K/k\$ is Galois, \$\\operatorname{Aut}_k K\$ is Abelian (cyclic if \$n\$ is prime), and \$\\operatorname{Aut}_k K\$ is isomorphic to a subgroup of \$\\mathbb{Z}_n^*\$."

w abelian-extension-is-galois proposition 3 9 "Abelian extension is Galois" "3 Galois theory" "3.9 Decomposition of Abelian extensions" \
  "An Abelian extension \$K/k\$ is Galois."

w decomposition-of-abelian-extension proposition 3 9 "Decomposition of finite Abelian extension" "3 Galois theory" "3.9 Decomposition of Abelian extensions" \
  "Let \$K/k\$ be finite dimensional and Abelian. Then \$K = k_1 \\cdots k_n\$ (disjoint product over \$k\$) where, for each \$i\$, \$k_i\$ is a cyclic extension of \$k\$ of prime power degree."

# s021: 3.9.8, 3.9.10
w witt-vectors-of-length-e definition 3 9 "Witt vectors of length e" "3 Galois theory" "3.9 Witt vectors" \
  "\$W_e K = \\{x = (x_0, \\ldots, x_{e-1}) \\mid x_i \\in K \\text{ for } 0 \\leq i \\leq e-1\\}\$."

w witt-vector-fixed-point-proposition proposition 3 9 "Fixed point in Witt vectors under Artin-Schreier" "3 Galois theory" "3.9 Witt vectors" \
  "Let \$\\sigma \\in \\operatorname{Aut} K\$ have finite order \$p^f\$ dividing \$p^e\$. Then there exists \$x \\in W_e K\$ such that \$\\sigma(x) = x + 1_f\$."

p witt-vector-fixed-point-proposition 3 9 "This is the additive analogue of Hilbert's Theorem 90 for Witt vectors. The proof proceeds by induction on \$e\$ using the Artin-Schreier operators."

# s022: 3.10.2
w kummer-theorem theorem 3 10 "Kummer's Theorem" "3 Galois theory" "3.10 Kummer theory" \
  "Let \$k\$ contain the multiplicative group \$E_n\$ of \$n\$th roots of unity in \$k_{\\text{Alg}}\$ and let \$n = mp^e\$ where \$m\$ and \$p\$ are relatively prime. Then \$\\operatorname{Hom}(G, E_m)\$ and \$k^*/k^{m^e}\$ are canonically isomorphic."

# s023: 3.11.3, 3.12.1
w solvable-by-radicals-theorem theorem 3 11 "Solvable if and only if solvable by radicals" "3 Galois theory" "3.11 Solvability by radicals" \
  "Let \$K/k\$ be a finite dimensional separable extension. Then \$K/k\$ is solvable if and only if \$K/k\$ is solvable by radicals."

w galois-fundamental-theorem theorem 3 12 "Fundamental Theorem of Galois Theory" "3 Galois theory" "3.12 The fundamental theorem of Galois theory" \
  "Let \$K/k\$ be a finite dimensional Galois extension with Galois group \$G = \\operatorname{Aut}_k K\$. Then there is a one-to-one correspondence between subfields \$k' \subseteq K\$ containing \$k\$ and subgroups \$H \\subseteq G\$, given by \$k' \\mapsto \\operatorname{Aut}_{k'} K\$ with inverse \$H \\mapsto K^H\$. Moreover, \$k'/k\$ is normal (resp. Galois) iff \$H\$ is normal in \$G\$, and in that case \$\\operatorname{Aut}_k k' \\cong G/H\$."

echo "--- s024-s027: Ch.4 Algebraic function fields ---"

# s024: 4.1.1, 4.1.2
w algebraic-function-field definition 4 1 "Algebraic function field" "4 Algebraic function fields" "4.1 Algebraic function fields" \
  "An algebraic function field over \$k\$ is a field extension \$K\$ of \$k\$ of the form \$K = k(x_1, \\ldots, x_n)\$."

w affine-variety definition 4 1 "Affine variety over k" "4 Algebraic function fields" "4.1 Algebraic function fields" \
  "An affine variety over \$k\$ is the set \$V = \\operatorname{Spec}_k k[x_1, \\ldots, x_n]\$ of \$k\$-linear ring homomorphisms from a subring \$k[x_1, \\ldots, x_n]\$ of a field extension \$L\$ of \$k\$ to an algebraically closed field."

# s025: 4.2.1, 4.3.1, 4.3.2
w lueroth-theorem theorem 4 2 "Lueroth's Theorem" "4 Algebraic function fields" "4.2 Lueroth's theorem" \
  "Let \$x\$ be transcendental over \$k\$ and let \$k'\$ be a subfield of \$k(x)\$ properly containing \$k\$. Then \$k' = k(y)\$ for some transcendental element \$y\$ over \$k\$."

p lueroth-theorem 4 2 "Let \$y \\in k' \\setminus k\$ and write \$y = u(x)/v(x)\$ with \$u, v\$ relatively prime in \$k[x]\$. Let \$n = \\max(\\deg u, \\deg v)\$. Then \$[k(x):k(y)] = n\$ and \$k' = k(y)\$ follows from degree considerations."

w derivation-definition definition 4 3 "Derivation" "4 Algebraic function fields" "4.3 Derivations and p-bases" \
  "A derivation from \$K\$ to \$L\$ over \$k\$ is a \$k\$-linear mapping \$D: K \\to L\$ such that \$D(xy) = D(x)y + xD(y)\$ for \$x, y \\in K\$. The set of derivations is denoted \$\\operatorname{Der}_k(K, L)\$. The derivations \$\\operatorname{Der}_k(K, K)\$ are called derivations of \$K/k\$, and form the derivation algebra."

w extension-of-derivations proposition 4 3 "Extension of derivations to separable extensions" "4 Algebraic function fields" "4.3 Derivations and p-bases" \
  "Let \$k'\$ be a subfield of \$K\$ containing \$k\$ and suppose that \$K/k'\$ is a finite dimensional separable extension. Then each derivation \$D'\$ from \$k'\$ to \$L\$ over \$k\$ has a unique extension to a derivation \$D\$ from \$K\$ to \$L\$ over \$k\$."

# s026: 4.3.5, 4.3.6, 4.3.7, 4.3.13
w p-basis definition 4 3 "p-basis" "4 Algebraic function fields" "4.3 Derivations and p-bases" \
  "A \$p\$-basis for an extension \$K/k\$ is a subset \$S\$ of \$K\$ such that \$K = k(K^p)(S)\$ and \$K \\neq k(K^p)(T)\$ for any proper subset \$T \\subsetneq S\$."

w existence-of-derivations-from-p-basis proposition 4 3 "Existence of derivations dual to p-basis" "4 Algebraic function fields" "4.3 Derivations and p-bases" \
  "Let \$S\$ be a \$p\$-basis for an extension \$K/k\$. Then for each \$s \\in S\$, there exists \$D_s \\in \\operatorname{Der}_k K\$ such that \$D_s(t) = \\delta_{st}\$ for all \$t \\in S\$."

w cardinality-of-p-basis-equals-derivation-dimension corollary 4 3 "Cardinality of p-basis equals derivation dimension" "4 Algebraic function fields" "4.3 Derivations and p-bases" \
  "Let \$K/k\$ be an algebraic function field and let \$p > 1\$. Then for any \$p\$-basis \$S\$ of \$K/k\$, the number of elements \$|S|\$ of \$S\$ is the dimension \$\\operatorname{Der}_k K : K\$ of \$\\operatorname{Der}_k K\$ over \$K\$."

w separable-extension-in-characteristic-p definition 4 3 "Separable extension (characteristic p definition)" "4 Algebraic function fields" "4.3 Derivations and p-bases" \
  "An extension \$K/k\$ is separable if for any algebraically closed field \$L\$ containing \$K\$, \$K\$ and \$k^{p^{-1}}\$ are linearly disjoint over \$k\$. (If \$p = 1\$, every extension is separable.)"

# s027: 4.3.15, 4.3.18, 5.1.1, 5.1.3, 5.1.4, 5.1.5, 5.1.6, 5.1.8, 5.1.9, 5.2.5, 5.2.7, 5.2.8
w purely-transcendental-is-separable proposition 4 3 "Purely transcendental extensions are separable" "4 Algebraic function fields" "4.3 Derivations and p-bases" \
  "Let \$K/k\$ be purely transcendental. Then \$K/k\$ is separable."

w maclane-theorem-separably-generated theorem 4 3 "MacLane's Theorem: separable iff separably generated" "4 Algebraic function fields" "4.3 Derivations and p-bases" \
  "Let \$K/k\$ be an algebraic function field. Then \$K/k\$ is separable if and only if \$K/k\$ is separably generated."

w k-subring-of-end-k definition 5 1 "K-subring of End K" "5 Higher derivation rings" "5.1 Higher derivation rings" \
  "A \$K\$-subring of \$\\operatorname{End} K\$ is a subring \$\\mathcal{A}\$ of \$\\operatorname{End} K\$ which is a \$K\$-subspace of \$\\operatorname{End} K\$."

w a-dual definition 5 1 "A-dual of a K-subring" "5 Higher derivation rings" "5.1 Higher derivation rings" \
  "\$\\mathcal{A}^A = \\{R \\in \\mathcal{A} \\mid T(xR) = T(x)R \\text{ for all } T \\in \\mathcal{A}, x \\in K\\}\$."

w characterization-of-a-dual proposition 5 1 "Characterization of A-dual" "5 Higher derivation rings" "5.1 Higher derivation rings" \
  "Let \$K_0\$ be a subset of \$K\$ such that \$\\hat{K}_0\$ separates \$\\mathcal{A}\$. Then \$\\mathcal{A}^A = \\{R \\in \\mathcal{A} \\mid R(K_0) \\subset K^A\\}\$."

w a-dual-as-operators-preserving-fixed-field corollary 5 1 "A-dual as operators preserving fixed field" "5 Higher derivation rings" "5.1 Higher derivation rings" \
  "\$\\mathcal{A}^A = \\{R \\in \\mathcal{A} \\mid R(K) \\subset K^A\\}\$."

w finite-dimensional-a-dual-theorem theorem 5 1 "Finite-dimensional A-dual theorem" "5 Higher derivation rings" "5.1 Higher derivation rings" \
  "Let \$\\mathcal{A} : K < \\infty\$. Then \$\\mathcal{A}^A\$ is a \$K^A\$-form of \$\\mathcal{A}\$ and \$\\mathcal{A}:K = K:K^A\$."

w a-product-on-vector-space definition 5 1 "A-product on a vector space" "5 Higher derivation rings" "5.1 Higher derivation rings" \
  "An \$\\mathcal{A}\$-product on \$V\$ is a mapping \$\\mathcal{A} \\times V \\to V\$, denoted \$(T, v) \\mapsto T(v)\$, satisfying natural linearity and compatibility axioms."

w ground-subspace-of-a-product definition 5 1 "Ground subspace of an A-product" "5 Higher derivation rings" "5.1 Higher derivation rings" \
  "The ground subspace of a vector space \$V\$ over \$K\$ with \$\\mathcal{A}\$-product is the \$K^{\\mathcal{A}}\$-subspace \$V^{\\mathcal{A}} = \\{v \\in V \\mid T(xv) = T(x)v \\text{ for all } T \\in \\mathcal{A}, x \\in K\\}\$."

w finite-dimensional-derivation-ring-theorem theorem 5 2 "Finite-dimensional derivation ring theorem" "5 Higher derivation rings" "5.2 Derivation rings" \
  "Let \$\\mathcal{D}:K < \\infty\$. Then \$\\mathcal{D}\$ has a \$p\$-basis of cardinality \$\\mathcal{D}:K\$."

w d-product-on-vector-space definition 5 2 "D-product on a vector space" "5 Higher derivation rings" "5.2 Derivation rings" \
  "A \$\\mathcal{D}\$-product on \$V\$ is a mapping \$\\mathcal{D} \\times V \\to V\$, denoted \$(D, v) \\mapsto D(v)\$, satisfying natural linearity and Leibniz-type axioms."

w ground-subspace-of-d-product definition 5 2 "Ground subspace of a D-product" "5 Higher derivation rings" "5.2 Derivation rings" \
  "The ground subspace of a vector space \$V\$ with \$\\mathcal{D}\$-product is the \$K^p\$-subspace \$V^p = \\{v \\in V \\mid D(xv) = D(x)v \\text{ for all } x \\in K, D \\in \\mathcal{D}\\}\$."

echo "--- s028-s029: Ch.5 continued ---"

# s028: 5.3.1, 5.3.2, 5.3.3, 5.3.7, 5.3.8, 5.3.10
w coclosed-subset definition 5 3 "Coclosed subset of End K" "5 Higher derivation rings" "5.3 Coclosed subsets and Hopf algebras" \
  "A coclosed subset of \$\\operatorname{End} K\$ (resp. \$\\operatorname{End}_k K\$) is a subset \$H\$ such that for each \$x \\in H\$, there exist \$x_1, \\ldots, x_n \\in H\$ with \$x(ab) = \\sum_i x(a)x_i(b)\$ for all \$a, b \\in K\$. A \$K\$-subbiring is a coclosed \$K\$-subring."

w hopf-algebra-of-endomorphisms definition 5 3 "Hopf algebra H(K) of endomorphisms" "5 Higher derivation rings" "5.3 Coclosed subsets and Hopf algebras" \
  "\$H(K)\$ (resp. \$H(K/k)\$) is the union of all coclosed subsets of \$\\operatorname{End} K\$ (resp. \$\\operatorname{End}(K/k)\$)."

w product-of-coclosed-subsets proposition 5 3 "Product of coclosed subsets is coclosed" "5 Higher derivation rings" "5.3 Coclosed subsets and Hopf algebras" \
  "For any two coclosed subsets \$H_1, H_2\$ of \$\\operatorname{End} K\$, the set \$H_1H_2 = \\{xy \\mid x \\in H_1, y \\in H_2\\}\$ is a coclosed subset."

w comultiplication-properties proposition 5 3 "Properties of comultiplication and counit" "5 Higher derivation rings" "5.3 Coclosed subsets and Hopf algebras" \
  "\$\\Delta\$ and \$\\varepsilon\$ are \$K\$-linear mappings satisfying the coalgebra axioms."

w hopf-algebra-structure-proposition proposition 5 3 "Hopf algebra structure of H(K)" "5 Higher derivation rings" "5.3 Coclosed subsets and Hopf algebras" \
  "\$H(K)\$ has the structure of a Hopf algebra over \$K\$ with comultiplication \$\\Delta\$, counit \$\\varepsilon\$, and antipode."

w hopf-algebra-characterization-theorem theorem 5 3 "H(K/k) = End_k K for finite extensions" "5 Higher derivation rings" "5.3 Coclosed subsets and Hopf algebras" \
  "For a finite dimensional extension \$K/k\$, \$H(K/k) = \\operatorname{End}_k K\$."

# s029: 5.3.15-5.3.21
w primitive-subspace definition 5 3 "Primitive subspace S^0" "5 Higher derivation rings" "5.3 Coclosed subsets and Hopf algebras" \
  "For \$S \\subset H\$, \$S^0 = \\{x \\in S \\mid \\varepsilon_H(x) = 0\\}\$."

w primitive-element definition 5 3 "Primitive element of a Hopf algebra" "5 Higher derivation rings" "5.3 Coclosed subsets and Hopf algebras" \
  "An element \$x \\in H\$ is primitive if \$\\varepsilon_H(x) = 0\$ and \$\\Delta_H x = x \\otimes I + I \\otimes x\$. The set of primitive elements is denoted \$D(H)\$. An element \$x\$ is primitive modulo \$S\$ if \$\\varepsilon_H(x) = 0\$ and \$\\Delta_H x = x \\otimes I + I \\otimes x + \\sum_{i \\geq 3} {}_i x \\otimes x_i\$ with \${}_i x, x_i \\in S^0\$."

w filtration-of-hopf-algebra definition 5 3 "Filtration of a Hopf algebra" "5 Higher derivation rings" "5.3 Coclosed subsets and Hopf algebras" \
  "A filtration for \$H\$ is a sequence \$H_i\$ of \$K_H\$-subspaces such that \$H_0 = K_H I\$, \$H_i \\subset H_{i+1}\$, and each element of \$H_{i+1}^0\$ is primitive modulo \$H_i\$ for all \$i\$."

w coradical-hopf-algebra definition 5 3 "Coradical Hopf algebra" "5 Higher derivation rings" "5.3 Coclosed subsets and Hopf algebras" \
  "\$H\$ is coradical if \$H\$ has a filtration."

w conormal-hopf-algebra definition 5 3 "Conormal Hopf algebra" "5 Higher derivation rings" "5.3 Coclosed subsets and Hopf algebras" \
  "\$H\$ is conormal if \$H\$ has a co-Galois subbiring \$H_{\\text{Gal}}\$ and a coradical subbiring \$H_{\\text{rad}}\$ such that \$H = H_{\\text{Gal}} H_{\\text{rad}}\$ (internal tensor product)."

w normality-characterization-via-hopf-algebra theorem 5 3 "Normality characterized by conormality of H(K/k)" "5 Higher derivation rings" "5.3 Coclosed subsets and Hopf algebras" \
  "Let \$K:k < \\infty\$. Then \$K/k\$ is normal if and only if \$H(K/k)\$ is conormal. If \$K/k\$ is normal, then \$K = K_{\\text{Gal}}K_{\\text{rad}}\$ and \$H(K/k) = H_{\\text{Gal}}H_{\\text{rad}}\$ (internal tensor products of \$k\$-algebras)."

echo "--- s030-s033: Ch.6 Linear transformations ---"

# s030: 6.1.5, 6.1.6, 6.1.7, 6.1.12, 6.1.13, 6.2.3, 6.2.4
w semisimplicity-characterization proposition 6 1 "Characterization of semisimple linear transformations" "6 Linear transformations on field extensions" "6.1 Linear transformations" \
  "Let \$t\$ be a linear transformation of \$V\$ and let \$L/k\$ be a splitting field of \$t\$. Then \$t\$ is semisimple if and only if \$L/k\$ is Galois and \$t_L\$ is diagonalizable on \$V_L\$."

w iterated-frobenius-gives-semisimple proposition 6 1 "Iterated Frobenius gives semisimple transformation" "6 Linear transformations on field extensions" "6.1 Linear transformations" \
  "Let \$p > 1\$ and let \$t\$ be a linear transformation of \$V\$. Then \$t^{p^e}\$ is semisimple for some \$e\$."

w k-torus definition 6 1 "k-torus on a vector space" "6 Linear transformations on field extensions" "6.1 Linear transformations" \
  "A \$k\$-torus on \$V\$ is a set \$T\$ of pairwise commuting semisimple linear transformations of \$V\$ such that \$as + bt \\in T\$ and \$t^p \\in T\$ for all \$a, b \\in k, s, t \\in T\$."

w weight-space-decomposition proposition 6 1 "Weight space decomposition for k-torus" "6 Linear transformations on field extensions" "6.1 Linear transformations" \
  "Let \$p > 1\$ and let \$T\$ be a \$k\$-torus on \$V\$. Then \$V = \\sum_{\\alpha \\in T_\\pi^*} V_\\alpha(T_\\pi)\$ (direct sum)."

w diagonalizability-criterion-for-k-torus theorem 6 1 "Diagonalizability criterion for k-torus" "6 Linear transformations on field extensions" "6.1 Linear transformations" \
  "Let \$p > 1\$. Then a \$k\$-torus \$T\$ on \$V\$ is diagonalizable on \$V\$ if and only if \$T\$ is the \$k\$-span of \$T_\\pi\$."

w toral-k-subbiring definition 6 2 "Toral k-subbiring of H(K/k)" "6 Linear transformations on field extensions" "6.2 Toral subrings" \
  "A toral \$k\$-subbiring (resp. \$k\$-subcoring) of \$H(K/k)\$ is a \$k\$-subbiring (resp. \$k\$-subcoring) \$T\$ of \$H(K/k)\$ which is a \$k\$-torus on \$K\$."

w grading-by-diagonalizable-toral-subcoring definition 6 2 "Grading by diagonalizable toral subcoring" "6 Linear transformations on field extensions" "6.2 Toral subrings" \
  "Let \$T\$ be a diagonalizable toral \$k\$-subcoring of \$H(K/k)\$. Then \$G(T) = \\{K_\\alpha(T) \\mid \\alpha \\in T^*, K_\\alpha(T) \\neq \\{0\\}\\}\$ is the grading of \$K\$ by \$T\$."

# s031: 6.2.7, 6.2.11
w toral-subring-from-group-ring definition 6 2 "Toral subring from group ring" "6 Linear transformations on field extensions" "6.2 Toral subrings" \
  "\$T(G) = \\{ \\bar{t} \\mid t \\in (kG)^* \\}\$, where \$\\bar{t}\$ denotes the action of \$t \\in kG\$ on \$K\$."

w diagonalizable-toral-subring-theorem theorem 6 2 "Diagonalizable toral subring theorem" "6 Linear transformations on field extensions" "6.2 Toral subrings" \
  "Let \$p > 1\$ and let \$T\$ be a diagonalizable toral \$k\$-subcoring (resp. \$k\$-subbiring) of \$H(K/k)\$. Then \$T_\\pi\$ is a \$\\pi\$-subcoring (resp. \$\\pi\$-subbiring) of \$H(K)\$ and \$H(K/K^T) = K\\langle T \\rangle = K\\langle T_\\pi \\rangle\$ (resp. \$H(K/K^T) = KT = KT_\\pi\$)."

# s032: 6.3.4, 6.3.7, 6.3.8, 6.3.9
w toral-subrings-for-radical-extensions theorem 6 3 "Toral subrings for radical extensions" "6 Linear transformations on field extensions" "6.3 Radical extensions and toral subrings" \
  "Let \$K/k\$ be a finite dimensional radical extension. Then the set of toral \$k\$-subcorings (resp. \$k\$-subbirings) of \$H(K/k)\$ is mapped bijectively to the set of \$G\$-stable diagonalizable toral \$k\$-subcorings (resp. \$k\$-subbirings) of \$H(\\bar{K}/k)\$ by \$T \\mapsto \\bar{T}\$, with inverse \$\\bar{T} \\mapsto \\bar{T}^G\$."

w primitive-modulo-property-theorem theorem 6 3 "Primitive modulo property for toral subcorings" "6 Linear transformations on field extensions" "6.3 Radical extensions and toral subrings" \
  "Let \$K/k\$ be a finite dimensional radical extension and let \$S, T\$ be toral \$k\$-subcorings of \$H(K/k)\$ with \$S \\subset T\$ and every element of \$T^0\$ primitive modulo \$S\$. Then \$T \\cap \\langle S \\rangle = \\{t \\in T \\mid t(a) = \\varepsilon(t)a \\text{ for all } a \\in K^S\\}\$."

w diagonalizable-toral-subring-correspondence theorem 6 3 "Correspondence for diagonalizable toral subrings" "6 Linear transformations on field extensions" "6.3 Radical extensions and toral subrings" \
  "Let \$K/k\$ be a finite dimensional radical extension and let \$S\$ and \$T\$ be diagonalizable toral \$k\$-subcorings of \$H(K/k)\$ with \$S \\subset T\$. Then there is a natural correspondence between their weight decompositions."

w weight-space-notation definition 6 3 "Weight space notation for Hopf algebras" "6 Linear transformations on field extensions" "6.3 Radical extensions and toral subrings" \
  "For any \$k\$-subspaces \$H\$ and \$T\$ of \$H(K/k)\$, we let \$H_\\alpha(T) = \\{x \\in H \\mid tx - xt = \\alpha(t)x \\text{ for all } t \\in T\\}\$ for \$\\alpha \\in T^*\$."

# s033: 6.3.11, 6.4.1
w fixed-subring-under-toral-action theorem 6 3 "Fixed subring under toral action" "6 Linear transformations on field extensions" "6.3 Radical extensions and toral subrings" \
  "Let \$K/k\$ be a finite dimensional radical extension and let \$T\$ be any toral \$k\$-subcoring in \$H(K/k)\$. Then \$H(K/k)^T\$ is a \$K^T\$-subbiring of \$H(K)\$ and \$H(K/k) = K H(K/k)^T\$ (\$K\$-span of \$H(K/k)^T\$)."

w restriction-to-fixed-field-theorem theorem 6 4 "Restriction to fixed field homomorphism" "6 Linear transformations on field extensions" "6.4 Structure of H(K/k)" \
  "Let \$K/k\$ be a finite dimensional radical extension and let \$T\$ be a toral \$k\$-subbiring of \$H(K/k)\$. Then \$K^T\$ is stable under \$H(K/k)^T\$ and the restriction mapping \$x \\mapsto x|_{K^T}\$ from \$H(K/k)^T\$ to \$H(K^T/k)\$ is a surjective homomorphism of \$k\$-algebras and \$K^T\$-coalgebras."

echo ""
echo "=== ALL $(grep -c '^w ' "$0") concepts written ==="
echo "=== Writing .done marker ==="
echo "DONE" > "$DST/.done"
echo "Done."