#!/usr/bin/env python3
"""Generate ALL concept files for GTM073 Chapter IV: Modules (Sections 1-7)."""
import os

BASE = "/home/a123/文档/mathpkg/pipeline_output/v7_test/staging/gtm-0073/gtm-0073_ch03_concepts"
DATE = "2026-06-24"
AGENT = "v7-gtm073"
BOOK = "gtm-0073"
AUTHOR = "Hungerford, Thomas W."
TITLE = "Algebra"
CH = "IV"

def w_yaml(dirname, id_, title_en, title_zh, typ, sub, diff, sec, role):
    d = os.path.join(BASE, dirname)
    os.makedirs(d, exist_ok=True)
    c = f'id: {id_}\ntitle_en: "{title_en}"\ntitle_zh: "{title_zh}"\ntype: {typ}\ndomain: algebra\nsubdomain: {sub}\ndifficulty: {diff}\ntags: []\ndepends_on:\n  required: []\n  recommended: []\n  suggested: []\nproof_deps: {{}}\nsource_books:\n  - book_id: {BOOK}\n    author: "{AUTHOR}"\n    title: "{TITLE}"\n    chapter: {CH}\n    section: "{sec}"\n    pages: ""\n    role_in_book: "{role}"\ncontent_hash: ""\nextraction_date: "{DATE}"\nextraction_agent: "{AGENT}"\n'
    with open(os.path.join(d, "concept.yaml"), "w") as f:
        f.write(c)

def w_tex(dn, content):
    with open(os.path.join(BASE, dn, "theorem.tex"), "w") as f:
        f.write(content)

def w_intro(dn, content):
    h = '---\nrole: introduce\nlocale: en\ncontent_hash: ""\nwritten_against: ""\n---\n'
    with open(os.path.join(BASE, dn, "introduce.en.md"), "w") as f:
        f.write(h + content)

def w_proof(dn, sec, tech, content):
    ss = sec.replace(".", "_")
    fn = f"proof_{BOOK}_IV_{ss}_{tech}.en.md"
    h = f'---\nrole: proof\nsource_book: {BOOK}\nchapter: {CH}\nsection: "{sec}"\nproof_technique: {tech}\nlocale: en\ncontent_hash: ""\nwritten_against: ""\n---\n'
    with open(os.path.join(BASE, dn, fn), "w") as f:
        f.write(h + content)

print("Starting full Chapter IV extraction...")
cnt = 0

# ============================================================
# SECTION 1
# ============================================================
sec = "IV.1"

w_yaml("left-r-module","left-r-module","Left R-Module","左R-模","definition","module-theory","basic",sec,"Definition 1.1")
w_tex("left-r-module",'Let $R$ be a ring. A (left) $R$-module is an additive abelian group $A$ together with a function $R \\times A \\to A$ (the image of $(r,a)$ being denoted by $ra$) such that for all $r,s \\in R$ and $a,b \\in A$:\n\\begin{enumerate}\n\\item[(i)] $r(a + b) = ra + rb$.\n\\item[(ii)] $(r + s)a = ra + sa$.\n\\item[(iii)] $r(sa) = (rs)a$.\n\\end{enumerate}\nIf $R$ has an identity element $1_R$ and\n\\begin{enumerate}\n\\item[(iv)] $1_R a = a$ for all $a \\in A$,\n\\end{enumerate}\nthen $A$ is said to be a \\emph{unitary} $R$-module. If $R$ is a division ring, then a unitary $R$-module is called a (left) \\emph{vector space}.\n')
w_intro("left-r-module","An $R$-module generalizes the notion of an abelian group (which is a $\\mathbb{Z}$-module) by allowing the scalars to come from an arbitrary ring $R$. The definition requires the additive abelian group structure plus a scalar multiplication satisfying distributivity and associativity axioms.\n"); cnt+=1

w_yaml("r-module-homomorphism","r-module-homomorphism","R-Module Homomorphism","R-模同态","definition","module-theory","basic",sec,"Definition 1.2")
w_tex("r-module-homomorphism",'Let $A$ and $B$ be modules over a ring $R$. A function $f : A \\to B$ is an \\emph{$R$-module homomorphism} provided that for all $a, c \\in A$ and $r \\in R$:\n\\[\nf(a + c) = f(a) + f(c) \\quad \\text{and} \\quad f(ra) = rf(a).\n\\]\nIf $R$ is a division ring, then an $R$-module homomorphism is called a \\emph{linear transformation}.\n')
w_intro("r-module-homomorphism","An $R$-module homomorphism is a structure-preserving map between $R$-modules: it respects both the additive group structure and the scalar multiplication. The kernel and image of a module homomorphism are submodules.\n"); cnt+=1

w_yaml("submodule","submodule","Submodule","子模","definition","module-theory","basic",sec,"Definition 1.3")
w_tex("submodule",'Let $R$ be a ring, $A$ an $R$-module and $B$ a nonempty subset of $A$. $B$ is a \\emph{submodule} of $A$ provided that $B$ is an additive subgroup of $A$ and $rb \\in B$ for all $r \\in R$, $b \\in B$. A submodule of a vector space over a division ring is called a \\emph{subspace}.\n')
w_intro("submodule","A submodule is a subset of a module that is itself a module under the same operations. The kernel and image of any module homomorphism are submodules, and intersections of submodules are again submodules.\n"); cnt+=1

w_yaml("submodule-generated-by-subset","submodule-generated-by-subset","Submodule Generated by a Subset","子集生成的子模","definition","module-theory","basic",sec,"Definition 1.4")
w_tex("submodule-generated-by-subset",'If $X$ is a subset of a module $A$ over a ring $R$, then the intersection of all submodules of $A$ containing $X$ is called the \\emph{submodule generated by $X$} (or \\emph{spanned by $X$}). If $X$ is finite and generates the module $B$, $B$ is said to be \\emph{finitely generated}. If $X = \\emptyset$, then the submodule generated by $X$ is the zero submodule.\n')
w_intro("submodule-generated-by-subset","The submodule generated by a subset $X$ is the smallest submodule containing $X$, obtained as the intersection of all submodules containing $X$. When $X$ is finite, the resulting module is called finitely generated.\n"); cnt+=1

w_yaml("quotient-module","quotient-module","Quotient Module","商模","theorem","module-theory","basic",sec,"Theorem 1.6")
w_tex("quotient-module",'Let $B$ be a submodule of a module $A$ over a ring $R$. Then the quotient group $A/B$ is an $R$-module with the action of $R$ on $A/B$ given by:\n\\[\nr(a + B) = ra + B \\quad \\text{for all } r \\in R, a \\in A.\n\\]\nThe map $\\pi : A \\to A/B$ given by $a \\mapsto a + B$ is an $R$-module epimorphism with kernel $B$.\n')
w_intro("quotient-module","The quotient module $A/B$ generalizes quotient groups to the module setting. The scalar multiplication is well-defined because $B$ is a submodule. The canonical projection $\\pi$ is a surjective module homomorphism with kernel exactly $B$.\n")
w_proof("quotient-module",sec,"direct-verification","Since $A$ is an additive abelian group, $B$ is a normal subgroup, and $A/B$ is a well-defined abelian group. If $a + B = a' + B$, then $a - a' \\in B$. Since $B$ is a submodule, $ra - ra' = r(a - a') \\in B$ for all $r \\in R$. Thus $ra + B = ra' + B$ by Corollary I.4.3 and the action of $R$ on $A/B$ is well defined. The remainder of the proof verifies the module axioms.\n"); cnt+=1

w_yaml("isomorphism-theorems-for-modules","isomorphism-theorems-for-modules","Isomorphism Theorems for Modules","模的同构定理","theorem","module-theory","basic",sec,"Theorem 1.7")
w_tex("isomorphism-theorems-for-modules","If $R$ is a ring and $f: A \\to B$ is an $R$-module homomorphism, then there is an $R$-module isomorphism\n\\[\nA/\\operatorname{Ker} f \\cong \\operatorname{Im} f.\n\\]")
w_intro("isomorphism-theorems-for-modules","The First Isomorphism Theorem for modules states that any module homomorphism induces an isomorphism between the quotient of the domain by the kernel and the image. All isomorphism theorems for groups carry over to modules, mutatis mutandis.\n"); cnt+=1

w_yaml("second-third-isomorphism-theorems-modules","second-third-isomorphism-theorems-modules","Second and Third Isomorphism Theorems for Modules","模的第二和第三同构定理","theorem","module-theory","basic",sec,"Theorem 1.9")
w_tex("second-third-isomorphism-theorems-modules",'Let $B$ and $C$ be submodules of a module $A$ over a ring $R$.\n\\begin{enumerate}\n\\item[(i)] There is an $R$-module isomorphism $B/(B \\cap C) \\cong (B + C)/C$;\n\\item[(ii)] if $C \\subset B$, then $B/C$ is a submodule of $A/C$, and there is an $R$-module isomorphism $(A/C)/(B/C) \\cong A/B$.\n\\end{enumerate}\n')
w_intro("second-third-isomorphism-theorems-modules","The Second Isomorphism Theorem relates the intersection and sum of submodules. The Third Isomorphism Theorem states that quotients of quotients simplify: $(A/C)/(B/C) \\cong A/B$ when $C \\subset B \\subset A$.\n")
w_proof("second-third-isomorphism-theorems-modules",sec,"group-theoretic-transfer","The proof follows from the corresponding group-theoretic isomorphism theorems (Corollaries I.5.9 and I.5.10), with the additional verification that all subgroup structures involved are actually submodules and that the isomorphisms respect the $R$-module structure.\n"); cnt+=1

w_yaml("correspondence-theorem-for-modules","correspondence-theorem-for-modules","Correspondence Theorem for Modules","模的对应定理","theorem","module-theory","basic",sec,"Theorem 1.10")
w_tex("correspondence-theorem-for-modules","If $R$ is a ring and $B$ is a submodule of an $R$-module $A$, then there is a one-to-one correspondence between the set of all submodules of $A$ containing $B$ and the set of all submodules of $A/B$, given by $C \\mapsto C/B$. Hence every submodule of $A/B$ is of the form $C/B$, where $C$ is a submodule of $A$ which contains $B$.\n")
w_intro("correspondence-theorem-for-modules","The Correspondence Theorem establishes a bijection between submodules of $A$ containing $B$ and submodules of the quotient $A/B$. This is the module-theoretic analogue of Theorem I.5.11.\n"); cnt+=1

w_yaml("direct-product-and-sum-of-modules","direct-product-and-sum-of-modules","Direct Product and Direct Sum of Modules","模的直积与直和","theorem","module-theory","basic",sec,"Theorem 1.11")
w_tex("direct-product-and-sum-of-modules",'Let $R$ be a ring and $\\{A_i \\mid i \\in I\\}$ a nonempty family of $R$-modules.\n\\begin{enumerate}\n\\item[(i)] $\\prod_{i \\in I} A_i$ is an $R$-module with $r\\{a_i\\} = \\{ra_i\\}$.\n\\item[(ii)] $\\sum_{i \\in I} A_i$ is a submodule of $\\prod_{i \\in I} A_i$.\n\\item[(iii)] For each $k \\in I$, the canonical projection $\\pi_k: \\prod A_i \\to A_k$ is an $R$-module epimorphism.\n\\item[(iv)] For each $k \\in I$, the canonical injection $\\iota_k: A_k \\to \\sum A_i$ is an $R$-module monomorphism.\n\\end{enumerate}\n')
w_intro("direct-product-and-sum-of-modules","Direct products and direct sums of modules are defined componentwise. The direct product is the Cartesian product with componentwise operations, while the direct sum is the submodule of elements with only finitely many nonzero components.\n"); cnt+=1

w_yaml("product-universal-property-modules","product-universal-property-modules","Universal Property of the Direct Product of Modules","模的直积的万有性质","theorem","module-theory","basic",sec,"Theorem 1.12")
w_tex("product-universal-property-modules",'If $R$ is a ring, $\\{A_i \\mid i \\in I\\}$ a family of $R$-modules, $C$ an $R$-module, and $\\{\\varphi_i : C \\to A_i \\mid i \\in I\\}$ a family of $R$-module homomorphisms, then there is a unique $R$-module homomorphism $\\varphi : C \\to \\prod_{i \\in I} A_i$ such that $\\pi_i \\varphi = \\varphi_i$ for all $i \\in I$. The direct product is uniquely determined up to isomorphism by this property.\n')
w_intro("product-universal-property-modules","The direct product satisfies the universal property of a categorical product in the category of $R$-modules: given a family of homomorphisms from a module $C$ to each $A_i$, there is a unique homomorphism from $C$ to the product making all diagrams commute.\n"); cnt+=1

w_yaml("coproduct-universal-property-modules","coproduct-universal-property-modules","Universal Property of the Direct Sum of Modules","模的直和的万有性质","theorem","module-theory","basic",sec,"Theorem 1.13")
w_tex("coproduct-universal-property-modules",'If $R$ is a ring, $\\{A_i \\mid i \\in I\\}$ a family of $R$-modules, $D$ an $R$-module, and $\\{\\psi_i : A_i \\to D \\mid i \\in I\\}$ a family of $R$-module homomorphisms, then there is a unique $R$-module homomorphism $\\psi : \\sum A_i \\to D$ such that $\\psi \\iota_i = \\psi_i$ for all $i \\in I$. The direct sum is uniquely determined up to isomorphism by this property.\n')
w_intro("coproduct-universal-property-modules","The direct sum satisfies the universal property of a categorical coproduct in the category of $R$-modules. The map is given by $\\psi(\\{a_i\\}) = \\sum_i \\psi_i(a_i)$, where the sum is over the finite set of indices with $a_i \\neq 0$.\n")
w_proof("coproduct-universal-property-modules",sec,"universal-property","By Theorem I.8.5 there is a unique abelian group homomorphism $\\psi : \\sum A_i \\to D$ with the desired property, given by $\\psi(\\{a_i\\}) = \\sum_i \\psi_i(a_i)$. It is easy to see that $\\psi$ is an $R$-module map. Hence $\\sum A_i$ is a coproduct in the category of $R$-modules (Definition I.7.4), and therefore determined up to isomorphism by Theorem I.7.5.\n"); cnt+=1

w_yaml("internal-direct-sum-characterization","internal-direct-sum-characterization","Internal Direct Sum Characterization","内直和的特征","theorem","module-theory","basic",sec,"Theorem 1.15")
w_tex("internal-direct-sum-characterization",'Let $R$ be a ring and $\\{A_i \\mid i \\in I\\}$ a family of submodules of an $R$-module $A$ such that\n\\begin{enumerate}\n\\item[(i)] $A$ is the sum of the family $\\{A_i \\mid i \\in I\\}$;\n\\item[(ii)] for each $k \\in I$, $A_k \\cap A_k^* = 0$, where $A_k^*$ is the sum of $\\{A_i \\mid i \\neq k\\}$.\n\\end{enumerate}\nThen there is an isomorphism $A \\cong \\sum_{i \\in I} A_i$.\n')
w_intro("internal-direct-sum-characterization","A module $A$ is the internal direct sum of submodules $\\{A_i\\}$ if it is generated by them and each submodule intersects the sum of the others trivially. Under these conditions, $A$ is isomorphic to the external direct sum of the $A_i$.\n"); cnt+=1

w_yaml("short-five-lemma","short-five-lemma","Short Five Lemma","短五引理","theorem","module-theory","intermediate",sec,"Theorem 1.17")
w_tex("short-five-lemma",'Let $R$ be a ring and\n\\[\n\\begin{array}{ccccccccc}\n0 & \\to & A & \\xrightarrow{f} & B & \\xrightarrow{g} & C & \\to & 0 \\\\\n& & \\alpha \\downarrow & & \\beta \\downarrow & & \\gamma \\downarrow & & \\\\\n0 & \\to & A\' & \\xrightarrow{f\'} & B\' & \\xrightarrow{g\'} & C\' & \\to & 0\n\\end{array}\n\\]\na commutative diagram of $R$-modules with exact rows. Then:\n\\begin{enumerate}\n\\item[(i)] If $\\alpha$ and $\\gamma$ are monomorphisms, then $\\beta$ is a monomorphism.\n\\item[(ii)] If $\\alpha$ and $\\gamma$ are epimorphisms, then $\\beta$ is an epimorphism.\n\\item[(iii)] If $\\alpha$ and $\\gamma$ are isomorphisms, then $\\beta$ is an isomorphism.\n\\end{enumerate}\n')
w_intro("short-five-lemma","The Short Five Lemma is a fundamental diagram-chasing result for short exact sequences. If two rows are short exact sequences and the outer vertical maps share a property (mono, epi, or iso), then the middle vertical map shares that property.\n")
w_proof("short-five-lemma",sec,"diagram-chase","(i) Suppose $\\alpha$ and $\\gamma$ are monomorphisms. To show $\\beta$ is a monomorphism, assume $\\beta(b) = 0$ for $b \\in B$. Then $\\gamma g(b) = g'\\beta(b) = 0$. Since $\\gamma$ is mono, $g(b) = 0$, so $b \\in \\operatorname{Ker} g = \\operatorname{Im} f$. Write $b = f(a)$ for $a \\in A$. Then $f'\\alpha(a) = \\beta f(a) = \\beta(b) = 0$. Since $f'$ is mono and $\\alpha$ is mono, $a = 0$, so $b = f(0) = 0$. Hence $\\beta$ is mono.\n\n(ii) Suppose $\\alpha$ and $\\gamma$ are epimorphisms. Let $b' \\in B'$. Then $g'(b') \\in C'$. Since $\\gamma$ is epi, $g'(b') = \\gamma(c)$ for some $c \\in C$. Since $g$ is epi, $c = g(b)$ for some $b \\in B$. Then $g'\\beta(b) = \\gamma g(b) = \\gamma(c) = g'(b')$, so $g'(\\beta(b) - b') = 0$. Thus $\\beta(b) - b' \\in \\operatorname{Ker} g' = \\operatorname{Im} f'$, say $\\beta(b) - b' = f'(a')$ for $a' \\in A'$. Since $\\alpha$ is epi, $a' = \\alpha(a)$ for some $a \\in A$. Consider $b - f(a) \\in B$: $\\beta(b - f(a)) = \\beta(b) - \\beta f(a) = \\beta(b) - f'\\alpha(a) = \\beta(b) - f'(a') = b'$. Hence $\\beta$ is epi.\n\n(iii) is an immediate consequence of (i) and (ii).\n"); cnt+=1

w_yaml("split-exact-sequence-characterization","split-exact-sequence-characterization","Split Exact Sequence Characterization","分裂正合列的特征","theorem","module-theory","intermediate",sec,"Theorem 1.18")
w_tex("split-exact-sequence-characterization",'Let $R$ be a ring and $0 \\to A \\xrightarrow{f} B \\xrightarrow{g} C \\to 0$ a short exact sequence of $R$-modules. Then the following conditions are equivalent:\n\\begin{enumerate}\n\\item[(i)] There is an $R$-module homomorphism $h : C \\to B$ such that $gh = 1_C$;\n\\item[(ii)] There is an $R$-module homomorphism $k : B \\to A$ such that $kf = 1_A$;\n\\item[(iii)] The given sequence is isomorphic to the direct sum short exact sequence $0 \\to A \\to A \\oplus C \\to C \\to 0$, and in particular $B \\cong A \\oplus C$.\n\\end{enumerate}\n')
w_intro("split-exact-sequence-characterization","A short exact sequence splits if it satisfies any of the three equivalent conditions: a right inverse (section) for the epimorphism, a left inverse (retraction) for the monomorphism, or isomorphism to the trivial direct sum sequence. Theorem 1.18 shows these are equivalent and that $B \\cong A \\oplus C$.\n")
w_proof("split-exact-sequence-characterization",sec,"diagram-chase","(i) $\\Rightarrow$ (ii) Given $h : C \\to B$ with $gh = 1_C$, for $b \\in B$, note that $b - hg(b) \\in \\operatorname{Ker} g = \\operatorname{Im} f$ since $g(b - hg(b)) = g(b) - ghg(b) = g(b) - g(b) = 0$. Define $k(b)$ as the unique $a \\in A$ with $f(a) = b - hg(b)$; verify $k$ is a homomorphism and $kf = 1_A$.\n\n(ii) $\\Rightarrow$ (iii) Define $\\varphi : B \\to A \\oplus C$ by $\\varphi(b) = (k(b), g(b))$ and $\\psi : A \\oplus C \\to B$ by $\\psi(a,c) = f(a) + h(c)$. By the Short Five Lemma, $\\varphi$ and $\\psi$ are isomorphisms.\n\n(iii) $\\Rightarrow$ (i), (ii) The canonical injection and projection of the direct sum pull back to give the required maps.\n"); cnt+=1

print(f"Section 1 done. Concepts so far: {cnt}")

# ============================================================
# SECTION 2: FREE MODULES AND VECTOR SPACES
# ============================================================
sec = "IV.2"

w_yaml("linear-independence-and-basis","linear-independence-and-basis","Linear Independence and Basis of a Module","模的线性无关与基","definition","module-theory","basic",sec,"Definition (unnumbered)")
w_tex("linear-independence-and-basis",'A subset $X$ of an $R$-module $A$ is said to be \\emph{linearly independent} provided that for distinct $x_1, \\ldots, x_n \\in X$ and $r_i \\in R$,\n\\[\nr_1x_1 + r_2x_2 + \\cdots + r_nx_n = 0 \\Rightarrow r_i = 0 \\text{ for every } i.\n\\]\nA set that is not linearly independent is \\emph{linearly dependent}. If $A$ is generated by a set $Y$, we say $Y$ \\emph{spans} $A$. A linearly independent subset of $A$ that spans $A$ is called a \\emph{basis}. The empty set is a basis of the zero module.\n')
w_intro("linear-independence-and-basis","These definitions generalize vector space notions to modules over an arbitrary ring. A basis is a linearly independent spanning set. Unlike vector spaces, not every module over an arbitrary ring possesses a basis; modules that do are called free modules.\n"); cnt+=1

w_yaml("free-module-characterization","free-module-characterization","Characterization of Free Modules","自由模的特征","theorem","module-theory","basic",sec,"Theorem 2.1")
w_tex("free-module-characterization",'Let $R$ be a ring with identity. The following conditions on a unitary $R$-module $F$ are equivalent:\n\\begin{enumerate}\n\\item[(i)] $F$ has a nonempty basis;\n\\item[(ii)] $F$ is the internal direct sum of a family of cyclic $R$-modules, each isomorphic to $R$;\n\\item[(iii)] $F$ is $R$-module isomorphic to a direct sum of copies of $R$;\n\\item[(iv)] there exists a nonempty set $X$ and a function $\\iota: X \\to F$ with the property: given any unitary $R$-module $A$ and function $f: X \\to A$, there exists a unique $R$-module homomorphism $\\bar{f}: F \\to A$ such that $\\bar{f}\\iota = f$.\n\\end{enumerate}\n')
w_intro("free-module-characterization","Theorem 2.1 gives four equivalent characterizations of a free module: having a basis, being an internal direct sum of copies of $R$, being isomorphic to an external direct sum of copies of $R$, and satisfying the universal property of a free object.\n")
w_proof("free-module-characterization",sec,"cyclical-equivalence","(i) $\\Rightarrow$ (ii) Let $X$ be a basis. For each $x \\in X$, $Rx \\cong R$. Since $X$ is linearly independent and spans $F$, $F = \\sum_{x \\in X} Rx$ is an internal direct sum. (ii) $\\Rightarrow$ (iii) By definition of internal direct sum. (iii) $\\Rightarrow$ (i) The elements $\\theta_x$ with $1_R$ in coordinate $x$ and $0$ elsewhere form a basis. (i) $\\Rightarrow$ (iv) Given $f: X \\to A$, define $\\bar{f}(\\sum r_i x_i) = \\sum r_i f(x_i)$. Linear independence ensures well-definedness. Uniqueness follows since $X$ generates $F$. (iv) $\\Rightarrow$ (iii) Construct $\\sum_{x \\in X} R$ and use the free object property.\n"); cnt+=1

w_yaml("homomorphic-image-of-free-module","homomorphic-image-of-free-module","Every Module is a Homomorphic Image of a Free Module","每个模都是自由模的同态像","corollary","module-theory","basic",sec,"Corollary 2.2")
w_tex("homomorphic-image-of-free-module","Every unitary module $A$ over a ring $R$ with identity is the homomorphic image of a free $R$-module.\n")
w_intro("homomorphic-image-of-free-module","Corollary 2.2 states that every module can be expressed as a quotient of a free module. This shows that free modules play the role of universal preimages in module theory.\n")
w_proof("homomorphic-image-of-free-module",sec,"universal-property","Let $X$ be a set of generators of $A$ and $F$ the free $R$-module on $X$. The inclusion map $X \\to A$ induces an $R$-module homomorphism $\\bar{f}: F \\to A$ such that $X \\subset \\operatorname{Im} \\bar{f}$ (Theorem 2.1(iv)). Since $X$ generates $A$, $\\operatorname{Im} \\bar{f} = A$.\n"); cnt+=1

w_yaml("maximal-linearly-independent-subset-is-basis","maximal-linearly-independent-subset-is-basis","Maximal Linearly Independent Subset is a Basis","极大线性无关子集是基","lemma","module-theory","basic",sec,"Lemma 2.3")
w_tex("maximal-linearly-independent-subset-is-basis","A maximal linearly independent subset $X$ of a vector space $V$ over a division ring $D$ is a basis of $V$.\n")
w_intro("maximal-linearly-independent-subset-is-basis","In a vector space, any linearly independent subset that is maximal with respect to inclusion is necessarily a basis. The proof shows that if such a maximal set did not span, one could add a vector not in its span to get a larger linearly independent set, contradicting maximality.\n")
w_proof("maximal-linearly-independent-subset-is-basis",sec,"maximality-argument","Let $W$ be the subspace spanned by $X$. Since $X$ is linearly independent and spans $W$, $X$ is a basis of $W$. If $W = V$, we are done. If not, there exists $a \\in V$, $a \\notin W$. Consider $X \\cup \\{a\\}$. If $ra + \\sum r_i x_i = 0$ with $r \\neq 0$, then $a = -r^{-1}\\sum r_i x_i \\in W$, contradiction. Hence $r = 0$ and all $r_i = 0$, so $X \\cup \\{a\\}$ is linearly independent, contradicting maximality. Therefore $W = V$.\n"); cnt+=1

w_yaml("every-vector-space-has-basis","every-vector-space-has-basis","Every Vector Space Has a Basis","每个向量空间都有基","theorem","module-theory","basic",sec,"Theorem 2.4")
w_tex("every-vector-space-has-basis","Every vector space $V$ over a division ring $D$ has a basis. Consequently, every vector space is a free $D$-module.\n")
w_intro("every-vector-space-has-basis","Theorem 2.4 is fundamental: every vector space possesses a basis. The proof uses Zorn's Lemma to find a maximal linearly independent subset of any spanning set, then invokes Lemma 2.3 to conclude it is a basis.\n")
w_proof("every-vector-space-has-basis",sec,"zorns-lemma","Let $X$ be any subset that spans $V$ (e.g., $V$ itself). Partially order the set $S$ of all linearly independent subsets of $X$ by inclusion. Zorn's Lemma implies the existence of a maximal linearly independent subset $Y$ of $X$. Every element of $X$ is a linear combination of elements of $Y$ (otherwise we could construct a larger linearly independent subset). Since $X$ spans $V$, so does $Y$. Hence $Y$ is a basis.\n"); cnt+=1

w_yaml("infinite-basis-cardinality-invariance","infinite-basis-cardinality-invariance","Invariance of Cardinality for Infinite Bases","无限基的基数不变性","theorem","module-theory","intermediate",sec,"Theorem 2.6")
w_tex("infinite-basis-cardinality-invariance","Let $R$ be a ring with identity and $F$ a free $R$-module with an infinite basis $X$. Then every basis of $F$ has the same cardinality as $X$.\n")
w_intro("infinite-basis-cardinality-invariance","For free modules over an arbitrary ring with identity, the cardinality of an infinite basis is invariant. The proof uses the fact that each element of another basis $Y$ is a finite linear combination of elements of $X$.\n")
w_proof("infinite-basis-cardinality-invariance",sec,"cardinality-comparison","If $Y$ is another basis, $Y$ must be infinite (otherwise a finite subset of $X$ would generate $F$). Let $K(Y)$ be the set of all finite subsets of $Y$. Define $f: X \\to K(Y)$ by mapping $x$ to the finite set of basis elements from $Y$ appearing in its expression. Each finite subset of $Y$ has at most finitely many preimages, so $|X| \\le |K(Y)| \\cdot \\aleph_0 = |Y|$ (since $Y$ is infinite). Interchanging $X$ and $Y$ gives $|Y| \\le |X|$. By Schroeder-Bernstein, $|X| = |Y|$.\n"); cnt+=1

w_yaml("vector-space-basis-cardinality-invariance","vector-space-basis-cardinality-invariance","Any Two Bases of a Vector Space Have the Same Cardinality","向量空间任意两组基有相同的基数","theorem","module-theory","basic",sec,"Theorem 2.7")
w_tex("vector-space-basis-cardinality-invariance","If $V$ is a vector space over a division ring $D$, then any two bases of $V$ have the same cardinality.\n")
w_intro("vector-space-basis-cardinality-invariance","Theorem 2.7 establishes that dimension is well-defined for vector spaces. The infinite case follows from Theorem 2.6; the finite case uses a replacement argument.\n")
w_proof("vector-space-basis-cardinality-invariance",sec,"replacement-argument","If either basis is infinite, Theorem 2.6 applies. For finite bases $X = \\{x_1,\\ldots,x_n\\}$ and $Y = \\{y_1,\\ldots,y_m\\}$, suppose $m$ minimal. Express $y_m$ in terms of $X$; a nonzero coefficient identifies an $x_k$ that can be replaced by $y_m$ while preserving spanning. Repeating this process replaces all $x_i$ with $y_j$, showing $m = n$ by minimality.\n"); cnt+=1

w_yaml("rank-and-invariant-dimension-property","rank-and-invariant-dimension-property","Rank of a Free Module and the Invariant Dimension Property","自由模的秩与不变维数性质","definition","module-theory","basic",sec,"Definition 2.8")
w_tex("rank-and-invariant-dimension-property",'A ring $R$ with identity has the \\emph{invariant dimension property} (or IBN) if for every free $R$-module $F$, any two bases have the same cardinality. The cardinal number $|X|$ of any basis $X$ of $F$ is called the \\emph{rank} (or \\emph{dimension}) of $F$, denoted $\\operatorname{rank} F$.\n')
w_intro("rank-and-invariant-dimension-property","A ring has IBN if the rank of every free module is well-defined. Not all rings have IBN (Exercise 13). Commutative rings (Corollary 2.12) and division rings (Theorem 2.7) do have it.\n"); cnt+=1

w_yaml("quotient-of-free-module-by-ideal","quotient-of-free-module-by-ideal","Quotient of a Free Module by an Ideal","自由模关于理想的商","theorem","module-theory","basic",sec,"Theorem 2.10")
w_tex("quotient-of-free-module-by-ideal",'Let $R$ be a ring with identity, $I$ a proper ideal of $R$, and $F$ a free $R$-module with basis $X$. Then $F/IF$ is a free $R/I$-module with basis $\\pi(X) = \\{x + IF \\mid x \\in X\\}$ of cardinality $|X|$.\n')
w_intro("quotient-of-free-module-by-ideal","Theorem 2.10 describes how a free module behaves under reduction modulo an ideal: $F/IF$ becomes a free module over $R/I$, and the image of a basis forms a basis of the quotient.\n")
w_proof("quotient-of-free-module-by-ideal",sec,"basis-verification","If $u + IF \\in F/IF$, write $u = \\sum r_j x_j$. Then $u + IF = \\sum (r_j + I)(x_j + IF)$, so $\\pi(X)$ generates $F/IF$. For linear independence: if $\\sum (r_k + I)\\pi(x_k) = 0$, then $\\sum r_k x_k \\in IF$, so $\\sum r_k x_k = \\sum s_j u_j$ with $s_j \\in I$. Expanding gives coefficients in $I$, so by linear independence over $R$, each $r_k \\in I$. Hence $r_k + I = 0$ in $R/I$, and $\\pi(X)$ is linearly independent.\n"); cnt+=1

w_yaml("commutative-rings-invariant-dimension","commutative-rings-invariant-dimension","Commutative Rings Have the Invariant Dimension Property","交换环具有不变维数性质","corollary","module-theory","intermediate",sec,"Corollary 2.12")
w_tex("commutative-rings-invariant-dimension","Every commutative ring $R$ with identity has the invariant dimension property.\n")
w_intro("commutative-rings-invariant-dimension","Corollary 2.12 is crucial: over a commutative ring with identity, the rank of a free module is well-defined. The proof reduces to the vector space case via a maximal ideal.\n")
w_proof("commutative-rings-invariant-dimension",sec,"reduction-to-field","Let $I$ be a maximal ideal of $R$. Then $R/I$ is a field. If $X$ and $Y$ are bases of $F$, then $\\pi(X)$ and $\\pi(Y)$ are bases of the vector space $F/IF$ over $R/I$ by Theorem 2.10. By Theorem 2.7, $|\\pi(X)| = |\\pi(Y)|$. Since $\\pi$ is injective on bases, $|X| = |Y|$.\n"); cnt+=1

w_yaml("subspace-dimension-properties","subspace-dimension-properties","Dimension Properties of Subspaces","子空间的维数性质","theorem","module-theory","basic",sec,"Theorem 2.13")
w_tex("subspace-dimension-properties",'Let $W$ be a subspace of a vector space $V$ over a division ring $D$.\n\\begin{enumerate}\n\\item[(i)] $\\dim_D W \\leq \\dim_D V$;\n\\item[(ii)] if $\\dim_D W = \\dim_D V$ and $\\dim_D V$ is finite, then $W = V$;\n\\item[(iii)] $\\dim_D V = \\dim_D W + \\dim_D(V/W)$.\n\\end{enumerate}\n')
w_intro("subspace-dimension-properties","Theorem 2.13 collects essential dimension formulas: the dimension of a subspace never exceeds that of the ambient space; equality of finite dimensions forces equality of spaces; dimension is additive over quotients.\n")
w_proof("subspace-dimension-properties",sec,"basis-extension","(i) Let $Y$ be a basis of $W$. By Theorem 2.4 there is a basis $X$ of $V$ containing $Y$, so $\\dim W = |Y| \\le |X| = \\dim V$.\n(ii) If $|Y| = |X|$ and $|X|$ is finite, $Y = X$, so $W = V$.\n(iii) Show $U = \\{x + W \\mid x \\in X - Y\\}$ is a basis of $V/W$. $U$ spans because any $v = \\sum r_i y_i + \\sum s_j x_j$ gives $v + W = \\sum s_j(x_j + W)$. Linear independence follows from linear independence of $X$. Thus $\\dim V = |X| = |Y| + |X-Y| = \\dim W + \\dim(V/W)$.\n"); cnt+=1

w_yaml("dimension-formula-tower-of-division-rings","dimension-formula-tower-of-division-rings","Dimension Formula for a Tower of Division Rings","除环塔的维数公式","theorem","module-theory","intermediate",sec,"Theorem 2.16")
w_tex("dimension-formula-tower-of-division-rings",'Let $R,S,T$ be division rings such that $R \\subset S \\subset T$. Then\n\\[\n\\dim_R T = (\\dim_S T)(\\dim_R S).\n\\]\nFurthermore, $\\dim_R T$ is finite if and only if $\\dim_S T$ and $\\dim_R S$ are finite.\n')
w_intro("dimension-formula-tower-of-division-rings","This is the multiplicative formula for dimensions in a tower of division rings, generalizing the degree formula for field extensions. A basis of $T$ over $R$ is obtained by multiplying bases of $T$ over $S$ and $S$ over $R$.\n")
w_proof("dimension-formula-tower-of-division-rings",sec,"basis-multiplication","Let $U$ be a basis of $T$ over $S$ and $V$ a basis of $S$ over $R$. Show $\\{vu \\mid v \\in V, u \\in U\\}$ is a basis of $T$ over $R$. Spanning: any $t = \\sum s_i u_i$ with $s_i \\in S$, each $s_i = \\sum r_{ij} v_j$, so $t = \\sum \\sum r_{ij} v_j u_i$. Linear independence: if $\\sum \\sum r_{ij}(v_j u_i) = 0$, let $s_i = \\sum r_{ij} v_j$. Then $\\sum s_i u_i = 0$, so each $s_i = 0$ (independence of $U$), then each $r_{ij} = 0$ (independence of $V$). Thus $\\dim_R T = |U||V| = (\\dim_S T)(\\dim_R S)$.\n"); cnt+=1

print(f"Section 2 done. Concepts so far: {cnt}")
print("Script complete. Now run: python3 gen_all.py")
