#!/usr/bin/env python3
"""Batch extract all concepts from GTM022 and write v8 5-file format."""
import os, json, hashlib

OUT = "/home/a123/文档/mathpkg/pipeline_output/math_pkg_tmp/concepts_batch3/gtm022"
SECTION_DIR = "/home/a123/文档/mathpkg/pipeline_output/stitched_sections/(GTM022)An Algebraic Introduction to Mathematical Logic"

os.makedirs(OUT, exist_ok=True)

# ─── Concept data ───────────────────────────────────────────────────────
# Each concept: (slug, type, title_en, chapter, section, latex_stmt, introduce_text, proof_text_or_None, exercises_or_None)
# exercises_or_None: list of (num, statement) tuples

concepts = []

# ─── CHAPTER I: Universal Algebra ───────────────────────────────────────
# §1 Introduction (s001)

concepts.append({
    "slug": "algebraic-type",
    "type": "definition",
    "title_en": "Type of a T-algebra",
    "ch": "I", "sec": "1",
    "latex": r"""A \emph{type} $\mathcal{T}$ is a set $T$ together with a function $\operatorname{ar}: T \to \mathbb{N}$, from $T$ into the non-negative integers. We shall write $\mathcal{T} = (T, \operatorname{ar})$.""",
    "intro": "A type specifies the arity (number of arguments) of each operation symbol in a $T$-algebra. It generalizes the notion of a signature in universal algebra, allowing arbitrary sets of operation symbols.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "t-algebra",
    "type": "definition",
    "title_en": "T-algebra",
    "ch": "I", "sec": "1",
    "latex": r"""A $T$-algebra $A$ is a set $A$ together with, for each $t \in T_n$, a function $t_A: A^n \to A$. If $\operatorname{ar}(t) = 0$, then $t_A$ is a distinguished element of $A$.""",
    "intro": "A $T$-algebra generalizes algebraic structures such as groups, rings, and modules by allowing an arbitrary type $T$ of operation symbols with specified arities. Examples include groups (with operations $e$, $i$, $*$), rings, and modules over a ring.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "equality-of-t-algebras",
    "type": "definition",
    "title_en": "Equality of T-algebras",
    "ch": "I", "sec": "1",
    "latex": r"""$T$-algebras $A, B$ are equal if and only if $A = B$ and $t_A = t_B$ for all $t \in T$.""",
    "intro": "Two $T$-algebras are equal precisely when they have the same underlying set and the same operations. This formalizes the notion that the algebraic structure is determined by both the carrier set and the interpretation of each operation symbol.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "t-subalgebra",
    "type": "definition",
    "title_en": "T-subalgebra",
    "ch": "I", "sec": "1",
    "latex": r"""If $A$ is a $T$-algebra, a subset $B$ of $A$ is called a \emph{$T$-subalgebra} of $A$ if it forms a $T$-algebra with operations the restrictions to $B$ of those on $A$, i.e., if for all $n$ and for all $t \in T_n$ and $b_1, \ldots, b_n \in B$, we have $t_A(b_1, \ldots, b_n) \in B$.""",
    "intro": "A $T$-subalgebra is a subset closed under all operations of the ambient $T$-algebra. Any intersection of subalgebras is a subalgebra, so given any subset, there exists a unique smallest subalgebra containing it.",
    "proof": None,
    "exercises": []
})

# §2 Free Algebras (s002)

concepts.append({
    "slug": "free-t-algebra",
    "type": "definition",
    "title_en": "Free T-algebra",
    "ch": "I", "sec": "2",
    "latex": r"""Let $X$ be any set, let $F$ be a $T$-algebra and let $\sigma: X \to F$ be a function. We say that $F$ (more strictly $(F, \sigma)$) is a \emph{free $T$-algebra} on the set $X$ of \emph{free generators} if, for every $T$-algebra $A$ and function $\tau: X \to A$, there exists a unique homomorphism $\varphi: F \to A$ such that $\varphi\sigma = \tau$.""",
    "intro": "A free $T$-algebra on $X$ is the most general $T$-algebra generated by $X$. It satisfies the universal property that any map from $X$ to any $T$-algebra extends uniquely to a homomorphism. The elements of a free algebra can be thought of as formal expressions built from the generators using the operations of $T$.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "existence-uniqueness-free-t-algebra",
    "type": "theorem",
    "title_en": "Existence and Uniqueness of Free T-algebras",
    "ch": "I", "sec": "2",
    "latex": r"""For any set $X$ and any type $T$, there exists a free $T$-algebra on $X$. This free $T$-algebra on $X$ is unique up to isomorphism.""",
    "intro": "Free $T$-algebras always exist and are essentially unique. The proof constructs the free algebra inductively as a union of layers $F_n$, where $F_0$ is the disjoint union of $X$ and $T_0$, and higher layers consist of formal tuples encoding operation applications.",
    "proof": r"""\textbf{Uniqueness.} Let $(F, \sigma)$ and $(F', \sigma')$ be free on $X$. By the universal property, there exist homomorphisms $\varphi: F \to F'$ with $\varphi\sigma = \sigma'$ and $\varphi': F' \to F$ with $\varphi'\sigma' = \sigma$. Then $\varphi'\varphi\sigma = \varphi'\sigma' = \sigma$, and by the uniqueness part of the universal property applied to $1_F$, we have $\varphi'\varphi = 1_F$. Similarly $\varphi\varphi' = 1_{F'}$. Thus $F \cong F'$.

\textbf{Existence.} Construct $F = \bigcup_{n \in \mathbb{N}} F_n$ inductively:
\begin{itemize}
\item $F_0$ is the disjoint union of $X$ and $T_0$.
\item Assuming $F_r$ defined for $0 \leqslant r < n$, define
$$F_n = \{(t, a_1, \ldots, a_k) \mid t \in T, \operatorname{ar}(t) = k, a_i \in F_{r_i}, \sum r_i = n-1\}.$$
\item For $t \in T_k$, define $t(a_1, \ldots, a_k) = (t, a_1, \ldots, a_k)$. For $t \in T_0$, $t_F$ is the element $t$ of $F_0$.
\item Define $\sigma: X \to F$ by the inclusion $X \subseteq F_0$.
\end{itemize}
Given $\tau: X \to A$, define $\varphi_0: F_0 \to A$ by $\varphi_0(x) = \tau(x)$ for $x \in X$ and $\varphi_0(t) = t_A$ for $t \in T_0$. Inductively, for $\alpha = (t, a_1, \ldots, a_k) \in F_n$,
$$\varphi_n(\alpha) = t_A(\varphi_{r_1}(a_1), \ldots, \varphi_{r_k}(a_k)).$$
The resulting $\varphi$ is the unique homomorphism extending $\tau$.""",
    "exercises": []
})

concepts.append({
    "slug": "t-expression",
    "type": "definition",
    "title_en": "T-expression (Coordinate Function)",
    "ch": "I", "sec": "2",
    "latex": r"""Let $A$ be any $T$-algebra, and let $F$ be the free $T$-algebra on the set $X = \{x_1, \ldots, x_n\}$. An element $w \in F$ is called a \emph{$T$-expression} (or \emph{word}) in $X$. For each such $w$, there is a unique associated function $f_w: A^n \to A$ called the \emph{coordinate function} defined by $f_w(a_1, \ldots, a_n) = \varphi(w)$ where $\varphi: F \to A$ is the unique homomorphism with $\varphi(x_i) = a_i$.""",
    "intro": "A $T$-expression formalizes the notion of a term built from variables using the operation symbols of $T$. Each such expression induces a derived operation (coordinate function) on any $T$-algebra.",
    "proof": None,
    "exercises": []
})

# Exercises 2.6-2.10
for i, stmt in enumerate([
    r"""$T$ consists of one unary operation, and $F$ is the free $T$-algebra on a one-element set $X$. How many elements are there in $F$?""",
    r"""If $T$ is empty and $X$ is any set, show that $X$ is the free $T$-algebra on $X$.""",
    r"""$T$ consists of a single binary operation, and $F$ is the free $T$-algebra on a one-element set $X$. How many elements are there in $F$?""",
    r"""If $T$ consists of one $0$-ary operation and one $2$-ary operation, and if $X = \varnothing$, then the free $T$-algebra $F$ on $X$ is countable.""",
    r"""$T$ is finite or countable, and contains at least one $0$-ary operation and at least one operation $t$ with $\operatorname{ar}(t) > 0$. $X$ is finite or countable. Prove that $F$ is countable."""
]):
    concepts.append({
        "slug": f"exercise-ch1-sec2-{i+6}",
        "type": "exercise",
        "title_en": f"Exercise I.2.{i+6}",
        "ch": "I", "sec": "2",
        "latex": stmt,
        "intro": f"Exercise I.2.{i+6} from Chapter I, Section 2 on free algebras.",
        "proof": None,
        "exercises": None,
        "exercise_num": i+6
    })

# §3 Varieties (s002)

concepts.append({
    "slug": "identical-relation",
    "type": "definition",
    "title_en": "Identical Relation on T-algebras",
    "ch": "I", "sec": "3",
    "latex": r"""An \emph{identical relation} on $T$-algebras is a pair $(u, v)$ of elements of the free $T$-algebra $F$ on the countable set $X = \{x_1, x_2, \ldots\}$ of variables. A $T$-algebra $A$ \emph{satisfies} the identical relation $(u, v)$ if $f_u = f_v$ as functions $A^n \to A$, where $n$ is such that $u, v \in F(X_n)$.""",
    "intro": "An identical relation (or identity) is a formal equality between two $T$-expressions. A $T$-algebra satisfies the identity if the two expressions evaluate to the same element for all assignments of values in the algebra.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "variety-of-t-algebras",
    "type": "definition",
    "title_en": "Variety of T-algebras",
    "ch": "I", "sec": "3",
    "latex": r"""If $L$ is a set of identical relations on $T$-algebras, the class $V$ of all $T$-algebras which satisfy every identical relation in $L$ is called a \emph{variety} of $T$-algebras. The elements of $L$ are called the \emph{laws} of $V$.""",
    "intro": "A variety is an equationally defined class of $T$-algebras. Classic examples include the variety of semigroups (defined by associativity), groups (defined by associativity, identity, and inverses), and abelian groups.",
    "proof": None,
    "exercises": []
})

# §4 Relatively Free Algebras (s002)

concepts.append({
    "slug": "relatively-free-algebra",
    "type": "definition",
    "title_en": "Relatively Free Algebra of a Variety",
    "ch": "I", "sec": "4",
    "latex": r"""A $T$-algebra $R$ in the variety $V$ is the \emph{(relatively) free algebra} of $V$ on the set $X$ of \emph{(relatively) free generators} (where a function $\sigma: X \to R$ is given, usually as an inclusion) if, for every $T$-algebra $A$ in $V$ and every function $\tau: X \to A$, there exists a unique homomorphism $\varphi: R \to A$ such that $\varphi\sigma = \tau$.""",
    "intro": "A relatively free algebra is the free object in a variety, satisfying the same universal property as a free algebra but with respect to algebras in the variety. It is obtained as a quotient of the absolutely free algebra by the congruence generated by the laws of the variety.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "existence-relatively-free-algebra",
    "type": "theorem",
    "title_en": "Existence of Relatively Free Algebras",
    "ch": "I", "sec": "4",
    "latex": r"""For any variety $V$ of $T$-algebras and any set $X$, there exists a relatively free algebra $R$ of $V$ on $X$.""",
    "intro": "The relatively free algebra is constructed as the quotient $F/{\sim}$ where $F$ is the absolutely free $T$-algebra on $X$ and $u \sim v$ if $\varphi(u) = \varphi(v)$ for every homomorphism $\varphi$ of $F$ into an algebra in $V$.",
    "proof": r"""Let $(F, \rho)$ be the free $T$-algebra on $X$. Define a congruence relation on $F$ by $u \sim v$ if $\varphi(u) = \varphi(v)$ for every homomorphism $\varphi: F \to A$ with $A \in V$. Then $\sim$ is an equivalence relation, and if $t \in T_k$ and $u_i \sim v_i$, then
$$\varphi(t(u_1, \ldots, u_k)) = t(\varphi(u_1), \ldots, \varphi(u_k)) = t(\varphi(v_1), \ldots, \varphi(v_k)) = \varphi(t(v_1, \ldots, v_k)),$$
so $\sim$ is a congruence. Define $R = F/{\sim}$ with $t(\bar{u}_1, \ldots, \bar{u}_k) = \overline{t(u_1, \ldots, u_k)}$ and $\sigma(x) = \overline{\rho(x)}$. Given $\tau: X \to A$ with $A \in V$, the universal property of $F$ gives a unique homomorphism $\psi: F \to A$ with $\psi\rho = \tau$, which factors through $R$ to give the required homomorphism.""",
    "exercises": []
})

# ─── CHAPTER II: Propositional Calculus ─────────────────────────────────

concepts.append({
    "slug": "proposition-algebra",
    "type": "definition",
    "title_en": "Proposition Algebra (Free Proposition Algebra on X)",
    "ch": "II", "sec": "2",
    "latex": r"""Let $T = \{F, \Rightarrow\}$, where $F$ is a $0$-ary operation and $\Rightarrow$ is a binary operation. The \emph{proposition algebra} $P(X)$ is the free $T$-algebra on the set $X$ of \emph{propositional variables}. The operations $\sim$, $\vee$, $\wedge$, $\Leftrightarrow$ are defined as abbreviations:
$$\sim p = p \Rightarrow F,$$
$$p \vee q = (\sim p) \Rightarrow q,$$
$$p \wedge q = \sim(p \Rightarrow \sim q),$$
$$p \Leftrightarrow q = (p \Rightarrow q) \wedge (q \Rightarrow p).$$""",
    "intro": "The proposition algebra $P(X)$ formalizes the way simple statements are combined using logical connectives. All standard connectives are defined in terms of the primitive connectives $F$ (falsehood) and $\Rightarrow$ (implication).",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "valuation-prop",
    "type": "definition",
    "title_en": "Valuation of a Proposition Algebra",
    "ch": "II", "sec": "3",
    "latex": r"""A \emph{valuation} of $P(X)$ is a proposition algebra homomorphism $v: P(X) \to \mathbb{Z}_2$. We say that $p \in P(X)$ is \emph{true} with respect to $v$ if $v(p) = 1$, and that $p$ is \emph{false} with respect to $v$ if $v(p) = 0$.""",
    "intro": "A valuation assigns truth values (0 for false, 1 for true) to propositions in a way that respects the logical connectives. Since $P(X)$ is freely generated by $X$, a valuation is uniquely determined by its values on $X$.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "semantic-consequence",
    "type": "definition",
    "title_en": "Semantic Consequence (Semantic Implication)",
    "ch": "II", "sec": "3",
    "latex": r"""Let $A \subseteq P(X)$ and $p \in P(X)$. We say that $p$ is a \emph{semantic consequence} of $A$, written $A \models p$, if $v(p) = 1$ for every valuation $v$ of $P(X)$ such that $v(a) = 1$ for all $a \in A$. $\operatorname{Con}(A) = \{p \in P(X) \mid A \models p\}$.""",
    "intro": "Semantic consequence captures the notion that $p$ must be true whenever all assumptions in $A$ are true. This is defined purely in terms of truth values, independent of any proof system.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "tautology",
    "type": "definition",
    "title_en": "Tautology (Valid Proposition)",
    "ch": "II", "sec": "3",
    "latex": r"""Let $p \in P(X)$. We say that $p$ is \emph{valid}, or is a \emph{tautology}, if $v(p) = 1$ for every valuation $v$ of $P(X)$. We write this as $\models p$.""",
    "intro": "A tautology is a proposition that is true under all possible truth assignments to its propositional variables. Tautologies are the logical truths of the propositional calculus.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "con-is-closure",
    "type": "lemma",
    "title_en": "Con is a Closure Operation",
    "ch": "II", "sec": "3",
    "latex": r"""$\operatorname{Con}$ is a closure operation on $P(X)$, that is,
(i) $A \subseteq \operatorname{Con}(A)$,
(ii) If $A_1 \subseteq A_2$, then $\operatorname{Con}(A_1) \subseteq \operatorname{Con}(A_2)$,
(iii) $\operatorname{Con}(\operatorname{Con}(A)) = \operatorname{Con}(A)$.""",
    "intro": "The semantic consequence operator Con satisfies the axioms of a closure operator: it is extensive, monotone, and idempotent. This structure is fundamental for studying the relationship between syntax and semantics.",
    "proof": r"""All three properties follow directly from the definition of $\operatorname{Con}(A)$. For (i), if $p \in A$, then any valuation making all of $A$ true makes $p$ true. For (ii), any valuation making all of $A_2$ true also makes all of $A_1$ true. For (iii), if $p \in \operatorname{Con}(\operatorname{Con}(A))$, then $v(p) = 1$ whenever $v(\operatorname{Con}(A)) \subseteq \{1\}$. But $v(A) \subseteq \{1\}$ implies $v(\operatorname{Con}(A)) \subseteq \{1\}$ by definition, so $v(p) = 1$, giving $\operatorname{Con}(\operatorname{Con}(A)) \subseteq \operatorname{Con}(A)$. The reverse inclusion follows from (i).""",
    "exercises": []
})

concepts.append({
    "slug": "proof-in-prop-calculus",
    "type": "definition",
    "title_en": "Proof in the Propositional Calculus",
    "ch": "II", "sec": "4",
    "latex": r"""In the propositional calculus on the set $X$, a \emph{proof} of $q$ from the assumptions $A$ is a finite sequence $p_1, p_2, \ldots, p_n$ of elements $p_i \in P(X)$ such that $p_n = q$ and for each $i$, either $p_i \in \mathcal{A} \cup A$ or for some $j, k < i$, we have $p_k = (p_j \Rightarrow p_i)$. Here $\mathcal{A} = \mathcal{A}_1 \cup \mathcal{A}_2 \cup \mathcal{A}_3$ where
$$\mathcal{A}_1 = \{p \Rightarrow (q \Rightarrow p) \mid p, q \in P(X)\},$$
$$\mathcal{A}_2 = \{(p \Rightarrow (q \Rightarrow r)) \Rightarrow ((p \Rightarrow q) \Rightarrow (p \Rightarrow r)) \mid p, q, r \in P(X)\},$$
$$\mathcal{A}_3 = \{\sim\sim p \Rightarrow p \mid p \in P(X)\}.$$""",
    "intro": "A proof is a formal derivation using the three axiom schemas and the single rule of inference Modus Ponens (from $p$ and $p \Rightarrow q$, deduce $q$). This gives a purely syntactic notion of deduction.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "syntactic-deduction",
    "type": "definition",
    "title_en": "Syntactic Deduction (Syntactic Implication)",
    "ch": "II", "sec": "4",
    "latex": r"""Let $q \in P(X)$ and let $A \subseteq P(X)$. We say that $q$ is \emph{deducible} from $A$, or $q$ is a \emph{syntactic consequence} of $A$, written $A \vdash q$ (or $q \in \operatorname{Ded}(A)$), if there exists a proof of $q$ from $A$ in the propositional calculus. If $\emptyset \vdash q$, we call $q$ a \emph{theorem} of the propositional calculus and write $\vdash q$.""",
    "intro": "Syntactic deduction formalizes provability: $q$ can be derived from assumptions $A$ using the axioms and rules of inference. The operator Ded is the syntactic counterpart of the semantic operator Con.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "substitution-theorem-prop",
    "type": "theorem",
    "title_en": "Substitution Theorem for Propositional Calculus",
    "ch": "II", "sec": "4",
    "latex": r"""Let $X, Y$ be any two sets, and let $\varphi: P(X) \to P(Y)$ be a homomorphism of the (free) proposition algebra on $X$ into the (free) proposition algebra on $Y$. Let $w = w(x_1, \ldots, x_n)$ be any element of $P(X)$ and let $A$ be any subset of $P(X)$. Put $a_i = \varphi(x_i)$. Then
$$\text{if } A \vdash w, \text{ then } \varphi(A) \vdash w(a_1, \ldots, a_n).$$""",
    "intro": "The Substitution Theorem states that provability is preserved under homomorphisms of proposition algebras. It allows substituting propositions for propositional variables uniformly throughout a proof.",
    "proof": r"""Let $p_1, \ldots, p_n$ be a proof of $w$ from $A$. We use induction on $n$. For $n = 1$, $w \in \mathcal{A} \cup A$. If $w \in A$, then $\varphi(w) \in \varphi(A)$. If $w$ is an axiom, then $\varphi(w)$ is also an axiom since the axiom schemas are closed under substitution. For $n > 1$, if $p_i = p_j \Rightarrow p_n$, then $\varphi(p_i) = \varphi(p_j) \Rightarrow \varphi(p_n)$, and the result follows by induction.""",
    "exercises": []
})

# ─── CHAPTER III: Properties of the Propositional Calculus ──────────────

concepts.append({
    "slug": "logic-definition",
    "type": "definition",
    "title_en": "Logic (Formal System)",
    "ch": "III", "sec": "1",
    "latex": r"""A \emph{logic} $\mathcal{L}$ is a system consisting of a set $P$ of elements (called \emph{propositions}), a set $\mathcal{V}$ of functions (called \emph{valuations}) from $P$ into some value set $W$, and, for each subset $A$ of $P$, a set of finite sequences of elements of $P$ (called \emph{proofs} from the assumptions $A$).""",
    "intro": "A logic is the most general formal framework for studying the relationship between truth (valuations) and proof. The propositional calculus Prop($X$) and the predicate calculus Pred($V, \mathcal{R}$) are both instances of this definition.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "sound-logic",
    "type": "definition",
    "title_en": "Sound Logic",
    "ch": "III", "sec": "1",
    "latex": r"""A logic $\mathcal{L}$ is \emph{sound} if $A \vdash p$ implies $A \models p$.""",
    "intro": "Soundness means that whatever is provable is true. It guarantees that the proof system does not derive false conclusions from true assumptions.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "consistent-logic",
    "type": "definition",
    "title_en": "Consistent Logic",
    "ch": "III", "sec": "1",
    "latex": r"""A logic $\mathcal{L}$ is \emph{consistent} if $F$ is not a theorem (i.e., $\emptyset \not\vdash F$).""",
    "intro": "Consistency means that a contradiction cannot be proved. For the propositional calculus, consistency follows from soundness since $F$ is not a tautology.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "adequate-logic",
    "type": "definition",
    "title_en": "Adequate Logic (Semantically Complete)",
    "ch": "III", "sec": "1",
    "latex": r"""A logic $\mathcal{L}$ is \emph{adequate} (or \emph{semantically complete}) if $A \models p$ implies $A \vdash p$.""",
    "intro": "Adequacy (completeness) means that every semantic consequence is provable. Together with soundness, it establishes the equivalence of truth and provability.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "decidable-for-validity",
    "type": "definition",
    "title_en": "Decidable for Validity",
    "ch": "III", "sec": "1",
    "latex": r"""A logic $\mathcal{L}$ is \emph{decidable for validity} if there exists an algorithm which determines for every proposition $p$, in a finite number of steps, whether or not $p$ is valid.""",
    "intro": "Decidability for validity means there is a mechanical procedure to determine if a formula is a tautology. For propositional logic, truth tables provide such a procedure.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "decidable-for-provability",
    "type": "definition",
    "title_en": "Decidable for Provability",
    "ch": "III", "sec": "1",
    "latex": r"""A logic $\mathcal{L}$ is \emph{decidable for provability} if there exists an algorithm which determines for every proposition $p$, in a finite number of steps, whether or not $p$ is a theorem.""",
    "intro": "Decidability for provability means there is a mechanical procedure to determine theoremhood. For a sound and adequate logic, this is equivalent to decidability for validity.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "soundness-theorem-prop",
    "type": "theorem",
    "title_en": "Soundness Theorem for Propositional Calculus",
    "ch": "III", "sec": "2",
    "latex": r"""Let $A \subseteq P(X)$, $p \in P(X)$. If $A \vdash p$ in $\operatorname{Prop}(X)$, then $A \models p$ in $\operatorname{Prop}(X)$.""",
    "intro": "The Soundness Theorem establishes that the formal proof system of Prop($X$) is correct: anything provable is semantically true. The proof uses induction on proof length and the fact that all axioms are tautologies.",
    "proof": r"""Suppose there exists a proof $p_1, \ldots, p_n$ of $p$ from $A$. Let $v: P(X) \to \mathbb{Z}_2$ be a valuation with $v(A) \subseteq \{1\}$. By induction on $n$:
$n=1$: $p \in \mathcal{A} \cup A$. If $p \in A$, then $v(p)=1$. If $p \in \mathcal{A}$, then $p$ is a tautology (Exercise 3.8 of Ch.II), so $v(p)=1$.
$n>1$: Assume $v(p_i)=1$ for $i<n$. If $p_n \in \mathcal{A} \cup A$, then $v(p_n)=1$. Otherwise, $p_i = p_j \Rightarrow p_n$ for some $i,j<n$. Then $v(p_j)=1$ and $v(p_j \Rightarrow p_n)=1$, so $v(p_n)=1$ by the homomorphism property.""",
    "exercises": []
})

concepts.append({
    "slug": "consistency-theorem-prop",
    "type": "corollary",
    "title_en": "Consistency Theorem for Propositional Calculus",
    "ch": "III", "sec": "2",
    "latex": r"""$F$ is not a theorem of $\operatorname{Prop}(X)$.""",
    "intro": "The Consistency Theorem follows immediately from the Soundness Theorem: if $F$ were a theorem, it would be a tautology, but $v(F) = 0$ for every valuation.",
    "proof": r"""If $\vdash F$, then by the Soundness Theorem, $\models F$. But for any valuation $v$, $v(F) = 0 \neq 1$, contradiction. Thus $\not\vdash F$.""",
    "exercises": []
})

concepts.append({
    "slug": "deduction-theorem-prop",
    "type": "theorem",
    "title_en": "Deduction Theorem for Propositional Calculus",
    "ch": "III", "sec": "2",
    "latex": r"""Let $A \subseteq P(X)$ and $p, q \in P(X)$. Then $A \cup \{p\} \vdash q$ if and only if $A \vdash p \Rightarrow q$.""",
    "intro": "The Deduction Theorem is a fundamental tool that relates implication to deduction: proving $q$ from $A$ plus $p$ is equivalent to proving $p \Rightarrow q$ from $A$ alone.",
    "proof": r"""($\Leftarrow$) If $A \vdash p \Rightarrow q$, then from a proof of $p \Rightarrow q$ from $A$, append $p$ (assumption) and $q$ (Modus Ponens) to get $A \cup \{p\} \vdash q$.
($\Rightarrow$) Suppose $p_1, \ldots, p_n = q$ is a proof of $q$ from $A \cup \{p\}$. We prove by induction on $n$ that $A \vdash p \Rightarrow p_i$ for each $i$.
$n=1$: If $q \in \mathcal{A} \cup A$, then $q, q \Rightarrow (p \Rightarrow q), p \Rightarrow q$ is a proof. If $q = p$, then $\vdash p \Rightarrow p$ (Example 4.5 of Ch.II).
$n>1$: If $p_i = p_j \Rightarrow q$ for $j,k < i$, the induction hypothesis gives $A \vdash p \Rightarrow p_j$ and $A \vdash p \Rightarrow (p_j \Rightarrow q)$. Using axiom $\mathcal{A}_2$ and Modus Ponens twice yields $A \vdash p \Rightarrow q$.""",
    "exercises": []
})

concepts.append({
    "slug": "consistent-subset",
    "type": "definition",
    "title_en": "Consistent and Maximal Consistent Subsets",
    "ch": "III", "sec": "2",
    "latex": r"""Let $A \subseteq P(X)$. We say that $A$ is \emph{consistent} if $F \notin \operatorname{Ded}(A)$. $A$ is called a \emph{maximal consistent subset} if $A$ is consistent and if every subset $T \subseteq P(X)$ which properly contains $A$ is inconsistent.""",
    "intro": "A consistent set of propositions is one from which a contradiction cannot be proved. A maximal consistent set is a consistent set that cannot be extended without becoming inconsistent.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "maximal-consistent-characterization",
    "type": "lemma",
    "title_en": "Characterization of Maximal Consistent Subsets",
    "ch": "III", "sec": "2",
    "latex": r"""The subset $A \subseteq P(X)$ is maximal consistent if and only if
(i) $F \notin A$,
(ii) $A = \operatorname{Ded}(A)$, and
(iii) for all $p \in P(X)$, either $p \in A$ or $\sim p \in A$.""",
    "intro": "This lemma gives an algebraic characterization of maximal consistent sets: they are deductively closed, contain no contradiction, and are complete in the sense that they decide every proposition.",
    "proof": r"""(a) Let $A$ be maximal consistent. Since $A$ is consistent, $F \notin \operatorname{Ded}(A)$, so $F \notin A$. By definition, $A \subseteq \operatorname{Ded}(A)$. If $\operatorname{Ded}(A) \neq A$, then $\operatorname{Ded}(A)$ properly contains $A$ and is consistent (since $F \notin \operatorname{Ded}(A)$), contradicting maximality. Thus $A = \operatorname{Ded}(A)$. For (iii), if $p \notin A$ and $\sim p \notin A$, then both $A \cup \{p\}$ and $A \cup \{\sim p\}$ are inconsistent, which would imply $A$ is inconsistent.
(b) Conversely, if $A$ satisfies (i)-(iii) and $B \supsetneq A$, pick $p \in B \setminus A$. By (iii), $\sim p \in A \subseteq B$, so $\{p, \sim p\} \subseteq B$. From $\{p, \sim p\} \vdash F$, we get $F \in \operatorname{Ded}(B)$, so $B$ is inconsistent.""",
    "exercises": []
})

concepts.append({
    "slug": "satisfiability-theorem-prop",
    "type": "theorem",
    "title_en": "Satisfiability Theorem for Propositional Calculus",
    "ch": "III", "sec": "2",
    "latex": r"""If $A$ is a consistent subset of $P(X)$, then there exists a valuation $v$ such that $v(A) \subseteq \{1\}$.""",
    "intro": "Every consistent set of propositions can be simultaneously satisfied by some valuation. This is the key lemma for proving the Adequacy (Completeness) Theorem.",
    "proof": r"""Let $M$ be a maximal consistent subset containing $A$ (exists by extending $A$ via Zorn's Lemma). For $p \in P(X)$, put $v(p) = 1$ if $p \in M$ and $v(p) = 0$ if $p \notin M$.
$v(F) = 0$ since $F \notin M$. To show $v(p \Rightarrow q) = v(p) \Rightarrow v(q)$:
- If $q \in M$, then $\{q\} \vdash p \Rightarrow q$, so $p \Rightarrow q \in M$, and $v(p \Rightarrow q) = 1 = v(p) \Rightarrow v(q)$.
- If $p \notin M$, then $\{\sim p\} \vdash p \Rightarrow q$, so $p \Rightarrow q \in M$, and $v(p \Rightarrow q) = 1 = v(p) \Rightarrow v(q)$.
- If $p \in M$ and $q \notin M$, then $p \Rightarrow q \notin M$ (otherwise Modus Ponens would give $q \in M$), so $v(p \Rightarrow q) = 0 = v(p) \Rightarrow v(q)$.""",
    "exercises": []
})

concepts.append({
    "slug": "adequacy-theorem-prop",
    "type": "theorem",
    "title_en": "Adequacy Theorem for Propositional Calculus",
    "ch": "III", "sec": "2",
    "latex": r"""Let $A \subseteq P(X)$, $p \in P(X)$. If $A \models p$ in $\operatorname{Prop}(X)$, then $A \vdash p$ in $\operatorname{Prop}(X)$.""",
    "intro": "The Adequacy (Completeness) Theorem establishes that semantic truth implies syntactic provability. Together with the Soundness Theorem, it shows $A \models p \iff A \vdash p$.",
    "proof": r"""Suppose $A \models p$. If $A \cup \{\sim p\}$ is consistent, then by the Satisfiability Theorem there is a valuation $v$ with $v(A \cup \{\sim p\}) \subseteq \{1\}$, contradicting $A \models p$. Hence $F \in \operatorname{Ded}(A \cup \{\sim p\})$, i.e., $A \cup \{\sim p\} \vdash F$. By the Deduction Theorem, $A \vdash \sim p \Rightarrow F$. Since $\vdash (\sim p \Rightarrow F) \Rightarrow p$, we obtain $A \vdash p$ by Modus Ponens.""",
    "exercises": []
})

concepts.append({
    "slug": "lindenbaum-algebra",
    "type": "definition",
    "title_en": "Lindenbaum Algebra",
    "ch": "III", "sec": "3",
    "latex": r"""Let $X_n = \{x_1, \ldots, x_n\}$. The \emph{Lindenbaum algebra} $L(X_n)$ is the set of congruence classes of elements of $P(X_n)$ with respect to the equivalence relation $u \sim v$ if $u \models v$ and $v \models u$ (i.e., $u$ and $v$ are semantically equivalent). Elements of $L(X_n)$ are identified with their associated truth functions $\mathbb{Z}_2^n \to \mathbb{Z}_2$.""",
    "intro": "The Lindenbaum algebra is the quotient of the proposition algebra by logical equivalence. Its elements correspond bijectively to truth functions, giving a finite Boolean algebra structure to the set of propositions in $n$ variables.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "truth-function",
    "type": "definition",
    "title_en": "Truth Function",
    "ch": "III", "sec": "3",
    "latex": r"""A function $f: \mathbb{Z}_2^n \to \mathbb{Z}_2$ is called a \emph{truth function}.""",
    "intro": "A truth function is any Boolean function of $n$ variables. The key result is that every truth function can be expressed by a proposition in $P(X_n)$.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "lindenbaum-is-all-truth-functions",
    "type": "theorem",
    "title_en": "Lindenbaum Algebra Equals All Truth Functions",
    "ch": "III", "sec": "3",
    "latex": r"""$L(X_n)$ is the set of all truth functions $f: \mathbb{Z}_2^n \to \mathbb{Z}_2$.""",
    "intro": "Every Boolean function in $n$ variables is representable by a propositional formula. This shows the functional completeness of the connectives $F$ and $\Rightarrow$.",
    "proof": r"""By induction on $n$. For $n = 0$, the constant functions $0 = \bar{F}$ and $1 = \overline{F \Rightarrow F}$ are in $L(X_n)$. Assume the result for $n-1$. For any truth function $f(x_1, \ldots, x_n)$, define $g(x_1, \ldots, x_{n-1}) = f(x_1, \ldots, x_{n-1}, 0)$ and $h(x_1, \ldots, x_{n-1}) = f(x_1, \ldots, x_{n-1}, 1)$. By induction, $g, h \in L(X_{n-1}) \subseteq L(X_n)$. Then $f = (\bar{x}_n \wedge g) \vee (x_n \wedge h)$, where $\bar{x}_n = \sim x_n$, is in $L(X_n)$ since $L(X_n)$ is closed under Boolean operations.""",
    "exercises": []
})

concepts.append({
    "slug": "prop-decidable-for-validity",
    "type": "theorem",
    "title_en": "Decidability of Prop(X) for Validity",
    "ch": "III", "sec": "3",
    "latex": r"""$\operatorname{Prop}(X)$ is decidable for validity.""",
    "intro": "The propositional calculus is decidable: there is an algorithm (truth tables) to determine in finitely many steps whether a formula is a tautology.",
    "proof": r"""For $w \in P(X)$, let $w = w(x_1, \ldots, x_n)$ be expressed in terms of finitely many variables. Let $\bar{w} \in L(X_n)$ be the associated truth function. Calculate $\bar{w}(a_1, \ldots, a_n)$ for each $(a_1, \ldots, a_n) \in \mathbb{Z}_2^n$. $w$ is valid iff all $2^n$ values are $1$.""",
    "exercises": []
})

concepts.append({
    "slug": "prop-decidable-for-provability",
    "type": "corollary",
    "title_en": "Decidability of Prop(X) for Provability",
    "ch": "III", "sec": "3",
    "latex": r"""$\operatorname{Prop}(X)$ is decidable for provability.""",
    "intro": "Since Prop($X$) is sound and adequate, provability coincides with validity, so the truth-table algorithm also decides theoremhood.",
    "proof": r"""An element $p \in P(X)$ is a theorem if and only if it is valid (by Soundness and Adequacy). The truth-table algorithm therefore decides provability.""",
    "exercises": []
})

# ─── CHAPTER IV: Predicate Calculus ────────────────────────────────────

concepts.append({
    "slug": "full-first-order-algebra",
    "type": "definition",
    "title_en": "Full First-Order Algebra",
    "ch": "IV", "sec": "1",
    "latex": r"""Let $\tilde{P}(V, \mathcal{R})$ be the free algebra on the set $\{(r, x_1, \ldots, x_n) \mid r \in \mathcal{R}, x_i \in V, n = \operatorname{ar}(r)\}$ of free generators, of type $\{F, \Rightarrow, (\forall x) \mid x \in V\}$, where $F$ is a $0$-ary operation, $\Rightarrow$ binary, and each $(\forall x)$ unary. This is called the \emph{full first-order algebra} on $(V, \mathcal{R})$.""",
    "intro": "The full first-order algebra extends the proposition algebra by adding universal quantifiers $(\forall x)$ for each individual variable $x$ and atomic formulas $r(x_1, \ldots, x_n)$ as generators. This provides the raw syntactic material for the predicate calculus.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "depth-of-quantification",
    "type": "definition",
    "title_en": "Depth of Quantification",
    "ch": "IV", "sec": "1",
    "latex": r"""Let $w \in \tilde{P}$. The \emph{depth of quantification} $d(w)$ is defined by:
(i) $d(F) = 0$, $d(r(x_1, \ldots, x_n)) = 0$ for every free generator,
(ii) $d(w_1 \Rightarrow w_2) = \max(d(w_1), d(w_2))$,
(iii) $d((\forall x)w) = 1 + d(w)$.""",
    "intro": "The depth of quantification measures the maximum nesting depth of quantifiers in a formula. It is used to define the congruence relation that yields the reduced first-order algebra.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "reduced-first-order-algebra",
    "type": "definition",
    "title_en": "Reduced First-Order Algebra",
    "ch": "IV", "sec": "1",
    "latex": r"""The \emph{reduced first-order algebra} $P(V, \mathcal{R})$ is the quotient of $\tilde{P}(V, \mathcal{R})$ by the congruence relation $\approx$ defined inductively: $w_1 \approx w_2$ if they have the same depth of quantification and are either identical (at depth 0), or their immediate subformulas are congruent (at depth $>0$), or they differ only by renaming of bound variables.""",
    "intro": "The reduced first-order algebra identifies formulas that differ only by renaming of bound variables (alpha-conversion). This avoids the technical complications of variable capture.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "free-variables-pred",
    "type": "definition",
    "title_en": "Free Variables of a Predicate Formula",
    "ch": "IV", "sec": "1",
    "latex": r"""For $w \in P$, the set $\operatorname{var}(w)$ of (free) variables of $w$ is defined inductively by:
(i) $\operatorname{var}(F) = \varnothing$,
(ii) $\operatorname{var}(r(x_1, \ldots, x_n)) = \{x_1, \ldots, x_n\}$,
(iii) $\operatorname{var}(w_1 \Rightarrow w_2) = \operatorname{var}(w_1) \cup \operatorname{var}(w_2)$,
(iv) $\operatorname{var}((\forall x)w) = \operatorname{var}(w) \setminus \{x\}$.""",
    "intro": "The set of free variables of a formula captures which individual variables occur outside the scope of any quantifier. This is fundamental for defining interpretations and the proof theory of quantifiers.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "interpretation-pred",
    "type": "definition",
    "title_en": "Interpretation of Pred(V, R)",
    "ch": "IV", "sec": "2",
    "latex": r"""An \emph{interpretation} of $P(V, \mathcal{R})$ consists of a non-empty set $U$, a function $\varphi: V \to U$, a function $\psi: \mathcal{R} \to \bigcup_n \operatorname{Pow}(U^n)$ such that $\psi(r) \subseteq U^{\operatorname{ar}(r)}$, and a valuation $v: P(V, \mathcal{R}) \to \mathbb{Z}_2$ satisfying natural conditions that make $v$ a homomorphism respecting the quantifiers.""",
    "intro": "An interpretation provides the semantic framework for predicate logic: a universe $U$, assignments of variables to elements of $U$, interpretations of relation symbols as relations on $U$, and a truth valuation respecting the logical connectives and quantifiers.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "axioms-of-pred",
    "type": "definition",
    "title_en": "Axioms of Pred(V, R)",
    "ch": "IV", "sec": "3",
    "latex": r"""The axioms of $\operatorname{Pred}(V, \mathcal{R})$ are all elements of $\mathcal{A} = \mathcal{A}_1 \cup \mathcal{A}_2 \cup \mathcal{A}_3 \cup \mathcal{A}_4 \cup \mathcal{A}_5$, where $\mathcal{A}_1, \mathcal{A}_2, \mathcal{A}_3$ are as in $\operatorname{Prop}(X)$ and
$$\mathcal{A}_4 = \{(\forall x)(p \Rightarrow q) \Rightarrow (p \Rightarrow ((\forall x)q)) \mid p, q \in P, x \notin \operatorname{var}(p)\},$$
$$\mathcal{A}_5 = \{(\forall x)p(x) \Rightarrow p(y) \mid p(x) \in P, y \in V\}.$$""",
    "intro": "The axioms of the predicate calculus extend those of the propositional calculus with two axiom schemas for quantifiers: $\mathcal{A}_4$ handles pulling quantifiers past non-free variables, and $\mathcal{A}_5$ is universal instantiation. The rules of inference are Modus Ponens and Generalisation.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "proof-in-pred",
    "type": "definition",
    "title_en": "Proof in Pred(V, R)",
    "ch": "IV", "sec": "3",
    "latex": r"""A \emph{proof} of length $n$ of $p$ from $A$ in $\operatorname{Pred}(V, \mathcal{R})$ is a sequence $p_1, \ldots, p_n$ such that $p_n = p$ and for each $i$, either (a) $p_i \in \mathcal{A} \cup A$, or (b) $p_j = p_k \Rightarrow p_i$ for some $j, k < i$ (Modus Ponens), or (c) $p_i = (\forall x)w$ where a proof of $w$ from some $A_0 \subseteq A$ with $x \notin \operatorname{var}(A_0)$ appears as a subsequence (Generalisation).""",
    "intro": "A proof in the predicate calculus extends the propositional notion by adding the rule of Generalisation: from a proof of $w(x)$ where $x$ is not free in the assumptions, infer $(\forall x)w(x)$.",
    "proof": None,
    "exercises": []
})

# §4 Properties (s007)

concepts.append({
    "slug": "semi-homomorphism",
    "type": "definition",
    "title_en": "Semi-Homomorphism of Predicate Algebras",
    "ch": "IV", "sec": "4",
    "latex": r"""A \emph{semi-homomorphism} $(\alpha, \beta): (P_1, V_1) \to (P_2, V_2)$ consists of a map $\alpha: P_1 \to P_2$ that preserves $F, \Rightarrow$, and a map $\beta: V_1 \to V_2$ such that $\alpha((\forall x)p) = (\forall \beta(x))\alpha(p)$ and $\beta$ is injective on $\operatorname{var}(p)$ whenever appropriate. It generalizes the notion of homomorphism to account for the renaming of variables.""",
    "intro": "A semi-homomorphism allows the renaming of individual variables while preserving the logical structure. It is the appropriate notion of morphism for predicate algebras, needed for the Substitution Theorem.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "substitution-theorem-pred",
    "type": "theorem",
    "title_en": "Substitution Theorem for Predicate Calculus",
    "ch": "IV", "sec": "4",
    "latex": r"""Let $(\alpha, \beta): (P_1, V_1) \to (P_2, V_2)$ be a semi-homomorphism. Let $A \subseteq P_1$, $p \in P_1$.
(a) If $A \vdash p$, then $\alpha(A) \vdash \alpha(p)$.
(b) If $A \models p$, then $\alpha(A) \models \alpha(p)$.""",
    "intro": "The Substitution Theorem for predicate calculus states that both provability and semantic consequence are preserved under semi-homomorphisms. This allows systematic renaming of variables in proofs and semantic arguments.",
    "proof": r"""(a) Let $p_1, \ldots, p_n$ be a proof from $A$. By induction on $n$, $\alpha(p_1), \ldots, \alpha(p_n)$ is a proof from $\alpha(A)$. The key case is when $p_n = (\forall x)w$ by Generalisation. Since $x \notin \operatorname{var}(A_0)$ and $\beta$ is injective on the relevant variables, $\beta(x) \notin \operatorname{var}(\alpha(A_0))$, so Generalisation applies.
(b) Similar induction over the proof using the semantic definitions.""",
    "exercises": []
})

concepts.append({
    "slug": "soundness-theorem-pred",
    "type": "theorem",
    "title_en": "Soundness Theorem for Predicate Calculus",
    "ch": "IV", "sec": "4",
    "latex": r"""Let $A \subseteq P(V, \mathcal{R})$, $p \in P(V, \mathcal{R})$. If $A \vdash p$ in $\operatorname{Pred}(V, \mathcal{R})$, then $A \models p$.""",
    "intro": "The Soundness Theorem for the predicate calculus guarantees that formal proofs produce only semantically valid consequences. The proof handles the Generalisation rule by using the interpretation's condition for quantified formulas.",
    "proof": r"""Let $p_1, \ldots, p_n$ be a proof of $p$ from $A$, and let $(U, \varphi, \psi, v)$ be an interpretation with $v(A) \subseteq \{1\}$. By induction on $n$:
$n=1$: $p \in \mathcal{A} \cup A$. All axioms are valid, so $v(p)=1$.
$n>1$: If by Modus Ponens, $v(p_j)=v(p_j \Rightarrow p_n)=1$, then $v(p_n)=1$. If by Generalisation, $p_n = (\forall x)q$, with a proof $q_1, \ldots, q_k$ of $q$ from $A_0$ where $x \notin \operatorname{var}(A_0)$. By the Substitution Theorem, for any extension with a new variable $t$, $q_1(t), \ldots, q_k(t)$ is a proof of $q(t)$ from $A_0$. By the induction hypothesis and condition $(c_r)$ in the definition of interpretation, $v((\forall x)q) = 1$.""",
    "exercises": []
})

concepts.append({
    "slug": "deduction-theorem-pred",
    "type": "theorem",
    "title_en": "Deduction Theorem for Predicate Calculus",
    "ch": "IV", "sec": "4",
    "latex": r"""Let $A \subseteq P(V, \mathcal{R})$ and $p, q \in P(V, \mathcal{R})$. If $A \cup \{p\} \vdash q$ and there is a proof of $q$ from $A \cup \{p\}$ in which Generalisation is not applied to any variable free in $p$, then $A \vdash p \Rightarrow q$.""",
    "intro": "The Deduction Theorem for predicate calculus carries a restriction: Generalisation must not be applied to variables that are free in the hypothesis being discharged. Without this restriction, one could incorrectly prove $p(x) \Rightarrow (\forall x)p(x)$.",
    "proof": r"""The proof follows the same inductive construction as for the propositional case, with the additional check for Generalisation. When the proof uses Generalisation to derive $(\forall x)r$ from $r$, where $x$ is not free in the assumptions (including $p$ by the hypothesis restriction), the corresponding step in the constructed proof uses $\mathcal{A}_4$ to distribute $p \Rightarrow$ over $(\forall x)$.""",
    "exercises": []
})

concepts.append({
    "slug": "satisfiability-theorem-pred",
    "type": "theorem",
    "title_en": "Satisfiability Theorem for Predicate Calculus",
    "ch": "IV", "sec": "4",
    "latex": r"""Let $A$ be a consistent subset of $P(V, \mathcal{R})$. Then there exists an interpretation of $P(V, \mathcal{R})$ in which all elements of $A$ are true.""",
    "intro": "Every consistent set of predicate formulas has a model. This is the key lemma for the Completeness Theorem, proved by constructing a maximal consistent extension with Henkin witnesses.",
    "proof": r"""Construct inductively $V^* = \bigcup_i V_i$ and $A^* = \bigcup_i A_i$ where $V_{i+1}$ adds new variables $t_p^{(i)}$ for each existential formula $(\exists x)q(x) \in A_i$, and $A_{i+1}$ adds $q(t_p^{(i)})$. The resulting $A^*$ is maximal consistent and has witnesses for all existential formulas. Then build a model with universe $V^*$ modulo the relation $x \sim y$ iff $\mathcal{I}(x, y) \in A^*$, and interpret relation symbols according to membership in $A^*$.""",
    "exercises": []
})

concepts.append({
    "slug": "adequacy-theorem-pred",
    "type": "theorem",
    "title_en": "Adequacy Theorem for Predicate Calculus (Gödel's Completeness Theorem)",
    "ch": "IV", "sec": "4",
    "latex": r"""Let $A \subseteq P(V, \mathcal{R})$, $p \in P(V, \mathcal{R})$. If $A \models p$ in $\operatorname{Pred}(V, \mathcal{R})$, then $A \vdash p$ in $\operatorname{Pred}(V, \mathcal{R})$. Thus $A \models p$ if and only if $A \vdash p$.""",
    "intro": "Gödel's Completeness Theorem (with Henkin's proof) establishes the equivalence of semantic and syntactic consequence for first-order logic. Together with the Soundness Theorem, it shows $A \models p \iff A \vdash p$.",
    "proof": r"""If $A \models p$, then $A \cup \{\sim p\}$ has no model, so is inconsistent by the Satisfiability Theorem. Thus $A \cup \{\sim p\} \vdash F$. By the Deduction Theorem, $A \vdash \sim p \Rightarrow F$, and $A \vdash p$ follows using the propositional tautology $(\sim p \Rightarrow F) \Rightarrow p$.""",
    "exercises": []
})

concepts.append({
    "slug": "compactness-theorem",
    "type": "corollary",
    "title_en": "Compactness Theorem for Predicate Calculus",
    "ch": "IV", "sec": "4",
    "latex": r"""If $A \models p$, then $A_0 \models p$ for some finite subset $A_0$ of $A$.""",
    "intro": "The Compactness Theorem states that if $p$ is a semantic consequence of $A$, it is already a consequence of some finite subset. This follows directly from the finiteness of proofs and the Completeness Theorem.",
    "proof": r"""If $A \models p$, then $A \vdash p$ by Adequacy. Any proof uses only finitely many assumptions from $A$, say $A_0$. Then $A_0 \vdash p$, and by Soundness $A_0 \models p$.""",
    "exercises": []
})

# ─── CHAPTER V: First-Order Mathematics ────────────────────────────────

concepts.append({
    "slug": "proper-interpretation",
    "type": "definition",
    "title_en": "Proper Interpretation",
    "ch": "V", "sec": "1",
    "latex": r"""Suppose $\mathcal{I} \in \mathcal{R}_2$. A \emph{proper interpretation} of $P(V, \mathcal{R})$ is an interpretation $(U, \varphi, \psi, v)$ such that $\psi(\mathcal{I})$ is the relation of identity on $U$.""",
    "intro": "A proper interpretation enforces that the distinguished binary relation symbol $\mathcal{I}$ is always interpreted as genuine equality. This is necessary for formalizing mathematics since equality has a fixed meaning across all structures.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "predicate-calculus-with-identity",
    "type": "definition",
    "title_en": "Predicate Calculus with Identity (Pred_g)",
    "ch": "V", "sec": "1",
    "latex": r"""$\operatorname{Pred}_g(V, \mathcal{R})$ is the logic with algebra of propositions $P(V, \mathcal{R} \cup \{\mathcal{I}\})$, valuations those arising from proper interpretations, and with proof of $p$ from $A$ in $\operatorname{Pred}_g(V, \mathcal{R})$ defined as a proof of $p$ from $I \cup A$ in $\operatorname{Pred}(V, \mathcal{R} \cup \{\mathcal{I}\})$.""",
    "intro": "$\operatorname{Pred}_g$ is the predicate calculus with equality built in. The axioms of identity $I$ include reflexivity and substitutivity for all relation symbols. Proofs in $\operatorname{Pred}_g$ are proofs in $\operatorname{Pred}$ with the identity axioms added as assumptions.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "first-order-theory",
    "type": "definition",
    "title_en": "First-Order Mathematical Theory",
    "ch": "V", "sec": "2",
    "latex": r"""A \emph{first-order mathematical theory} is a triple $\mathcal{T} = (\mathcal{R}, A, C)$ where $\mathcal{I} \in \mathcal{R}$, $A \subseteq P(V, \mathcal{R})$ for some $V \supseteq C$ such that $V \setminus C$ is infinite, and $\operatorname{var}(A) = C$. The set $A$ is called the set of (mathematical) axioms of $\mathcal{T}$, the set $C$ is called the set of (individual) constants, while the \emph{language} is $\mathcal{L}(\mathcal{T}) = \{p \in P(V, \mathcal{R}) \mid \operatorname{var}(p) \subseteq C\}$. A \emph{theorem} of $\mathcal{T}$ is $p \in \mathcal{L}(\mathcal{T})$ with $A \vdash p$.""",
    "intro": "A first-order theory formalizes a branch of mathematics by specifying relation symbols, individual constants, and axioms. The language consists of sentences (formulas with no free variables beyond the constants). This is the framework for studying formalized mathematical theories.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "model-of-first-order-theory",
    "type": "definition",
    "title_en": "Model of a First-Order Theory",
    "ch": "V", "sec": "2",
    "latex": r"""A \emph{model} of the first-order theory $\mathcal{T}$ is a proper interpretation $(M, v, \psi)$ of $P(V, \mathcal{R})$ such that $v(A) \subseteq \{1\}$. $M$ is the underlying set of the model, $v: C \to M$ maps constants to elements, and $\psi: \mathcal{R} \to \operatorname{rel}(M)$ interprets relation symbols.""",
    "intro": "A model is a set-theoretic structure in which all axioms of the theory are true. Model theory studies the relationship between formal theories and their interpretations.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "definable-relation",
    "type": "definition",
    "title_en": "Definable Relation and Function in a Theory",
    "ch": "V", "sec": "2",
    "latex": r"""The $n$-ary relation $\rho$ on the model $M$ of $\mathcal{T}$ is \emph{definable} in $\mathcal{T}$ if $\rho = \psi(p)$ for some $n$-variable formula $p$ of $\mathcal{T}$. A function $f: M^n \to M$ is \emph{definable} if there is an $(n+1)$-variable formula $p$ such that $f(a_1, \ldots, a_n) = b$ iff $p(a_1, \ldots, a_n, b)$ is true, and $\mathcal{T} \vdash (\forall x_1)\cdots(\forall x_n)(\exists!y)p(x_1, \ldots, x_n, y)$.""",
    "intro": "Definability captures which relations and functions on a model can be expressed within the formal language of the theory. A definable function must be provably single-valued.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "categorical-theory",
    "type": "definition",
    "title_en": "Categorical Theory in a Cardinal",
    "ch": "V", "sec": "3",
    "latex": r"""Let $\chi$ be a cardinal number. The theory $\mathcal{T}$ is called \emph{$\chi$-categorical} or \emph{categorical in cardinal $\chi$} if all models of $\mathcal{T}$ which have cardinal $\chi$ are isomorphic.""",
    "intro": "A theory is categorical in a cardinal if it determines a unique structure (up to isomorphism) of that size. For example, the theory of dense linear orders without endpoints is $\aleph_0$-categorical.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "models-of-arbitrarily-large-finite-cardinal",
    "type": "theorem",
    "title_en": "Theory with Arbitrarily Large Finite Models has Infinite Model",
    "ch": "V", "sec": "3",
    "latex": r"""Suppose the theory $\mathcal{T}$ has models of arbitrarily large finite cardinal. Then $\mathcal{T}$ has an infinite model.""",
    "intro": "If a theory has finite models of unbounded size, the Compactness Theorem implies it must also have an infinite model. This is a classic application of compactness.",
    "proof": r"""Let $\mathcal{T} = (\mathcal{R}, A, C)$ and put $\mathcal{T}' = (\mathcal{R}, A \cup \{\operatorname{al}(n) \mid n \in \mathbb{N}^+\}, C)$. Any finite subset of the new axioms is satisfied by a sufficiently large finite model of $\mathcal{T}$, so $\mathcal{T}'$ is consistent by Compactness. A model of $\mathcal{T}'$ is infinite.""",
    "exercises": []
})

concepts.append({
    "slug": "lowenheim-skolem-theorem",
    "type": "theorem",
    "title_en": "Löwenheim-Skolem Theorem",
    "ch": "V", "sec": "3",
    "latex": r"""Let $\mathcal{T}$ be a first-order theory of cardinal $\chi$, and let $\aleph$ be any infinite cardinal such that $\aleph \geqslant \chi$. Suppose $\mathcal{T}$ has an infinite model. Then $\mathcal{T}$ has a model of cardinal $\aleph$.""",
    "intro": "The Löwenheim-Skolem Theorem shows that first-order theories with infinite models have models in every sufficiently large infinite cardinality. This reveals a fundamental limitation of first-order logic: it cannot control the cardinality of its models.",
    "proof": r"""Choose $V_0 \supseteq C$ with $|V_0 \setminus C| = \aleph$. Then $|P(V_0, \mathcal{R})| = \aleph$. Add axioms $\sim \mathcal{I}(x, y)$ for all distinct $x, y \in V_0$ to force the model to have at least $\aleph$ elements. The resulting theory is consistent (by Compactness, since any finite subset involves only finitely many variables). A model is obtained via the Satisfiability Theorem with universe of cardinality $\aleph$.""",
    "exercises": []
})

concepts.append({
    "slug": "infinite-model-not-categorical",
    "type": "corollary",
    "title_en": "Infinite Model Implies Not Categorical",
    "ch": "V", "sec": "3",
    "latex": r"""If the first-order theory $\mathcal{T}$ has an infinite model, then $\mathcal{T}$ is not categorical (i.e., not categorical in all cardinals).""",
    "intro": "By the Löwenheim-Skolem Theorem, a theory with an infinite model has models of different infinite cardinalities, which cannot be isomorphic. Hence no first-order theory with infinite models can be categorical in all powers.",
    "proof": r"""By the Löwenheim-Skolem Theorem, $\mathcal{T}$ has models of cardinal $\aleph_0$ and $\aleph_1$, which are not isomorphic. Thus $\mathcal{T}$ is not categorical.""",
    "exercises": []
})

concepts.append({
    "slug": "categoricity-implies-completeness",
    "type": "corollary",
    "title_en": "Categoricity in an Infinite Cardinal Implies Completeness",
    "ch": "V", "sec": "3",
    "latex": r"""Suppose the theory $\mathcal{T}$ has cardinal $\chi$, and has only infinite models. Suppose also that $\mathcal{T}$ is categorical in some infinite cardinal $\aleph \geqslant \chi$. Then $\mathcal{T}$ is complete.""",
    "intro": "This is the Łoś-Vaught test: categoricity in an infinite cardinal implies completeness for theories with only infinite models. It provides a powerful method for proving completeness of theories.",
    "proof": r"""Let $p \in \mathcal{L}(\mathcal{T})$ and suppose neither $p$ nor $\sim p$ is a theorem. Then both $\mathcal{T} \cup \{p\}$ and $\mathcal{T} \cup \{\sim p\}$ are consistent, so each has an infinite model. By Löwenheim-Skolem, each has a model of cardinal $\aleph$. These models are isomorphic by categoricity, but $p$ is true in one and false in the other, contradiction.""",
    "exercises": []
})

concepts.append({
    "slug": "reduction-of-quantifiers",
    "type": "definition",
    "title_en": "Reduction of Quantifiers",
    "ch": "V", "sec": "4",
    "latex": r"""Let $\Pi \subseteq P(\mathcal{T})$. We say that $\mathcal{T}$ \emph{admits $\Pi$-reduction of quantifiers} if there is a process which assigns to each $p \in P(\mathcal{T})$ an element $q \in P(\mathcal{T})$ such that (i) $q$ is a propositional combination of elements of $\Pi$, (ii) $\operatorname{var}(q) \subseteq \operatorname{var}(p)$, and (iii) $\mathcal{T} \vdash p \Leftrightarrow q$.""",
    "intro": "Quantifier reduction (or elimination) allows every formula to be expressed equivalently as a Boolean combination of simple formulas. This is a key technique for proving decidability and completeness of theories.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "theory-of-equality-decidable",
    "type": "theorem",
    "title_en": "Decidability of the Theory of Equality",
    "ch": "V", "sec": "4",
    "latex": r"""The theory $\mathcal{E} = (\{\mathcal{I}\}, \varnothing, \varnothing)$ of equality is decidable.""",
    "intro": "The pure theory of equality (with no relation symbols except identity) admits quantifier elimination to formulas involving only 'there exist at least $n$ elements' statements. This yields decidability via truth-table analysis.",
    "proof": r"""The reduction process described in the text eliminates quantifiers, reducing every sentence to a propositional combination of $\operatorname{al}(n)$ formulas ($n \geqslant 1$). Since the only possible combinations of truth values for $\operatorname{al}(1), \ldots, \operatorname{al}(k)$ in any model are those where truth of $\operatorname{al}(n+1)$ implies truth of $\operatorname{al}(n)$, one checks the finitely many possibilities to determine if the formula is a theorem.""",
    "exercises": []
})

# ─── CHAPTER VI: Zermelo-Fraenkel Set Theory ──────────────────────────

for zf_name, zf_num, zf_stmt in [
    ("axiom-of-extension", "ZF1", r"""If $a$ and $b$ are sets, and if for all sets $x$ we have $x \in a$ if and only if $x \in b$, then $a = b$."""),
    ("axiom-schema-of-subsets", "ZF2", r"""For any set $a$ and any property $\pi$, there is a set $b$ such that $x \in b$ if and only if $x \in a$ and $x$ has the property $\pi$."""),
    ("axiom-of-pairing", "ZF3", r"""For any sets $a$ and $b$, there exists a set $c$ such that $a \in c$ and $b \in c$."""),
    ("axiom-of-union", "ZF4", r"""For every set $c$, there exists a set $a$ such that, if $x \in b$ and $b \in c$, then $x \in a$."""),
    ("axiom-of-power-set", "ZF5", r"""For each set $a$, there exists a set $b$ such that, if $x \subseteq a$, then $x \in b$."""),
    ("axiom-of-infinity", "ZF6", r"""There exists a set $a$ such that $\varnothing \in a$ and for each $x \in a$, $x \cup \{x\} \in a$."""),
    ("axiom-of-choice", "ZF7", r"""For each set $a$, there exists a function $f: \{x \in \operatorname{Pow}(a) \mid x \neq \varnothing\} \to a$, such that for every non-empty subset $x$ of $a$, $f(x) \in x$."""),
    ("axiom-schema-of-replacement", "ZF8", r"""For any property $\pi$ such that for each $x$ there is a unique $y$ with $\pi(x, y)$, and for any set $a$, there exists a set $b$ consisting of all $y$ for which there is $x \in a$ with $\pi(x, y)$."""),
    ("axiom-schema-of-restriction", "ZF9", r"""For any property $\pi$, if there exists a set $a$ with property $\pi$, then there exists a set $b$ with property $\pi$ such that no member of $b$ has property $\pi$."""),
]:
    concepts.append({
        "slug": zf_name,
        "type": "axiom",
        "title_en": f"{zf_num} — {zf_name.replace('-', ' ').title()}",
        "ch": "VI", "sec": "2",
        "latex": zf_stmt,
        "intro": f"Axiom {zf_num} of Zermelo-Fraenkel Set Theory. This axiom is part of the standard axiomatization of set theory that serves as the foundation for most of modern mathematics.",
        "proof": None,
        "exercises": []
    })

# ZF as first-order theory
concepts.append({
    "slug": "first-order-zf",
    "type": "definition",
    "title_en": "First-Order ZF (Zermelo-Fraenkel Formal Theory)",
    "ch": "VI", "sec": "3",
    "latex": r"""The formal theory $\mathcal{S}$ is the first-order theory with relation symbols $\{\mathcal{I}, \in\}$ (both binary), no individual constants, and the formalized versions of the ZF axioms (ZF1)-(ZF9).""",
    "intro": "Zermelo-Fraenkel Set Theory is formalized as a first-order theory with two binary relation symbols: equality and membership. The informal ZF axioms are expressed as sentences in the language of Pred$_g$.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "peano-axioms-formal",
    "type": "definition",
    "title_en": "Peano Axioms (Formal First-Order Theory)",
    "ch": "VI", "sec": "4",
    "latex": r"""The first-order theory $\mathcal{P}$ of Peano arithmetic has one unary relation symbol $\theta$ ($\theta(x)$ means $x = 0$) and one binary relation symbol $s$ ($s(x, y)$ means $x$ is the successor of $y$), with axioms:
$$P_1: (\exists!x)\theta(x), \quad P_2: (\forall x)(\exists!y)s(y, x),$$
$$P_3: (\forall x)(\forall y)(\forall z)((s(z, x) \wedge s(z, y)) \Rightarrow x = y),$$
$$P_4: (\forall x)(\forall y)(s(x, y) \Rightarrow \sim\theta(x)),$$
and the induction axiom scheme $P_5$.""",
    "intro": "The Peano axioms are formalized in first-order logic as the theory $\mathcal{P}$. The induction axiom is an axiom scheme parameterized by formulas $\pi$. Within ZF set theory, the natural numbers satisfy $\mathcal{P}$ and are determined up to isomorphism.",
    "proof": None,
    "exercises": []
})

# ─── CHAPTER VII: Ultraproducts ────────────────────────────────────────

concepts.append({
    "slug": "filter",
    "type": "definition",
    "title_en": "Filter on a Set",
    "ch": "VII", "sec": "1",
    "latex": r"""A set $\mathcal{F}$ of subsets of $I$ is a \emph{filter} on $I$ if:
(i) $\varnothing \notin \mathcal{F}$,
(ii) Every subset of $I$ which contains a set of $\mathcal{F}$ belongs to $\mathcal{F}$,
(iii) Every finite intersection of sets of $\mathcal{F}$ belongs to $\mathcal{F}$.
An \emph{ultrafilter} is a filter satisfying additionally:
(iv) For each $A \subseteq I$, exactly one of $A$ and $I \setminus A$ belongs to $\mathcal{F}$.""",
    "intro": "A filter formalizes the notion of a collection of 'large' subsets. An ultrafilter is a maximal filter, deciding membership for every subset. Filters are fundamental for constructing ultraproducts.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "los-theorem",
    "type": "theorem",
    "title_en": "Łoś's Theorem (Ultraproduct Theorem)",
    "ch": "VII", "sec": "1",
    "latex": r"""Let $\mathcal{T}$ be a first-order theory and $(M_i, v_i, \psi_i)$ ($i \in I$) be models of $\mathcal{T}$. Let $\mathcal{F}$ be an ultrafilter on $I$. Then the ultraproduct $\prod_{i \in I} M_i / \mathcal{F}$ is a model of $\mathcal{T}$, and for any formula $p(x)$,
$$(a^{(1)}\mathcal{F}, \ldots, a^{(n)}\mathcal{F}) \text{ satisfies } p(x) \iff \{i \in I \mid (a^{(1)}_i, \ldots, a^{(n)}_i) \text{ satisfies } p(x)\} \in \mathcal{F}.$$""",
    "intro": "Łoś's Theorem is the fundamental result about ultraproducts: truth in the ultraproduct is equivalent to truth in 'almost all' factors (with respect to the ultrafilter). It enables the construction of models with prescribed properties.",
    "proof": r"""By induction on the complexity of formulas. For atomic formulas, it follows from the definition of the ultraproduct structure (operations and relations are defined componentwise via the ultrafilter). For propositional connectives, the filter properties (ii) and (iii) handle $\wedge$ and $\vee$, while (iv) handles negation. For the universal quantifier, both directions require careful argument using condition (iv) and the fact that elements of the ultraproduct are equivalence classes of functions.""",
    "exercises": []
})

concepts.append({
    "slug": "finite-intersection-property",
    "type": "definition",
    "title_en": "Finite Intersection Property",
    "ch": "VII", "sec": "2",
    "latex": r"""The set $S$ of subsets of $I$ is said to have the \emph{finite intersection property} if every finite subset of $S$ has non-empty intersection.""",
    "intro": "The finite intersection property is the necessary and sufficient condition for a collection of sets to be extendable to a filter. It is a key tool for constructing ultrafilters with specific properties.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "filter-extension-lemma",
    "type": "lemma",
    "title_en": "Existence of Filter Containing a Set",
    "ch": "VII", "sec": "2",
    "latex": r"""Let $S$ be a set of subsets of $I$. There exists a filter on $I$ containing $S$ if and only if $S$ has the finite intersection property.""",
    "intro": "This lemma characterizes when a family of sets can be extended to a filter. The construction takes all finite intersections of sets in $S$, then all supersets of these intersections.",
    "proof": r"""Necessity is immediate. For sufficiency, put $T = \{U \subseteq I \mid U = J_1 \cap \cdots \cap J_n \text{ for some } n, J_i \in S\}$ and $\mathcal{F} = \{F \subseteq I \mid F \supseteq U \text{ for some } U \in T\}$. Then $\mathcal{F}$ is a filter containing $S$: $\varnothing \notin \mathcal{F}$ by the finite intersection property, upward closure is by definition, and finite intersections of sets in $\mathcal{F}$ contain finite intersections of elements of $T$, which are again in $T$.""",
    "exercises": []
})

concepts.append({
    "slug": "ultrafilter-existence",
    "type": "lemma",
    "title_en": "Every Filter is Contained in an Ultrafilter",
    "ch": "VII", "sec": "2",
    "latex": r"""Every filter $\mathcal{F}$ on $I$ is contained in an ultrafilter on $I$.""",
    "intro": "Using Zorn's Lemma, every filter can be extended to a maximal filter (ultrafilter). This guarantees the existence of non-principal ultrafilters on infinite sets.",
    "proof": r"""The set of filters on $I$ containing $\mathcal{F}$ is partially ordered by inclusion. Every chain has an upper bound (the union). By Zorn's Lemma, there exists a maximal element, which must be an ultrafilter (if it did not satisfy condition (iv), it could be properly extended).""",
    "exercises": []
})

concepts.append({
    "slug": "algebraic-closure-existence-via-ultraproducts",
    "type": "theorem",
    "title_en": "Existence of Algebraic Closure (via Ultraproducts)",
    "ch": "VII", "sec": "3",
    "latex": r"""Let $F$ be a field. Then there exists an algebraic closure of $F$.""",
    "intro": "The existence of algebraic closures is proved using ultraproducts, providing an elegant alternative to the classical algebraic proof using Zorn's Lemma. The ultraproduct of splitting fields yields an algebraically closed extension.",
    "proof": r"""Let $T$ be elementary field theory augmented with constants for $F$ and axioms for the field operations of $F$. For each polynomial $r \in F[x]$, let $F_r$ be a splitting field of $r$. Let $J_r = \{s \in F[x] \mid r \text{ splits over } F_s\}$. The family $\{J_r\}$ has the finite intersection property (since $r_1\cdots r_n \in J_{r_1} \cap \cdots \cap J_{r_n}$). By Lemmas 2.4 and 2.5, there exists an ultrafilter $\mathcal{F}$ containing all $J_r$. The ultraproduct $F^* = \prod F_r / \mathcal{F}$ is a field extension of $F$. For any monic polynomial $r$ over $F$, the set of indices where $r$ splits is in $\mathcal{F}$, so by Łoś's Theorem $r$ splits in $F^*$. Thus $F^*$ is algebraically closed. Let $\bar{F}$ be the subfield of $F^*$ of elements algebraic over $F$. Then $\bar{F}$ is an algebraic closure of $F$.""",
    "exercises": []
})

concepts.append({
    "slug": "alpha-complete-ultrafilter",
    "type": "definition",
    "title_en": "α-Complete Ultrafilter",
    "ch": "VII", "sec": "4",
    "latex": r"""An ultrafilter $\mathcal{F}$ on $I$ is called \emph{$\alpha$-complete} if the intersection of any $\beta < \alpha$ sets of $\mathcal{F}$ is again in $\mathcal{F}$. Otherwise, $\mathcal{F}$ is called \emph{$\alpha$-incomplete}.""",
    "intro": "An $\alpha$-complete ultrafilter is closed under intersections of fewer than $\alpha$ members. This generalizes the finite intersection property. The $\alpha$-completeness of an ultrafilter determines whether ultrapowers are trivial.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "ultrapower-triviality",
    "type": "theorem",
    "title_en": "Triviality Criterion for Ultrapowers",
    "ch": "VII", "sec": "4",
    "latex": r"""Let $\mathcal{F}$ be an ultrafilter on $I$ and let $\alpha = |M|$. Then $M = M^I / \mathcal{F}$ (i.e., the embedding is onto) if and only if $\mathcal{F}$ is $\alpha$-complete.""",
    "intro": "An ultrapower is trivial (isomorphic to the original model) exactly when the ultrafilter is sufficiently complete relative to the cardinality of the model. Non-principal ultrafilters on countable sets are $\omega$-incomplete, hence produce proper extensions.",
    "proof": r"""For $\mathcal{F}$ $\alpha$-complete, each $f\mathcal{F}$ equals some constant $m$ since $\{J_m = f^{-1}(m)\}$ partitions $I$ into $\alpha$ sets, so some $J_m \in \mathcal{F}$. Conversely, if $\mathcal{F}$ is $\alpha$-incomplete, $\alpha$ is infinite and one constructs a function that is not almost everywhere constant, giving a non-standard element.""",
    "exercises": []
})

concepts.append({
    "slug": "algebraic-theory",
    "type": "definition",
    "title_en": "Algebraic Theory",
    "ch": "VII", "sec": "6",
    "latex": r"""A theory $\mathcal{T}$ is called \emph{algebraic} if every axiom of $\mathcal{T}$ is either universal (of the form $(\forall y_1)\cdots(\forall y_s)q$ with $q$ quantifier-free) or has the form $(\forall x_1)\cdots(\forall x_r)(\exists y_1)\cdots(\exists y_s)p(x, y, c)$ where $p$ is built from primitive formulas using $\vee, \wedge$ only.""",
    "intro": "Algebraic theories are those whose axioms have a specific quantifier structure (universal or universal-existential with positive matrix). The category of models of an algebraic theory is closed under direct limits, generalizing the fact that classes like groups and rings are closed under direct limits.",
    "proof": None,
    "exercises": []
})

# ─── CHAPTER VIII: Non-Standard Models ─────────────────────────────────

concepts.append({
    "slug": "elementary-standard-system",
    "type": "definition",
    "title_en": "Elementary Standard System",
    "ch": "VIII", "sec": "1",
    "latex": r"""An \emph{elementary standard system} $\mathbf{S}$ is a set $S$ together with a subset $\mathcal{R}$ of the set of relations on $S$ such that $\mathcal{I} \in \mathcal{R}$.""",
    "intro": "An elementary standard system formalizes a mathematical structure (like the real numbers with addition, multiplication, and order) at the first-order level: only relations between elements, not properties of subsets, are treated.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "standard-and-nonstandard-models",
    "type": "definition",
    "title_en": "Standard and Non-Standard Models",
    "ch": "VIII", "sec": "1",
    "latex": r"""Let $*\mathbf{S}$ be any model of $\mathcal{T}(\mathbf{S})$. We say that $*\mathbf{S}$ is a \emph{standard model} if $*\mathbf{S}$ is isomorphic to $\mathbf{S}$, and otherwise $*\mathbf{S}$ is called a \emph{non-standard model}.""",
    "intro": "A standard model is the intended interpretation up to isomorphism. Non-standard models contain elements that do not correspond to any element of the original system, such as infinitesimals in non-standard analysis.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "concurrent-relation",
    "type": "definition",
    "title_en": "Concurrent Relation",
    "ch": "VIII", "sec": "3",
    "latex": r"""A binary relation $\rho$ on $S$ is called \emph{concurrent} if its domain is $D_\rho = \{x \in S \mid (\exists y \in S)\rho(x, y)\}$ and if, for any finite subset $\{x_1, \ldots, x_n\}$ of $D_\rho$, there exists $y \in S$ such that $\rho(x_i, y)$ is true for all $i = 1, \ldots, n$.""",
    "intro": "A concurrent relation is one that is finitely satisfiable: any finite collection of elements in the domain has a common $\rho$-image. The order relation on $\mathbb{R}$ is concurrent. Concurrent relations are used to construct enlargements with 'ideal' elements.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "enlargement",
    "type": "definition",
    "title_en": "Enlargement of a Theory",
    "ch": "VIII", "sec": "3",
    "latex": r"""The \emph{enlargement} of $\mathcal{T} = (\mathcal{R}, A, S)$ with respect to a set $\sigma$ of concurrent relations is the theory $\mathcal{T}^\sigma = (\mathcal{R}, A \cup A_\sigma, S \cup \{c_\rho \mid \rho \in \sigma\})$ where $A_\sigma = \{\rho(x, c_\rho) \mid \rho \in \sigma, x \in D_\rho\}$. A \emph{full enlargement} takes $\sigma$ as all concurrent relations.""",
    "intro": "An enlargement adds new constants $c_\rho$ that act as 'ideal elements' for each concurrent relation, satisfying $\rho(x, c_\rho)$ for all $x$ in the domain. This is the key construction for obtaining non-standard models with saturation properties.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "internal-and-external-relations",
    "type": "definition",
    "title_en": "Internal and External Relations",
    "ch": "VIII", "sec": "5",
    "latex": r"""An \emph{internal} first-order $n$-ary relation on $S^\sigma$ is an element of $(\mathcal{R}_n^{(1)})^\sigma$, i.e., belongs to the enlargement of the set of all $n$-ary relations. A relation that is not internal is called \emph{external}.""",
    "intro": "Internal relations are those that belong to the non-standard extension of the power set; they satisfy the same first-order properties as standard relations. External relations (like the set of standard natural numbers) are not captured by the formal theory and can exhibit properties not expressible in the first-order language.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "finite-infinite-infinitesimal-reals",
    "type": "definition",
    "title_en": "Finite, Infinite, and Infinitesimal Elements of *R",
    "ch": "VIII", "sec": "6",
    "latex": r"""An element $a \in *\mathbb{R}$ is called \emph{finite} if there exists a standard real number $b$ such that $|a| < b$. Otherwise $a$ is called \emph{infinite}. A finite element $a$ is called \emph{infinitesimal} if $|a| < b$ for all standard real numbers $b > 0$.""",
    "intro": "These definitions form the foundation of non-standard analysis. Finite numbers are bounded by standard reals, infinite numbers exceed all standard reals, and infinitesimals are smaller than all positive standard reals.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "monad",
    "type": "definition",
    "title_en": "Monad of a Real Number",
    "ch": "VIII", "sec": "6",
    "latex": r"""The \emph{monad} of the finite real number $a$ is the set $\mu(a) = \{r \in *\mathbb{R} \mid r \cong a\}$, where $a \cong b$ means $a - b$ is infinitesimal.""",
    "intro": "The monad of a standard real $a$ is the set of all hyperreals infinitesimally close to $a$. The quotient of the finite hyperreals by the infinitesimals is isomorphic to $\mathbb{R}$.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "monad-standard-unique",
    "type": "theorem",
    "title_en": "Structure of Finite Hyperreals",
    "ch": "VIII", "sec": "6",
    "latex": r"""If $a$ is a finite real number, then $\mu(a)$ contains exactly one standard real number. If $R_0$ is the set of finite real numbers and $R_1$ the set of infinitesimal real numbers, then $R_0$ is a ring, $R_1$ is an ideal of $R_0$, and $R_0 / R_1$ is isomorphic to $\mathbb{R}$.""",
    "intro": "Every finite hyperreal is infinitesimally close to exactly one standard real (its 'standard part'). The algebra of finite and infinitesimal numbers gives a clean algebraic characterization of the relationship between $\mathbb{R}$ and $*\mathbb{R}$.",
    "proof": r"""Uniqueness: if $r, s \in \mu(a)$ are standard, then $|r-s|$ is an infinitesimal standard real, so $|r-s|=0$ and $r=s$. Existence: consider $\{r \in \mathbb{R} \mid r < a\}$, a Dedekind cut, and by completeness of $\mathbb{R}$ it has a least upper bound $r_0$. Then $r_0 \in \mu(a)$. That $R_0$ is a ring and $R_1$ an ideal follows from the algebraic properties of infinitesimals. The map sending each finite $a$ to the unique standard real in $\mu(a)$ induces the isomorphism $R_0/R_1 \cong \mathbb{R}$.""",
    "exercises": []
})

concepts.append({
    "slug": "limit-via-nonstandard-analysis",
    "type": "theorem",
    "title_en": "Characterization of Limits via Non-Standard Analysis",
    "ch": "VIII", "sec": "6",
    "latex": r"""For a sequence $s: \mathbb{N} \to \mathbb{R}$, $\lim_{n \to \infty} s(n) = r$ if and only if $*s(n) \in \mu(r)$ for all infinite natural numbers $n$.""",
    "intro": "Non-standard analysis gives a remarkably intuitive characterization of limits: a sequence converges to $r$ exactly when its terms at all infinite indices are infinitesimally close to $r$. This eliminates the epsilon-delta quantifier complexity.",
    "proof": r"""Suppose $\lim s(n) = r$. For any standard $\varepsilon > 0$, there exists $n_0 \in \mathbb{N}$ such that $|s(n) - r| < \varepsilon$ for $n > n_0$. This statement transfers to $*\mathbb{R}$: for $n \in *\mathbb{N}$ with $n > n_0$, $|*s(n) - r| < \varepsilon$. So for infinite $n$, $|*s(n) - r| < \varepsilon$ for all standard $\varepsilon > 0$, i.e., $*s(n) \in \mu(r)$. The converse uses the same transfer principle in reverse.""",
    "exercises": []
})

concepts.append({
    "slug": "continuity-via-nonstandard-analysis",
    "type": "theorem",
    "title_en": "Characterization of Continuity via Non-Standard Analysis",
    "ch": "VIII", "sec": "6",
    "latex": r"""Let $U$ contain a neighbourhood of $a \in \mathbb{R}$ and $f: U \to \mathbb{R}$. Then $\lim_{x \to a} f(x) = \ell$ iff $*f(x) \in \mu(\ell)$ for all $x \neq a$ in $\mu(a)$. Consequently, $f$ is continuous at $a$ iff $*f(x) \cong *f(a)$ for all $x \in \mu(a)$.""",
    "intro": "A function is continuous at $a$ exactly when it maps the monad of $a$ into the monad of $f(a)$. This provides an intuitive rigorous foundation for the calculus of infinitesimals.",
    "proof": r"""The translation of the epsilon-delta definition into non-standard terms: $\lim_{x \to a} f(x) = \ell$ means $\forall \varepsilon > 0 \exists \delta > 0 \forall x (0 < |x-a| < \delta \Rightarrow |f(x)-\ell| < \varepsilon)$. In $*\mathbb{R}$, this transfers to: for $x \in \mu(a)$, $x \neq a$, we have $|x-a| < \delta$ for all standard $\delta > 0$, hence $|*f(x)-\ell| < \varepsilon$ for all standard $\varepsilon > 0$, so $*f(x) \in \mu(\ell)$.""",
    "exercises": []
})

# ─── CHAPTER IX: Turing Machines and Gödel Numbers ────────────────────

concepts.append({
    "slug": "turing-machine",
    "type": "definition",
    "title_en": "Turing Machine",
    "ch": "IX", "sec": "2",
    "latex": r"""A \emph{Turing machine} with (finite) alphabet $\mathfrak{S}$ and (finite) set $\mathfrak{Q}$ of internal states is a subset $M$ of $\mathfrak{Q} \times \mathfrak{S} \times (\mathfrak{S} \cup \{L, R\}) \times \mathfrak{Q}$ such that for each pair $(q_i, s_j)$ there is at most one quadruple beginning with $(q_i, s_j)$. The actions are: $(q_i, s_j, s_t, q_r)$ replaces $s_j$ by $s_t$ and changes state to $q_r$; $(q_i, s_j, R, q_r)$ moves right; $(q_i, s_j, L, q_r)$ moves left; the machine stops when no quadruple applies.""",
    "intro": "A Turing machine is a formal model of computation consisting of a finite-state control and an infinite tape. Despite its simplicity, it can compute any function intuitively regarded as 'effectively computable' (Church-Turing Thesis).",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "instantaneous-description",
    "type": "definition",
    "title_en": "Instantaneous Description of a Turing Machine",
    "ch": "IX", "sec": "2",
    "latex": r"""An \emph{instantaneous description} of a Turing machine $M$ with alphabet $\mathfrak{S}$ and set $\mathfrak{Q}$ of internal states is a finite string $s_{\alpha_1} \cdots s_{\alpha_r} q s_{\beta_1} \cdots s_{\beta_t}$ where $s_{\alpha_i}, s_{\beta_j} \in \mathfrak{S}$ and $q \in \mathfrak{Q}$.""",
    "intro": "An instantaneous description captures the complete configuration of a Turing machine at any moment: the tape contents and the current state. The computation proceeds by transitions between instantaneous descriptions.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "computation-turing-machine",
    "type": "definition",
    "title_en": "Computation by a Turing Machine",
    "ch": "IX", "sec": "2",
    "latex": r"""A \emph{computation} by the machine $M$ is a finite sequence $[d_0], [d_1], \ldots, [d_p]$ of states such that $[d_0]$ is initial ($q = q_0$), $[d_p]$ is terminal (no applicable quadruple), and $[d_i] \xrightarrow{M} [d_{i+1}]$ for $i = 0, 1, \ldots, p-1$. $M$ \emph{fails} for input $[d_0]$ if no such finite computation exists.""",
    "intro": "A computation is a finite sequence of machine configurations starting from an initial state and ending in a terminal state. Failure means the machine runs forever (infinite loop).",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "recursive-function",
    "type": "definition",
    "title_en": "(Partial) Recursive Function",
    "ch": "IX", "sec": "3",
    "latex": r"""A function $f: U \to \mathbb{N}^t$ with domain $U \subseteq \mathbb{N}^k$ is called \emph{(partial) recursive} if there exists a Turing machine $M$ such that $\Psi_M^{(k, t)} = f$, where $\Psi_M^{(k,t)}$ is the function computed by $M$ on inputs coded as $s_1^{n_1}s_0 s_1^{n_2}s_0 \cdots$.""",
    "intro": "A recursive function is one computable by a Turing machine. The class of recursive functions captures the intuitive notion of effective computability and is closed under composition, primitive recursion, and minimalisation.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "effectively-axiomatised-theory",
    "type": "definition",
    "title_en": "Effectively Axiomatised Theory",
    "ch": "IX", "sec": "5",
    "latex": r"""A theory $\mathcal{T}$ is called \emph{effectively axiomatised} if there is a Turing machine which, given the Gödel number of an element $q \in P(V^*, \mathcal{R}^*)$, determines whether or not $q$ is an axiom of $\mathcal{T}$.""",
    "intro": "A theory is effectively axiomatised when the set of (Gödel numbers of) axioms is recursive. This is a minimal requirement for a theory to be amenable to algorithmic study.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "decidable-theory",
    "type": "definition",
    "title_en": "Decidable Theory",
    "ch": "IX", "sec": "5",
    "latex": r"""A theory $\mathcal{T}$ is \emph{decidable} if there is a Turing machine which, for every $p \in \mathcal{L}(\mathcal{T})$, determines in a finite number of steps whether or not $\mathcal{T} \vdash p$.""",
    "intro": "A decidable theory has an algorithm for determining theoremhood. For effectively axiomatised and complete theories, decidability follows automatically.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "stopping-problem",
    "type": "theorem",
    "title_en": "Unsolvability of the Stopping Problem (Halting Problem)",
    "ch": "IX", "sec": "5",
    "latex": r"""The stopping problem for Turing machines is recursively insoluble: there is no Turing machine which determines, for all $n, r$, whether the $n$-th Turing machine $M_n$, started in state $q_0 \operatorname{code}(r)$, ever stops.""",
    "intro": "The Halting Problem is the classic example of a recursively unsolvable problem. The proof uses a diagonal argument: if a machine $H$ decided halting, one could construct a machine that halts iff $H$ says it does not, a contradiction.",
    "proof": r"""Suppose $f(n) = 1$ if $f_n(n)$ exists (i.e., $M_n$ halts on input $n$), $f(n) = 0$ otherwise, is recursive. Define $g(n) = f_n(n) + 1$ if $f_n(n)$ exists, $g(n) = 0$ otherwise. Then $g$ is recursive. Let $g = f_m$. Then $g(m) = f_m(m) = g(m)$, but also $g(m) = f_m(m) + 1$ if $f_m(m)$ exists. This is a contradiction, so $f$ cannot be recursive.""",
    "exercises": []
})

concepts.append({
    "slug": "sequence-number-function",
    "type": "lemma",
    "title_en": "Sequence Number Function (Gödel's β-function)",
    "ch": "IX", "sec": "6",
    "latex": r"""There exists a strongly definable function $\operatorname{seq}(b, r)$ and a pairing function $P$ such that every finite sequence can be encoded and decoded within recursive arithmetic. Specifically, for every sequence $t_0, \ldots, t_m$, there exists $b$ such that $\operatorname{seq}(b, r) = t_r$ for $r = 0, \ldots, m$.""",
    "intro": "The sequence number function (Gödel's $\beta$-function) allows encoding finite sequences of natural numbers as single numbers, enabling the formalization of syntactic notions like proofs within arithmetic. This is the key technical lemma for Gödel's Incompleteness Theorems.",
    "proof": r"""Using triangular numbers $T(n) = n(n+1)/2$ and the pairing $P(x,y) = T(x+y-2) + y$, define left/right inverses $L(z), R(z)$. Then $\operatorname{seq}(b, r) = \text{remainder of } L(b) \div (1 + (r+1)R(b))$. For any finite sequence $t_0, \ldots, t_m$, using the Chinese Remainder Theorem one finds $b$ with $\operatorname{seq}(b, r) = t_r$ for all $r \leqslant m$.""",
    "exercises": []
})

concepts.append({
    "slug": "recursive-functions-strongly-definable",
    "type": "theorem",
    "title_en": "Every Partial Recursive Function is Strongly Definable",
    "ch": "IX", "sec": "6",
    "latex": r"""Let $\mathcal{T} \supseteq \mathcal{N}_0$ be a theory with $\mathbb{N}$ as model. Then every partial recursive function is strongly definable in $\mathcal{T}$.""",
    "intro": "Any theory extending $\mathcal{N}_0$ (recursive arithmetic without induction) can express all partial recursive functions. This is the crucial link between recursion theory and formal arithmetic that enables the proof of undecidability.",
    "proof": r"""The Turing machine's step-by-step behavior is encoded using the sequence number function. For each quadruple of $M$, a formula $M_{\alpha,\beta}(x,y,z)$ describes one computation step. A formula $\psi(u,v;x,y,z)$ expresses that $x$ codes the $y$-th configuration of the computation on input $u$ with output $z$ at position $y$, with the computation having length $v$. The function computed is then extracted by existential quantification over computation codes.""",
    "exercises": []
})

concepts.append({
    "slug": "undecidability-of-recursive-arithmetic",
    "type": "theorem",
    "title_en": "Undecidability of Theories Extending N_0",
    "ch": "IX", "sec": "6",
    "latex": r"""Let $\mathcal{T} \supseteq \mathcal{N}_0$ be a theory which has $\mathbb{N}$ as model. Then $\mathcal{T}$ is undecidable. In particular, $\mathcal{N}$ (recursive arithmetic) is undecidable.""",
    "intro": "This is Church's Theorem: any consistent theory extending a minimal amount of arithmetic is undecidable. The proof reduces the Halting Problem to theoremhood in $\mathcal{T}$.",
    "proof": r"""Since every partial recursive function is strongly definable, there is a formula $\operatorname{comp}(x_1, x_2, x_3)$ defining the relation that $M_{x_1}$ on input $x_2$ computes $x_3$. If $\mathcal{T}$ were decidable, then for each $n$, one could decide $\mathcal{T} \vdash (\exists x)\operatorname{comp}(n, n, x)$, which would solve the Stopping Problem.""",
    "exercises": []
})

concepts.append({
    "slug": "godels-incompleteness-theorem",
    "type": "theorem",
    "title_en": "Gödel's First Incompleteness Theorem",
    "ch": "IX", "sec": "6",
    "latex": r"""Let $\mathcal{T} \supseteq \mathcal{N}_0$ be an effectively axiomatised theory which has $\mathbb{N}$ as model. Then $\mathcal{T}$ is incomplete: there exists $q \in \mathcal{L}(\mathcal{T})$ such that neither $\mathcal{T} \vdash q$ nor $\mathcal{T} \vdash \sim q$. In particular, $\mathcal{N}$ is incomplete.""",
    "intro": "Gödel's First Incompleteness Theorem shows that any consistent, effectively axiomatised theory containing enough arithmetic cannot be both complete and consistent. There will always be statements that are true but unprovable. Moreover, adding the unprovable statement as an axiom only creates new unprovable statements.",
    "proof": r"""By the strong definability of recursive functions, there is a formula $\pi(x,y)$ such that $\pi(m,n)$ is true in $\mathbb{N}$ iff $n$ is the Gödel number of a formula $w(x_0)$ and $m$ is the Gödel number of a proof of $w(\overline{G(w)})$ in $\mathcal{T}$. Choose $w(x_0) = \sim \pi(x_0, x_0)$ and let $q = w(\overline{G(w)})$. Then $\mathcal{T} \vdash q$ would imply $q$ is true in $\mathbb{N}$ (since $\mathbb{N}$ is a model), but $\mathcal{T} \vdash q$ would also mean some $m$ is a proof of $q$, so $\pi(n,n)$ would be true where $n = G(w)$, contradicting $q = \sim\pi(n,n)$. Thus $\not\vdash q$. But $q$ is true in $\mathbb{N}$, so $\sim q$ is false in $\mathbb{N}$ and hence $\not\vdash \sim q$ (by soundness).""",
    "exercises": []
})

concepts.append({
    "slug": "undecidability-of-predicate-calculus",
    "type": "theorem",
    "title_en": "Undecidability of the Predicate Calculus",
    "ch": "IX", "sec": "7",
    "latex": r"""If $\mathcal{R}$ contains at least one $n$-ary relation symbol with $n \geqslant 2$, then $\operatorname{Pred}(V, \mathcal{R})$ is undecidable. Moreover (Kalmar's Theorem), $\operatorname{Pred}(V, \{r\})$ is undecidable for any binary predicate symbol $r$.""",
    "intro": "The predicate calculus is undecidable as soon as it contains a binary relation symbol. This is Church's Theorem for first-order logic. Kalmar strengthened this to show that even the pure predicate calculus with a single binary relation symbol is undecidable.",
    "proof": r"""The proof reduces the undecidability of $\operatorname{Pred}(V, \{\rho\})$ (with a 4-ary $\rho$, which follows from the undecidability of $\mathcal{N}$) to that of $\operatorname{Pred}(V, \{r\})$ with binary $r$. The key lemma encodes a 4-ary relation on $S$ as a binary relation on $S' = \{K\} \cup S^2 \cup S^4$ via a carefully constructed $r$. A translation $f: P(V, \{\rho\}) \to P(V, \{r\})$ is defined such that $f(p)$ is a theorem iff $p$ is a theorem, preserving theoremhood while reducing the arity.""",
    "exercises": []
})

# ─── CHAPTER X: Hilbert's Tenth Problem, Word Problems ────────────────

concepts.append({
    "slug": "recursive-function-characterization",
    "type": "theorem",
    "title_en": "Algebraic Characterization of Recursive Functions",
    "ch": "X", "sec": "1",
    "latex": r"""The set of recursive functions coincides with the set of functions obtainable from the set $I$ of initial functions (zero, successor, projection) by finite iterations of composition, primitive recursion, and minimalisation.""",
    "intro": "Recursive functions can be built up algebraically from a small set of basic functions using three operations. This characterization (due to Kleene) provides evidence for Church's Thesis that all formalizations of effective computability are equivalent.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "diophantine-set",
    "type": "definition",
    "title_en": "Diophantine Set, Relation, and Function",
    "ch": "X", "sec": "1",
    "latex": r"""$S \subseteq \mathbb{N}^n$ is \emph{diophantine} if there is a polynomial $P(x_1, \ldots, x_n, y_1, \ldots, y_m)$ in $m+n$ variables such that $(x_1, \ldots, x_n) \in S$ iff $(\exists y_1, \ldots, y_m) P(x_1, \ldots, x_n, y_1, \ldots, y_m) = 0$. A function $f: \mathbb{N}^n \to \mathbb{N}$ is diophantine if its graph is diophantine.""",
    "intro": "A diophantine set is one definable by a polynomial equation using existential quantifiers. Matiyasevich's Theorem (building on work of Davis, Putnam, and Robinson) shows that recursively enumerable sets are exactly the diophantine sets.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "recursive-iff-diophantine",
    "type": "theorem",
    "title_en": "Recursive Functions are Diophantine (Matiyasevich's Theorem)",
    "ch": "X", "sec": "1",
    "latex": r"""A function is recursive if and only if it is diophantine. Equivalently, a subset $E \subseteq \mathbb{N}$ is recursively enumerable if and only if it is diophantine.""",
    "intro": "This is the celebrated result that solved Hilbert's Tenth Problem negatively. It establishes the exact equivalence between recursive enumerability and diophantine definability, showing that polynomial equations over $\mathbb{N}$ can encode arbitrary computations.",
    "proof": r"""One direction (diophantine $\Rightarrow$ recursive) is straightforward: checking membership involves an unbounded search. The converse uses the algebraic characterization of recursive functions: the initial functions are diophantine, and the class of diophantine functions is closed under composition, primitive recursion (using the sequence number function to encode intermediate values), and minimalisation.""",
    "exercises": []
})

concepts.append({
    "slug": "hilberts-tenth-problem-unsolvable",
    "type": "theorem",
    "title_en": "Insolubility of Hilbert's Tenth Problem",
    "ch": "X", "sec": "1",
    "latex": r"""There is no algorithm (Turing machine) that determines, for an arbitrary polynomial equation $P(x_1, \ldots, x_n) = 0$ with integer coefficients, whether it has a solution in integers.""",
    "intro": "Hilbert's Tenth Problem, asking for an algorithm to decide solvability of Diophantine equations, is unsolvable. The proof: if such an algorithm existed, every recursively enumerable set would be recursive (since diophantine = r.e.), contradicting the existence of non-recursive r.e. sets.",
    "proof": r"""Suppose there is an algorithm deciding solvability of Diophantine equations. Since every recursively enumerable set $E$ is diophantine, there is a polynomial $P$ such that $x \in E$ iff $(\exists y_1, \ldots, y_m) P(x, y_1, \ldots, y_m) = 0$. The algorithm would then decide membership in $E$, making $E$ recursive. But there exist recursively enumerable sets that are not recursive (e.g., the Halting Problem). Contradiction.""",
    "exercises": []
})

concepts.append({
    "slug": "group-presentation",
    "type": "definition",
    "title_en": "Group Presentation",
    "ch": "X", "sec": "2",
    "latex": r"""A \emph{group presentation} is a set $X$ together with a set $R$ of group-theoretical words on the elements of $X$. The presentation $(X, R)$ is called \emph{finite} if both $X$ and $R$ are finite. The group determined by $(X, R)$ is $F/K$ where $F$ is the free group on $X$ and $K$ is the smallest normal subgroup of $F$ containing $R$, written $G = \langle X \mid R \rangle$.""",
    "intro": "A group presentation specifies a group by generators and relations. The word problem asks whether two words represent the same group element. The conjugacy problem asks whether two elements are conjugate. The isomorphism problem asks whether two presentations define isomorphic groups.",
    "proof": None,
    "exercises": []
})

concepts.append({
    "slug": "semigroup-with-insoluble-word-problem",
    "type": "theorem",
    "title_en": "Existence of a Finitely Presented Semigroup with Insoluble Word Problem",
    "ch": "X", "sec": "2",
    "latex": r"""Let $E$ be a recursively enumerable but non-recursive subset of $\mathbb{N}$, and let $M$ be a Turing machine which stops on input $n$ iff $n \in E$. Then the semigroup presentation associated with $M$ has insoluble word problem.""",
    "intro": "By encoding Turing machine computations as semigroup relations, one constructs a finitely presented semigroup whose word problem is as hard as the Halting Problem. This construction (Post-Markov) is the foundation for proving the insolubility of the word problem for finitely presented groups.",
    "proof": r"""The semigroup presentation is constructed from the Turing machine $M$: generators include the symbols $s_j$, state symbols $q_i$, an end marker $e$, and possibly extra symbols. Relations encode the machine transitions. By Lemma 2.8, special words $w, w'$ with $w'$ terminal are equivalent iff there is a forward computation path. Thus the word problem for this presentation solves the halting problem for $M$ on inputs coding natural numbers. Since $E$ is non-recursive, the word problem is insoluble.""",
    "exercises": []
})


# ─── Write all files ────────────────────────────────────────────────────
def write_concept(c):
    slug = c["slug"]
    d = os.path.join(OUT, slug)
    os.makedirs(d, exist_ok=True)

    # concept.yaml
    yaml = f"""id: {slug}
title_en: "{c['title_en']}"
title_zh: ""
type: {c['type']}
domain: foundations
subdomain: mathematical-logic
difficulty: {'basic' if c['type'] in ('definition','axiom') else 'intermediate'}
tags: []
depends_on:
  required: []
  recommended: []
  suggested: []
source_books:
  - book_id: "gtm022"
    author: "Donald W. Barnes, John M. Mack"
    title: "An Algebraic Introduction to Mathematical Logic"
    chapter: "{c['ch']}"
    section: "{c['sec']}"
    pages: ""
    role_in_book: ""
content_hash: ""
extraction_date: "2026-06-27"
extraction_agent: "v8-full-extract"
"""
    with open(os.path.join(d, "concept.yaml"), "w") as f:
        f.write(yaml)

    # theorem.tex
    with open(os.path.join(d, "theorem.tex"), "w") as f:
        f.write(c["latex"] + "\n")

    # introduce.en.md
    intro = f"""---
role: introduce
locale: en
content_hash: ""
written_against: ""
---

{c['intro']}
"""
    with open(os.path.join(d, "introduce.en.md"), "w") as f:
        f.write(intro)

    # proof file (if applicable)
    if c.get("proof") and c["type"] not in ("definition", "axiom", "exercise"):
        ch_sec = c["ch"].replace("I", "1").replace("V", "5").replace("X", "10")
        # simpler mapping
        ch_map = {"I":"1","II":"2","III":"3","IV":"4","V":"5","VI":"6","VII":"7","VIII":"8","IX":"9","X":"10"}
        ch_num = ch_map.get(c["ch"], c["ch"])
        proof = f"""---
role: proof
locale: en
of_concept: {slug}
source_book: gtm022
source_chapter: "{c['ch']}"
source_section: "{c['sec']}"
---

{c['proof']}
"""
        fname = f"proof_gtm022_{ch_num}.{c['sec']}.en.md"
        with open(os.path.join(d, fname), "w") as f:
            f.write(proof)

    # exercise files
    if c.get("exercises"):
        for ex_num, ex_stmt in c["exercises"]:
            ch_num = ch_map.get(c["ch"], c["ch"])
            ex_file = f"exercise_gtm022_{ch_num}.{c['sec']}.{ex_num}.en.md"
            ex = f"""---
role: exercise
locale: en
chapter: "{c['ch']}"
section: "{c['sec']}"
exercise_number: {ex_num}
---

{ex_stmt}
"""
            with open(os.path.join(d, ex_file), "w") as f:
                f.write(ex)


for c in concepts:
    write_concept(c)

print(f"Written {len(concepts)} concepts to {OUT}")
with open(os.path.join(OUT, ".done"), "w") as f:
    f.write("DONE\n")
print("DONE marker written.")
