import Mathlib

open scoped Classical

/-!
# a-adic Filtration

For an ideal `a` of a commutative ring `R`, the **a-adic filtration** is the descending chain
of ideals

    a ⊇ a² ⊇ a³ ⊇ ··· ⊇ aⁱ ⊇ aⁱ⁺¹ ⊇ ···

where `aⁱ` denotes the `i`-th power of the ideal `a` (the ideal generated by all products
`a₁ ··· aᵢ` with each `aⱼ ∈ a`).

More generally, for any `R`-module `M`, the a-adic filtration on `M` is given by
`aⁱ • M` (the submodule generated by products of elements of `aⁱ` with elements of `M`).

## Mathlib4 Implementation

Mathlib4 provides the general notion of an `I`-filtration in `Mathlib/RingTheory/Filtration.lean`
as `Ideal.Filtration I M`, a structure consisting of a sequence of submodules `N i` with
`N (i+1) ≤ N i` and `I • N i ≤ N (i+1)`.

The a-adic filtration is the special case `Ideal.stableFiltration a ⊤` on `R` as an `R`-module,
which produces the sequence `N i = aⁱ`.
-/

variable {R : Type*} [CommRing R] (a : Ideal R)

/-- The **a-adic filtration** of the ring `R` by the ideal `a`.
This is the descending sequence `a⁰ ⊇ a¹ ⊇ a² ⊇ ⋯` of powers of `a`.

This is a special case of `Ideal.stableFiltration`, which gives
`I ^ i • N` for any `I`-filtration of a module `N`.
-/
abbrev adicFiltration : a.Filtration R :=
  Ideal.stableFiltration a ⊤

/-- The **a-adic filtration** of an `R`-module `M` by the ideal `a`.
This is the descending sequence `a⁰ • M ⊇ a¹ • M ⊇ a² • M ⊇ ⋯`.
-/
abbrev adicFiltration' (M : Type*) [AddCommGroup M] [Module R M] : a.Filtration M :=
  Ideal.stableFiltration a ⊤

example (a : Ideal ℤ) : (adicFiltration a).N 2 = a ^ 2 := by
  simp [adicFiltration, Ideal.stableFiltration]
