import Mathlib

open scoped Classical
open Ideal
open MvPolynomial

/-!
# Algebraic Variety

An **algebraic set** `V` defined by polynomials `f₁, …, fₘ` in `F[x₁, …, xₙ]` is called
an **algebraic variety** if the ideal `⟨f₁, …, fₘ⟩` generated by those polynomials is
a prime ideal of `F[x₁, …, xₙ]`.

Equivalently, an algebraic set `V = zeroLocus(I)` is a variety iff `vanishingIdeal(V)`
is prime (by the Nullstellensatz, over an algebraically closed field).

This file formalizes the classical definition using Mathlib4's existing
`MvPolynomial.zeroLocus` and `Ideal.IsPrime`.

## Main Definitions
* `MvPolynomial.zeroLocus K I` -- the zero set of an ideal `I` of multivariate polynomials
  (defined in `Mathlib/RingTheory/Nullstellensatz.lean`)
* `IsAlgebraicVariety V` -- the predicate that a subset `V ⊆ Fⁿ` is a nonempty algebraic set
  arising from a **prime ideal** of polynomials.

## Mathlib4 Cross-References
* `MvPolynomial.zeroLocus` -- defines algebraic sets in `RingTheory/Nullstellensatz.lean`
* `MvPolynomial.vanishingIdeal` -- the ideal of polynomials vanishing on a set
* `Ideal.IsPrime` -- prime ideal typeclass in `RingTheory/Ideal/Prime.lean`
* `MvPolynomial.IsPrime.vanishingIdeal_zeroLocus` -- for a prime ideal `P`,
  `vanishingIdeal(zeroLocus(P)) = P`
-/

variable {F : Type*} [Field F] {n : ℕ}

/-- An **algebraic variety** is a nonempty subset of `Fⁿ` that can be expressed
as the zero locus of a **prime ideal** of multivariate polynomials.

Formally, `V ⊆ Fⁿ` is an algebraic variety if `V ≠ ∅` and there exists a prime
ideal `P ⊲ F[x₁, …, xₙ]` such that `V = zeroLocus F P`.

This captures the classical definition: an algebraic set defined by polynomials
`f₁, …, fₘ` is a variety exactly when the ideal `⟨f₁, …, fₘ⟩` is prime. -/
def IsAlgebraicVariety (V : Set (Fin n → F)) : Prop :=
  V.Nonempty ∧ ∃ (P : Ideal (MvPolynomial (Fin n) F)), P.IsPrime ∧
    V = zeroLocus F P

/-! ## Examples -/

/-- **Example 1 (affine space):** The whole affine space `Fⁿ` is an algebraic variety.
It is the zero locus of the zero ideal `(0)`, which is prime because
the polynomial ring `F[x₁, …, xₙ]` is an integral domain. -/
example : IsAlgebraicVariety (Set.univ : Set (Fin n → F)) := by
  have h_nonempty : (Set.univ : Set (Fin n → F)).Nonempty :=
    ⟨λ _ => 0, Set.mem_univ _⟩
  have h_prime : (⊥ : Ideal (MvPolynomial (Fin n) F)).IsPrime :=
    Ideal.bot_prime
  refine ⟨h_nonempty, ⊥, h_prime, ?_⟩
  simp [zeroLocus_bot]

/-- **Example 2 (empty set):** The empty set is NOT an algebraic variety
because it fails the nonempty condition. -/
example : ¬ IsAlgebraicVariety (∅ : Set (Fin n → F)) := by
  intro h
  rcases h with ⟨hne, _, _, _⟩
  exact hne.ne_empty rfl

/-- **Example 3 (hyperplane):** The hyperplane `V(X₁) = {x | x₁ = 0}` in `F²`
is an algebraic variety because `⟨X₁⟩` is a prime ideal.
(Note: `X₁` is prime in `F[x₁,x₂]` since the quotient `F[x₁,x₂]/⟨X₁⟩ ≅ F[x₂]` is a domain.) -/
example (hprime : ((Ideal.span {MvPolynomial.X 0} : Ideal (MvPolynomial (Fin 2) F))).IsPrime) :
    IsAlgebraicVariety (zeroLocus F (Ideal.span {MvPolynomial.X 0} : Ideal (MvPolynomial (Fin 2) F))) := by
  have h_nonempty : (zeroLocus F (Ideal.span {MvPolynomial.X 0} : Ideal (MvPolynomial (Fin 2) F))).Nonempty := by
    refine ⟨λ _ => 0, ?_⟩
    rw [mem_zeroLocus_iff]
    intro p hp
    rw [Ideal.mem_span_singleton] at hp
    rcases hp with ⟨q, rfl⟩
    simp
  exact ⟨h_nonempty, Ideal.span {MvPolynomial.X 0}, hprime, rfl⟩

/-- **Example 4 (algebraic variety via prime ideal):** Given any prime ideal `P` of
`F[x₁, …, xₙ]`, its zero locus `zeroLocus F P` is nonempty (assuming `F` is algebraically
closed, by the Nullstellensatz). We demonstrate the definition with a specific prime ideal
`⟨X₁⟩` in `F[x₁, x₂]`, which yields the hyperplane `{x | x₁ = 0}`. -/
example (hprime : ((Ideal.span {MvPolynomial.X 0} : Ideal (MvPolynomial (Fin 2) F))).IsPrime) :
    IsAlgebraicVariety (zeroLocus F (Ideal.span {MvPolynomial.X 0} : Ideal (MvPolynomial (Fin 2) F))) := by
  have h_nonempty : (zeroLocus F (Ideal.span {MvPolynomial.X 0} : Ideal (MvPolynomial (Fin 2) F))).Nonempty := by
    refine ⟨λ _ => 0, ?_⟩
    rw [mem_zeroLocus_iff]
    intro p hp
    rw [Ideal.mem_span_singleton] at hp
    rcases hp with ⟨q, rfl⟩
    simp
  exact ⟨h_nonempty, Ideal.span {MvPolynomial.X 0}, hprime, rfl⟩
