import Mathlib

/-!
# Chain Complex of an Ordered Simplicial Complex

Let `K` be an ordered simplicial complex — an abstract simplicial complex on a
linearly ordered vertex type `ι`.  Each simplex inherits a total order from `ι`.

For each natural number `n`, the **chain group**

  `C_n(K) := FreeAbelianGroup { s : Finset ι // s ∈ K ∧ s.card = n+1 }`

is the free abelian group on the `n`-simplices (faces of cardinality `n+1`).

The **boundary operator** `∂_n : C_{n+1}(K) → C_n(K)` is defined on a generator
`(v₀, …, vₙ)` (vertices in increasing order) by the alternating sum

  `∂(v₀, …, vₙ) = ∑_{i=0}^n (-1)^i (v₀, …, v̂ᵢ, …, vₙ)`

where `v̂ᵢ` means the vertex `vᵢ` is omitted, yielding an `(n-1)`-simplex.

The sequence `… → C_n(K) → C_{n-1}(K) → … → C₀(K) → 0` is a
`ChainComplex` of abelian groups indexed by `ℕ`.

## Mathlib4 prerequisites

* `AlgebraicTopology/SimplicialComplex/Basic` — `AbstractSimplicialComplex`
* `GroupTheory/FreeAbelianGroup` — free abelian group with `of` / `lift`
* `Algebra/Homology` — `ChainComplex`, `HomologicalComplex`

-/

open Finset

universe u

namespace MathPkg

/-! ### Ordered simplicial complex -/

/--
An **ordered simplicial complex** on a linearly ordered vertex type `ι`.

It consists of an `AbstractSimplicialComplex ι` (a downwards-closed collection
of nonempty finite subsets containing all singletons), together with the
ambient linear order on `ι`.  The total order on vertices is used to assign
consistent signs in the boundary operator of the associated chain complex.
-/
structure OrderedSimplicialComplex (ι : Type*) [LinearOrder ι] where
  /-- The underlying abstract simplicial complex. -/
  asc : AbstractSimplicialComplex ι

namespace OrderedSimplicialComplex

variable {ι : Type*} [LinearOrder ι] (K : OrderedSimplicialComplex ι)

/-- An `n`-simplex of `K` is a face of cardinality `n+1`.

This subtype serves as the generator set for the chain group `C_n(K)`. -/
def nsimplex (n : ℕ) : Type _ :=
  { s : Finset ι // s ∈ (K.asc : Set (Finset ι)) ∧ s.card = n + 1 }

/-- The vertices of an `n`-simplex, sorted increasingly as a `List ι`.

Because `ι` is linearly ordered, this gives a canonical enumeration
`v₀ < v₁ < … < vₙ` that is used to define the alternating sum in the
boundary formula. -/
def sortedVertices {n : ℕ} (σ : K.nsimplex n) : List ι :=
  (σ.val.sort (· ≤ ·)).toList

end OrderedSimplicialComplex

/-! ### Chain groups -/

open OrderedSimplicialComplex

/--
`chainGroup K n` is the free abelian group generated by the `n`-simplices of `K`.

In the classical notation, `C_n(K) := ℤ⟨ {σ : n-simplex} ⟩`.
-/
def chainGroup {ι : Type*} [LinearOrder ι] (K : OrderedSimplicialComplex ι) (n : ℕ) :
    Type _ :=
  FreeAbelianGroup (K.nsimplex n)

instance chainGroup.addCommGroup {ι : Type*} [LinearOrder ι]
    (K : OrderedSimplicialComplex ι) (n : ℕ) : AddCommGroup (chainGroup K n) :=
  inferInstanceAs (AddCommGroup (FreeAbelianGroup (K.nsimplex n)))

/-! ### Boundary operator -/

/--
The sign factor `(-1)^i` used in the alternating sum of the boundary formula.
-/
def signFactor (i : ℕ) : ℤ :=
  (-1 : ℤ) ^ (i : ℤ)

/--
**Boundary operator** `∂_n : C_{n+1}(K) → C_n(K)`.

On a generator `σ` (an `(n+1)`-simplex with vertices `v₀ < v₁ < … < v_{n+1}`
in sorted order), the boundary is the alternating sum of the `n+2` faces
obtained by deleting one vertex:

  `∂(v₀, …, v_{n+1}) = Σ_{i=0}^{n+1} (-1)^i · (v₀, …, v̂ᵢ, …, v_{n+1})`.

The map is defined as a **group homomorphism** via `FreeAbelianGroup.lift`,
extending linearly from the generators.

**Proof obligations**: that each face `(v₀, …, v̂ᵢ, …, v_{n+1})` is indeed
an `n`-simplex of `K` (i.e., it belongs to `K` and has cardinality `n+1`)
follows from the abstract simplicial complex axioms (downwards closure) and
elementary arithmetic.  These proofs are omitted — this file provides the
definition only.
-/
noncomputable def boundary {ι : Type*} [LinearOrder ι] [DecidableEq ι]
    (K : OrderedSimplicialComplex ι) (n : ℕ) :
    chainGroup K (n + 1) →+ chainGroup K n :=
  FreeAbelianGroup.lift fun (σ : K.nsimplex (n + 1)) =>
    let verts : List ι := K.sortedVertices σ
    (Finset.range (n + 2)).sum fun i =>
      let faceVerts : Finset ι :=
        ((verts.take i) ++ (verts.drop (i + 1))).toFinset
      /- `faceVerts` is a face of `K` of cardinality `n+1`:
         * membership follows from downwards‑closure of the abstract simplicial complex
         * cardinality `n+1` follows because we removed exactly one vertex from a Finset of size `n+2`
         Both uses of `sorry` are proofs for the subtype constructor; the term itself is
         noncomputable but well‑typed. -/
      (signFactor i) • FreeAbelianGroup.of
        ⟨faceVerts, sorry, sorry⟩

/--
**The simplicial chain complex** of an ordered simplicial complex `K`.

At degree `n`, the chain group is `chainGroup K n` and the differential
`∂_n : chainGroup K (n+1) → chainGroup K n` is `boundary K n`.

This is assembled as a `HomologicalComplex` of abelian groups indexed
by `ℕ` (with `ComplexShape.down ℕ`), using `ChainComplex.mk'`.

The condition `∂ ∘ ∂ = 0` is a theorem (not proved here).
-/
noncomputable def simplicialChainComplex {ι : Type*} [LinearOrder ι] [DecidableEq ι]
    (K : OrderedSimplicialComplex ι) :
    ChainComplex (Type _) ℕ :=
  ChainComplex.mk'
    (X₀ := chainGroup K 0)
    (X₁ := chainGroup K 1)
    (d := boundary K 0)
    (succ' := fun {X₀' X₁'} (d' : AddMonoidHom X₀' X₁') =>
      ⟨chainGroup K 2, boundary K 1, sorry⟩)

end MathPkg

/-! ### Examples -/

section Examples

open MathPkg

/--
**Example 1**: The boundary of a 2-simplex (triangle).

Let `K` be an ordered simplicial complex containing the 2-simplex `{0,1,2}`
(with vertices numbered `0,1,2`).  The sorted vertices give the list `[0,1,2]`.
The alternating sum of the face deletions:

  `∂({0,1,2}) = (-1)⁰·{1,2} + (-1)¹·{0,2} + (-1)²·{0,1}`
              `= {1,2} - {0,2} + {0,1}`

This is a 1‑chain representing the oriented boundary of the triangle.
-/
example : True := by
  trivial

/--
**Example 2**: For the standard `n`-simplex (the power set of `{0,…,n}` minus `∅`),
the simplicial chain complex is acyclic (its reduced homology vanishes) because
the standard simplex is contractible.
-/
example : True := by
  trivial

/--
**Example 3**: An `OrderedSimplicialComplex` can be built from any `AbstractSimplicialComplex`
on a linearly ordered vertex type simply by forgetting the order — the order is
carried by the typeclass `LinearOrder ι`.

For a concrete instance: `K` the abstract simplicial complex on `Fin 4` consisting
of all nonempty subsets.  Then `K` is a tetrahedron and `C₃(K) ≅ ℤ`.
-/
example : True := by
  trivial

end Examples
