import Mathlib

open scoped Classical
open scoped BigOperators

/-!
# Characterization of Membership in a Homogeneous Ideal via its Truncation

Let `I` be a homogeneous ideal in the polynomial ring `K[Z₀,…,Zₙ]`, and let
`I' = I ∩ (Z₀,…,Zₙ)^k` be the **truncation** of `I` at degree `k`.

**Theorem:** A polynomial `F` lies in `I` if and only if the product of `F` with
every homogeneous polynomial of sufficiently high degree lies in `I'`.

Formally:
  `F ∈ I ↔ ∃ d₀, ∀ d ≥ d₀, ∀ G homogeneous of degree d, F·G ∈ I'`

This is a fundamental result in commutative algebra / algebraic geometry: the
truncation determines the ideal completely, since multiplying by all sufficiently
high-degree homogeneous polynomials and testing against the truncation recovers
membership.
-/

variable {K : Type*} [CommRing K] {n : ℕ}

/-- The **irrelevant maximal ideal** `𝔪 = (Z₀, …, Zₙ)` in `K[Z₀,…,Zₙ]`:
the ideal generated by all the variables. -/
def irrelevantIdeal : Ideal (MvPolynomial (Fin (n+1)) K) :=
  Ideal.span (Set.range MvPolynomial.X)

/-- An ideal `I` in `K[Z₀,…,Zₙ]` is **homogeneous** if for every `f ∈ I`,
all homogeneous components of `f` belong to `I`.

This is equivalent to `I` being generated by homogeneous polynomials. -/
def IsHomogeneousIdeal (I : Ideal (MvPolynomial (Fin (n+1)) K)) : Prop :=
  ∀ (f : MvPolynomial (Fin (n+1)) K), f ∈ I →
    ∀ (d : ℕ), MvPolynomial.homogeneousComponent d f ∈ I

/-- **Characterization of a homogeneous ideal via its truncation.**
Let `I` be a homogeneous ideal and `I' = I ∩ 𝔪^k` (the truncation). Then
`F ∈ I` iff `F·G ∈ I'` for all homogeneous `G` of sufficiently high degree. -/
theorem characterisation_of_i_via_truncation_i
    (I : Ideal (MvPolynomial (Fin (n+1)) K))
    (hI : IsHomogeneousIdeal I)
    (k : ℕ)
    (F : MvPolynomial (Fin (n+1)) K) :
    (F ∈ I) ↔ ∃ (d₀ : ℕ), ∀ (d : ℕ), d₀ ≤ d →
      ∀ (G : MvPolynomial (Fin (n+1)) K), G.IsHomogeneous d →
        F * G ∈ I ⊓ (irrelevantIdeal ^ k) := by
  sorry
