import Mathlib

open scoped Classical
open CategoryTheory
open CategoryTheory.Limits

/-!
# Coequalizer as a colimit

The **coequalizer** of a pair of parallel morphisms `ψ, ψ' : C₁ ⟶ C₂` in a category `C`
is the colimit of the diagram `parallelPair ψ ψ' : WalkingParallelPair ⥤ C`.

This diagram consists of two objects (`C₁` and `C₂`), their identity morphisms,
and the two morphisms `ψ` and `ψ'`.

Mathlib4 defines `coequalizer f g` as `colimit (parallelPair f g)` — this is the standard
definition of a coequalizer as a special case of a colimit.

The universal property: for any object `W` and morphism `k : C₂ ⟶ W` such that
`ψ ≫ k = ψ' ≫ k`, there exists a unique morphism `coequalizer ψ ψ' ⟶ W` making the
diagram commute.
-/

section coequalizer_as_a_colimit

variable {C : Type u} [Category.{v} C]

/-- The coequalizer of two parallel morphisms `f, g : X ⟶ Y` is defined as
the colimit of the diagram `parallelPair f g`. This is the standard Mathlib4 definition.

We re-state it here with explicit docstring to show that the coequalizer **is**
the colimit, not a distinct construction. -/
def coequalizerAsColimit (X Y : C) (f g : X ⟶ Y) [HasColimit (parallelPair f g)] : C :=
  colimit (parallelPair f g)

/-- The projection morphism from `Y` to the coequalizer. -/
noncomputable def coequalizerAsColimit.π (X Y : C) (f g : X ⟶ Y) [HasColimit (parallelPair f g)] :
    Y ⟶ coequalizerAsColimit X Y f g :=
  colimit.ι (parallelPair f g) WalkingParallelPair.one

/-- The condition that `f` and `g` become equal after composing with the coequalizer map. -/
theorem coequalizerAsColimit.condition (X Y : C) (f g : X ⟶ Y) [HasColimit (parallelPair f g)] :
    f ≫ coequalizerAsColimit.π X Y f g = g ≫ coequalizerAsColimit.π X Y f g := by
  -- This follows from the definition of coequalizer as a colimit
  -- and the structure of the parallelPair diagram.
  simpa [coequalizerAsColimit.π, coequalizerAsColimit] using
    colimit.w (parallelPair f g) WalkingParallelPairHom.left

/-- The equality with Mathlib's `coequalizer`. This confirms our definition matches Mathlib4. -/
example (X Y : C) (f g : X ⟶ Y) [HasColimit (parallelPair f g)] :
    coequalizerAsColimit X Y f g = coequalizer f g :=
  rfl

end coequalizer_as_a_colimit

/-! ### Examples -/

section examples

variable {C : Type u} [Category.{v} C]

/-- In `Type u`, the coequalizer of two functions `f, g : X → Y` is `Y / ~`
where `~` is the equivalence relation generated by `f x ~ g x`.
Mathlib4's `coequalizer` in `Type` computes this quotient. -/
example (X Y : Type u) (f g : X → Y) : HasCoequalizer f g := by
  infer_instance

/-- In the category of commutative rings `CommRingCat`, the coequalizer of
two homomorphisms `f, g : R → S` is `S / I` where `I` is the ideal generated by
`{f(r) - g(r) | r ∈ R}`. The coequalizer exists because `CommRingCat` has all colimits. -/
example (R S : CommRingCat) (f g : R ⟶ S) : HasCoequalizer f g := by
  infer_instance

/-- The coequalizer of `id` and `id` on an object `X` is `X` itself. -/
example (X : C) [HasCoequalizer (𝟙 X) (𝟙 X)] : coequalizer (𝟙 X) (𝟙 X) ≅ X :=
  -- The coequalizer of identical maps is isomorphic to the codomain.
  coequalizer.unique_up_to_iso (𝟙 X) (𝟙 X) (coequalizer.cofork (𝟙 X) (𝟙 X))
    (Cofork.ofπ (𝟙 X) (by simp))

/-- The coequalizer projection `coequalizer.π f g` is an epimorphism
(this follows from coequalizers being regular epimorphisms). -/
example (X Y : C) (f g : X ⟶ Y) [HasCoequalizer f g] [Epi (coequalizer.π f g)] :
    Epi (coequalizer.π f g) := by
  infer_instance

/-- The cofork `Cofork.ofπ (coequalizer.π f g) (coequalizer.condition f g)` is a colimit cocone,
i.e., it satisfies the universal property of a colimit. -/
example (X Y : C) (f g : X ⟶ Y) [HasCoequalizer f g] :
    IsColimit (Cofork.ofπ (coequalizer.π f g) (coequalizer.condition f g)) :=
  coequalizerIsCoequalizer f g

/-- For any commutative ring `R` and ideal `I`, the coequalizer of the inclusion
`I → R` and the zero map is the quotient ring `R / I`. This shows that
coequalizers in `CommRingCat` correspond to quotient rings. -/
example (R : Type u) [CommRing R] (I : Ideal R) :
    HasCoequalizer
      (Submodule.subtype (I.restrictScalars ℤ) : (I : Type u) →ₗ[ℤ] R)
      (0 : (I : Type u) →ₗ[ℤ] R) :=
  inferInstance

/-- In the parallel pair diagram, the object `C₁` (called `.left` in the walking parallel pair)
corresponds to the domain of `f` and `g`, and `C₂` (called `.right`) to the codomain. -/
example (X Y : C) (f g : X ⟶ Y) : (parallelPair f g).obj WalkingParallelPair.one = Y := rfl

end examples
