import Mathlib

open MvPolynomial

/-!
# Definition of Coordinate Ring of an Algebraic Set

The coordinate ring C(A) of an algebraic set A ⊆ K^σ (where K is a field and σ is an
index type for the variables) is the ring of all polynomial functions on A, with
pointwise addition and multiplication.

Formally, C(A) = K[X_σ] / I(A), where I(A) = `vanishingIdeal K A` is the ideal of
polynomials that vanish at every point of A. The field K is identified with the constant
polynomials (via the map `k ↦ [k]`), making C(A) a ring extension of K generated by the
images of the coordinate functions `X_i`.

## Main definitions

* `coordinateRing K A` : The coordinate ring of a subset A ⊆ (σ → K), defined as the
  quotient `MvPolynomial σ K ⧸ MvPolynomial.vanishingIdeal K A`.
* `coordinateRing.mk` : The quotient map from the polynomial ring onto the coordinate ring.
* `coordinateRing.coordinate i` : The image of the variable `X_i` in the coordinate ring.

## References

* `Mathlib/RingTheory/Nullstellensatz.lean` for `vanishingIdeal` and `zeroLocus`.
-/

noncomputable section

variable (K : Type*) [Field K] {σ : Type*}

/-- The coordinate ring of a subset `A` of K^σ. This is the ring of polynomial functions
on A, obtained by quotienting the polynomial ring K[X_σ] by the ideal `I(A)` of polynomials
that vanish on A.

If A = V(J) is an algebraic set (the zero locus of an ideal J), then by the Nullstellensatz
(for algebraically closed K) the coordinate ring is K[X_σ] / √J, i.e., the reduced ring
of polynomial functions on A. For an arbitrary subset A, we take the ideal
`MvPolynomial.vanishingIdeal K A` of all polynomials that vanish everywhere on A. -/
def coordinateRing (A : Set (σ → K)) : Type _ :=
  MvPolynomial σ K ⧸ MvPolynomial.vanishingIdeal K A

namespace coordinateRing

variable {K} {σ} (A : Set (σ → K))

/-- The coordinate ring carries a natural commutative ring structure
inherited from the quotient ring. -/
noncomputable instance instCommRing : CommRing (coordinateRing K A) :=
  inferInstanceAs (CommRing (MvPolynomial σ K ⧸ MvPolynomial.vanishingIdeal K A))

/-- The coordinate ring is a K-algebra via the map `k ↦ [constant k]`. -/
noncomputable instance instAlgebra : Algebra K (coordinateRing K A) :=
  inferInstanceAs (Algebra K (MvPolynomial σ K ⧸ MvPolynomial.vanishingIdeal K A))

/-- The canonical quotient map from the polynomial ring K[X_σ] onto the
coordinate ring C(A) = K[X_σ] / I(A). -/
def mk : MvPolynomial σ K → coordinateRing K A :=
  Ideal.Quotient.mk (MvPolynomial.vanishingIdeal K A)

/-- The image of the variable `X_i` in the coordinate ring. These are the
coordinate functions on A (the restrictions of the coordinate projections K^σ → K). -/
def coordinate (i : σ) : coordinateRing K A :=
  mk A (X i)

end coordinateRing

section Examples

open coordinateRing

variable (K : Type*) [Field K]

/-- Example: The coordinate ring of the algebraic set A = V(X₁) = {x ∈ K² | x₁ = 0}
is the quotient K[X₁,X₂] / ⟨X₁⟩. In the coordinate ring, the coordinate function
`coordinate A 0` (image of X₁) is zero. -/
example : True := by
  let A : Set (Fin 2 → K) := MvPolynomial.zeroLocus K (Ideal.span {MvPolynomial.X 0})
  -- C(A) = K[X₁,X₂] / I(A)
  have h_def : coordinateRing K A =
      MvPolynomial (Fin 2) K ⧸ MvPolynomial.vanishingIdeal K A := rfl
  -- X₁ maps to zero in C(A)
  have h_x1_zero : mk A (MvPolynomial.X 0) = (0 : coordinateRing K A) := by
    apply Ideal.Quotient.eq_zero_iff_mem.mpr
    -- X₁ ∈ I(A) because X₁ vanishes on the zero locus of ⟨X₁⟩
    exact MvPolynomial.le_vanishingIdeal_zeroLocus (Ideal.span {MvPolynomial.X 0})
      (Ideal.subset_span (by simp))
  trivial

/-- Example: The coordinate ring of the empty set is the zero ring, because the
vanishing ideal of the empty set is the whole ring. -/
example : True := by
  have h_ideal : MvPolynomial.vanishingIdeal K (∅ : Set (Fin 2 → K)) = ⊤ :=
    MvPolynomial.vanishingIdeal_empty
  -- Hence C(∅) = K[X] / ⊤ ≅ {0} (the zero ring)
  have h_ring : coordinateRing K (∅ : Set (Fin 2 → K)) = MvPolynomial (Fin 2) K ⧸ (⊤ : Ideal (MvPolynomial (Fin 2) K)) := by
    simpa [coordinateRing, h_ideal]
  trivial

/-- Example: For the whole affine space A = K^σ, the coordinate ring is the
full polynomial ring K[X_σ], because `zeroLocus K ⊥ = ⊤` and `vanishingIdeal K ⊤ = ⊥`
(for K infinite; for finite fields the vanishing ideal of the whole space is still ⊥
since one can interpolate). -/
example : True := by
  let A : Set (Fin 2 → K) := Set.univ
  -- The coordinate ring of all K² is K[X₁,X₂] modulo the ideal of polynomials
  -- that vanish everywhere; when K is infinite this ideal is ⊥.
  have h : coordinateRing K A = MvPolynomial (Fin 2) K ⧸ MvPolynomial.vanishingIdeal K Set.univ := rfl
  trivial

end Examples
