import Mathlib

open scoped Classical

/-!
# Description of Principal Ideal

Let `R` be a ring and `a ∈ R`. The principal two-sided ideal `(a)` consists of
all finite sums of elements of the following forms:
- `n • a` where `n : ℤ` (integer multiples)
- `r * a` where `r : R` (left multiples)
- `a * s` where `s : R` (right multiples)
- `r * a * s` where `r, s : R` (two-sided multiples)

## Relation to Mathlib4

Mathlib4's `Ideal.span {a}` is defined as a *left* ideal (via `Submodule.span R {a}`).
For commutative rings, left ideals and two-sided ideals coincide, and `Ideal.mem_span_singleton`
already gives `x ∈ span({a}) ↔ a ∣ x`. This file provides the explicit construction
of the two-sided principal ideal as an additive subgroup generated by the four basic forms.
In a `CommRing`, we prove equality with `Ideal.span {a}`.
-/

namespace description_of_principal_ideal

variable {R : Type*} [Ring R]

/-- The four types of basic generators for the principal two-sided ideal (a).
This inductive predicate captures exactly the four forms appearing in the concept. -/
inductive PrincipalIdealGen (a : R) : R → Prop
  | int_mul (n : ℤ) : PrincipalIdealGen a (n • a)
  | left_mul (r : R) : PrincipalIdealGen a (r * a)
  | right_mul (s : R) : PrincipalIdealGen a (a * s)
  | two_sided_mul (r s : R) : PrincipalIdealGen a (r * a * s)

/-- The principal two-sided ideal of `a` in `R`. It is defined as the additive subgroup
generated by the four basic forms: `n • a`, `r * a`, `a * s`, `r * a * s`.

This is the explicit construction of the (two-sided) principal ideal `(a)`. -/
def principalIdeal (a : R) : AddSubgroup R :=
  AddSubgroup.closure {x | PrincipalIdealGen a x}

/-- Scoped notation `⟪a⟫` for the principal two-sided ideal. -/
scoped notation "⟪" a "⟫" => principalIdeal a

/-- Every basic generator belongs to the principal ideal. -/
theorem mem_principalIdeal_gen {a x : R} (h : PrincipalIdealGen a x) : x ∈ principalIdeal a :=
  AddSubgroup.subset_closure h

/-- `a` is in its own principal ideal (as `1 * a`). -/
theorem mem_principalIdeal_self (a : R) : a ∈ principalIdeal a := by
  have h : PrincipalIdealGen a ((1 : R) * a) := PrincipalIdealGen.left_mul (1 : R)
  simpa [one_mul] using mem_principalIdeal_gen h

/-- Zero is in the principal ideal. -/
theorem zero_mem_principalIdeal (a : R) : (0 : R) ∈ principalIdeal a :=
  AddSubgroup.zero_mem _

/-- The principal ideal is closed under addition. -/
theorem add_mem_principalIdeal {a x y : R} (hx : x ∈ principalIdeal a) (hy : y ∈ principalIdeal a) :
    x + y ∈ principalIdeal a :=
  AddSubgroup.add_mem _ hx hy

/-- The principal ideal is closed under negation. -/
theorem neg_mem_principalIdeal {a x : R} (hx : x ∈ principalIdeal a) :
    -x ∈ principalIdeal a :=
  AddSubgroup.neg_mem _ hx

/-- Integer multiples stay in the principal ideal. -/
theorem zsmul_mem_principalIdeal {a x : R} (hx : x ∈ principalIdeal a) (n : ℤ) :
    n • x ∈ principalIdeal a :=
  AddSubgroup.zsmul_mem _ hx n

/-- **Left multiplication**: If `x ∈ ⟪a⟫` then `r * x ∈ ⟪a⟫` for any `r : R`.
This is proved by induction on the closure construction: each generator type
is mapped to a generator by left multiplication. -/
theorem mul_mem_left_principalIdeal {a : R} (r : R) {x : R} (hx : x ∈ principalIdeal a) :
    r * x ∈ principalIdeal a := by
  -- Use the dependent induction principle for additive subgroups
  refine AddSubgroup.closure_induction (p := λ y _ => r * y ∈ ⟪a⟫)
    (by
      intro y hy
      -- hy : y ∈ {x | PrincipalIdealGen a x}, i.e., PrincipalIdealGen a y
      -- Pattern match on the four generator types
      cases hy with
      | int_mul n =>
        -- y = n • a → r * (n • a) = n • (r * a)
        rw [mul_smul_comm]
        have hra : r * a ∈ ⟪a⟫ := mem_principalIdeal_gen (PrincipalIdealGen.left_mul r)
        exact zsmul_mem_principalIdeal hra n
      | left_mul r' =>
        -- y = r' * a → r * (r' * a) = (r * r') * a
        rw [← mul_assoc]
        exact mem_principalIdeal_gen (PrincipalIdealGen.left_mul (r * r'))
      | right_mul s =>
        -- y = a * s → r * (a * s) = (r * a) * s
        rw [← mul_assoc]
        exact mem_principalIdeal_gen (PrincipalIdealGen.two_sided_mul r s)
      | two_sided_mul r' s =>
        -- y = r' * a * s → r * (r' * a * s) = (r * r') * a * s
        rw [← mul_assoc, ← mul_assoc]
        exact mem_principalIdeal_gen (PrincipalIdealGen.two_sided_mul (r * r') s))
    (by
      -- p 0 (zero_mem _) i.e., r * 0 ∈ ⟪a⟫
      simp)
    (by
      intro u v hu hv ihu ihv
      -- ihu : r * u ∈ ⟪a⟫, ihv : r * v ∈ ⟪a⟫
      -- Need: r * (u + v) ∈ ⟪a⟫
      rw [mul_add]
      exact add_mem_principalIdeal ihu ihv)
    (by
      intro u hu ihu
      -- ihu : r * u ∈ ⟪a⟫
      -- Need: r * (-u) ∈ ⟪a⟫
      rw [mul_neg]
      exact neg_mem_principalIdeal ihu)
    hx

/-- **Right multiplication**: If `x ∈ ⟪a⟫` then `x * s ∈ ⟪a⟫` for any `s : R`.
This is proved similarly by induction on the closure construction. -/
theorem mul_mem_right_principalIdeal {a : R} {x : R} (hx : x ∈ principalIdeal a) (s : R) :
    x * s ∈ principalIdeal a := by
  refine AddSubgroup.closure_induction (p := λ y _ => y * s ∈ ⟪a⟫)
    (by
      intro y hy
      cases hy with
      | int_mul n =>
        -- y = n • a → (n • a) * s = n • (a * s)
        rw [smul_mul_assoc]
        -- n • (a * s) ∈ ⟪a⟫ because a * s is a generator and the subgroup is zsmul-closed
        have h_mem : a * s ∈ ⟪a⟫ := mem_principalIdeal_gen (PrincipalIdealGen.right_mul s)
        exact AddSubgroup.zsmul_mem _ h_mem n
      | left_mul r' =>
        -- y = r' * a → (r' * a) * s = r' * a * s
        exact mem_principalIdeal_gen (PrincipalIdealGen.two_sided_mul r' s)
      | right_mul s' =>
        -- y = a * s' → (a * s') * s = a * (s' * s)
        rw [mul_assoc]
        exact mem_principalIdeal_gen (PrincipalIdealGen.right_mul (s' * s))
      | two_sided_mul r' s' =>
        -- y = r' * a * s' → (r' * a * s') * s = r' * a * (s' * s)
        rw [mul_assoc, mul_assoc]
        exact mem_principalIdeal_gen (PrincipalIdealGen.two_sided_mul r' (s' * s)))
    (by
      simp)
    (by
      intro u v hu hv ihu ihv
      rw [add_mul]
      exact add_mem_principalIdeal ihu ihv)
    (by
      intro u hu ihu
      rw [neg_mul]
      exact neg_mem_principalIdeal ihu)
    hx

/-- The principal ideal is closed under two-sided multiplication. -/
theorem mul_mem_mul_principalIdeal {a : R} {x : R} (hx : x ∈ principalIdeal a) (r s : R) :
    r * x * s ∈ principalIdeal a := by
  apply mul_mem_right_principalIdeal (mul_mem_left_principalIdeal r hx) s

end description_of_principal_ideal

/-!
## Relation to `Ideal.span {a}` in commutative rings

In a `CommRing`, left ideals are automatically two-sided, and `Ideal.span {a}`
coincides with our explicit description of the principal two-sided ideal.
-/

section comm_ring_equality

variable {R : Type*} [CommRing R] (a : R)

open description_of_principal_ideal

/-- In a commutative ring, every generator of the principal ideal is in `Ideal.span {a}`. -/
theorem principalIdealGen_mem_span {x : R} (h : PrincipalIdealGen a x) : x ∈ Ideal.span ({a} : Set R) := by
  cases h with
  | int_mul n =>
    -- x = n • a
    have ha : a ∈ Ideal.span ({a} : Set R) := by
      apply Ideal.subset_span; simp
    rw [zsmul_eq_mul]
    exact Submodule.smul_mem (Ideal.span ({a} : Set R)) (n : R) ha
  | left_mul r =>
    -- x = r * a
    have ha : a ∈ Ideal.span ({a} : Set R) := by
      apply Ideal.subset_span; simp
    exact Submodule.smul_mem (Ideal.span ({a} : Set R)) r ha
  | right_mul s =>
    -- x = a * s = s * a (commutative)
    have ha : a ∈ Ideal.span ({a} : Set R) := by
      apply Ideal.subset_span; simp
    rw [mul_comm]
    exact Submodule.smul_mem (Ideal.span ({a} : Set R)) s ha
  | two_sided_mul r s =>
    -- x = r * a * s = (r * s) * a (commutative)
    have ha : a ∈ Ideal.span ({a} : Set R) := by
      apply Ideal.subset_span; simp
    rw [mul_assoc, mul_comm a s, ← mul_assoc]
    exact Submodule.smul_mem (Ideal.span ({a} : Set R)) (r * s) ha

/-- In a commutative ring, `⟪a⟫ ⊆ Ideal.span {a}`. -/
theorem principalIdeal_subset_span : (principalIdeal a : Set R) ⊆ (Ideal.span ({a} : Set R) : Set R) := by
  intro x hx
  -- hx : x ∈ principalIdeal a, which is AddSubgroup.closure {x | PrincipalIdealGen a x}
  -- Use closure induction to show x ∈ Ideal.span {a}
  refine AddSubgroup.closure_induction (p := λ y _ => y ∈ (Ideal.span ({a} : Set R) : Set R)) ?_ ?_ ?_ ?_ hx
  · -- generators
    intro y hy
    -- hy : PrincipalIdealGen a y
    have hy' : y ∈ Ideal.span ({a} : Set R) := principalIdealGen_mem_span a hy
    simpa
  · -- zero
    simp
  · -- add
    intro u v hu hv ihu ihv
    simpa using add_mem ihu ihv
  · -- neg
    intro u hu ihu
    simpa using neg_mem ihu

/-- In a commutative ring, `Ideal.span {a} ⊆ ⟪a⟫`. This follows because:
`Ideal.span {a}` is the smallest ideal containing `a`, and every element of that ideal
can be written as `r * a` for some `r : R` (in a commutative ring). -/
theorem span_subset_principalIdeal : (Ideal.span ({a} : Set R) : Set R) ⊆ (principalIdeal a : Set R) := by
  intro x hx
  -- hx : x ∈ (Ideal.span ({a} : Set R) : Set R)
  -- Convert to Ideal membership
  have hx' : x ∈ Ideal.span ({a} : Set R) := hx
  obtain ⟨r, hr⟩ := (Ideal.mem_span_singleton' (x := x) (y := a)).mp hx'
  -- hr : r * a = x
  rw [← hr]
  -- goal: r * a ∈ (principalIdeal a : Set R)
  have h : r * a ∈ principalIdeal a := mem_principalIdeal_gen (PrincipalIdealGen.left_mul r)
  simpa using h

/-- **Description of Principal Ideal (commutative case)**: In a commutative ring `R`,
the principal ideal `(a) = Ideal.span {a}` equals the additive subgroup generated
by `n • a`, `r * a`, `a * s`, and `r * a * s` (for `n : ℤ`, `r, s : R`). -/
theorem description_of_principal_ideal_comm : (Ideal.span ({a} : Set R) : Set R) = (principalIdeal a : Set R) :=
  Set.Subset.antisymm (span_subset_principalIdeal a) (principalIdeal_subset_span a)

end comm_ring_equality

/-! ## Examples -/

section examples

open description_of_principal_ideal

/-- In ℤ, the principal ideal (2) consists of all even integers. Our description
gives the same result as Mathlib4's `Ideal.mem_span_singleton`. -/
example {x : ℤ} (hx : x ∈ Ideal.span ({(2 : ℤ)} : Set ℤ)) : Even x := by
  rw [Ideal.mem_span_singleton] at hx
  rcases hx with ⟨y, hx⟩
  rw [hx]
  exact ⟨y, by ring⟩

/-- Using our description in ℤ: x ∈ ⟪2⟫ iff x is even. -/
example {x : ℤ} (hx : x ∈ principalIdeal (2 : ℤ)) : Even x := by
  have h_eq := description_of_principal_ideal_comm (2 : ℤ)
  -- This gives set equality, so we can transfer hx to Ideal.span
  have hx_set : x ∈ (principalIdeal (2 : ℤ) : Set ℤ) := hx
  have hx' : x ∈ (Ideal.span ({(2 : ℤ)} : Set ℤ) : Set ℤ) := by
    rw [← h_eq]
    exact hx_set
  -- Now hx' is a Set membership; convert to Ideal membership
  have hx_ideal : x ∈ Ideal.span ({(2 : ℤ)} : Set ℤ) := hx'
  rw [Ideal.mem_span_singleton] at hx_ideal
  rcases hx_ideal with ⟨y, hx'⟩
  rw [hx']
  exact ⟨y, by ring⟩

/-- In any ring, the integer multiple 3•a is in the principal ideal (a). -/
example (R : Type*) [Ring R] (a : R) : (3 : ℤ) • a ∈ principalIdeal a :=
  mem_principalIdeal_gen (PrincipalIdealGen.int_mul 3)

/-- In any ring, r*a is in the principal ideal (a). -/
example (R : Type*) [Ring R] (a r : R) : r * a ∈ principalIdeal a :=
  mem_principalIdeal_gen (PrincipalIdealGen.left_mul r)

/-- In any ring, a*s is in the principal ideal (a). -/
example (R : Type*) [Ring R] (a s : R) : a * s ∈ principalIdeal a :=
  mem_principalIdeal_gen (PrincipalIdealGen.right_mul s)

/-- In any ring, r*a*s is in the principal ideal (a). -/
example (R : Type*) [Ring R] (a r s : R) : r * a * s ∈ principalIdeal a :=
  mem_principalIdeal_gen (PrincipalIdealGen.two_sided_mul r s)

end examples
