import Mathlib

open Set
open Subgroup

set_option maxHeartbeats 800000

/-
Description of the subgroup generated by a set.

If `G` is a group and `X` is a nonempty subset of `G`, then the subgroup `⟨X⟩` generated by `X`
equals the join (in the subgroup lattice) of all cyclic subgroups `⟨a⟩` for `a ∈ X`.
In other words, every element of `⟨X⟩` is a finite product of integer powers of elements of `X`.

In particular, for a single element `a ∈ G`, `⟨a⟩ = {aⁿ | n ∈ ℤ}` (the `zpowers` of `a`).
-/

/-- The subgroup generated by a nonempty set `X` equals the supremum (join) of the cyclic
subgroups `zpowers a` for `a ∈ X`. This is the fundamental characterization theorem:
`⟨X⟩` consists of all finite products `a₁ⁿ¹ a₂ⁿ² ⋯ aₜⁿᵗ` where `aᵢ ∈ X` and `nᵢ ∈ ℤ`. -/
theorem closure_eq_iSup_zpowers_of_nonempty {G : Type*} [Group G] {X : Set G} (hX : X.Nonempty) :
    closure X = ⨆ a ∈ X, zpowers a := by
  apply le_antisymm
  · -- `closure X ≤ ⨆ a ∈ X, zpowers a`
    -- Since `⨆ a ∈ X, zpowers a` is a subgroup containing `X`,
    -- and `closure X` is the smallest such subgroup.
    rw [closure_le]
    intro x hx
    have hx' : x ∈ zpowers x := mem_zpowers x
    have hmem : zpowers x ≤ ⨆ a ∈ X, zpowers a :=
      le_iSup₂ (f := fun (a : G) (_ : a ∈ X) => zpowers a) x hx
    exact hmem hx'
  · -- `⨆ a ∈ X, zpowers a ≤ closure X`
    -- Since each `zpowers a = closure {a} ≤ closure X`, the join is also ≤ closure X.
    apply iSup₂_le
    intro a ha
    calc
      zpowers a = closure ({a} : Set G) := zpowers_eq_closure a
      _ ≤ closure X := closure_mono (singleton_subset_iff.mpr ha)

/-- For a single element `a`, the subgroup generated by `{a}` equals the cyclic subgroup
`zpowers a`, i.e., the set `{aⁿ | n ∈ ℤ}`. (This is already provided by Mathlib as
`zpowers_eq_closure`; we restate it as a corollary for completeness.) -/
theorem singleton_closure_eq_zpowers {G : Type*} [Group G] (a : G) :
    closure ({a} : Set G) = zpowers a :=
  (zpowers_eq_closure a).symm

/-- Membership in `closure X` (for nonempty `X`) is equivalent to being in the join
of the cyclic subgroups generated by elements of `X`. -/
theorem mem_closure_iff_nonempty {G : Type*} [Group G] {X : Set G} (hX : X.Nonempty) {g : G} :
    g ∈ closure X ↔ g ∈ ⨆ a ∈ X, zpowers a := by
  rw [closure_eq_iSup_zpowers_of_nonempty hX]

/-- Every element of the subgroup generated by a nonempty set `X` can be written
as a product of integer powers of elements from `X`. This follows from the
characterization `closure X = ⨆ a ∈ X, zpowers a`.

We use an inductive predicate to avoid heavy `List` computations in the motive
of `Subgroup.closure_induction`. -/

inductive IsZpowProduct {G : Type*} [Group G] (X : Set G) : G → Prop
  | base (a : G) (ha : a ∈ X) (n : ℤ) : IsZpowProduct X (a ^ n)
  | one : IsZpowProduct X 1
  | mul {g h : G} : IsZpowProduct X g → IsZpowProduct X h → IsZpowProduct X (g * h)

theorem isZpowProduct_inv {G : Type*} [Group G] {X : Set G} {g : G}
    (h : IsZpowProduct X g) : IsZpowProduct X g⁻¹ := by
  induction h with
  | base a ha n =>
      have : (a ^ n)⁻¹ = a ^ (-n) := by simp
      rw [this]
      exact IsZpowProduct.base a ha (-n)
  | one => simpa using IsZpowProduct.one
  | mul g h hg_ih hh_ih =>
      rw [mul_inv_rev]
      exact IsZpowProduct.mul hh_ih hg_ih

theorem exists_zpow_product_of_mem_closure {G : Type*} [Group G] {X : Set G} (hX : X.Nonempty)
    {g : G} (hg : g ∈ closure X) :
    IsZpowProduct X g := by
  refine Subgroup.closure_induction hg
    (mem := ?_)
    (one := ?_)
    (mul := ?_)
    (inv := ?_)
  · -- Base case: elements of X
    intro x hx
    have : x = x ^ (1 : ℤ) := by simp
    rw [this]
    exact IsZpowProduct.base x hx 1
  · -- Identity case
    exact IsZpowProduct.one
  · -- Closure under multiplication
    intro x y hx hy ihx ihy
    exact IsZpowProduct.mul ihx ihy
  · -- Closure under inverses
    intro x hx ihx
    exact isZpowProduct_inv ihx

/-- For a single element `a ∈ G`, `g ∈ ⟨a⟩` iff `g = aⁿ` for some `n ∈ ℤ`. -/
theorem mem_closure_singleton_zpowers {G : Type*} [Group G] (a g : G) :
    g ∈ closure ({a} : Set G) ↔ ∃ n : ℤ, a ^ n = g :=
  mem_closure_singleton
