import Mathlib

/-!
# Discrete Valuation Ring (DVR)

A **discrete valuation ring** (DVR) is a one-dimensional regular local ring;
equivalently, the valuation ring of a discrete valuation.

In Mathlib4, a DVR is defined as a local principal ideal domain (PID) that is not a field.
The class `IsDiscreteValuationRing R` extends `IsPrincipalIdealRing R` and `IsLocalRing R`,
with the additional condition that the maximal ideal is not the zero ideal (`not_a_field'`).

## Equivalent Characterizations

The following are equivalent (see `Mathlib/RingTheory/DiscreteValuationRing/TFAE.lean`):
1. `R` is a DVR (local PID, not a field).
2. `R` is a PID with a unique non-zero prime ideal.
3. `R` is a one-dimensional regular local ring.
4. `R` is the valuation ring of a discrete valuation on its fraction field.

## Key Properties

- A DVR has exactly one non-zero prime ideal (its maximal ideal).
- A DVR's maximal ideal is generated by a single irreducible element (a uniformizer).
- Every non-zero ideal in a DVR is a power of the maximal ideal.
- The `ℤ`-adic integers `ℤₚ` (p prime) are the prototypical DVR.

## Usage in Mathlib4

```lean
import Mathlib.RingTheory.DiscreteValuationRing.Basic

variable (R : Type) [CommRing R] [IsDomain R]

-- Assert that R is a DVR
variable [IsDiscreteValuationRing R]
```
-/

/--
`DiscreteValuationRing R` is a type synonym for a ring that satisfies
`IsDiscreteValuationRing R`. This wraps the Mathlib4 predicate into a typeclass
that can be used as a hypothesis.

A discrete valuation ring is a local principal ideal domain that is not a field.
-/
abbrev DiscreteValuationRing (R : Type u) [CommRing R] [IsDomain R] :=
  IsDiscreteValuationRing R

-- Example: `ℤₚ` (the p-adic integers) form a DVR for any prime `p`.
example (p : ℕ) [Fact p.Prime] : IsDiscreteValuationRing (ℤ_[p]) := by
  infer_instance

-- Example: Any field of fractions of a DVR admits a rank-one discrete valuation.
example (A K : Type) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Field K] [Algebra A K] [IsFractionRing A K] : True := by
  have h := IsDiscreteValuationRing.isRankOneDiscrete A K
  trivial
