import Mathlib

open Set

/-!
# Existence and Extension of Transcendence Bases

Let `K` be a field extension of `F`.
1. There exists a transcendence basis for `K/F`.
2. If `T ⊆ K` such that `K/F(T)` is algebraic, then `T` contains a transcendence basis for `K/F`.
3. If `S ⊆ K` is algebraically independent over `F`, then `S` is contained in a transcendence
   basis of `K/F`.
4. If `S ⊆ T ⊆ K`, with `S` algebraically independent over `F` and `K/F(T)` algebraic, then
   there is a transcendence basis `X` for `K/F` with `S ⊆ X ⊆ T`.

## Mathlib4 references

- `IsTranscendenceBasis R x` — the indexed family `x : ι → A` is a transcendence basis over `R`
- `AlgebraicIndependent R x` — the indexed family `x : ι → A` is algebraically independent over `R`
- `Algebra.IsAlgebraic R A` — `A` is an algebraic `R`-algebra
- `IntermediateField.adjoin F T` — the subfield of `K` generated by `F` and the set `T`
-/

theorem existence_and_extension_of_transcendence_bases
    (F K : Type*) [Field F] [Field K] [Algebra F K] :
    -- (1) Existence of a transcendence basis
    (∃ (ι : Type*) (x : ι → K), IsTranscendenceBasis F x) ∧
    -- (2) Any set T for which K/F(T) is algebraic contains a transcendence basis
    (∀ (T : Set K), Algebra.IsAlgebraic (IntermediateField.adjoin F T) K →
      ∃ (ι : Type*) (x : ι → K), Set.range x ⊆ T ∧ IsTranscendenceBasis F x) ∧
    -- (3) Any algebraically independent set S can be extended to a transcendence basis
    (∀ (S : Set K), AlgebraicIndependent F (Subtype.val : S → K) →
      ∃ (ι : Type*) (x : ι → K), S ⊆ Set.range x ∧ IsTranscendenceBasis F x) ∧
    -- (4) With S ⊆ T, S algebraically independent, K/F(T) algebraic, there is a
    --     transcendence basis X satisfying S ⊆ X ⊆ T
    (∀ (S T : Set K), S ⊆ T → AlgebraicIndependent F (Subtype.val : S → K) →
      Algebra.IsAlgebraic (IntermediateField.adjoin F T) K →
      ∃ (ι : Type*) (x : ι → K), S ⊆ Set.range x ∧ Set.range x ⊆ T ∧ IsTranscendenceBasis F x) :=
  by sorry
