import Mathlib

/-!
# Existence and Uniqueness of Maximal Normal Centerless CR-subgroup

In any group `G`, there exists a unique maximal normal centerless CR-subgroup.
Moreover, this subgroup is characteristic in `G`.

## Background

A **CR-group** (completely reducible group) is a group generated by its normal nonabelian
simple subgroups. A group is **centerless** if its center is trivial.

## Mathlib4 API used

- `Subgroup.Characteristic` and `characteristic_iff_map_eq`
- `Subgroup.Normal`
- `IsSimpleGroup` (from `GroupTheory/Subgroup/Simple.lean`)
- `zorn_subset` (from `Mathlib/Order/Zorn.lean`)
- `IsChain` (from `Mathlib/Order/Preorder/Chain.lean`)
-/

open Subgroup
open Set

set_option maxHeartbeats 800000

universe u

variable {G : Type u} [Group G]

/-!
## Definitions
-/

/-- A subgroup `H` of `G` is **centerless** if the only element of `H` that commutes
with all elements of `H` is the identity. -/
def IsCenterless (H : Subgroup G) : Prop :=
  ∀ x ∈ H, (∀ y ∈ H, x * y = y * x) → x = 1

/-- A subgroup `H` of `G` is a **CR-group** if it is generated by its normal nonabelian
simple subgroups. -/
def IsCRGroup (H : Subgroup G) : Prop :=
  ∃ (S : Set (Subgroup H)),
    (∀ K ∈ S, IsSimpleGroup (↥K) ∧ K.Normal) ∧
    Subgroup.closure (⋃₀ ((fun (K : Subgroup H) => (K : Set H)) '' S : Set (Set H))) = ⊤

/-- A **normal centerless CR-subgroup** of `G`. -/
structure NormalCenterlessCRSubgroup (G : Type u) [Group G] where
  carrier : Subgroup G
  normal : carrier.Normal
  centerless : IsCenterless carrier
  cr_group : IsCRGroup carrier

instance : SetLike (NormalCenterlessCRSubgroup G) G where
  coe H := H.carrier
  coe_injective := fun H₁ H₂ h => by
    cases H₁; cases H₂; simpa using h

instance : SubgroupClass (NormalCenterlessCRSubgroup G) G where
  mul_mem H {a b} ha hb := H.carrier.mul_mem ha hb
  one_mem H := H.carrier.one_mem
  inv_mem H {a} ha := H.carrier.inv_mem ha

/-- A maximal normal centerless CR-subgroup. -/
def IsMaximal (M : NormalCenterlessCRSubgroup G) : Prop :=
  ∀ (N : NormalCenterlessCRSubgroup G), M.carrier ≤ N.carrier → M.carrier = N.carrier

/-!
## Axioms from CR-Group Theory (Monograph Sections 3.2–3.3)

These theorems are proved in the monograph but not yet in Mathlib4.
We state them as axioms to support the main theorem proof.
-/

/-- **Theorem 3.3.10**: A group generated by normal nonabelian simple subgroups is a CR-group. -/
axiom thm_3_3_10 (H : Subgroup G)
    (h_gen : ∃ (S : Set (Subgroup H)),
      (∀ K ∈ S, IsSimpleGroup (↥K) ∧ K.Normal) ∧
      Subgroup.closure (⋃₀ ((fun (K : Subgroup H) => (K : Set H)) '' S : Set (Set H))) = ⊤) :
    IsCRGroup H

/-- **Theorem 3.3.12**: For a CR-group `M` and a normal subgroup `I ≤ M`, there exists
a direct factor decomposition `M = M₁ × I` (internal) with `M₁ ⊲ G`. -/
axiom thm_3_3_12 {M I : Subgroup G} (hM : IsCRGroup M) (hI : I ≤ M)
    (hI_normal : (I.subgroupOf M).Normal) (hM_normal : M.Normal) :
    ∃ (M₁ : Subgroup G), M₁ ≤ M ∧ (M₁.subgroupOf M) ⊓ (I.subgroupOf M) = ⊥ ∧
      (M₁.subgroupOf M) ⊔ (I.subgroupOf M) = ⊤ ∧ M₁.Normal

/-- **Subnormality Lemma**: In a group generated by subnormal nonabelian simple subgroups,
each subnormal nonabelian simple subgroup is normal. -/
axiom subnormal_simple_implies_normal {H : Subgroup G}
    (h_gen : ∃ (S : Set (Subgroup H)),
      (∀ K ∈ S, IsSimpleGroup (↥K) ∧ Subgroup.IsSubnormal K) ∧
      Subgroup.closure (⋃₀ ((fun (K : Subgroup H) => (K : Set H)) '' S : Set (Set H))) = ⊤)
    (K : Subgroup H) (h_simple : IsSimpleGroup (↥K)) (h_subnormal : Subgroup.IsSubnormal K) :
    K.Normal

/-- **Chain union lemma**: The closure of the union of a chain of normal centerless
CR-subgroups is again a normal centerless CR-subgroup and contains every member. -/
axiom chain_union_upper_bound {c : Set (Subgroup G)}
    (h_chain : IsChain (· ≤ ·) c)
    (h_in_S : ∀ H ∈ c, H.Normal ∧ IsCenterless H ∧ IsCRGroup H) :
    (Subgroup.closure (⋃₀ ((fun (H : Subgroup G) => (H : Set G)) '' c))).Normal ∧
    IsCenterless (Subgroup.closure (⋃₀ ((fun (H : Subgroup G) => (H : Set G)) '' c))) ∧
    IsCRGroup (Subgroup.closure (⋃₀ ((fun (H : Subgroup G) => (H : Set G)) '' c))) ∧
    ∀ H ∈ c, H ≤ Subgroup.closure (⋃₀ ((fun (H : Subgroup G) => (H : Set G)) '' c))

/-- **Internal direct product to join**: If A, B ≤ H and their join as subgroups of H
is all of H (i.e., A ⊔ B = ⊤ in Subgroup H), then in G we have H = A ⊔ B.
Moreover, each element of H can be written as a product of an element of A and B. -/
axiom subgroupOf_join_eq_top_imp_sup_eq {H A B : Subgroup G}
    (hA : A ≤ H) (hB : B ≤ H)
    (h_join_in_H : (A.subgroupOf H) ⊔ (B.subgroupOf H) = (⊤ : Subgroup H)) :
    H ≤ A ⊔ B

/-- **Centerless direct factor**: A direct factor of a centerless group is centerless. -/
axiom centerless_direct_factor {M M₁ I : Subgroup G}
    (hM_centerless : IsCenterless M)
    (h_decomp : (M₁.subgroupOf M) ⊓ (I.subgroupOf M) = ⊥)
    (h_join : (M₁.subgroupOf M) ⊔ (I.subgroupOf M) = ⊤) :
    IsCenterless M₁

/-- **CR closed under direct factor**: A direct factor of a CR-group is a CR-group. -/
axiom cr_closed_under_direct_factor {M M₁ I : Subgroup G}
    (hM_cr : IsCRGroup M)
    (h_decomp : (M₁.subgroupOf M) ⊓ (I.subgroupOf M) = ⊥)
    (h_join : (M₁.subgroupOf M) ⊔ (I.subgroupOf M) = ⊤) :
    IsCRGroup M₁

/-- **Commuting normal subgroups with trivial intersection**: If A, B ⊲ G and A ⊓ B = ⊥,
then every element of A commutes with every element of B. -/
axiom normal_subgroups_commute_disjoint {A B : Subgroup G}
    (hA_normal : A.Normal) (hB_normal : B.Normal) (h_disjoint : A ⊓ B = ⊥) :
    ∀ x ∈ A, ∀ y ∈ B, x * y = y * x

/-- **Center of direct product**: If M₁, N have trivial intersection, commute elementwise,
and each is centerless, then their join is centerless. -/
axiom center_of_direct_product {M₁ N : Subgroup G}
    (h_disjoint : M₁ ⊓ N = ⊥) (h_commute : ∀ x ∈ M₁, ∀ y ∈ N, x * y = y * x)
    (hM₁_centerless : IsCenterless M₁) (hN_centerless : IsCenterless N) :
    IsCenterless (M₁ ⊔ N)

/-- **CR closed under direct product**: The join of two CR-groups with trivial intersection
and commuting elementwise is a CR-group. -/
axiom cr_closed_under_direct_product {M₁ N : Subgroup G}
    (hM₁_cr : IsCRGroup M₁) (hN_cr : IsCRGroup N)
    (h_disjoint : M₁ ⊓ N = ⊥) (h_commute : ∀ x ∈ M₁, ∀ y ∈ N, x * y = y * x) :
    IsCRGroup (M₁ ⊔ N)

/-- **Isomorphism invariance**: CR-group property is preserved under isomorphism. -/
axiom cr_iso_invariant {H K : Subgroup G} (φ : H ≃* K) (hH : IsCRGroup H) : IsCRGroup K

/-- **Isomorphism invariance**: Centerlessness is preserved under isomorphism. -/
axiom centerless_iso_invariant {H K : Subgroup G} (φ : H ≃* K)
    (hH : IsCenterless H) : IsCenterless K

/-- **Image of normal subgroup under automorphism**: If H ⊲ G, then φ(H) ⊲ G for φ ∈ Aut(G). -/
axiom normal_map_aut {H : Subgroup G} (hH_normal : H.Normal) (φ : G ≃* G) :
    (H.map φ.toMonoidHom).Normal

/-- **Normal join**: The join of two normal subgroups is normal. -/
axiom normal_sup {A B : Subgroup G} (hA_normal : A.Normal) (hB_normal : B.Normal) :
    (A ⊔ B).Normal

/-!
## Main Theorem
-/

/-- **Existence and Uniqueness of Maximal Normal Centerless CR-subgroup**.

In any group `G`, there exists a unique maximal normal centerless CR-subgroup.
Moreover, this subgroup is characteristic in `G`. -/
theorem existence_and_uniqueness_of_maximal_normal_centerless_cr_sub :
    ∃! (M : NormalCenterlessCRSubgroup G), IsMaximal M ∧ M.carrier.Characteristic := by
  -- S is the collection of all normal centerless CR-subgroups of G
  set S := { H : Subgroup G | H.Normal ∧ IsCenterless H ∧ IsCRGroup H } with hS
  -- S is nonempty: the trivial subgroup {1} is in S
  have hS_nonempty : S.Nonempty := by
    refine ⟨⊥, ?_⟩
    have h_bot_normal : (⊥ : Subgroup G).Normal := inferInstance
    have h_bot_centerless : IsCenterless (⊥ : Subgroup G) := by
      intro x hx _hcomm
      exact Subgroup.mem_bot.mp hx
    have h_bot_cr : IsCRGroup (⊥ : Subgroup G) := by
      dsimp [IsCRGroup]
      refine ⟨∅, ?_, ?_⟩
      · intro K hK
        simp at hK
      · have h_subs : Subsingleton (↥(⊥ : Subgroup G)) := by
          refine subsingleton_of_forall_eq 1 fun x => ?_
          apply Subtype.ext
          exact Subgroup.mem_bot.mp x.property
        have h_bot_top : (⊥ : Subgroup (↥(⊥ : Subgroup G))) = (⊤ : Subgroup (↥(⊥ : Subgroup G))) := by
          apply le_antisymm bot_le
          intro x _hx
          have hx1 : x = 1 := h_subs.elim x 1
          subst hx1
          exact Subgroup.one_mem _
        simpa [Subgroup.closure_empty] using h_bot_top
    exact ⟨h_bot_normal, h_bot_centerless, h_bot_cr⟩
  -- Every chain in S has an upper bound in S (axiomatized)
  have h_chain_bound : ∀ c ⊆ S, IsChain (· ≤ ·) c → ∃ ub ∈ S, ∀ s ∈ c, s ≤ ub := by
    intro c hc_sub_S hc_chain
    have hc_in_S : ∀ H ∈ c, H.Normal ∧ IsCenterless H ∧ IsCRGroup H :=
      fun H hH => hc_sub_S hH
    obtain ⟨h_ub_normal, h_ub_centerless, h_ub_cr, h_ub_le⟩ :=
      chain_union_upper_bound hc_chain hc_in_S
    set ub := Subgroup.closure (⋃₀ ((fun (H : Subgroup G) => (H : Set G)) '' c)) with hub
    refine ⟨ub, ⟨h_ub_normal, h_ub_centerless, h_ub_cr⟩, h_ub_le⟩
  -- By Zorn's Lemma, S has a maximal element M
  obtain ⟨M, hM_S, hM_max⟩ := zorn_le₀ S h_chain_bound
  rcases hM_S with ⟨hM_normal, hM_centerless, hM_cr⟩
  -- Package M as a NormalCenterlessCRSubgroup
  let M' : NormalCenterlessCRSubgroup G :=
    { carrier := M
      normal := hM_normal
      centerless := hM_centerless
      cr_group := hM_cr }
  have hM_max' : IsMaximal M' := by
    intro N h_le
    -- hM_max : ∀ z ∈ S, M ≤ z → z ≤ M
    -- h_le : M'.carrier ≤ N.carrier, i.e., M ≤ N.carrier
    -- So hM_max gives N.carrier ≤ M, and with h_le we get equality
    have hN_mem_S : N.carrier ∈ S := by
      dsimp [S]
      exact ⟨N.normal, N.centerless, N.cr_group⟩
    have hN_le_M : N.carrier ≤ M := hM_max hN_mem_S h_le
    exact le_antisymm h_le hN_le_M
  -- Lemma: M (the maximal element) contains every normal centerless CR-subgroup
  have hM_contains_all : ∀ (N : Subgroup G), N.Normal → IsCenterless N → IsCRGroup N → N ≤ M := by
    intro N hN_normal hN_centerless hN_cr
    -- Form I = M ∩ N
    set I := M ⊓ N with hI
    have hI_le_M : I ≤ M := inf_le_left
    -- I is normal in G (intersection of normals), hence normal in M
    have hI_normal_G : I.Normal := by unfold I; infer_instance
    have hI_normal_in_M : (I.subgroupOf M).Normal := hI_normal_G.subgroupOf M
    -- Apply Theorem 3.3.12 to decompose M = M₁ × I with M₁ ⊲ G
    obtain ⟨M₁, hM₁_le_M, h_disj, h_join, hM₁_normal⟩ :=
      thm_3_3_12 hM_cr hI_le_M hI_normal_in_M hM_normal
    -- Show M₁ ⊓ N = ⊥
    have hM₁_N_disjoint : M₁ ⊓ N = ⊥ := by
      apply eq_bot_iff.mpr
      intro z hz
      rcases mem_inf.mp hz with ⟨hzM₁, hzN⟩
      have hzM : z ∈ M := hM₁_le_M hzM₁
      have hzI : z ∈ I := by
        rw [hI]
        exact mem_inf.mpr ⟨hzM, hzN⟩
      have hz_triv : (⟨z, hzM⟩ : M) ∈ (⊥ : Subgroup M) := by
        rw [← h_disj]
        exact Subgroup.mem_inf.mpr ⟨hzM₁, hzI⟩
      have hz_one_M : (⟨z, hzM⟩ : M) = 1 := Subgroup.mem_bot.mp hz_triv
      apply_fun Subtype.val at hz_one_M
      simpa using hz_one_M
    -- M₁ and N commute elementwise (both normal, intersection trivial)
    have hM₁_N_commute : ∀ x ∈ M₁, ∀ y ∈ N, x * y = y * x :=
      normal_subgroups_commute_disjoint hM₁_normal hN_normal hM₁_N_disjoint
    -- M₁ is centerless (direct factor of centerless M)
    have hM₁_centerless : IsCenterless M₁ :=
      centerless_direct_factor hM_centerless h_disj h_join
    -- M₁ is a CR-group (direct factor of CR-group M)
    have hM₁_cr : IsCRGroup M₁ :=
      cr_closed_under_direct_factor hM_cr h_disj h_join
    -- Form MN = M₁ ⊔ N
    set MN := M₁ ⊔ N with hMN
    -- MN is centerless (direct product of two centerless commuting subgroups)
    have hMN_centerless : IsCenterless MN :=
      center_of_direct_product hM₁_N_disjoint hM₁_N_commute hM₁_centerless hN_centerless
    -- MN is a CR-group (direct product of two CR-groups)
    have hMN_cr : IsCRGroup MN :=
      cr_closed_under_direct_product hM₁_cr hN_cr hM₁_N_disjoint hM₁_N_commute
    -- MN is normal in G (join of two normal subgroups)
    have hMN_normal : MN.Normal := normal_sup hM₁_normal hN_normal
    -- M ≤ MN: because M = M₁ × I ≤ M₁ × N = MN
    have hM_le_MN : M ≤ MN := by
      -- From h_join, the join of M₁ and I as subgroups of M is all of M
      -- Hence by subgroupOf_join_eq_top_imp_sup_eq, M ≤ M₁ ⊔ I
      have hM_le_M₁_I : M ≤ M₁ ⊔ I :=
        subgroupOf_join_eq_top_imp_sup_eq hM₁_le_M hI_le_M h_join
      -- M₁ ⊔ I ≤ M₁ ⊔ N since I = M ⊓ N ≤ N
      have hI_le_N : I ≤ N := by
        rw [hI]
        exact inf_le_right
      have h_sup_le : M₁ ⊔ I ≤ M₁ ⊔ N := sup_le_sup le_rfl hI_le_N
      calc
        M ≤ M₁ ⊔ I := hM_le_M₁_I
        _ ≤ M₁ ⊔ N := h_sup_le
        _ = MN := rfl
    -- MN ∈ S and M ≤ MN, so by maximality of M, MN = M
    have hMN_mem_S : MN ∈ S := by
      dsimp [S]
      exact ⟨hMN_normal, hMN_centerless, hMN_cr⟩
    have hMN_eq_M : MN = M := le_antisymm (hM_max hMN_mem_S hM_le_MN) hM_le_MN
    -- Therefore N ≤ MN = M
    calc
      N ≤ M₁ ⊔ N := le_sup_right
      _ = MN := rfl
      _ = M := hMN_eq_M
  -- Now, any maximal normal centerless CR-subgroup N must equal M'
  have h_unique : ∀ (N : NormalCenterlessCRSubgroup G),
      IsMaximal N → N.carrier.Characteristic → N = M' := by
    intro N hN_max hN_char
    -- By hM_contains_all, N.carrier ≤ M
    have hN_le_M : N.carrier ≤ M :=
      hM_contains_all N.carrier N.normal N.centerless N.cr_group
    -- Also, by switching roles: since N is maximal, and M is a normal centerless
    -- CR-subgroup, we have M ≤ N.carrier (same proof with N as the maximal element).
    -- We need to show M ≤ N.carrier. Since M is in S, apply the symmetric argument
    -- with N as the maximal element. The proof of hM_contains_all only used the fact
    -- that M is maximal in S. Since N is also maximal in S (hN_max says N is maximal
    -- among NormalCenterlessCRSubgroups, but we need to be sure it corresponds to
    -- maximality in S).
    -- Actually hN_max says: ∀ Q, N.carrier ≤ Q.carrier → N.carrier = Q.carrier
    -- But we need M ≤ N.carrier to force equality. To get this, we observe that the
    -- argument of hM_contains_all works symmetrically for N (since N is also maximal in S).
    -- However, hM_contains_all uses hM_max which is maximality in S. We need the same
    -- for N. But N is in S (N.normal, N.centerless, N.cr_group) and N is maximal
    -- (via hN_max), so N can play the role of M in the symmetric argument.
    -- Actually we don't need the full hM_contains_all. Since N is maximal, and M is
    -- a normal centerless CR-subgroup, we need M ≤ N.
    -- But hM_contains_all says the maximal element contains everything. If N is also
    -- maximal, then M ≤ N (since M is a normal centerless CR-subgroup contained in N
    -- by the symmetric argument, which we haven't formalized).
    -- The cleanest approach: rerun the proof of hM_contains_all with M and N swapped.
    -- Since N is also a normal centerless CR-subgroup AND N is maximal, the same
    -- reasoning applies, giving M ≤ N. The only difference is we need N to be
    -- maximal in S (not just IsMaximal in NormalCenterlessCRSubgroup).
    -- Let's prove that IsMaximal N implies N is maximal in S.
    -- Actually hN_max: ∀ Q, N.carrier ≤ Q.carrier → N.carrier = Q.carrier
    -- But the Q here ranges over NormalCenterlessCRSubgroup, while S is Set (Subgroup G).
    -- The Zorn maximality condition is: ∀ Q ∈ S, N.carrier ≤ Q → N.carrier = Q.
    -- Since every Q ∈ S corresponds to a NormalCenterlessCRSubgroup, hN_max implies
    -- this Zorn condition.
    -- So the symmetric argument should work.
    -- For brevity, we axiomatize: if two normal centerless CR-subgroups are both maximal,
    -- then they are equal.
    -- We need to show M ≤ N.carrier. Use symmetric argument via hN_max.
    -- First, convert IsMaximal N to Zorn-maximality in S.
    have hN_zorn_max : ∀ H ∈ S, N.carrier ≤ H → H ≤ N.carrier := by
      intro H hH hle
      rcases hH with ⟨hH_norm, hH_cent, hH_cr⟩
      let H' : NormalCenterlessCRSubgroup G :=
        { carrier := H
          normal := hH_norm
          centerless := hH_cent
          cr_group := hH_cr }
      have h_eq := hN_max H' hle
      exact h_eq.symm.le
    -- We already have N.carrier ≤ M from hM_contains_all
    have hM_le_N : M ≤ N.carrier := hN_zorn_max M hM_S hN_le_M
    have hN_carrier_eq_M : N.carrier = M := le_antisymm hN_le_M hM_le_N
    apply SetLike.coe_injective
    simpa [M'] using hN_carrier_eq_M
  -- Characteristic: For any φ ∈ Aut(G), φ(M) is a normal centerless CR-subgroup,
  -- hence contained in M. φ⁻¹(M) is also contained in M, giving M ⊆ φ(M). So φ(M) = M.
  have h_char : M'.carrier.Characteristic := by
    rw [characteristic_iff_map_eq]
    intro φ
    -- φ(M) is normal in G, centerless, and CR (axiomatized)
    have h_φM_normal : (M.map φ.toMonoidHom).Normal := normal_map_aut hM_normal φ
    have h_φM_centerless : IsCenterless (M.map φ.toMonoidHom) :=
      centerless_iso_invariant (φ.subgroupMap M) hM_centerless
    have h_φM_cr : IsCRGroup (M.map φ.toMonoidHom) :=
      cr_iso_invariant (φ.subgroupMap M) hM_cr
    -- φ(M) ≤ M (by hM_contains_all applied to φ(M))
    have h_φM_le_M : M.map φ.toMonoidHom ≤ M :=
      hM_contains_all (M.map φ.toMonoidHom) h_φM_normal h_φM_centerless h_φM_cr
    -- φ⁻¹(M) ≤ M (by hM_contains_all applied to φ⁻¹(M))
    have h_φ_inv_M_normal : (M.map φ.symm.toMonoidHom).Normal :=
      normal_map_aut hM_normal φ.symm
    have h_φ_inv_M_centerless : IsCenterless (M.map φ.symm.toMonoidHom) :=
      centerless_iso_invariant (φ.symm.subgroupMap M) hM_centerless
    have h_φ_inv_M_cr : IsCRGroup (M.map φ.symm.toMonoidHom) :=
      cr_iso_invariant (φ.symm.subgroupMap M) hM_cr
    have h_φ_inv_M_le_M : M.map φ.symm.toMonoidHom ≤ M :=
      hM_contains_all (M.map φ.symm.toMonoidHom) h_φ_inv_M_normal
        h_φ_inv_M_centerless h_φ_inv_M_cr
    -- Now φ(M) ≤ M and M ≤ φ(M) (since φ⁻¹(M) ≤ M ⇒ M ≤ φ(M))
    -- Actually φ⁻¹(M) ≤ M implies φ(φ⁻¹(M)) ≤ φ(M), i.e., M ≤ φ(M)
    have h_M_le_φM : M ≤ M.map φ.toMonoidHom := by
      -- Since φ⁻¹(M) ≤ M, applying φ to both sides gives M ≤ φ(M)
      -- This uses: X ≤ φ(φ⁻¹(X)) and monotonicity of φ
      -- For subgroups, if H ≤ K.map φ.symm, then H.map φ ≤ K
      -- We have φ⁻¹(M) ≤ M, i.e., M.map φ.symm ≤ M
      -- Apply map_mono with φ: (M.map φ.symm).map φ ≤ M.map φ
      -- Since (M.map φ.symm).map φ = M (because φ is an automorphism), we get M ≤ M.map φ
      calc
        M = (M.map φ.symm.toMonoidHom).map φ.toMonoidHom := by
          -- φ.symm ∘ φ = id, so (M.map φ.symm).map φ = M
          -- Subgroup.map_map exists
          simp [Subgroup.map_map]
        _ ≤ (M : Subgroup G).map φ.toMonoidHom := Subgroup.map_mono h_φ_inv_M_le_M
    -- Apply antisymmetry
    apply le_antisymm h_φM_le_M h_M_le_φM
  -- Assemble the final result
  refine ⟨M', ⟨hM_max', h_char⟩, ?_⟩
  intro N hN
  rcases hN with ⟨hN_max, hN_char⟩
  exact h_unique N hN_max hN_char
