import Mathlib

/-!
# Initial Form and Initial Form Ideal

Let `K` be a commutative ring and `σ` an index type for variables. For a nonzero polynomial
`f ∈ K[X_σ]`, write `f = Σ_{d ≥ 0} f_d` where `f_d` is the homogeneous component
of degree `d`. The **initial form** `f_in` of `f` is the lowest-degree nonzero
homogeneous component:
  `f_in := f_m` where `m = min { d | f_d ≠ 0 }`.

For an ideal `I ⊆ K[X_σ]`, the **initial form ideal** is the ideal generated by
the initial forms of all nonzero elements of `I`:
  `I_in := (f_in | f ∈ I \ {0})`.

This definition is the basis for the theory of tangent cones and the study of
singularities via associated graded rings. The initial form ideal describes the
"lowest-order" behaviour of the ideal `I` at the origin.

## Main definitions

* `MvPolynomial.initialForm f` : the homogeneous component of `f` of lowest
  total degree (returns 0 if `f = 0`).
* `initialFormIdeal I` : the ideal generated by the initial forms of all nonzero
  elements of `I`.

## References

* `Mathlib/RingTheory/MvPolynomial/Homogeneous.lean` for `homogeneousComponent` and
  `totalDegree`.
-/

open scoped BigOperators

variable {σ : Type*} {K : Type*} [CommRing K]

namespace MvPolynomial

/--
The **initial form** of a multivariate polynomial `f` over a commutative ring `K`:
the homogeneous component of lowest total degree. When `f = 0`, returns `0`.

Formally, `initialForm f` is `homogeneousComponent m f` where `m` is the minimal
natural number such that `homogeneousComponent m f ≠ 0`. This is well-defined
because `sum_homogeneousComponent` says `f = Σ_{i ≤ totalDegree f} homogeneousComponent i f`,
so for `f ≠ 0` there exists at least one `n` with a nonzero homogeneous component.
-/
noncomputable def initialForm (f : MvPolynomial σ K) : MvPolynomial σ K :=
  if h : ∃ n : ℕ, homogeneousComponent n f ≠ 0 then
    homogeneousComponent (Nat.find h) f
  else
    0

/--
`initialForm f` is homogeneous of the minimal degree where `f` has a nonzero
homogeneous component (or degree 0 trivially if `f = 0`).
-/
lemma initialForm_isHomogeneous (f : MvPolynomial σ K) :
    (initialForm f).IsHomogeneous
      (if h : ∃ n : ℕ, homogeneousComponent n f ≠ 0 then Nat.find h else 0) := by
  unfold initialForm
  split
  · exact homogeneousComponent_isHomogeneous
  · exact isHomogeneous_zero _

end MvPolynomial

open MvPolynomial

/--
The **initial form ideal** of an ideal `I` in a multivariate polynomial ring
over a commutative ring `K`. This is the ideal generated by the initial forms
(lowest-degree nonzero homogeneous components) of all nonzero elements of `I`.

Formally: `initialFormIdeal I := Ideal.span { initialForm f | f ∈ I, f ≠ 0 }`.

This ideal describes the tangent cone of the vanishing set `V(I)` at the origin
and is fundamental in the study of singularities and local properties of
algebraic varieties.
-/
noncomputable def initialFormIdeal (I : Ideal (MvPolynomial σ K)) : Ideal (MvPolynomial σ K) :=
  Ideal.span { initialForm f | (f : MvPolynomial σ K) (hf : f ∈ I) (hf0 : f ≠ 0)}

/--
The initial form ideal of the zero ideal is the zero ideal (since the only element
of the zero ideal is 0, which has no corresponding nonzero initial form).
-/
example : initialFormIdeal (⊥ : Ideal (MvPolynomial σ K)) = ⊥ := by
  simp [initialFormIdeal]

/--
For the unit ideal, the initial form ideal contains the initial form of 1,
which is the constant polynomial 1 (its homogeneous component of degree 0).
-/
example : initialFormIdeal (⊤ : Ideal (MvPolynomial σ K)) = ⊤ := by
  rw [initialFormIdeal]
  apply Ideal.eq_top_of_isUnit_mem
  refine Ideal.subset_span ⟨1, Submodule.mem_top, one_ne_zero, ?_⟩
  simp [initialForm]

/--
If `f ∈ I` and `f ≠ 0`, then `initialForm f` belongs to `initialFormIdeal I`.
This is the defining property of the initial form ideal.
-/
example (I : Ideal (MvPolynomial σ K)) (f : MvPolynomial σ K) (hf : f ∈ I) (hf0 : f ≠ 0) :
    initialForm f ∈ initialFormIdeal I := by
  rw [initialFormIdeal]
  apply Ideal.subset_span
  exact ⟨f, hf, hf0, rfl⟩
