import Mathlib

/-!
# Initial Submodule (Initial Ideal)

Let `σ` be an index type for indeterminates, `R` a commutative ring, and `m : MonomialOrder σ`
a monomial order. For an ideal `I ⊆ MvPolynomial σ R`, the **initial submodule** `in(I)`
(also called the **initial ideal** or **leading term ideal**) is the monomial ideal generated
by the leading terms of all elements of `I` with respect to `m`.

Formally:
  `in(I) := ⟨{m.leadingTerm f | f ∈ I}⟩`

where `m.leadingTerm f` is the leading term of `f` with respect to the monomial order `m`.

## Main Definition

* `initialSubmodule m I` : the ideal generated by the leading terms of elements of `I`.

## Significance in Gröbner Basis Theory

A finite subset `G ⊆ I` is a Gröbner basis for `I` if and only if the initial submodule of `I`
is generated by the leading terms of the elements of `G`:
  `initialSubmodule m I = ⟨{m.leadingTerm g | g ∈ G}⟩`.

This property is the foundation of the Gröbner basis algorithm and Buchberger's criterion.

## Generalization to Modules

In the more general setting of submodules of a free module `F = (MvPolynomial σ R)^k`,
the initial submodule is defined analogously using a module monomial order (a term order
on `(σ →₀ ℕ) × {1,…,k}`). The definition below handles the special case `k = 1`,
i.e., ideals in the polynomial ring.

## References

* [Becker-Weispfenning1993] Becker, T., Weispfenning, V. *Gröbner Bases*.
* [Cox-Little-O'Shea1997] Cox, D., Little, J., O'Shea, D. *Ideals, Varieties, and Algorithms*.
-/

open scoped MonomialOrder

variable {σ : Type*} {R : Type*} [CommRing R] {m : MonomialOrder σ}

/--
Given a monomial order `m` and an ideal `I` in the multivariate polynomial ring
`MvPolynomial σ R`, `initialSubmodule m I` is the ideal generated by the leading terms
of all elements of `I` with respect to `m`.

Formally: `initialSubmodule m I := Ideal.span {m.leadingTerm f | f ∈ I}`.

This is a fundamental concept in Gröbner basis theory. A finite subset `G ⊆ I`
is a Gröbner basis for `I` if and only if `initialSubmodule m I` is generated by
`{m.leadingTerm g | g ∈ G}`.
-/
noncomputable def initialSubmodule (I : Ideal (MvPolynomial σ R)) : Ideal (MvPolynomial σ R) :=
  Ideal.span {m.leadingTerm f | (f : MvPolynomial σ R) (_ : f ∈ I)}

/--
For the zero ideal, the initial submodule is the zero ideal.
-/
example : initialSubmodule (m := m) (I := ⊥ : Ideal (MvPolynomial σ R)) = ⊥ := by
  simp [initialSubmodule]

/--
If `g ∈ I`, then `m.leadingTerm g` belongs to `initialSubmodule m I`.
This is the fundamental membership property of the initial submodule.
-/
example (I : Ideal (MvPolynomial σ R)) (g : MvPolynomial σ R) (hg : g ∈ I) :
    m.leadingTerm g ∈ initialSubmodule (m := m) I := by
  rw [initialSubmodule]
  apply Ideal.subset_span
  exact ⟨g, hg, rfl⟩
