import Mathlib

open scoped Classical

/-!
# Locally Principal Ideal

A fractional ideal `I` of an integral domain `R` is called **locally principal** if for every
prime ideal `P ∈ Spec(R)`, the localization `I_P` is a principal ideal of the local ring `R_P`,
i.e., `I_P = (a)R_P` for some `a ∈ I`.

Equivalently, for each prime ideal `P`, the `R_P`-submodule of the fraction field `K`
generated by `I` is a principal submodule (spanned by a single element).

This property is fundamental in Dedekind domain theory: a Dedekind domain is precisely an
integral domain in which every nonzero fractional ideal is locally principal (and invertible).

## Mathlib4 relation

Mathlib4 provides:
- `FractionalIdeal R⁰ K` for fractional ideals of `R` in its fraction field `K`
- `IsLocalization.AtPrime RP P` for the localization of `R` at the complement of prime ideal `P`
- `Submodule.IsPrincipal` for the property of being generated by a single element
- `IsScalarTower R (Localization.AtPrime P) K` which allows viewing `K` as an `R_P`-module

There is no existing `IsLocallyPrincipal` definition in Mathlib4; this is new.

## Implementation note

Since `IsScalarTower R (Localization.AtPrime P) K` holds (the fraction field is a
localization of `R_P`), we can view the localized ideal `I_P` as the `R_P`-submodule
of `K` spanned by `I`. This avoids needing to construct a map from `K` into a separate
localization type — we work entirely within the fraction field `K`.
-/

section locally_principal_ideal

variable {R : Type*} [CommRing R] [IsDomain R] (K : Type*) [Field K]
  [Algebra R K] [IsFractionRing R K]

/-- A fractional ideal `I` of an integral domain `R` is **locally principal** if for every
prime ideal `P` of `R`, the localization `I_P` is a principal ideal of the local ring `R_P`.

Formally, we require that for each prime ideal `P`, the `R_P`-submodule of `K` spanned by
`I` (where `R_P = Localization.AtPrime P`) is principal, i.e., generated by a single
element of `K`.

Parameters:
- `R` : an integral domain
- `K` : the fraction field of `R`
- `I` : a fractional ideal of `R` in `K`

See also:
- `Mathlib/RingTheory/FractionalIdeal/Basic.lean` for the definition of `FractionalIdeal`
- `Mathlib/RingTheory/DedekindDomain/Basic.lean` for Dedekind domains where all fractional
  ideals are locally principal
- `Mathlib/RingTheory/Localization/AtPrime/Basic.lean` for localization at a prime ideal
-/
def IsLocallyPrincipal (I : FractionalIdeal R⁰ K) : Prop :=
  ∀ (P : Ideal R) [IsPrime P],
    Submodule.IsPrincipal
      (Submodule.span (Localization.AtPrime P) ((I : Submodule R K) : Set K))

end locally_principal_ideal

/-!
## Examples

Below we demonstrate the definition in use.
-/

section examples

variable {R : Type*} [CommRing R] [IsDomain R] (K : Type*) [Field K]
  [Algebra R K] [IsFractionRing R K]

/-- **Example 1**: Extracting the property for a specific prime ideal.
Given a locally principal fractional ideal `I` and a prime ideal `P`, we obtain that
the localized ideal I_P is principal. -/
example (I : FractionalIdeal R⁰ K) (P : Ideal R) [IsPrime P] (h : IsLocallyPrincipal K I) :
    Submodule.IsPrincipal
      (Submodule.span (Localization.AtPrime P) ((I : Submodule R K) : Set K)) :=
  h P

/-- **Example 2**: In a principal ideal domain, every fractional ideal is principal as an
R-submodule, and thus locally principal. (In fact, `IsLocallyPrincipal` follows immediately
from `Submodule.IsPrincipal` of the original fractional ideal, because if `I = R·a`,
then `I_P = R_P·a`.) -/
example (R : Type*) [CommRing R] [IsDomain R] [IsPrincipalIdealRing R]
    (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K]
    (I : FractionalIdeal R⁰ K) [hprinc : Submodule.IsPrincipal (I : Submodule R K)] :
    IsLocallyPrincipal K I := by
  intro P
  rcases hprinc with ⟨a, ha⟩
  -- If I = R·a, then span_RP(I) = RP·a, which is principal
  refine ⟨a, ?_⟩
  calc
    Submodule.span (Localization.AtPrime P) ((I : Submodule R K) : Set K)
        = Submodule.span (Localization.AtPrime P) ((Submodule.span R {a}) : Set K) := by
      rw [ha]
    _ = Submodule.span (Localization.AtPrime P) {a} := by
      -- The R_P-span of the R-span of {a} is the R_P-span of {a}
      -- because R_P is an R-algebra sitting above R in the scalar tower
      rw [Submodule.span_le, Submodule.span_eq]
      exact ?
    _ = Submodule.span (Localization.AtPrime P) {a} := rfl

/-- **Example 3**: Trivially, the zero fractional ideal is locally principal. -/
example : IsLocallyPrincipal K (0 : FractionalIdeal R⁰ K) := by
  intro P
  refine ⟨0, ?_⟩
  simp

/-- **Example 4**: The unit fractional ideal (1) = R is locally principal. -/
example : IsLocallyPrincipal K (1 : FractionalIdeal R⁰ K) := by
  intro P
  refine ⟨1, ?_⟩
  rw [← FractionalIdeal.coe_one, ← Submodule.span_singleton_one]
  sorry

end examples
