import Mathlib

open scoped Classical

/-!
# Maschke's Theorem

Let `G` be a finite group and `k` a field. The group algebra `k[G]` is semisimple
if and only if the characteristic of `k` does not divide the order of `G`.

The forward direction (`¬ ringChar k ∣ Fintype.card G → IsSemisimpleRing (MonoidAlgebra k G)`)
follows from the existing proof in `Mathlib/RepresentationTheory/Maschke.lean`.

This file provides the complete if-and-only-if statement with the converse:
if `k[G]` is semisimple, then `ringChar k ∤ |G|`.

## Proof of the converse

Assume `ringChar k ∣ |G|`. Define the norm element `z = ∑_{g∈G} e_g`.
Then `z² = |G| · z = 0` (since `|G| = 0` in `k`) and `z ≠ 0`.
The element `z` is central (conjugation by any `g` just permutes the basis),
so the two-sided ideal `I = (z)` satisfies `I² = 0`.
In a semisimple ring, every ideal is generated by an idempotent:
`I = (e)` with `e² = e`. But then `(e) = (e)² = I² = 0`, so `z = 0`, contradiction.
-/

section maschke_theorem

variable (k : Type*) [Field k] (G : Type*) [Group G] [Fintype G]

open MonoidAlgebra

/-- The norm (averaging) element `z = ∑_{g∈G} e_g` in the group algebra.
This is the sum of all standard basis elements. It is central and satisfies `z² = |G|·z`. -/
noncomputable def normElement : MonoidAlgebra k G :=
  ∑ g : G, single g (1 : k)

/-- The norm element is nonzero (it has coefficient 1 at each group element). -/
theorem normElement_ne_zero : normElement k G ≠ 0 := by
  intro h
  have hval : (normElement k G) (1 : G) = (1 : k) := by
    simp [normElement]
  have hzero : (0 : MonoidAlgebra k G) (1 : G) = (0 : k) := by simp
  rw [h] at hval
  rw [hzero] at hval
  exact one_ne_zero hval

/-- The norm element is central in the group algebra.
For any `g ∈ G`, `e_g · z = z · e_g` because both are the sum of all basis elements
(the map `h ↦ g*h` is a bijection of `G`, as is `h ↦ h*g`). -/
theorem normElement_central (x : MonoidAlgebra k G) :
    x * normElement k G = normElement k G * x := by
  -- First prove it for basis elements single g 1
  have h_basis (g : G) : single g (1 : k) * normElement k G = normElement k G * single g (1 : k) := by
    calc
      single g (1 : k) * normElement k G
          = single g (1 : k) * (∑ h : G, single h (1 : k)) := rfl
      _ = ∑ h : G, (single g (1 : k) * single h (1 : k)) := by
        simp [Finset.mul_sum]
      _ = ∑ h : G, single (g * h) (1 : k) := by simp
      _ = ∑ h : G, single (h * g) (1 : k) := by
        -- The map h ↦ g*h gives a bijection of G, so the sums are equal
        classical
        simpa using (Fintype.sum_bijective (fun (h : G) => g * h)
          (Group.mulLeft_bijective g) _ _ (fun h => by simp)).symm
      _ = (∑ h : G, single h (1 : k)) * single g (1 : k) := by
        simp [Finset.sum_mul]
      _ = normElement k G * single g (1 : k) := rfl
  -- Extend from basis elements to arbitrary elements by linearity
  refine Finsupp.induction x ?_ ?_
  · simp
  · intro g r x' hx hx'
    simp [add_mul, mul_add, h_basis g, hx, hx']

/-- The square of the norm element: `z² = |G| · z`. This is the key computation. -/
theorem normElement_sq_eq :
    normElement k G * normElement k G = (Fintype.card G : k) • normElement k G := by
  have h_sq_eq : normElement k G * normElement k G = (Fintype.card G : k) • normElement k G := by
    calc
      normElement k G * normElement k G
          = (∑ g : G, single g (1 : k)) * (∑ h : G, single h (1 : k)) := rfl
      _ = ∑ g : G, ∑ h : G, (single g (1 : k) * single h (1 : k)) := by
        simp [Finset.sum_mul, Finset.mul_sum]
      _ = ∑ g : G, ∑ h : G, single (g * h) (1 : k) := by simp
      _ = ∑ s : G, (Fintype.card G : k) • single s (1 : k) := by
        classical
        -- Reindex: for each s, count pairs (g, h) with g*h = s. There are |G| such pairs.
        calc
          ∑ g : G, ∑ h : G, single (g * h) (1 : k)
              = ∑ s : G, ∑ g : G, single s (1 : k) := by
            -- Reindex (g, h) ↦ s = g*h, h. The map is
            -- ((s, h) ↦ (s*h⁻¹, h)) with inverse ((g, h) ↦ (g*h, h)).
            -- Simpler: for fixed s, the number of g with single (g*h) = s is...
            -- Actually, use the bijection: G×G → G×G, (g, h) ↦ (g*h, h)
            -- The inverse is (s, h) ↦ (s*h⁻¹, h)
            -- So sum_{(g,h)} f(g*h) = sum_{(s,h)} f(s) = |G| * sum_s f(s)
            -- But we need sum_{(g,h)} single(g*h, 1) = sum_s (∑_h single(s, 1))
            -- Since G is finite, for each s, there are exactly |G| pairs (g,h) with g*h=s.
            have h_eq : (∑ p : G × G, single (p.1 * p.2) (1 : k)) = (∑ p : G × G, single p.1 (1 : k)) := by
              refine Fintype.sum_bijective (fun p => (p.1 * p.2, p.2)) ?_ _ _ (fun p => rfl)
              -- The map (g, h) ↦ (g*h, h) is bijective: inverse is (s, h) ↦ (s*h⁻¹, h)
              refine {
                toFun := fun p => (p.1 * p.2, p.2)
                invFun := fun p => (p.1 * p.2⁻¹, p.2)
                left_inv := ?_
                right_inv := ?_
              }
              · intro p; ext <;> simp
              · intro p; ext <;> simp
            simpa [Finset.sum_product] using h_eq
          _ = ∑ s : G, ((Fintype.card G : ℕ) : k) • single s (1 : k) := by
            simp [Finset.sum_const_nsmul, smul_smul]
          _ = ∑ s : G, (Fintype.card G : k) • single s (1 : k) := by simp
      _ = (Fintype.card G : k) • (∑ s : G, single s (1 : k)) := by
        simp [Finset.smul_sum]
      _ = (Fintype.card G : k) • normElement k G := rfl
  exact h_sq_eq

/-- If the characteristic divides the group order, then `z² = 0`. -/
theorem normElement_sq_eq_zero_of_char_dvd (h : ringChar k ∣ Fintype.card G) :
    normElement k G * normElement k G = 0 := by
  rw [normElement_sq_eq k G]
  have h_card_zero : (Fintype.card G : k) = 0 := by
    rw [← CharP.cast_eq_zero_iff k (Fintype.card G)]
    exact h
  simp [h_card_zero]

/-- The converse direction of Maschke's theorem.
If the group algebra is semisimple, then the characteristic does not divide the group order.

Proof: If char(k) ∣ |G|, then z² = 0 and z ≠ 0 with z central.
The ideal I = (z) satisfies I² = 0.
In a semisimple ring, I = (e) for some idempotent e.
Then (e) = (e)² = I² = 0, so z = 0, contradiction. -/
theorem not_char_dvd_of_semisimple [IsSemisimpleRing (MonoidAlgebra k G)] :
    ¬ ringChar k ∣ Fintype.card G := by
  intro h_char_dvd
  have hz_sq_zero : normElement k G * normElement k G = 0 :=
    normElement_sq_eq_zero_of_char_dvd k G h_char_dvd
  have hz_ne_zero : normElement k G ≠ 0 := normElement_ne_zero k G
  have hz_central : ∀ x : MonoidAlgebra k G, x * normElement k G = normElement k G * x :=
    normElement_central k G
  -- Let I = (z), the principal ideal generated by z
  let I : Ideal (MonoidAlgebra k G) := Ideal.span {normElement k G}
  -- Since z is central, I*z = 0 and z*I = 0, so I² = 0
  have hI_sq_eq_bot : I * I = ⊥ := by
    apply Ideal.mul_eq_bot.mpr
    constructor
    · -- Left annihilator condition: for all a ∈ I, a * I = 0
      intro a ha
      rw [Ideal.mem_span_singleton] at ha
      rcases ha with ⟨r, hr⟩
      subst hr
      ext b
      simp only [ZeroMemClass.coe_zero, Finsupp.coe_zero, Pi.zero_apply]
      intro hb
      rw [Ideal.mem_span_singleton] at hb
      rcases hb with ⟨s, hs⟩
      subst hs
      simp only [Finsupp.coe_smul, Pi.smul_apply, smul_eq_mul]
      calc
        (r * normElement k G) * (s * normElement k G)
            = (r * s) * (normElement k G * normElement k G) := by
          ring
        _ = (r * s) * 0 := by rw [hz_sq_zero]
        _ = 0 := by simp
    · -- Right annihilator condition: for all b ∈ I, I * b = 0
      intro b hb
      rw [Ideal.mem_span_singleton] at hb
      rcases hb with ⟨s, hs⟩
      subst hs
      ext a
      simp only [ZeroMemClass.coe_zero, Finsupp.coe_zero, Pi.zero_apply]
      intro ha
      rw [Ideal.mem_span_singleton] at ha
      rcases ha with ⟨r, hr⟩
      subst hr
      simp only [Finsupp.coe_smul, Pi.smul_apply, smul_eq_mul]
      calc
        (r * normElement k G) * (s * normElement k G)
            = (r * s) * (normElement k G * normElement k G) := by
          ring
        _ = (r * s) * 0 := by rw [hz_sq_zero]
        _ = 0 := by simp
  -- In a semisimple ring, every ideal is generated by an idempotent
  rcases IsSemisimpleRing.ideal_eq_span_idempotent I with ⟨e, he_idem, hI_eq⟩
  -- Now I = (e) and e² = e
  -- Since I² = ⊥, (e) = (e)² = I² = ⊥
  have hI_sq_eq_I : I * I = I := by
    rw [hI_eq]
    -- (e) * (e) = (e²) = (e) since e² = e
    have h_span_sq : Ideal.span {e} * Ideal.span {e} = Ideal.span {e} := by
      apply le_antisymm
      · -- (e)*(e) ⊆ (e): product of two elements from (e) is in (e)
        rw [Ideal.mul_le]
        intro a ha b hb
        rw [Ideal.mem_span_singleton] at ha hb
        rcases ha with ⟨r, hr⟩
        rcases hb with ⟨s, hs⟩
        rw [hr, hs]
        rw [Ideal.mem_span_singleton]
        refine ⟨r * e * s, ?_⟩
        calc
          (r * e) * (s * e) = r * e * s * e := by ring
          _ = (r * e * s) * e := by ring
      · -- (e) ⊆ (e)*(e): since e = e² ∈ (e)*(e)
        rw [Ideal.span_le, Set.singleton_subset_iff]
        -- e = e*e ∈ (e)*(e)
        have he_sq : e * e = e := by
          have := he_idem
          -- IsIdempotentElem means e*e = e
          simpa [IsIdempotentElem] using this
        rw [← he_sq]
        -- Now e*e ∈ (e)*(e)
        have h_mem : e * e ∈ Ideal.span {e} * Ideal.span {e} := by
          apply Submodule.mul_mem_mul
          · exact Ideal.subset_span (by simp)
          · exact Ideal.subset_span (by simp)
        exact h_mem
    exact h_span_sq
  -- Now I² = ⊥ and I² = I, so I = ⊥
  rw [hI_sq_eq_bot] at hI_sq_eq_I
  -- So I = ⊥, and since z ∈ I, z = 0, contradiction
  have hz_mem_I : normElement k G ∈ I := Ideal.subset_span (by simp)
  have hz_eq_zero : normElement k G = 0 := by
    have h_bot_eq_I : (⊥ : Ideal (MonoidAlgebra k G)) = I := by symm; exact hI_sq_eq_I
    rw [← Submodule.mem_bot (R := MonoidAlgebra k G), h_bot_eq_I]
    exact hz_mem_I
  exact hz_ne_zero hz_eq_zero

/-- **Maschke's theorem**: The group algebra `k[G]` of a finite group `G` over a field `k`
is semisimple if and only if the characteristic of `k` does not divide the order of `G`. -/
theorem maschke : IsSemisimpleRing (MonoidAlgebra k G) ↔ ¬ ringChar k ∣ Fintype.card G := by
  constructor
  · -- Reverse direction: semisimple ⇒ char ∤ |G|
    intro h_semisimple
    haveI := h_semisimple
    exact not_char_dvd_of_semisimple k G
  · -- Forward direction: char ∤ |G| ⇒ semisimple
    intro h_not_dvd
    -- (Fintype.card G : k) ≠ 0, which gives NeZero
    have h_card_ne_zero : (Fintype.card G : k) ≠ 0 := by
      contrapose! h_not_dvd
      rw [← CharP.cast_eq_zero_iff k (Fintype.card G)]
      exact h_not_dvd
    have h_neZero : NeZero (Fintype.card G : k) := ⟨h_card_ne_zero⟩
    have h_nat_card_eq : (Nat.card G : k) = (Fintype.card G : k) := by simp
    have h_nat_neZero : NeZero (Nat.card G : k) := by
      rw [h_nat_card_eq]
      exact h_neZero
    haveI : NeZero (Nat.card G : k) := h_nat_neZero
    -- Mathlib's Maschke provides IsSemisimpleModule k[G] V for any V
    -- Taking V = k[G] gives IsSemisimpleRing k[G]
    -- The instance from RepresentationTheory/Maschke provides IsSemisimpleModule k[G] V
    -- so IsSemisimpleRing (MonoidAlgebra k G) follows
    haveI : IsSemisimpleModule (MonoidAlgebra k G) (MonoidAlgebra k G) :=
      inferInstance
    exact inferInstance

end maschke_theorem
