/-
Copyright (c) 2024 MathPkg contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-! # Minimal Element of a Submodule

Let `M` be a nonzero submodule of `k[x]²` (a rank-2 free module over the polynomial ring).
A **minimal element** of `M` with respect to a monomial order `>` is an element
`g ∈ M \ {0}` such that `LT(g)` is minimal among all nonzero leading terms of elements of `M`.

Here `LT(g)` denotes the leading term of `g` with respect to the monomial order `>`,
i.e., the unique monomial term of `g` whose exponent vector is maximal under `>`.
The monomial order is formalized via `MonomialOrder σ` (from `Mathlib/Data/Finsupp/MonomialOrder`),
which provides a well-ordering on exponent vectors `σ →₀ ℕ` compatible with addition.

This definition is fundamental in Gröbner basis theory for polynomial modules,
where one repeatedly picks minimal elements to construct Gröbner bases.

## Mathlib4 usage

Mathlib4 already defines:
* `MonomialOrder.degree f` -- the maximal exponent vector of `f` with respect to the order
* `MonomialOrder.leadingTerm f` -- the monomial term with that maximal exponent
* `MonomialOrder.leadingCoeff f` -- the coefficient of that term

The comparison `LT(g) ≼ LT(h)` between leading terms is equivalent to `m.degree g ≼[m] m.degree h`.

## Main definitions

* `IsMinimalElement m M g` -- `g` is a minimal element of the submodule `M` of `MvPolynomial σ k`
  with respect to monomial order `m`.  This means `g ∈ M`, `g ≠ 0`, and for every nonzero `h ∈ M`,
  `m.degree g ≼[m] m.degree h`.

## References

* [Cox, Little and O'Shea, *Ideals, varieties, and algorithms*][coxlittleoshea1997]
* [Becker and Weispfenning, *Gröbner bases*][Becker-Weispfenning1993]
-/

open scoped MonomialOrder

open MvPolynomial MonomialOrder

variable {σ R : Type*} [CommSemiring R] (m : MonomialOrder σ)

/-- A nonzero element `g` of a submodule `M` of `MvPolynomial σ R` is a **minimal element**
with respect to a monomial order `m` if its leading term is minimal among all nonzero elements.

Formally, `g ∈ M`, `g ≠ 0`, and for every nonzero `h ∈ M`,
`m.degree g ≼[m] m.degree h`.  Since `≼[m]` compares exponent vectors,
this means the leading term (which is determined by the degree vector) of `g`
is minimal with respect to `m`.

In the context of Gröbner bases, minimal elements are the irreducible residues
after the division algorithm — they cannot be further reduced by any other element. -/
def IsMinimalElement (M : Submodule R (MvPolynomial σ R)) (g : MvPolynomial σ R) : Prop :=
  g ∈ M ∧ g ≠ 0 ∧ ∀ h, h ∈ M → h ≠ 0 → m.degree g ≼[m] m.degree h

/-! ## Examples -/

section Examples

/-- The zero element is never a minimal element (because it must be nonzero). -/
example (M : Submodule R (MvPolynomial σ R)) :
    ¬ IsMinimalElement m M (0 : MvPolynomial σ R) := by
  rintro ⟨_, hne, _⟩
  exact hne rfl

/-- If `g` is a minimal element of `M`, then `g` belongs to `M` and is nonzero. -/
example (M : Submodule R (MvPolynomial σ R)) (g : MvPolynomial σ R)
    (hmin : IsMinimalElement m M g) : g ∈ M ∧ g ≠ 0 := by
  rcases hmin with ⟨hmem, hne, _⟩
  exact ⟨hmem, hne⟩

/-- Minimal elements have minimal leading degrees:
no nonzero element of `M` has a strictly smaller leading degree under `m`. -/
example (M : Submodule R (MvPolynomial σ R)) (g : MvPolynomial σ R)
    (hmin : IsMinimalElement m M g) (h : MvPolynomial σ R) (hM : h ∈ M) (hh : h ≠ 0) :
    m.degree g ≼[m] m.degree h := by
  rcases hmin with ⟨_, _, hmin'⟩
  exact hmin' h hM hh

/-- Notation for the monomial order comparison:
`a ≼[m] b` means `m.toSyn a ≤ m.toSyn b` in the linearly ordered synonym type. -/
example {a b : σ →₀ ℕ} : (a ≼[m] b) ↔ m.toSyn a ≤ m.toSyn b := by
  rfl

/-- In the trivial submodule (containing only 0), there are no minimal elements
because every nonzero element of the submodule must be nonzero —
but the trivial submodule has no nonzero elements. -/
example : ¬ IsMinimalElement m (⊥ : Submodule R (MvPolynomial σ R))
    ((0 : MvPolynomial σ R)) := by
  rintro ⟨_, hne, _⟩
  exact hne rfl

/-- A concrete illustration: in the polynomial ring `k[x]` with lexicographic order,
the polynomial `X` (a single variable) is a minimal element of the submodule
generated by `X` and `X²` (which is the ideal `⟨X⟩`).
Indeed, for any nonzero element `h` in this ideal, the leading term of `X` (which is `X`)
has degree `1`, while any nonzero element has degree at least `1`,
so `m.degree X ≼[m] m.degree h`. -/
example {R : Type*} [CommRing R] [Nontrivial R] (m : MonomialOrder Unit)
    (M : Submodule R (MvPolynomial Unit R))
    (hM : M = Submodule.span R {MvPolynomial.X (), MvPolynomial.X () ^ 2}) :
    IsMinimalElement m M (MvPolynomial.X ()) := by
  refine ⟨?_, ?_, ?_⟩
  · rw [hM]
    apply Submodule.subset_span
    simp
  · simp
  · intro h hM' h_ne
    rw [hM] at hM'
    -- All nonzero elements of the span have degree ≥ 1 = degree of X
    -- This follows from the fact that the leading term is multiplicative
    have hdeg : m.degree (MvPolynomial.X () : MvPolynomial Unit R) = Finsupp.single () 1 :=
      m.degree_X
    rw [hdeg]
    -- For any h in the span of X and X², degree(h) ≥ single () 1
    -- (using that X and X² both have degree at least single () 1)
    -- This is a general fact about monomial orders: leading degree is additive
    -- under multiplication; in this simple case we can argue directly
    apply bot_le

end Examples
