import Mathlib

open scoped Classical

/-!
# Purely Transcendental Extension

A field `F` is called a **purely transcendental extension** of a field `K` if
`F = K(S)`, where `S ⊆ F` and `S` is algebraically independent over `K`.

This is the typeclass `IsPurelyTranscendental K F`, the transcendental dual
to Mathlib's `IsPurelyInseparable`.
-/

/-! ### Typeclass definition -/

section purely_transcendental

variable (K F : Type*) [Field K] [Field F] [Algebra K F]

/-- `IsPurelyTranscendental K F` means `F` is a purely transcendental extension of `K`:
there exists a subset `S` of `F` that is algebraically independent over `K`
and generates `F` as a field extension. -/
class IsPurelyTranscendental : Prop where
  exists_algebraicIndependent_generating_set : ∃ (S : Set F),
    AlgebraicIndependent K (fun x : S => (x : F)) ∧
    IntermediateField.adjoin K S = ⊤

end purely_transcendental

/-! ### Examples -/

section examples

open IntermediateField

/-- The rational function field `RatFunc K` is a purely transcendental
extension of `K` (generated by `X`). -/
example (K : Type*) [Field K] : IsPurelyTranscendental K (RatFunc K) := by
  refine ⟨?exists_algebraicIndependent_generating_set⟩
  -- Use the singleton set {X}
  use {RatFunc.X}
  constructor
  · -- `X` is algebraically independent over `K` (i.e., transcendental)
    -- The index type is a singleton, so we use the singleton criterion
    have h_transcendental : Transcendental K (RatFunc.X : RatFunc K) :=
      RatFunc.transcendental_X (K := K)
    -- For a singleton index type, algebraic independence ↔ transcendental
    have h_indep : AlgebraicIndependent K (fun x : ({RatFunc.X} : Set (RatFunc K)) =>
      (x : RatFunc K)) := by
      -- Use the singleton algebraic independence criterion
      apply (algebraicIndependent_singleton_iff (i := ⟨RatFunc.X, by simp⟩)).mpr
      simpa only [Subtype.coe_mk] using h_transcendental
    exact h_indep
  · -- The field generated by {X} over K is all of RatFunc K
    -- This is exactly RatFunc.adjoin_X
    simpa using (RatFunc.adjoin_X (K := K))

end examples
