import Mathlib

open scoped Classical
open scoped BigOperators

/-!
# Radical of Annihilator and Properties of Parameter Ideals

Let `M` be a finitely generated module over a ring `R`, and `q` an ideal.
Then `rad(ann(M/qM)) = rad(q + ann M)`.

In particular, if `(R, m)` is a local ring:

(a) `q` is a parameter ideal for `M` iff `q + ann M ⊇ m^n` for some `n ≫ 0`
    iff `q` is a parameter ideal for `R/(ann M)`;

(b) For a short exact sequence `0 → M' → M → M'' → 0`, `q` is a parameter ideal
    for `M` iff it is a parameter ideal for both `M'` and `M''`;

(c) `dim M` is the minimal number of generators of a parameter ideal for `M`.
-/

section general

variable {R : Type u} [CommRing R] {M : Type v} [AddCommGroup M] [Module R M]

/-- The radical of the annihilator of `M/qM` equals the radical of `q + ann M`,
for any finitely generated `R`-module `M` and ideal `q` of `R`. -/
theorem radical_ann_quotient_eq_radical_q_add_ann
    (hM : Module.Finite R M) (q : Ideal R) :
    Ideal.radical (Module.annihilator R (M ⧸ (q • (⊤ : Submodule R M)))) =
    Ideal.radical (q + Module.annihilator R M) := by
  sorry

end general

section local

variable {R : Type u} [CommRing R] [LocalRing R] {M : Type v} [AddCommGroup M] [Module R M]

/-- An ideal `q` in a local ring `(R, m)` is a **parameter ideal** for the finitely generated
module `M` if `q ⊆ m` and the quotient module `M/qM` has finite length as an `R`-module.

In the language of systems of parameters, `q` is generated by a system of parameters
for `M`, which implies that `q` is generated by `dim M` elements and `M/qM` is
Artinian (hence of finite length). -/
structure IsParameterIdeal (hM : Module.Finite R M) (q : Ideal R) : Prop where
  contained_in_max : q ≤ LocalRing.maximalIdeal R
  finite_length_quotient : Module.FiniteLength R (M ⧸ (q • (⊤ : Submodule R M)))

/-- (a) For a local ring `(R, m)`, an ideal `q` is a parameter ideal for `M` if and only
if `q + ann M` contains a power of the maximal ideal `m`. -/
theorem isParameterIdeal_iff_q_add_ann_contains_m_pow
    (hM : Module.Finite R M) (q : Ideal R) :
    IsParameterIdeal hM q ↔
    ∃ (n : ℕ), (LocalRing.maximalIdeal R) ^ n ≤ q + Module.annihilator R M := by
  sorry

/-- (a, second form) `q` is a parameter ideal for `M` iff `q` is a parameter ideal
for `R/(ann M)` regarded as a module over the quotient ring. -/
theorem isParameterIdeal_iff_isParameterIdeal_quotient_ann
    (hM : Module.Finite R M) (q : Ideal R) :
    IsParameterIdeal hM q ↔
    IsParameterIdeal (by
      have : Module (R ⧸ Module.annihilator R M) M := inferInstance
      have : Module.Finite (R ⧸ Module.annihilator R M) M :=
        Module.Finite.of_restrictScalars (R ⧸ Module.annihilator R M)
          (Module.annihilator R M).mkQ
      exact this
    ) (q.map (Ideal.Quotient.mk (Module.annihilator R M))) := by
  sorry

/-- (b) For a short exact sequence `0 → M' → M → M'' → 0` of finitely generated `R`-modules,
an ideal `q` is a parameter ideal for `M` if and only if it is a parameter ideal for both
`M'` and `M''`. -/
theorem isParameterIdeal_short_exact_sequence
    {M' M'' : Type v} [AddCommGroup M'] [AddCommGroup M''] [Module R M'] [Module R M'']
    (hM : Module.Finite R M) (hM' : Module.Finite R M') (hM'' : Module.Finite R M'')
    (f : M' →ₗ[R] M) (g : M →ₗ[R] M'')
    (h_exact : Function.Exact f g) (h_inj : Function.Injective f) (h_surj : Function.Surjective g)
    (q : Ideal R) :
    IsParameterIdeal hM q ↔ IsParameterIdeal hM' q ∧ IsParameterIdeal hM'' q := by
  sorry

/-- (c) The Krull dimension `dim M` is the minimal number of generators of a parameter ideal
for `M`. That is, there exists a parameter ideal with at most `dim M` generators, and every
parameter ideal has at least `dim M` generators. -/
theorem dim_eq_minimal_generators_of_parameter_ideal
    (hM : Module.Finite R M) :
    (∃ (q : Ideal R) (hq : IsParameterIdeal hM q) (s : Finset R),
      Ideal.span (s : Set R) = q ∧ (s.card : ℕ∞) ≤ krullDim R) ∧
    (∀ (q : Ideal R) (hq : IsParameterIdeal hM q) (s : Finset R),
      Ideal.span (s : Set R) = q → (krullDim R : ℕ∞) ≤ (s.card : ℕ∞)) := by
  sorry

end local
