import Mathlib

open CategoryTheory

/-!
# Short Exact Sequence of Singular Chains for Two Open Sets

Let `X = U ∪ V` be the union of two open sets. There is a short exact sequence
of singular chains: `0 → S_q(U ∩ V) → S_q(U) ⊕ S_q(V) → S_q^U(X) → 0`.

This is the chain-level Mayer-Vietoris short exact sequence, a key ingredient in the
proof of the Mayer-Vietoris long exact sequence for singular homology. The sequence
is exact in each degree.
-/

noncomputable section

variable {X : TopCat.{u}} (U V : TopologicalSpace.Opens X) (hcover : U ⊔ V = ⊤)

/--
**Short exact sequence for two open sets.**

Let `X = U ∪ V` be a topological space covered by two open sets. For any
commutative ring `R` and degree `q`, there is a short exact sequence of `R`-modules:

`0 → S_q(U ∩ V; R) → S_q(U; R) ⊕ S_q(V; R) → S_q^U(X; R) → 0`

where:

* `S_q(Y; R)` denotes the module of singular `q`-chains with coefficients in `R`
  on the topological space `Y`
* `S_q^U(X; R)` is the submodule of `S_q(X; R)` generated by singular simplices
  whose image is contained in `U` or `V` (the "small" chains for the cover `{U, V}`)
* The first map `S_q(U ∩ V; R) → S_q(U; R) ⊕ S_q(V; R)` is induced by the
  inclusions `U ∩ V ↪ U` and `U ∩ V ↪ V` (with a sign convention)
* The second map `S_q(U; R) ⊕ S_q(V; R) → S_q^U(X; R)` is induced by the
  inclusions `U ↪ X` and `V ↪ X`, viewed as a map into the small chain submodule
-/
theorem short_exact_sequence_for_two_open_sets (R : Type u) [CommRing R] (q : ℕ) :
    ∃ (S : ShortComplex (ModuleCat R)), S.ShortExact := by
  sorry

end
