import Mathlib

/-!
# Stable Quotient of an Ideal

Let `R` be a commutative ring, `I` an ideal of `R`, and `f ∈ R`.
The **stable quotient** of `I` with respect to `f`, denoted `I : f^∞`, is the ideal

  `I : f^∞ := { g ∈ R | ∃ n ≥ 1, f^n * g ∈ I }`

In commutative algebra, this is also called the **saturation of `I` with respect to the
multiplicative set `{1, f, f^2, …}`**. The colon ideals `I : (f^n)` form an increasing chain:

  `I ⊆ (I : f) ⊆ (I : f^2) ⊆ … ⊆ (I : f^∞)`

and the stable quotient is the union of this ascending chain.

## Main definition

* `Ideal.stableQuotient I f` : the ideal `I : f^∞`.

## Notation

* `I :ₛ f` : scoped notation for `Ideal.stableQuotient I f`.

## Source

This is definition 67 from the pipeline.

-/

open scoped Classical

variable {R : Type*} [CommRing R]

namespace Ideal

/-- The **stable quotient** `I : f^∞` is the ideal consisting of all `g ∈ R` such that
`f^n * g ∈ I` for some `n ≥ 1`.

Formally: `I :ₛ f = { g : R | ∃ n : ℕ, 1 ≤ n ∧ f ^ n * g ∈ I }`.

This is also written `I : ⟨f⟩^∞` or `S_f(I)` (saturation with respect to the
multiplicative set generated by `f`) in the literature. -/
def stableQuotient (I : Ideal R) (f : R) : Ideal R where
  carrier := {g : R | ∃ n : ℕ, 1 ≤ n ∧ f ^ n * g ∈ I}
  zero_mem' := by
    refine ⟨1, by norm_num, ?_⟩
    simp
  add_mem' := by
    intro g₁ g₂ h₁ h₂
    rcases h₁ with ⟨n₁, hn₁, hg₁⟩
    rcases h₂ with ⟨n₂, hn₂, hg₂⟩
    let n := max n₁ n₂
    have hn_pos : 1 ≤ n := le_trans hn₁ (le_max_left _ _)
    refine ⟨n, hn_pos, ?_⟩
    rw [mul_add]
    have h₁' : f ^ n * g₁ ∈ I := by
      have hpow : f ^ n = f ^ (n - n₁) * f ^ n₁ := by
        rw [← pow_add, add_comm, Nat.add_sub_cancel' (le_max_left _ _)]
      rw [hpow, mul_assoc]
      exact I.mul_mem_left _ hg₁
    have h₂' : f ^ n * g₂ ∈ I := by
      have hpow : f ^ n = f ^ (n - n₂) * f ^ n₂ := by
        rw [← pow_add, add_comm, Nat.add_sub_cancel' (le_max_right _ _)]
      rw [hpow, mul_assoc]
      exact I.mul_mem_left _ hg₂
    exact I.add_mem h₁' h₂'
  smul_mem' := by
    intro r g hg
    rcases hg with ⟨n, hn, hg⟩
    refine ⟨n, hn, ?_⟩
    rw [mul_left_comm (f ^ n) r g, smul_eq_mul]
    exact I.mul_mem_right _ hg

/-- Scoped notation `I :ₛ f` for the stable quotient `I : f^∞`.

The subscript "s" stands for "stable" (as opposed to the single-step colon `(I : f)`). -/
scoped notation:70 I:70 " :ₛ " f:70 => stableQuotient I f

/-- Membership criterion for the stable quotient. -/
lemma mem_stableQuotient_iff {I : Ideal R} {f g : R} :
    g ∈ I :ₛ f ↔ ∃ n : ℕ, 1 ≤ n ∧ f ^ n * g ∈ I := by
  rfl

/-- Every element of `I` belongs to `I : f^∞` (take `n = 1`).
So `I ⊆ I : f^∞`. -/
lemma subset_stableQuotient (I : Ideal R) (f : R) : I ≤ I :ₛ f := by
  intro g hg
  refine ⟨1, by norm_num, ?_⟩
  simpa using I.mul_mem_left f hg

/-- Monotonicity: if `I ⊆ J` then `I : f^∞ ⊆ J : f^∞`. -/
lemma stableQuotient_mono {I J : Ideal R} (hIJ : I ≤ J) (f : R) : I :ₛ f ≤ J :ₛ f := by
  intro g hg
  rcases hg with ⟨n, hn, hg⟩
  refine ⟨n, hn, hIJ hg⟩

end Ideal

/-! ## Examples -/

section examples

open Ideal

/-- **Example 1**: In any commutative ring, if `g ∈ I` then `g ∈ I :ₛ f`. -/
example (R : Type*) [CommRing R] (I : Ideal R) (f g : R) (hg : g ∈ I) : g ∈ I :ₛ f :=
  Ideal.subset_stableQuotient I f hg

/-- **Example 2**: Zero is always in the stable quotient (take `n = 1`). -/
example (R : Type*) [CommRing R] (I : Ideal R) (f : R) : (0 : R) ∈ I :ₛ f := by
  rw [Ideal.mem_stableQuotient_iff]
  refine ⟨1, by norm_num, ?_⟩
  simp

/-- **Example 3**: In ℤ, `(0) :ₛ 2` consists of all integers `g` such that `2^n * g = 0`
for some `n ≥ 1`. Since ℤ is an integral domain, this forces `g = 0`.

So `(0) :ₛ 2 = (0)` in ℤ. -/
example : (⊥ : Ideal ℤ) :ₛ (2 : ℤ) = (⊥ : Ideal ℤ) := by
  apply le_antisymm
  · intro g hg
    rcases Ideal.mem_stableQuotient_iff.mp hg with ⟨n, hn, hg⟩
    rw [Ideal.mem_bot] at hg ⊢
    -- hg : 2^n * g = 0, and 2^n ≠ 0, so by integral domain property g = 0
    have hp : (2 : ℤ) ^ n ≠ 0 := by
      simp
    apply mul_eq_zero.mp at hg
    · rcases hg with (h | h)
      · exact hp h
      · exact h
    · -- commutativity
      ring
  · -- ⊥ ⊆ ⊥ :ₛ 2 is always true
    exact Ideal.subset_stableQuotient ⊥ (2 : ℤ)

/-- **Example 4**: In ℤ, taking `I = (6)` and `f = 2`, the element `g = 3` is in `(6) :ₛ 2`
because `2^1 * 3 = 6 ∈ (6)`. -/
example : (3 : ℤ) ∈ (Ideal.span {(6 : ℤ)}) :ₛ (2 : ℤ) := by
  rw [Ideal.mem_stableQuotient_iff]
  refine ⟨1, by norm_num, ?_⟩
  -- 2^1 * 3 = 6 ∈ (6)
  simp

/-- **Example 5**: Monotonicity demonstration: if `(2) ⊆ (1)` in ℤ then
`(2) :ₛ 3 ⊆ (1) :ₛ 3`. -/
example : (Ideal.span {(2 : ℤ)}) :ₛ (3 : ℤ) ≤ (Ideal.span {(1 : ℤ)}) :ₛ (3 : ℤ) :=
  Ideal.stableQuotient_mono (Ideal.span_le_span_singleton.mpr (by norm_num)) (3 : ℤ)

end examples
