import Mathlib

open Set

/-!
# Structure of the Ω-subgroup generated by a set

If G is an Ω-group and X is a nonempty subset, then the Ω-subgroup X^Ω generated
by X consists of all elements of the form

  (x_{i₁}^{ε₁})^{ω₁} · (x_{i₂}^{ε₂})^{ω₂} · ... · (x_{i_r}^{ε_r})^{ω_r}

where x_i ∈ X, ε_i = ±1, r ≥ 0, and each ω_i is a finite sequence of operators
from Ω applied successively.

## Mathlib4 References
- `MulDistribMulAction`: `GroupAction/Defs.lean`
- `Subgroup`: `Algebra/Group/Subgroup/Defs.lean`
- `Subgroup.closure`: `Algebra/Group/Subgroup/Lattice.lean`
-/

universe u v

/-! ### Ω-subgroup definition -/

variable {Ω : Type v} [Monoid Ω] {G : Type u} [Group G] [MulDistribMulAction Ω G]

/-- An Ω-subgroup of an Ω-group G is a subgroup H that is Ω-admissible, i.e.,
for every h ∈ H and ω ∈ Ω, we have ω • h ∈ H. -/
def IsOmegaSubgroup (H : Subgroup G) : Prop :=
  ∀ (h : G), h ∈ H → ∀ (ω : Ω), ω • h ∈ H

/-- Predicate for Ω-subgroups containing a set X. Pulled out to help typeclass inference. -/
def IsOmegaSubgroupContaining (X : Set G) (H : Subgroup G) : Prop :=
  IsOmegaSubgroup H ∧ X ⊆ (H : Set G)

/-- The Ω-subgroup generated by a set X is the intersection of all Ω-subgroups
containing X. This is the smallest Ω-subgroup of G that contains X. -/
def omegaClosure (X : Set G) : Subgroup G :=
  sInf ({H : Subgroup G | IsOmegaSubgroupContaining X H} : Set (Subgroup G))

/-- The omega closure contains X. -/
lemma subset_omegaClosure (X : Set G) : X ⊆ (omegaClosure X : Set G) := by
  intro x hx
  show x ∈ (omegaClosure X : Set G)
  dsimp [omegaClosure]
  refine (Subgroup.mem_sInf.mpr ?_)
  intro H hH
  rcases hH with ⟨_, hXsub⟩
  exact hXsub hx

/-- Each Ω-subgroup containing X contains the omega closure. -/
lemma omegaClosure_le {X : Set G} {H : Subgroup G} (hH : IsOmegaSubgroup H) (hX : X ⊆ (H : Set G)) :
    omegaClosure X ≤ H := by
  dsimp [omegaClosure]
  apply sInf_le
  exact ⟨hH, hX⟩

/-! ### Finite sequences of operators -/

/-- A finite sequence of operators from Ω. We use `List Ω`. -/
abbrev OmegaSeq := List Ω

/-- Apply a sequence of operators to an element of the group, applying from
left to right. For sequence [ω₁, ω₂, ..., ω_k], the result is
ω_k(···(ω₂(ω₁(g)))···).  -/
def applySeq (seq : List Ω) (g : G) : G :=
  List.foldl (fun x ω => ω • x) g seq

@[simp]
theorem applySeq_nil (g : G) : applySeq [] g = g := rfl

@[simp]
theorem applySeq_singleton (ω : Ω) (g : G) : applySeq [ω] g = ω • g := rfl

@[simp]
theorem applySeq_cons (ω : Ω) (seq : List Ω) (g : G) :
    applySeq (ω :: seq) g = applySeq seq (ω • g) := rfl

theorem applySeq_append (s₁ s₂ : List Ω) (g : G) :
    applySeq (s₁ ++ s₂) g = applySeq s₂ (applySeq s₁ g) := by
  induction' s₁ with ω s₁ ih generalizing g
  · rfl
  · simp [applySeq_cons, ih]

/-- The identity is preserved by any operator sequence. -/
theorem applySeq_one (seq : List Ω) : applySeq seq (1 : G) = 1 := by
  induction' seq with ω seq ih
  · rfl
  · simp [applySeq_cons, ih]

/-- Operator sequences preserve multiplication (they are compositions of endomorphisms). -/
theorem applySeq_mul (seq : List Ω) (g h : G) :
    applySeq seq (g * h) = applySeq seq g * applySeq seq h := by
  induction' seq with ω seq ih generalizing g h
  · rfl
  · simp [applySeq_cons, ih]

/-! ### Structure theorem -/

namespace StructureTheorem

variable {X : Set G}

/-- The set W of all elements of the form
(∏_{j=1}^{r} (x_j^{ε_j})^{ω_j}) where x_j ∈ X, ε_j = ±1, r ≥ 0,
and each ω_j is a finite sequence of operators.

We use `List G` to represent the product of factors. -/
def W (X : Set G) : Set G :=
  { w : G | ∃ (factors : List G),
      w = factors.prod ∧
      ∀ f ∈ factors, ∃ (x : G) (_hx : x ∈ X) (ε : ℤ) (hε : ε = 1 ∨ ε = -1) (ω : List Ω),
        f = applySeq ω (x ^ ε) }

/-- The identity is in W (empty product, r = 0). -/
theorem mem_W_one : (1 : G) ∈ W X := by
  refine ⟨[], ?_, ?_⟩
  · simp
  · intro f hf; exfalso; exact List.not_mem_nil f hf

/-- Each x ∈ X appears in W (take r = 1, ε = 1, empty operator sequence). -/
theorem mem_W_of_mem_X {x : G} (hx : x ∈ X) : x ∈ W X := by
  refine ⟨[x], ?_, ?_⟩
  · simp
  · intro f hf
    have : f = x := by simpa using hf
    rcases this with rfl
    refine ⟨x, hx, 1, Or.inl rfl, [], ?_⟩
    simp

/-- W is closed under multiplication (concatenate lists). -/
theorem W_mul_mem {a b : G} (ha : a ∈ W X) (hb : b ∈ W X) : a * b ∈ W X := by
  rcases ha with ⟨fs, rfl, hfs⟩
  rcases hb with ⟨gs, rfl, hgs⟩
  refine ⟨fs ++ gs, by simp, ?_⟩
  intro f hf
  rcases List.mem_append.mp hf with (hf' | hf')
  · exact hfs f hf'
  · exact hgs f hf'

/-- W is closed under inverses.
For a product ∏ f_i, its inverse is ∏ f_{n-i}⁻¹.
If f = (x^ε)^ω, then f⁻¹ = (x^{-ε})^ω (since ω is an endomorphism). -/
theorem W_inv_mem {a : G} (ha : a ∈ W X) : a⁻¹ ∈ W X := by
  rcases ha with ⟨fs, rfl, hfs⟩
  have h_each : ∀ f ∈ fs, f⁻¹ ∈ W X := by
    intro f hf
    rcases hfs f hf with ⟨x, hx, ε, hε, ω, rfl⟩
    refine ⟨[applySeq ω (x ^ (-ε))], by simp, ?_⟩
    intro g hg
    have : g = applySeq ω (x ^ (-ε)) := by simpa using hg
    rcases this with rfl
    refine ⟨x, hx, -ε, ?_, ω, rfl⟩
    rcases hε with (rfl | rfl)
    · exact Or.inr rfl
    · exact Or.inl rfl
  refine ⟨List.reverse (List.map (fun f => f⁻¹) fs), ?_, ?_⟩
  · simp [List.prod_reverse]
  · intro f hf
    rcases List.mem_reverse.mp hf with hf'
    rcases List.mem_map.mp hf' with ⟨g, hg, rfl⟩
    exact h_each g hg

/-- W is closed under the action of operators.
If a = ∏ f_i with f_i = (x_i^{ε_i})^{ω_i}, then
ω • a = ω • (∏ f_i) = ∏ (ω • f_i) (since ω is an endomorphism)
and ω • f_i = ω • ((x_i^{ε_i})^{ω_i}) = (x_i^{ε_i})^{ω_i ++ [ω]}. -/
theorem W_omega_closed {a : G} (ha : a ∈ W X) (ω : Ω) : ω • a ∈ W X := by
  rcases ha with ⟨fs, rfl, hfs⟩
  have h_each : ∀ f ∈ fs, ω • f ∈ W X := by
    intro f hf
    rcases hfs f hf with ⟨x, hx, ε, hε, ωs, rfl⟩
    refine ⟨[applySeq (ωs ++ [ω]) (x ^ ε)], by simp, ?_⟩
    intro g hg
    have : g = applySeq (ωs ++ [ω]) (x ^ ε) := by simpa using hg
    rcases this with rfl
    refine ⟨x, hx, ε, hε, ωs ++ [ω], rfl⟩
  have hprod : ω • (fs.prod) = (List.map (fun f => ω • f) fs).prod := by
    induction' fs with f fs ih
    · simp
    · simp [ih]
  rw [hprod]
  refine ⟨List.map (fun f => ω • f) fs, rfl, ?_⟩
  intro g hg
  rcases List.mem_map.mp hg with ⟨f, hf, rfl⟩
  exact h_each f hf

/-- W forms a subgroup of G. -/
def W_subgroup : Subgroup G where
  carrier := W X
  one_mem' := mem_W_one
  mul_mem' := W_mul_mem
  inv_mem' := W_inv_mem

/-- W as a subgroup is an Ω-subgroup. -/
theorem W_isOmegaSubgroup : IsOmegaSubgroup (W_subgroup : Subgroup G) := by
  intro h hh ω
  have hhW : h ∈ W X := hh
  have hωW : ω • h ∈ W X := W_omega_closed hhW ω
  exact hωW

/-- X is contained in W. -/
theorem X_subset_W : X ⊆ (W_subgroup : Set G) := by
  intro x hx
  exact mem_W_of_mem_X hx

/-- Helper lemma: if a is in an Ω-subgroup H and seq is a finite sequence of operators,
then applySeq seq a is also in H. -/
lemma applySeq_mem_omega_subgroup (H : Subgroup G) (hH : IsOmegaSubgroup H) {a : G} (ha : a ∈ H)
    (seq : List Ω) : applySeq seq a ∈ H := by
  induction' seq with ω seq ih generalizing a
  · exact ha
  · have hωa : ω • a ∈ H := hH a ha ω
    rw [applySeq_cons]
    exact ih hωa

/-- **Inclusion W ⊆ X^Ω**: Every element of W is contained in every Ω-subgroup
that contains X. -/
theorem W_subset_omegaClosure : W X ⊆ (omegaClosure X : Set G) := by
  intro w hw
  rcases hw with ⟨fs, rfl, hfs⟩
  dsimp [omegaClosure]
  refine (Subgroup.mem_sInf.mpr ?_)
  intro H hHcond
  rcases hHcond with ⟨hH_omega, hXsub⟩
  have h_factors : ∀ f ∈ fs, f ∈ H := by
    intro f hf
    rcases hfs f hf with ⟨x, hx, ε, hε, ωs, rfl⟩
    have hxH : x ∈ H := hXsub hx
    have hxpowH : x ^ ε ∈ H := by
      rcases hε with (rfl | rfl)
      · simpa using hxH
      · have : x⁻¹ ∈ H := Subgroup.inv_mem hxH
        simpa using this
    exact applySeq_mem_omega_subgroup H hH_omega hxpowH ωs
  refine Subgroup.list_prod_mem _ h_factors

/-- **Inclusion X^Ω ⊆ W**: Every element of the Ω-subgroup generated by X is in W.
This follows because W itself is an Ω-subgroup containing X, and X^Ω is
the smallest such (defined as the intersection). -/
theorem omegaClosure_subset_W : (omegaClosure X : Set G) ⊆ W X := by
  have hW_omega : IsOmegaSubgroup (W_subgroup : Subgroup G) := W_isOmegaSubgroup
  have hX_sub_W : X ⊆ (W_subgroup : Set G) := X_subset_W
  have hle : omegaClosure X ≤ W_subgroup :=
    omegaClosure_le hW_omega hX_sub_W
  intro w hw
  have hw' : w ∈ (W_subgroup : Set G) := hle hw
  exact hw'

/-- **Structure Theorem**: If G is an Ω-group and X is a nonempty subset, then
the Ω-subgroup X^Ω generated by X consists exactly of all elements of the form

  (x_{i₁}^{ε₁})^{ω₁} · (x_{i₂}^{ε₂})^{ω₂} · ... · (x_{i_r}^{ε_r})^{ω_r}

where x_i ∈ X, ε_i = ±1, r ≥ 0, and each ω_i is a finite sequence of
operators from Ω applied successively. -/
theorem structure_of_omega_subgroup_generated_by_set :
    (omegaClosure X : Set G) = W X := by
  apply Set.Subset.antisymm
  · exact omegaClosure_subset_W
  · exact W_subset_omegaClosure

end StructureTheorem

/-! ### Example -/

section Example

variable {G : Type u} [Group G]

/-- Example: An Ω-group where Ω is `Unit` (a single operator) acting as the identity. -/
instance trivialMulDistribMulAction : MulDistribMulAction Unit G where
  smul := fun _ g => g
  one_smul := by intro _; rfl
  mul_smul := by intro _ _ _; rfl
  smul_one := by intro _; rfl
  smul_mul := by intro _ _ _; rfl

/-- In the trivial Ω-group (where operators act as identity), the ω-closure of a
nonempty set X coincides with the ordinary subgroup generated by X. -/
theorem omegaClosure_eq_subgroup_closure (X : Set G) (hX : X.Nonempty) :
    (omegaClosure (Ω := Unit) X : Set G) = (Subgroup.closure X : Set G) := by
  have h_eq := StructureTheorem.structure_of_omega_subgroup_generated_by_set
    (Ω := Unit) (X := X)
  have hW_eq_closure : StructureTheorem.W (Ω := Unit) X = (Subgroup.closure X : Set G) := by
    ext g
    constructor
    · intro hg
      rcases hg with ⟨fs, rfl, hfs⟩
      refine Subgroup.list_prod_mem (Subgroup.closure X) ?_
      intro f hf
      rcases hfs f hf with ⟨x, hx, ε, hε, ωs, rfl⟩
      have h_omega_id : ∀ (seq : List Unit) (a : G), applySeq (Ω := Unit) seq a = a := by
        intro seq a
        induction' seq with u seq ih
        · rfl
        · simp [applySeq_cons (Ω := Unit), ih]
      simp [h_omega_id]
      rcases hε with (rfl | rfl)
      · exact Subgroup.subset_closure hx
      · have hx' : x ∈ Subgroup.closure X := Subgroup.subset_closure hx
        exact Subgroup.inv_mem _ hx'
    · intro hg
      refine Subgroup.closure_induction hg ?_ ?_ ?_ ?_
      · intro x hx
        exact StructureTheorem.mem_W_of_mem_X (Ω := Unit) hx
      · exact StructureTheorem.mem_W_one (Ω := Unit) (X := X)
      · intro a b ha hb
        exact StructureTheorem.W_mul_mem (Ω := Unit) ha hb
      · intro a ha
        exact StructureTheorem.W_inv_mem (Ω := Unit) ha
  rw [h_eq, hW_eq_closure]

/-- Detailed check: a specific element in the subgroup generated by two elements
is also in the ω-closure. -/
example (a b : G) (hX : ({a, b} : Set G).Nonempty) :
    (a * b⁻¹) ∈ (omegaClosure (Ω := Unit) ({a, b} : Set G) : Set G) := by
  have h := omegaClosure_eq_subgroup_closure {a, b} (by
    refine ⟨a, ?_⟩
    simp)
  rw [h]
  refine Subgroup.mul_mem _ (Subgroup.subset_closure (by simp))
    (Subgroup.inv_mem _ (Subgroup.subset_closure (by simp)))

end Example
