import Mathlib

open scoped TensorProduct

/-!
# Tensor Product of Modules (Definition 5.1)

Let `A` be a right module and `B` a left module over a ring `R`. For a commutative `R`
these coincide with ordinary `R`-modules. The **tensor product** `A ⊗_R B` is
constructed as follows:

1. Let `F` be the free abelian group on the set `A × B`.
2. Let `K` be the subgroup of `F` generated by all elements of the forms:
   - `(a₁ + a₂, b) - (a₁, b) - (a₂, b)` (additivity in the first factor)
   - `(a, b₁ + b₂) - (a, b₁) - (a, b₂)` (additivity in the second factor)
   - `(r·a, b) - (a, r·b)` (balanced/associative property)
3. The tensor product is the quotient group `F / K`.

In Mathlib4, `TensorProduct R A B` (notation `A ⊗[R] B`) is constructed
equivalently as the quotient of `FreeAddMonoid (A × B)` by the additive
congruence generated by the bilinearity relations. This file documents
the available API and proves the fundamental properties.

## Main concepts
* `TensorProduct R A B` : the tensor product type, notation `A ⊗[R] B`
* `tmul R a b` : the canonical map `a ⊗ₜ[R] b`, the image of `(a, b)` in the quotient
* `TensorProduct.mk R A B` : the canonical bilinear map `A →ₗ[R] B →ₗ[R] A ⊗[R] B`
* `TensorProduct.lift` : the universal property lift

## References
* Dummit & Foote, Definition 5.1 (Tensor Product)
* Mathlib: `Mathlib/LinearAlgebra/TensorProduct/Defs.lean`
-/

/-! ### Core definition (from Mathlib) -/

section Definition

variable (R : Type*) [CommSemiring R]
variable (A B : Type*) [AddCommMonoid A] [Module R A] [AddCommMonoid B] [Module R B]

/--
The tensor product `A ⊗[R] B` is Mathlib's `TensorProduct`, which follows the
textbook construction of Definition 5.1 as a quotient of `FreeAddMonoid (A × B)`
by the additive congruence of bilinearity relations.
-/
example : Type _ := A ⊗[R] B

/-- The canonical function `A → B → A ⊗[R] B` sending `(a, b)` to the
coset of the generator `(a, b)` in the quotient. -/
example (a : A) (b : B) : A ⊗[R] B := a ⊗ₜ[R] b

/-- The canonical `R`-bilinear map `A →ₗ[R] B →ₗ[R] A ⊗[R] B`. -/
example : A →ₗ[R] B →ₗ[R] A ⊗[R] B := TensorProduct.mk R A B

/-- The `TensorProduct` is an `R`-module. -/
example : Module R (A ⊗[R] B) := by infer_instance

/-- The `TensorProduct` is an additive commutative monoid. -/
example : AddCommMonoid (A ⊗[R] B) := by infer_instance

/-- Addition is commutative in the tensor product. -/
example (x y : A ⊗[R] B) : x + y = y + x := by
  abel

end Definition

/-! ### Bilinearity properties (matching the quotient relations) -/

section Bilinearity

open TensorProduct

variable {R : Type*} [CommSemiring R]
variable {A B : Type*} [AddCommMonoid A] [Module R A] [AddCommMonoid B] [Module R B]

/-- Additivity in the first argument (corresponds to the relation
`(a₁ + a₂, b) = (a₁, b) + (a₂, b)` in the subgroup K). -/
example (a₁ a₂ : A) (b : B) : (a₁ + a₂) ⊗ₜ[R] b = a₁ ⊗ₜ[R] b + a₂ ⊗ₜ[R] b := by
  simp [add_tmul]

/-- Additivity in the second argument (corresponds to the relation
`(a, b₁ + b₂) = (a, b₁) + (a, b₂)` in the subgroup K). -/
example (a : A) (b₁ b₂ : B) : a ⊗ₜ[R] (b₁ + b₂) = a ⊗ₜ[R] b₁ + a ⊗ₜ[R] b₂ := by
  simp [tmul_add]

/-- Zero in the first argument maps to zero. -/
example (b : B) : (0 : A) ⊗ₜ[R] b = (0 : A ⊗[R] B) := by
  simp [zero_tmul]

/-- Zero in the second argument maps to zero. -/
example (a : A) : a ⊗ₜ[R] (0 : B) = (0 : A ⊗[R] B) := by
  simp [tmul_zero]

/-- The balanced property (corresponds to the relation
`(r·a, b) = (a, r·b)` in the subgroup K). -/
example (r : R) (a : A) (b : B) : (r • a) ⊗ₜ[R] b = a ⊗ₜ[R] (r • b) := by
  simp [smul_tmul]

end Bilinearity

/-! ### The universal property -/

section UniversalProperty

open TensorProduct

variable {R A B P : Type*}
variable [CommSemiring R] [AddCommMonoid A] [Module R A]
variable [AddCommMonoid B] [Module R B] [AddCommMonoid P] [Module R P]

/-- The universal property: given any `R`-bilinear map `f : A →ₗ[R] B →ₗ[R] P`,
there exists a unique `R`-linear map `lift f : A ⊗[R] B →ₗ[R] P` such that
`(lift f) (a ⊗ₜ b) = f a b`. -/
example (f : A →ₗ[R] B →ₗ[R] P) : A ⊗[R] B →ₗ[R] P :=
  TensorProduct.lift f

/-- The lift satisfies the defining equation. -/
example (f : A →ₗ[R] B →ₗ[R] P) (a : A) (b : B) :
    TensorProduct.lift f (a ⊗ₜ[R] b) = f a b :=
  rfl

/-- `TensorProduct.lift` is the unique linear map with this property. -/
example (f : A →ₗ[R] B →ₗ[R] P) (g : A ⊗[R] B →ₗ[R] P)
    (h : ∀ a b, g (a ⊗ₜ[R] b) = f a b) : g = TensorProduct.lift f :=
  TensorProduct.ext' h

end UniversalProperty

/-! ### Example: tensor product over ℤ -/

section ZExamples

open TensorProduct

/-- Construct the element `2 ⊗ 3` in `ℤ ⊗[ℤ] ℤ`. -/
example : ℤ ⊗[ℤ] ℤ :=
  (2 : ℤ) ⊗ₜ[ℤ] (3 : ℤ)

/-- Additivity in the first argument for ℤ-modules. -/
example (a₁ a₂ b : ℤ) : (a₁ + a₂) ⊗ₜ[ℤ] b = a₁ ⊗ₜ[ℤ] b + a₂ ⊗ₜ[ℤ] b := by
  simp [add_tmul]

/-- Additivity in the second argument for ℤ-modules. -/
example (a b₁ b₂ : ℤ) : a ⊗ₜ[ℤ] (b₁ + b₂) = a ⊗ₜ[ℤ] b₁ + a ⊗ₜ[ℤ] b₂ := by
  simp [tmul_add]

/-- The balanced property for ℤ-modules. -/
example (r a b : ℤ) : (r • a) ⊗ₜ[ℤ] b = a ⊗ₜ[ℤ] (r • b) := by
  simpa using smul_tmul (r : ℤ) a b

/-- Zero on the left gives zero. -/
example (b : ℤ) : (0 : ℤ) ⊗ₜ[ℤ] b = (0 : ℤ ⊗[ℤ] ℤ) := by
  simp [zero_tmul]

/-- Zero on the right gives zero. -/
example (a : ℤ) : a ⊗ₜ[ℤ] (0 : ℤ) = (0 : ℤ ⊗[ℤ] ℤ) := by
  simp [tmul_zero]

/-- The tensor product forms an `AddCommMonoid`. -/
example : AddCommMonoid (ℤ ⊗[ℤ] ℤ) := by
  infer_instance

/-- The tensor product over a commutative ring is an `R`-module. -/
example (R : Type*) [CommRing R] (A B : Type*)
    [AddCommGroup A] [Module R A] [AddCommGroup B] [Module R B] :
    Module R (A ⊗[R] B) := by
  infer_instance

/-- Addition is commutative in the tensor product. -/
example (x y : ℤ ⊗[ℤ] ℤ) : x + y = y + x := by
  abel

end ZExamples

/-! ### Example: tensor product over a field (vector spaces) -/

section FieldExamples

open TensorProduct

variable (K V W : Type*) [Field K] [AddCommGroup V] [Module K V]
  [AddCommGroup W] [Module K W]

/-- The tensor product of two vector spaces over K is a K-vector space. -/
example : Module K (V ⊗[K] W) := by infer_instance

/-- Basis elements: if `eᵢ` is a basis of `V` and `fⱼ` is a basis of `W`,
then `eᵢ ⊗ₜ fⱼ` spans `V ⊗[K] W`. -/
example (v : V) (w : W) : V ⊗[K] W := v ⊗ₜ[K] w

end FieldExamples
