import Mathlib

/-!
# Trivial and Proper Subgroups

The subgroup `{1_G}` is called the trivial subgroup (denoted `1`).
Any subgroup `H ≠ G` is a proper subgroup, written `H < G`.

In Mathlib4:
- The trivial subgroup is `⊥ : Subgroup G`, the bottom element in the subgroup lattice.
  `mem_bot` gives `x ∈ (⊥ : Subgroup G) ↔ x = 1`.
- A proper subgroup `H < G` is expressed as `H < ⊤` or `H ≠ ⊤`, using the lattice strict order.
- There is no dedicated `IsProperSubgroup` predicate in Mathlib4; we define one here for textbook
  compatibility.

## Main definitions

* `Subgroup.trivialSubgroup G` — alias for `⊥ : Subgroup G`, the trivial subgroup
* `Subgroup.IsProper H` — predicate stating `H` is a proper subgroup of `G`, i.e. `H ≠ ⊤`
-/

open Subgroup

variable {G : Type*} [Group G]

namespace Subgroup

/-- The trivial subgroup of `G`, i.e. the subgroup consisting only of the identity element `1`.
This is an alias for `⊥ : Subgroup G`, which Mathlib4 uses for the trivial subgroup. -/
def trivialSubgroup (G : Type*) [Group G] : Subgroup G := ⊥

/-- Every element of the trivial subgroup is the identity. -/
@[simp]
theorem mem_trivialSubgroup {x : G} : x ∈ trivialSubgroup G ↔ x = 1 :=
  mem_bot

/-- The trivial subgroup equals `⊥` by definition. -/
@[simp]
theorem trivialSubgroup_eq_bot : trivialSubgroup G = (⊥ : Subgroup G) := rfl

/-- A subgroup `H` of `G` is proper if it is not the whole group.
In Mathlib4 this is equivalent to `H < ⊤` or `H ≠ ⊤`. -/
def IsProper (H : Subgroup G) : Prop := H ≠ ⊤

/-- A proper subgroup is strictly less than the full group. -/
theorem isProper_iff_lt_top {H : Subgroup G} : IsProper H ↔ H < ⊤ := by
  constructor
  · intro h
    exact Ne.lt_of_le h (le_top (a := H))
  · intro h
    exact ne_of_lt h

/-- The trivial subgroup is proper in any nontrivial group. -/
theorem trivialSubgroup_isProper [Nontrivial G] : IsProper (trivialSubgroup G) := by
  rw [isProper_iff_lt_top, trivialSubgroup_eq_bot]
  have hne : (⊥ : Subgroup G) ≠ ⊤ := top_ne_bot.symm
  exact Ne.lt_of_le hne (bot_le (a := ⊤))

/-- A subgroup is either the whole group or proper. -/
theorem eq_top_or_isProper (H : Subgroup G) : H = ⊤ ∨ IsProper H := by
  by_cases h : H = ⊤
  · exact Or.inl h
  · exact Or.inr h

/-- The trivial subgroup is `⊥`. -/
example (G : Type*) [Group G] : trivialSubgroup G = (⊥ : Subgroup G) :=
  trivialSubgroup_eq_bot

/-- In any nontrivial group, the trivial subgroup is proper. -/
example [Nontrivial G] : IsProper (trivialSubgroup G) :=
  trivialSubgroup_isProper

/-- A proper subgroup is strictly contained in the full group. -/
example [Nontrivial G] : trivialSubgroup G < (⊤ : Subgroup G) := by
  rw [← isProper_iff_lt_top]
  exact trivialSubgroup_isProper

/-- The subgroup generated by the identity element is trivial. -/
example (G : Type*) [Group G] : Subgroup.zpowers (1 : G) = ⊥ := by
  simp

end Subgroup
