import Mathlib

open scoped Classical
open scoped BigOperators

/-!
# Zero Set of Polynomials

Let `K` be a field and `K` its algebraic closure (or any field extension).
For a set `S ⊆ K[X₁, ..., Xₙ]`, the **zero set** is

    Z(S) = { x ∈ Kⁿ | f(x) = 0 for all f ∈ S }.

Mathlib4 already defines this concept as `MvPolynomial.zeroLocus` in
`Mathlib/RingTheory/Nullstellensatz.lean`.  This file re-exports that definition
and adds convenience wrappers that accept an arbitrary set `S` of polynomials
(rather than requiring an ideal).
-/

section zero_set_of_polynomials

open MvPolynomial

variable {k K : Type*} [Field k] [Field K] [Algebra k K]
variable {σ : Type*}

/-! ### Core definition from Mathlib4

`MvPolynomial.zeroLocus` (defined in `RingTheory/Nullstellensatz`) is the
set of points in `Kⁿ` that are zeros of all polynomials in a given ideal.
The type `σ → K` represents `Kⁿ` where `σ` is the variable index set.

    def zeroLocus (I : Ideal (MvPolynomial σ k)) : Set (σ → K) :=
      {x : σ → K | ∀ p ∈ I, aeval x p = 0}
-/

/-- Expose the Mathlib4 definition under a more discoverable name.
`zeroSet` is an alias for `MvPolynomial.zeroLocus` that works with any set
of polynomials (not only ideals).  For an ideal `I` the two coincide;
for a general set `S` we take the ideal generated by `S`. -/
def zeroSet (S : Set (MvPolynomial σ k)) : Set (σ → K) :=
  MvPolynomial.zeroLocus K (Ideal.span S)

/-- A point `x` belongs to the zero set of `S` iff every polynomial in `S`
evaluates to zero at `x`. -/
theorem mem_zeroSet_iff {S : Set (MvPolynomial σ k)} {x : σ → K} :
    x ∈ zeroSet S ↔ ∀ p ∈ S, aeval x p = 0 := by
  simp [zeroSet, MvPolynomial.zeroLocus_span]

/-- Notation `Z(S)` for the zero set, mimicking the classical algebraic geometry
notation. -/
notation:max "Z(" S ")" => zeroSet S

end zero_set_of_polynomials

/-! ### Examples -/

section examples

open MvPolynomial

variable (k K : Type*) [Field k] [Field K] [Algebra k K]

/-- Example: the zero set of a single polynomial `X² + Y² - 1` in two variables.
This is the unit circle over the field `K`. -/
example : Z({MvPolynomial.X (0 : Fin 2) ^ 2 + MvPolynomial.X 1 ^ 2 - (1 : MvPolynomial (Fin 2) k)} : Set (MvPolynomial (Fin 2) k)) =
    { x : Fin 2 → K | aeval x (MvPolynomial.X (0 : Fin 2) ^ 2 + MvPolynomial.X 1 ^ 2 - 1) = 0 } := by
  ext x; simp [mem_zeroSet_iff]

/-- Example: the zero set of the empty set is all of `Kⁿ`. -/
example : Z((∅ : Set (MvPolynomial σ k))) = (⊤ : Set (σ → K)) := by
  ext x; simp [mem_zeroSet_iff]

/-- Example: the zero set of the whole polynomial ring is empty
(because it contains the constant polynomial `1`, which never vanishes). -/
example : Z((⊤ : Set (MvPolynomial σ k))) = (∅ : Set (σ → K)) := by
  ext x; simp [mem_zeroSet_iff]

/-- Example: using Mathlib4's built-in `zeroLocus` directly with an ideal.
The zero set of the ideal generated by `X₁, …, Xₙ` is the singleton `{0}`. -/
example (σ : Type*) [Fintype σ] [DecidableEq σ] :
    MvPolynomial.zeroLocus K (Ideal.span (Set.range MvPolynomial.X : Set (MvPolynomial σ k))) =
    { x : σ → K | ∀ i, x i = 0 } := by
  ext x; simp [MvPolynomial.mem_zeroLocus_iff, Ideal.mem_span_singleton]

/-- Example: for a single variable `X`, the zero set of the ideal `(X - a)`
is the singleton `{a}`, where `a : k` lifts to `K` via `algebraMap`. -/
example (a : k) :
    MvPolynomial.zeroLocus K (Ideal.span {MvPolynomial.X (0 : Unit) - C a} : Ideal (MvPolynomial Unit k)) =
    { x : Unit → K | x () = algebraMap k K a } := by
  ext x; simp [MvPolynomial.mem_zeroLocus_iff, Ideal.mem_span_singleton]

end examples
